### ISSUE TITLE
UserDialogs.Instance.Progress floating when updating .Title

### ISSUE THREAD

**Issue by pewa0500** [aritchie/userdialogs#101]
Hi!
I'm using MessagingCenter.Subscribe to update .PercentComplete on my Progress dialog and it works fine. But when I use this method to set .Title. The dialog keeps resizing and floating around because the length of the text varies. 
I use .Title to prompt where in the working process the code are.

Is there a way to set fixed width on the dialog or another solution to this?

Best regards, Peter W

**Comment by aritchie** [comment]
There isn't a way to set a fixed width on the dialog (at least without override the dialog itself).  Your best bet is to figure out the "max" length and trim to that length (ie. This is my max length = This is my max...")
