### ISSUE TITLE
Button Direction on iOS

### ISSUE THREAD

**Issue by supreettare** [aritchie/userdialogs#105]
Hello, 
Thank you for this wonderful library. We use it in almost all our Xamarin Forms projects. 
I was just asked by our clients to change the direction of the buttons on a confirm popup for iOS. 
Here is my code:

   UserDialogs.Instance.Confirm(new ConfirmConfig
                            {
                                Message = "Are you sure you want to logout?",
                                OkText = AppConstants.LogoutPositiveText, 
                                CancelText = AppConstants.CancelText,
                                OnConfirm = async (s) =>
                                {
                                     // Do something
                                }
                            });

On android the button order is (Left to right) Cancel, Logout 
On iOS the button order is (Left to right) Logout, Cancel 

Is there a way we can change this for iOS to match it with the android version? 
Thanks foe looking into this. 
Appreciate your help. 

ST

**Comment by aritchie** [comment]
This has already been fixed for the next release.

**Comment by supreettare** [comment]
Fantastic. 
Where can I see when the next release will be available? 
Thanks
