### ISSUE TITLE
NullReferenceException in iOS (related to BigTed)

### ISSUE THREAD

**Issue by alexrainman** [aritchie/userdialogs#106]
Having this issue in iOS with Xamarin.Forms 2 project:

![screen shot 2015-12-02 at 2 38 44 pm](https://cloud.githubusercontent.com/assets/3793554/11543484/8942221c-9902-11e5-9cf2-4c57182f1669.png)

**Comment by aritchie** [comment]
Please send the full stack trace as text.  It has cut off most of what I'm looking for.  Please also review FAQ #1 in the readme

**Comment by alexrainman** [comment]
Allan, it's related to #4, as i use a LaunchScreen. If i move the Loading to OnAppearing(), it works. How to show a loading wheel on the first page on XF?

**Comment by alexrainman** [comment]
Solved. I moved my Loading call to OnAppearing on my home page and to avoid to be called when back button is pressed, i added IsLoaded bool. Thanks
