### ISSUE TITLE
Loading and alert breaks Xamarin Forms navigation

### ISSUE THREAD

**Issue by theiwaz** [aritchie/userdialogs#107]
I've got a Xamarin forms application 

- navigating to another screen with a PushPageModel command (FreshMVVM) and 
- that page shows a loading indicator (page not is shown yet)  
- then the receiving screen throws an exception 
- shows an alert and I log and swallow the exception after showing the alert. 

This causes the receiving screen never to be shown and breaking the navigation. After the exception has been thrown it's not possible to go to the second screen anymore even though the I can see the page on the navigation stack. 

See the code below. I've also tried to execute a `PopToRoot` in the OnOk of the alert to force the app to go somewhere else. Any bright ideas are really welcome

```
        private void FindUsers()
        {
            try
            {  
                _userDialogs.ShowLoading();
                SelectedUsers = new ObservableCollection<Gebruiker>(_databaseService.GetGebruikers(searchTerm));
                _userDialogs.HideLoading();
            }
            catch (NullReferenceException ex)
            {
                Insights.Report(ex);
                _userDialogs.HideLoading();
                _userDialogs.Alert(string.Format("Er ging iets mis bij het zoeken van de gebruiker:\n{0}", ex.Message));
            }
            catch (ArgumentOutOfRangeException ex) 
            {
                Insights.Report(ex);
                _userDialogs.HideLoading();
                _userDialogs.Alert(new AlertConfig{
                    Message = "Geen geldige invoer. Voer een zoekterm in van minimaal 4 karakters.",
                    OnOk = new Action(()=> this.CurrentPage.Navigation.PopToRoot(true)),
                    Title= "GFY"
                } );
            }
            catch (Exception ex) 
            {
                Insights.Report(ex);
                _userDialogs.HideLoading();
                _userDialogs.Alert(ex.ToString());
            }
  
        }
```

**Comment by aritchie** [comment]
I need the platform and the exception to offer any advice.

**Comment by theiwaz** [comment]
Thanks for the response. The platform is iOS 9 and I am running a iPad Air2 Emulator and the exception is ArgumentOutOfRangeException. 

I've found what solved it is *not* running the procedure that throws the exception - as stated above - in the `init` method but in the `ViewIsAppearing`. 

If you have pointers for still using the `init` method I'd be grateful but this is an acceptable solution to me. The only ugly thing in this situation right now is that the view appears, throws the exception and then disappears.

**Comment by aritchie** [comment]
I need the full exception stacktrace to really understand the issue and perhaps the code leading up to FindUsers.  I have no idea what context "init" is used in since it doesn't apply to an iOS execution path.
