### ISSUE TITLE
Question: Is there any way we can close the alert from code? 

### ISSUE THREAD

**Issue by supreettare** [aritchie/userdialogs#108]
Hi Alan, 
we have one requirement where we need to navigate the app to a different page dynamically based on a logic that runs in the background. 
The problem is, if I have an alert open on current page & the background logic executes & navigates the user to another page, that alert remains open & visible on this second page. 

Is there any way we can close all alerts in the app dynamically? 

Here is a sample code we are using to show a sample confirm/ alert 

    UserDialogs.Instance.Confirm(new ConfirmConfig
    {
         Message = "Are you sure you want to logout?",
         OkText = AppConstants.LogoutPositiveText, 
         CancelText = AppConstants.CancelText,
         OnConfirm = async (s) =>
              {
                  // Do something
              }
    });

Thanks, looking for your response.

**Comment by aritchie** [comment]
Not at the moment.  This is being considered for v5.  Please refer to #68

**Comment by supreettare** [comment]
Cool, 
It can wait. Do we have any dates in mind, just so I can update the clients for time being? 
Also when is 4.3 out? 
Thanks

**Comment by aritchie** [comment]
I'm sorry.  I don't do dates.  This is OSS and I'm one person.

**Comment by supreettare** [comment]
Totally understand.
Thank you. I'll wait for when we have a fix available.
Thanks
