### ISSUE TITLE
Toasts - without background color?

### ISSUE THREAD

**Issue by aunanue** [aritchie/userdialogs#109]
Hi, first to all great work!!

Is it possible to display the Toast messages without the semi-transparent background color? 
Currently it is displaying the toast with the message at the bottom (as expected) but using semi-transparent background occupying the whole screen (like a modal message as with the rest of the messages).
Is there a way to get only the area of the message without the full semi-transparent part? 
I tried to change the background (System.Drawing.Color.Empty) color via ToastConfig but it is ignoring the values set to the Background property.

**Comment by aritchie** [comment]
The toasts in android are provided via AndHUD.  Unfortunately, the background colors don't apply to this mechanism.  You can override the mechanism or switch to the appcompat version to get around this.
