### ISSUE TITLE
Make a toast disappear on click

### ISSUE THREAD

**Issue by PaulAchess** [aritchie/userdialogs#11]
Hi,
I'm trying to make a toast to let the possibility to the user to cancel an action on a toast click.
In this case, I'd like the toast to disappear when the user click on it.

The code could look like (example on android) : 

    public override void Toast(string message, int timeoutSeconds = 3, bool dismissOnClick = false, Action onClick = null) {
            Utils.RequestMainThread(() => {
            onClick = () => {
                                if (onClick != null) onClick.Invoke()
                                if (dismissOnClick) AndHUD.Shared.Dismiss();
                            });

                AndHUD.Shared.ShowToast(
                    this.getTopActivity(),
                    message,
                    MaskType.Clear,
                    TimeSpan.FromSeconds(timeoutSeconds),
                    false,
                    onClick
                );
            });
        }

**Comment by PaulAchess** [comment]
Another way to do this, and probably a better way, would be to get back a Toast object that you can manipulate :
`Toast t = dialogs.Toast("test", 3, () => t.Dismiss());`

**Comment by aritchie** [comment]
Not all platforms support a click option right now.  The onclick that exists in android, should dismiss upon click anyhow

**Comment by PaulAchess** [comment]
Still, couldn't we be able to dismiss a toast manually ?
I like the idea to control that (regardless of the dimiss on click, which seems appropriate)

**Comment by aritchie** [comment]
When clicking on a toast, it will automatically dismiss in 3.0.5
