### ISSUE TITLE
Can´t compile after updating to Xamarin.Android.Support.V7.AppCompat 23.1.1

### ISSUE THREAD

**Issue by xleon** [aritchie/userdialogs#110]
![image](https://cloud.githubusercontent.com/assets/145087/11962428/147d1eb2-a8e0-11e5-80b5-0ab68a199713.png)

I installed the Android SDK in the SDK manager. Still the same problem.
![image](https://cloud.githubusercontent.com/assets/145087/11962515/a96a2128-a8e0-11e5-941c-99bade9cf252.png)
![image](https://cloud.githubusercontent.com/assets/145087/11962558/ed1710ca-a8e0-11e5-8fd9-8f4a91c39fe9.png)

**Comment by aritchie** [comment]
I'm not sure what this has to do with this library?  

Best suggestion is to clear all your obj/bin folders in your entire solution, restart VS, and recompile.  Sometimes emptying out you Resources.cs and letting it fully regen helps too.  

In any case, you should phrase this question to xamarin and/or on their forums.

**Comment by xleon** [comment]
Hi @aritchie 
It´s true that the title of the issue is vague. Sorry for that.
All errors are references to global::Arc.UserDialogs, so it´s related. 
The reference to 23.1.1 is to let you know that the UserDialogs needs updates to support it

**Comment by aritchie** [comment]
The appcompat library updates every other week and I won't update right away.  I'll start enforcing specific versions inline with xamarin.forms

**Comment by xleon** [comment]
Is there any quick workaround I may use for this? 
Not sure how to make those updates myself

**Comment by aritchie** [comment]
Downgrade the android support library

**Comment by xleon** [comment]
I can´t do this cause other libs are using it. But it´s ok. I´ll find my way.
Thanks for your help @aritchie

**Comment by robertbaker** [comment]
ran into this issue as well. Don't want to downgrade, any eta of when you will update it?
