### ISSUE TITLE
UserDialogs.Instance.ActionSheetAsync title string will be shortened

### ISSUE THREAD

**Issue by fvermeulen** [aritchie/userdialogs#113]
I have a problem with the ActionSheet under android. The title will be shortened. What Can I do there, that the hole string will be shown?

Iphone works fine

![screenshot_2016-01-05-11-34-04](https://cloud.githubusercontent.com/assets/1662765/12113003/541ddc4e-b3a0-11e5-83c5-6ff20f4cfc71.png)

![screen shot 2016-01-05 at 11 37 17](https://cloud.githubusercontent.com/assets/1662765/12113055/b9bde9d6-b3a0-11e5-8479-6dc46685e53f.png)

**Comment by aritchie** [comment]
You can try changing your alertdialog theme.  Right now, this is just the default behavior for android.  Honestly, I wouldn't set long titles here anyhow.  The form factors can change from device to device.

**Comment by fvermeulen** [comment]
I looked in your code and found a solution for this

https://github.com/aritchie/userdialogs/pull/114

I have to rearrange everything and so on, but it will work

**Comment by fvermeulen** [comment]
@aritchie what do you think about it?

**Comment by aritchie** [comment]
This can break custom themes on the alertdialogs.  I am pretty sure the line count can be increased via themes.
