### ISSUE TITLE
Success/Error icons not showing...

### ISSUE THREAD

**Issue by leonpotgieter** [aritchie/userdialogs#115]
Hi, with the last update I've noticed that the ShowError/ShowSuccess icons are no longer visible in my Xamarin Forms(2.0.0.6490)/iOS app...

Worked previously but after updating to 4.2.0 they disappeared... Dialog still shows text but the image is no longer there... any ideas as to what could be wrong and how I could sort this out?

Tx

**Comment by aritchie** [comment]
I haven't been able to reproduce it on ios or android.  On what platform are you having the issue?
