### ISSUE TITLE
payload Acr.UserDialogs.xr.xml not found

### ISSUE THREAD

**Issue by codeknox** [aritchie/userdialogs#116]
Hey man,
the fix was easy, but I dont know what causes it! :)

on the folder
.nuget\packages\Acr.UserDialogs\4.2.1\lib\uap10.0

I created this folder:
md Acr.UserDialogs

and copied 
copy Acr.UserDialogs.xr.xml Acr.UserDialogs

into it.

Now I can build.

Probably some nuspec error?

**Comment by aritchie** [comment]
It does have something to do with nuget.  4.2.1 does have the xml as an embedded resource which is supposed to fix the issue.  

Please follow #112 going forward
