### ISSUE TITLE
LoginResult Not Being Updated on UWP

### ISSUE THREAD

**Issue by brettcook99** [aritchie/userdialogs#117]
I'm having an issue with the login dialog not returning the correct login results on UWP.  

I am calling the login dialog from a BeginInvokeOnMainThread and the OnReturn action is on a different thread.  Could this be non-thread safe case, or is something not setup right in the UWP implementation?

**Comment by aritchie** [comment]
What about the results is wrong?

**Comment by brettcook99** [comment]
It just returns what I set as the LoginValue for the LoginText, and the Password returns as null regardless of what the user inputs.

**Comment by brettcook99** [comment]
Any update on this bug?

**Comment by Dexyon** [comment]
I guess nobody did look at this issue. Can you implement a bugfix yourself and submit a PR? Then this bug can be resolved a little bit faster ;)

**Comment by aritchie** [comment]
I don't have the time to look at this right now as UWP isn't high on my list.  You can either submit a PR or wait until I get around to it.
