### ISSUE TITLE
TabbedPage not working properly for WP and iOS if navigate to tabbed page Just after ShowLoading and HideLoading

### ISSUE THREAD

**Issue by techprash** [aritchie/userdialogs#118]
Step to reproduce:
Xamarin.Form Portable project with version Xamarin.Forms.2.0.0.6490
Acr.UserDialogs.4.2.1
On content page using following code:
sl.GestureRecognizers.Add(new TapGestureRecognizer
            {
                Command = new Command(() =>
                {
                    Device.BeginInvokeOnMainThread(async () =>
                       {
                           Acr.UserDialogs.UserDialogs.Instance.ShowLoading("Please Wait...");
                           await Task.Delay(1000);
                           Acr.UserDialogs.UserDialogs.Instance.HideLoading();
                           //TabbedPage With 2 Content Page
                           TabPage tabview = new TabPage();
                           await App.Navigation.PushAsync(tabview);
                       });
                 })
            });
Tabbed page not working fine. If I comment the ShowLoading and HideLoading Its working fine.

**Comment by aritchie** [comment]
What isn't working specifically?  It isn't navigating?  It isn't showing the dialog?
