### ISSUE TITLE
Dialog boxes causes Android app to leave immersive mode

### ISSUE THREAD

**Issue by Adam--** [aritchie/userdialogs#119]
When an application is in immersive/full screen mode (low profile, hide navigation, fullscreen, and immersive sticky UI options set). Displaing a dialog, for example `IUserDialogs.PromptAsync(...`, causes the app to leave immersive mode while displaying the dialog.

**Comment by Adam--** [comment]
http://stackoverflow.com/a/23207365/1113813 may provide some insight into staying in immersive mode.

**Comment by aritchie** [comment]
This sounds more like a bug with android.  I'm not sure I want to add the hacky fix for this.  You can over the methods that create the alert dialog to fix this though

**Comment by Adam--** [comment]
I agree, but figured I'd bring it up. It's not common to be in immersive mode and show a dialog, let alone not be okay with temporarily leaving immersive mode. 

What additional info do you need?

**Comment by aritchie** [comment]
I've marked this as additional info because I'd like to test it more in the future because I may have a future use-case around this.  It isn't that I won't fix this.  It is just that the proposed solution from the SO answer is less than ideal.
