### ISSUE TITLE
Add option to remove button borders

### ISSUE THREAD

**Issue by phazlett** [aritchie/userdialogs#12]
It would be really great if UserDialogs provided a way to remove the border around button. In the attached screenshot of an ActionSheet on WP8 you'll see a double border around the buttons, so it would be aesthetically pleasing to remove the inner border.

![screen shot 2015-03-16 at 11 52 26 am](https://cloud.githubusercontent.com/assets/3076332/6670323/55e9d1ea-cbd4-11e4-890b-69467ed53d20.png)

**Comment by aritchie** [comment]
Do you have any global styles of any type?  I was unable to see this in the samples.

**Comment by phazlett** [comment]
Oh my gosh, I can't believe that I overlooked that. Sorry for the erroneous report. You can close this one.

Thanks!
