### ISSUE TITLE
Does not contain a definition for "...." 

### ISSUE THREAD

**Issue by AhmedWarreth** [aritchie/userdialogs#121]
Getting the following error in my Droid project when i compile. Compiling against 23.1.0.

Mobile.Droid.Resource.Dimension' does not contain a definition fordesign_tab_min_width' (CS0117) (Mobile.Droid)

Mobile.Droid.Resource.Dimension' does not contain a definition fordialog_fixed_height_major' (CS0117) (Mobile.Droid)

Mobile.Droid.Resource.Dimension' does not contain a definition for `dialog_fixed_height_minor' (CS0117) (Mobile.Droid)

Mobile.Droid.Resource.Dimension' does not contain a definition for `dialog_fixed_width_major' (CS0117) (Mobile.Droid)

**Comment by aritchie** [comment]
This has to do with the version of the support library I use.  I upgrade with the android support library with xamarin form releases.  Sorry, since I have a vast majority of people on it without a standing need for features from the support libraries, this is how it has to work for now.

**Comment by AhmedWarreth** [comment]
Ok no worries. 

Well i downloaded your code and updated the references and its compiling fine....but my question is...how are you getting it to output the Acr.UserDialogs,Android.Appcompat.dll ?

**Comment by aritchie** [comment]
I don't understand your question!?  I compile it...

**Comment by AhmedWarreth** [comment]
...I did that man...i can't find the Acr.UserDialogs,Android.Appcompat.dll in any of the bin folders.

**Comment by aritchie** [comment]
no idea man.  works for me.  make sure your build configuration profile is set to mixed platforms and release.

**Comment by AhmedWarreth** [comment]
Cool! thanks dude :+1:

**Comment by AhmedWarreth** [comment]
Sorry to bother you about his again man, I built in release mode, and i still for the life of me can't find where the Acr.UserDialogs.Android.Appcompat.dll is being built to. 

This is all i have in the release folder

![screen shot 2016-01-27 at 10 39 52](https://cloud.githubusercontent.com/assets/5125127/12611030/98661d96-c4e2-11e5-9a41-478e4949f6f6.png)
 
checked all the other folders too

**Comment by aritchie** [comment]
No idea.  Make sure it is building properly for you.  I can't offer you any assistance beyond that at this point
