### ISSUE TITLE
ShowLoading not appearing

### ISSUE THREAD

**Issue by theiwaz** [aritchie/userdialogs#122]
Platform: Xamarin Forms in combination with FreshMVVM

When calling ShowLoading from ViewIsAppearing it's not shown, Calling it from the Init works but doesn't work on re-entry on the page.

**Comment by aritchie** [comment]
What platform?  Code sample?  I don't use freshmvvm.

**Comment by theiwaz** [comment]
Thanks for the speedy reply. Found out it was my own fault. Async issue. So not in issue with 'Userdialogs'
