### ISSUE TITLE
Toasts look strange in UWP

### ISSUE THREAD

**Issue by WarBorg** [aritchie/userdialogs#124]
hi,

using this code in a Xamarin Forms PCL project running version 2.0.1

```
UserDialogs.Instance.Toast(new ToastConfig(ToastEvent.Warn, "Warning", "Working offline, Tap to reconnect")
                {
                    Duration = TimeSpan.FromSeconds(8),
                    Action = async () => await ReconnectToServer()
                });

```
I get this on the simulator with the UWP app

![Screenshot](http://s23.postimg.org/3xfg29umz/screenshot_UWP_toast.jpg)

if I use any longer ones they get clipped, should't they be a little smaller ? and the title above the content ? 

thx

**Comment by aritchie** [comment]
I haven't spent a lot of time on the UWP stuff yet.  I could use a little help in the pretty design area in any case.  Please feel free to submit a PR.

**Comment by WarBorg** [comment]
ok, thank you for the reply, I will see if I can help in anyway

**Comment by aritchie** [comment]
This is actually a defect with coding4fun toolkit.
