### ISSUE TITLE
Please update the android support libs

### ISSUE THREAD

**Issue by robertbaker** [aritchie/userdialogs#125]
The android support libs have been out for a while now. I cannot use this lib with the latest support lib version.

Will you merge a PR that updates this?

**Comment by xleon** [comment]
+ 1

**Comment by Dexyon** [comment]
Well you could add a PR to fix it. @aritchie do you require it on v5 or the master?

**Comment by aritchie** [comment]
I've been evaluating the upgrade for a while.  A pull request is unnecessary at this point as I already have one internal.  I have to finish testing with xamarin forms first as there is a large userbase that uses it that also uses this library.

In any case, I need the upgrade as well for mvvmcross 4 stuff.

**Comment by Dexyon** [comment]
@aritchie Thanks for the new version :)!

**Comment by Dexyon** [comment]
@aritchie Spoted a small mistake while updating the references. Made a PR for it (without pumping of version numbers, resources etc).

**Comment by aritchie** [comment]
Thanks.  Strange that the nuget updated, but the reference did not :+1:
