### ISSUE TITLE
Fail to compile - Ver. 4.3.0 - WP8.1

### ISSUE THREAD

**Issue by gadipaz** [aritchie/userdialogs#128]
I'm using Android & iOS version and it works great.
But when compiling to WP8.1 it won't compile and I get those errors:
Severity	Code	Description	Project	File	Line	Suppression State
1. Error		Payload file 'D:\Development\CS\Mobile\GitProjects\OfficeTrack\packages\Acr.UserDialogs.4.3.0\lib\wpa81\Acr.UserDialogs\Acr.UserDialogs.xr.xml' does not exist.	OfficeTrack.WP			
2. Severity	Code	Description	Project	File	Line	Suppression State
Error		Payload file 'D:\Development\CS\Mobile\GitProjects\OfficeTrack\packages\Acr.UserDialogs.4.3.0\lib\wpa81\Acr.UserDialogs\ActionSheetContentDialog.xbf' does not exist.	OfficeTrack.WP			
3. Severity	Code	Description	Project	File	Line	Suppression State
Error		Payload file 'D:\Development\CS\Mobile\GitProjects\OfficeTrack\packages\Acr.UserDialogs.4.3.0\lib\wpa81\Acr.UserDialogs\LoginContentDialog.xbf' does not exist.	OfficeTrack.WP			
4. Severity	Code	Description	Project	File	Line	Suppression State
Error		Payload file 'D:\Development\CS\Mobile\GitProjects\OfficeTrack\packages\Acr.UserDialogs.4.3.0\lib\wpa81\Acr.UserDialogs\ProgressContentDialog.xbf' does not exist.	OfficeTrack.WP			
5. Severity	Code	Description	Project	File	Line	Suppression State
Error		Payload file 'D:\Development\CS\Mobile\GitProjects\OfficeTrack\packages\Acr.UserDialogs.4.3.0\lib\wpa81\Acr.UserDialogs\PromptContentDialog.xbf' does not exist.	OfficeTrack.WP			

I'm using VS2015 Update 1
Any idea how can I solve this?
(BTW, I tried using Ver. 4.2.1 and it compiles but crushes when trying to display a message with this error:
This is the PCL library, not the platform library.  You must install the nuget package in your main executable/application project)

**Comment by aritchie** [comment]
Wp81 was only added recently as a pull request from someone.  I will leave this open for now, but unless the original contributor replies, I will pull support.  In any case, you should know that once wp10 is released, I will be dropping support anyhow.

**Comment by gadipaz** [comment]
Thanks @aritchie,
I see that the original contributor is not responding.
Can you please see if there's something you can do about it?
This is really important for me.
As said, I use your great component for iOS & Android and it works like a charm.
Is there any chance you can tell me how can I workaround the issue with Windows Phone 8.1?
Thanks in advanced

**Comment by aritchie** [comment]
I only sent the message to the contributor yesterday, so try being a little more patient.  You are welcome to see what you can do about it yourself as well, especially if it is important to you.  This is open source after all.

I myself, would have to do the same by checking google.  Personally, I don't want to support WP8-8.1 at all.  It is there simply because of contributions.

**Comment by TJProcessa** [comment]
Hi 
I have the same problem and I really have no idea how to solve it!

**Comment by aritchie** [comment]
Please try 4.3.2 and let me know if that fixes it

**Comment by pafvcio** [comment]
Application WP8.1 compiles, but when I call UserDialogs.Instance.ShowLoading() show exception:

> Exception thrown: 'Windows.UI.Xaml.Markup.XamlParseException' in Acr.UserDialogs.DLL
> 
> Additional information: XAML parsing failed.

**Comment by gmwilhelm** [comment]
I get the same error message on UWP

**Comment by aritchie** [comment]
Please include the full stack traces.  I can't test WPA81.  I have tested UWP without issue though.

**Comment by gmwilhelm** [comment]
This is all i get:

> XAML parsing failed
> 
>    at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
>    at Acr.UserDialogs.ProgressContentDialog.InitializeComponent()
>    at Acr.UserDialogs.ProgressDialog..ctor()
>    at Acr.UserDialogs.UserDialogsImpl.CreateDialogInstance()
>    at Acr.UserDialogs.AbstractUserDialogs.Progress(ProgressDialogConfig config)
>    at Acr.UserDialogs.AbstractUserDialogs.Loading(String title, Action onCancel, String cancelText, Boolean show, Nullable`1 maskType)
>    at ClickLearn.Mobile.Forms.App.<OnStart>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
>    at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

**Comment by gadipaz** [comment]
Thanks @aritchie 
4.3.2 compiles and works as expected.
BTW, I'm not using ShowLoading() so I can't say if it's working or not but Alerts & Toasts work good.
Thanks

**Comment by aritchie** [comment]
Moving loading defect to #112
