### ISSUE TITLE
Android ShowLoading not showing text or loading icon

### ISSUE THREAD

**Issue by alexbleks** [aritchie/userdialogs#129]
1) Please check all of the platforms you are having the issue on
[] iOS
[*] Android
[] WP81
[] WP8
[] UWP
[] PCL

2) Please state the issue to the best of your ability below
UserDialogs.Instance.ShowLoading puts a "gray overlay" over the app and showing no text, no loading icon or whatsoever.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.
 
N/A

**Comment by aritchie** [comment]
Examples work fine.  How are you calling it?

**Comment by alexbleks** [comment]
UserDialogs.Instance.ShowLoading(load_text);

**Comment by aritchie** [comment]
and what's the value of load_text?  Empty string or null?

**Comment by alexbleks** [comment]
its a string argument from a function.

It works great on iOS and WP

**Comment by aritchie** [comment]
Does it have a value though - on android?

**Comment by alexbleks** [comment]
![skjermbilde 2016-02-24 kl 23 06 52](https://cloud.githubusercontent.com/assets/17303226/13302711/a635b128-db4b-11e5-84dd-2fabccc79a11.png)

**Comment by aritchie** [comment]
1) Is this in MvvmCross, Xamarin Forms, or straight up native?
2) Which flavour of Init are you calling?

**Comment by alexbleks** [comment]
Xamarin.Forms.  The ALERT function works correctly tho
![skjermbilde 2016-02-25 kl 08 27 23](https://cloud.githubusercontent.com/assets/17303226/13312803/b449118a-db99-11e5-9b35-72e47b9cebd2.png)

**Comment by aritchie** [comment]
Ok, we'll try this in two steps

1) Try using UserDialogs.Init(() => (Activity)Forms.Context);

2) Try not to use ShowLoading & HideLoading.  If you forget to call hide loading somewhere, it can leave things "stranded".  Instead, use UserDialogs.Instance.Loading("Message") wrapped in a using statement (check samples).  It is a cleaner approach.

**Comment by alexbleks** [comment]
Didn't help anything :s  (Same gray overlay with no text or spinning wheel)

Btw, I use version 4.2.1

**Comment by aritchie** [comment]
Ok... unfortunately, you're doing something off the standard use-cases.  Please attach a test case that I can use to reproduce this otherwise there isn't much more I can do to help.

**Comment by XaviRR75** [comment]
alexbleks try add nuget to android project https://www.nuget.org/packages/AndHUD/, this work for me
