### ISSUE TITLE
Latest Nuget Doesn't install on Xamarin.Forms Android with  'Xamarin.Android.Support.v4 23.0.1.3 

### ISSUE THREAD

**Issue by ahmedkhan25** [aritchie/userdialogs#130]
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
[] iOS
[X] Android
[] WP81
[] WP8
[] UWP
[X] PCL

2) Please state the issue to the best of your ability below

Installing Package on Xamarin.Forms Droid Project -I get the following error:

Adding Acr.UserDialogs...
Attempting to resolve dependency 'Splat (≥ 1.6.2 && < 2.0.0)'.
Attempting to resolve dependency 'Acr.Support (≥ 1.1.1 && < 2.0.0)'.
Attempting to resolve dependency 'Xamarin.Android.Support.v4 (≥ 23.1.1 && < 24.0.0)'.
Updating 'Xamarin.Android.Support.v4 23.0.1.3' to 'Xamarin.Android.Support.v4 23.1.1.0' failed. Unable to find a version of 'Xamarin.Forms' that is compatible with 'Xamarin.Android.Support.v4 23.1.1.0'.

Xamarin.Forms requires Xamarin.Android.Support.v4 23.0.1.3  and doest let me update to  'Xamarin.Android.Support.v4 23.1.1.0'.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

**Comment by Dexyon** [comment]
There is also an issue in bugzilla from Xamarin. 
https://bugzilla.xamarin.com/show_bug.cgi?id=37509

Basically you have to remove and add (and try a couple of times). Not really an issue with this library

**Comment by ahmedkhan25** [comment]
Ok, per that bugzilla link,  In the droid project, I tried removing and re-adding Xamarin.Forms and the Android Support Libraries  3 times according to the workaround instructions so far it still doesn't update the Android support library version to  23.1.1.0 -in fact in the nuget package chooser window it still lists Xamarin.Forms requiring 23.0.1.3

kind of frustrating....sigh

**Comment by aritchie** [comment]
Xamarin forms uses an old version of the android support library.  This isn't a bug on XF or this library.  4.3 of dialogs uses the new one.  You can install User Dialogs 4.2.1 if you are using XF.

**Comment by ahmedkhan25** [comment]
Ok thanks for the info. I cannot find UserDialogs 4.2.1 on nuget however -The only package I found lower than 4.3.0 was 4.0.0 which still gives me the same install XF Android library issue

I only found this: https://www.nuget.org/packages/Acr.XamForms.UserDialogs/4.0.0

**Comment by aritchie** [comment]
That just redirects to this one.  https://www.nuget.org/packages/Acr.UserDialogs/

Uninstall that package and install the one above using 4.2.1

**Comment by ahmedkhan25** [comment]
Ok that worked -I was able to install that package on android

It may be helpful to have clearer install instructions for XF users  in this regard

thank you for your quick support.

**Comment by aritchie** [comment]
The nuget error message was extremely informative of your issue.  While I appreciate the feedback, this isn't something I'm going to document for this case.

**Updating 'Xamarin.Android.Support.v4 23.0.1.3' to 'Xamarin.Android.Support.v4 23.1.1.0' failed. Unable to find a version of 'Xamarin.Forms' that is compatible with 'Xamarin.Android.Support.v4 23.1.1.0'.**

**Comment by quakeulf** [comment]
I can't seem to install anything as the conflicts between Splat and Acr.Userdialogs persist.

This is extremely frustrating and I have wasted enough time on this already.

I should bill you for the hours tried making this work. When all the other packages install perfectly why doesn't this?

**Comment by quakeulf** [comment]
Error		
"Could not install package 'Splat 2.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

It's on you now.

**Comment by aritchie** [comment]
That has to be the single stupidest way to ask for help I've ever seen.  Do you realize that this library is free and that I work on it in my OWN time, you self entitled little brat.  

It's on you now, because you clearly can't read that the nuget package has a hard version on 1.6.2.  Don't come back, you aren't welcome.

**Comment by quakeulf** [comment]
How would I know?

I deleted the message because it wasn't appropriate anyhow. At least you know my frustrations.
