### ISSUE TITLE
Support Libraries Version Mismatch

### ISSUE THREAD

**Issue by drungrin** [aritchie/userdialogs#131]
I'm getting errors on updating AcrUserDialogs, It needs latest Android Support Libraries, and latest Xamarin.Forms nugget isn't compatible with it.

Maybe the version requirement on the nugget shouldn't be pumped, and walks together with the latest Xamarin.Forms requirements?

**Comment by aritchie** [comment]
I can't be held back from updates because of one technology vs another.  I drive these libraries based on my needs and unfortunately, xamarin forms is a very low priority in that scheme.

Use 4.2.1 and ask xamarin to update their stuff accordingly.

**Comment by drungrin** [comment]
I asked both :)

I'm already using 4.2.1 until Xamarin fixes it.

Thanks for the feedback, and for the library!
