### ISSUE TITLE
UserDialogs.Instance.HideLoading (); does not work

### ISSUE THREAD

**Issue by acaliaro** [aritchie/userdialogs#132]
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
[] iOS
[X] Android
[] WP81
[] WP8
[] UWP
[] PCL

2) Please state the issue to the best of your ability below

I have this code
`
			buttonAvanti.Clicked += async (object sender, EventArgs e) =>{ 
				try{

					buttonAvanti.IsEnabled = false;

					// Verifico che tutti i record siano stati letti
					if(App.Globali.Pallet.FindAll (o=>o.Scannerizzato == true).Count != App.Globali.Pallet.Count){
						await DisplayAlert ("Attenzione", "Non tutti i barcode sono stati letti", "Ok");
						buttonAvanti.IsEnabled = true;
						return;
					}

					UserDialogs.Instance.Loading ("Attendi...");

					ErroreJson errore = await App.WebService.SendOracoloCheck (App.Globali.OperatoreSelezionato.idOperatore, App.Globali.Pallet);

					if(errore != null){ // ho un errore
						if(errore.isBlockingError)
							throw new Exception (errore.message);
						else{
							UserDialogs.Instance.HideLoading ();
							var ret = DisplayAlert ("Attenzione", errore.message, "Si", "No").Result;
							if(!ret)
								return;
							else
								UserDialogs.Instance.Loading ("Attendi...");
							
						}
					}

					App.Globali.Attivita =  await App.WebService.SendOracoloNoCheck (App.Globali.OperatoreSelezionato.idOperatore, App.Globali.Pallet);
					
					await Library.ApriPage (App.Globali.Attivita, false);
				}
				catch(Exception ex){
					UserDialogs.Instance.HideLoading ();
					await App.WebService.SendLog (App.Globali.OperatoreSelezionato != null ? App.Globali.OperatoreSelezionato.username : "", ex.Message, ex.HResult, ex.StackTrace);
					await DisplayAlert("Attenzione", ex.Message, "Ok");
					//Library.SetMainPage (new PageWebService ());
				}
				finally{
					buttonAvanti.IsEnabled = true;
					UserDialogs.Instance.HideLoading ();
				}
			};
`
I have some UserDialogs.Instance.Loading("Attendi...") and in the "finally" I have a UserDialogs.Instance.HideLoading that should close the "Loading", but it does not work.
There are some calls to webservices and a new page is visualized (in `await Library.ApriPage (App.Globali.Attivita, false);`

I am using 4.2.1

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

**Comment by aritchie** [comment]
You aren't using the library properly.  You must use ShowLoading & HideLoading together.  However, these methods are not the best practice.  You should use Loading on it's own.  Loading returns a disposable and ensures that the loading dialog disappears once the action is done.


using (UserDialogs.Instance.Loading("Waiting for stuff")) 
{
    // do some stuff here, async or sync
}

**Comment by jamesatgithub** [comment]
it would be better to add the correct usage in the doc, I made same mistake for show/hide the loading indicator and encountered same issue sometime the hide not work and then I searched and found this thread.

**Comment by EmilAlipiev** [comment]
hi @aritchie, quick question. if we use showloading/hideloading instead of using statement like you wrote above, can this cause memory leak and in order to prevent that we must manually call dispose?

**Comment by aritchie** [comment]
@EmilAlipiev With ShowLoading & HideLoading, I simply store the disposable for you.  Memory doesn't leak since there will only ever be 1 instance.

Before asking questions like this in the future, please browse the source code.  Please be respectful of my time!
