### ISSUE TITLE
UserDialogs is not compatible with popular image processing libraries such as AForge (because of userdialogs dependency on Splat)

### ISSUE THREAD

**Issue by SOFSPEEL** [aritchie/userdialogs#134]
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
[x] iOS
[x] Android
[] WP81
[] WP8
[] UWP
[x] PCL

2) Please state the issue to the best of your ability below

Recent versions of userdialogs that reference Splat are **not** compatible with popular image processing libraries such as AForge which reference shim.dll. The reason is that both Splat.dll and shim.dll have their own implementation of Shim.Drawing. Resulting in compile errors shown below.

**Suggestion**
Does userdialogs really need to reference splat? It seems to me that it would not be necessary to raise dialogs in cross platform, for example, raising a dialog in Android does not require the bitmap support that splat provides.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

![splat](https://cloud.githubusercontent.com/assets/1612646/13574476/1f146b16-e439-11e5-8a5b-586ca9a85959.png)

![shim](https://cloud.githubusercontent.com/assets/1612646/13574490/2bd89d72-e439-11e5-8d39-861652a1a0d7.png)

![image](https://cloud.githubusercontent.com/assets/1612646/13574510/3c12c19a-e439-11e5-8a39-83a6dd2cf15a.png)

**Comment by aritchie** [comment]
Q) Does userdialogs really need to reference splat?
A) Yes, it does.  Splat is used for colors and icon loading for toasts and actionsheets.

**Comment by SOFSPEEL** [comment]
Q) Can you elaborate on how its using color/icons? From the Android/IOS perspective colors and icons are usually provided via Android/IOS Resources?

**Comment by aritchie** [comment]
You are welcome to take a look at the samples and source code of the library itself.  Splat is used specifically so I'm not stuck to the way android or iOS loads this data up.  I wanted this library to be as cross platform as possible.

You are welcome to submit a PR that gives all the same support as splat, but without the library if you want.  I'm afraid it isn't something I specifically want to tackle.
