### ISSUE TITLE
Theme issue with Android M

### ISSUE THREAD

**Issue by Martz94** [aritchie/userdialogs#139]
Hello,

I encounter this [issue](https://stackoverflow.com/questions/33228454/android-6-0-dialog-text-doesnt-appear) on Android M only.

Would be nice to have access to some kind of configuration in the PCL to be able to do something like...
`var dialog = Build.VERSION.SdkInt >= BuildVersionCodes.Lollipop ? 
                new AlertDialog.Builder(this, Android.Resource.Style.ThemeMaterialLightDialogAlert).Create() : 
                new AlertDialog.Builder(this).Create();`

Does someone also has this issue? Is there a workaround I'm not aware of?

Thanks.

**Comment by ferrydeboer** [comment]
To follow up on this. For some reason this problem deceased to exist when using version 4.3.4 be reemerged again once updated to 5.0.0. Due to time constraints I downgraded to 4.3.4.

I noticed that it does however not occur for all our dialogs. I've been looking at the code and it seems that it's dialogs that are created with a FragmentActivity as a top level activity expose this issue while dialogs coming from an AppCompatActivity don't.

**Comment by aritchie** [comment]
This is not an issue with this library.  You can work with this using styles as stated in the original help article.

**Comment by ferrydeboer** [comment]
@aritchie Ok, no issue if I'm doing something wrong here. I don't expect to know everything. :) Please point me to 'the original help article'? Since all documentation I know about is the readme.md which doesn't seem to be mentioning this.

**Comment by aritchie** [comment]
The stackoverflow article mentioned in the first post of this issue will have what you are looking for.  I don't document this because it is android styling which is external to this library.

**Comment by simonwptsg** [comment]
I can see you could define a style for each dialog when using AlertDialog.Builder, but how do you specify a style when using UserDialogs.Instance?
I've got the same issue after upgrading to Marshmallow on a Note 4 with the latest version 5.2.2

**Comment by aritchie** [comment]
Almost every dialog uses alertdialog in this library.

**Comment by aritchie** [comment]
Closing this defect as it is an android styling configuration that the user can perform themselves.  For appcompat alertdialog styling, take a look at http://stackoverflow.com/questions/29797134/how-to-use-and-style-the-new-alertdialog-from-appcompat-22-1-and-above

**Comment by aritchie** [comment]
I have decided to add AndroidStyleId to dialog configurations where appropriate.  You can also set global styles using the static setters Dialog.DefaultAndroidStyleId as 5.3.

**Comment by aritchie** [comment]
Add https://github.com/aritchie/userdialogs/commit/7a56ab00f2f00b082448bb7c096de7e33ea59758
