### ISSUE TITLE
OnCreate & UserDialogs.Init multiple times?

### ISSUE THREAD

**Issue by bobbanks** [aritchie/userdialogs#14]
Hello,

Running in a Xamarin Forms project, is there a best practice for dealing with UserDialogs.Init(Activity) being called multiple times? I can't explain why OnCreate() is firing multiple times but it is.  Safe to just swallow the exception?

**Comment by aritchie** [comment]
Yes or you can check Instance for null before calling Init.  This only happens in android because of the mainactivity being the wake point
