### ISSUE TITLE
AppCompat and Xamarin Forms

### ISSUE THREAD

**Issue by vbisbest** [aritchie/userdialogs#140]
It seems that when coding in Xamarin Forms that you cannot have the latest version of Xamarin Forms and AppCompat 23.1.x.x.   XamForms 2.0 uses app Compat 23.0.x.x so the install of UserDialogs fails.   Is there a way around this or a version of UserDialogs that uses app compat 23.0.x.x

Thanks!

**Comment by aritchie** [comment]
Use 4.2.1.  The problem is xamarin forms uses a specific version of appcompat, while this library uses the latest

**Comment by aritchie** [comment]
This will be updated in the next release.  The appcompat version will be a bit more flexible.
