### ISSUE TITLE
NotFoundException: Resource ID #0x0 in Android when showing an ActionSheet

### ISSUE THREAD

**Issue by chrismcb** [aritchie/userdialogs#141]
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
[] iOS
[x] Android
[] WP81
[] WP8
[] UWP
[] PCL

2) Please state the issue to the best of your ability below
I am trying to use ACR.UserDialogs and I'm getting an error. I tried the sample in ACR.UserDialogs and am getting the same error.
If I use Samples.Droid.Classic, use nuget to get the 4.2 versions of ACR.UserDialogs, and then try to show an Action Sheet I get:

'Android.Content.Res.Resources+NotFoundException: Resource ID #0x0'

when calling 'UserDialogs.Instance.ActionSheet(cfg)'

It feels like I'm doing something wrong in the setup. 

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.
03-31 03:15:34.900 I/MonoDroid(23156): UNHANDLED EXCEPTION:
03-31 03:15:34.908 I/MonoDroid(23156): Android.Content.Res.Resources+NotFoundException: Resource ID #0x0
03-31 03:15:34.908 I/MonoDroid(23156):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2692/e98e9627/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
03-31 03:15:34.908 I/MonoDroid(23156):   at Android.Runtime.JNIEnv.CallObjectMethod (IntPtr jobject, IntPtr jmethod) [0x00063] in /Users/builder/data/lanes/2692/e98e9627/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:178 
03-31 03:15:34.908 I/MonoDroid(23156):   at Android.Support.V7.App.AlertDialog+Builder.Create () [0x00049] in <filename unknown>:0 
03-31 03:15:34.908 I/MonoDroid(23156):   at Acr.UserDialogs.Extensions.ShowExt (Android.Support.V7.App.Builder builder) [0x00000] in C:\dev\libs\userdialogs\src\Acr.UserDialogs.Android\Extensions.cs:31 
03-31 03:15:34.908 I/MonoDroid(23156):   at Acr.UserDialogs.UserDialogsImpl+<>c__DisplayClass6_0.<ActionSheet>b__6 () [0x00000] in C:\dev\libs\userdialogs\src\Acr.UserDialogs.Android\UserDialogsImpl.cs:79 
03-31 03:15:34.908 I/MonoDroid(23156):   at Acr.Support.Android.Extensions.RequestMainThread (System.Action action) [0x00019] in <filename unknown>:0 
03-31 03:15:34.908 I/MonoDroid(23156):   at Acr.UserDialogs.UserDialogsImpl.ActionSheet (Acr.UserDialogs.ActionSheetConfig config) [0x0016b] in C:\dev\libs\userdialogs\src\Acr.UserDialogs.Android\UserDialogsImpl.cs:79 
03-31 03:15:34.908 I/MonoDroid(23156):   at Xamarin.Forms.Command+<>c__DisplayClass2.<.ctor>b__0 (System.Object o) [0x00000] in <filename unknown>:0 
03-31 03:15:34.908 I/MonoDroid(23156):   at Xamarin.Forms.Command.Execute (System.Object parameter) [0x00000] in <filename unknown>:0 
03-31 03:15:34.908 I/MonoDroid(23156):   at Xamarin.Forms.Button.Xamarin.Forms.IButtonController.SendClicked () [0x00011] in <filename unknown>:0 
03-31 03:15:34.908 I/MonoDroid(23156):   at Xamarin.Forms.Platform.Android.ButtonRenderer+ButtonClickListener.OnClick (Android.Views.View v) [0x00015] in <filename unknown>:0 
03-31 03:15:34.908 I/MonoDroid(23156):   at Android.Views.View+IOnClickListenerInvoker.n_OnClick_Landroid_view_View_ (IntPtr jnienv, IntPtr native__this, IntPtr native_v) [0x00011] in /Users/builder/data/lanes/2692/e98e9627/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Views.View.cs:1903 
03-31 03:15:34.908 I/MonoDroid(23156):   --- End of managed exception stack trace ---
03-31 03:15:34.908 I/MonoDroid(23156): android.content.res.Resources$NotFoundException: Resource ID #0x0
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2304)
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.support.v7.app.AlertController$AlertParams.createListView(AlertController.java:734)
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.support.v7.app.AlertController$AlertParams.apply(AlertController.java:711)
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.support.v7.app.AlertDialog$Builder.create(AlertDialog.java:883)
03-31 03:15:34.908 I/MonoDroid(23156): 	at md5d4dd78677dce656d5db26c85a3743ef3.ButtonRenderer_ButtonClickListener.n_onClick(Native Method)
03-31 03:15:34.908 I/MonoDroid(23156): 	at md5d4dd78677dce656d5db26c85a3743ef3.ButtonRenderer_ButtonClickListener.onClick(ButtonRenderer_ButtonClickListener.java:29)
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.view.View.performClick(View.java:4240)
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.view.View$PerformClick.run(View.java:17721)
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.os.Handler.handleCallback(Handler.java:730)
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.os.Handler.dispatchMessage(Handler.java:92)
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.os.Looper.loop(Looper.java:137)
03-31 03:15:34.908 I/MonoDroid(23156): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
03-31 03:15:34.908 I/MonoDroid(23156): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-31 03:15:34.908 I/MonoDroid(23156): 	at java.lang.reflect.Method.invoke(Method.java:525)
03-31 03:15:34.908 I/MonoDroid(23156): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
03-31 03:15:34.908 I/MonoDroid(23156): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
03-31 03:15:34.908 I/MonoDroid(23156): 	at dalvik.system.NativeStart.main(Native Method)
An unhandled exception occured.

**Comment by aritchie** [comment]
The samples don't currently run as they are done in xamarin forms which does not support the latest appcompat library

**Comment by chrismcb** [comment]
Isn't 4.2 supported in Xamarin.Forms?
I actually ran into this problem several months ago, using 4.2. Of course it is possible this issue has been fixed since then, but the release notes don't allude to the issue.

**Comment by aritchie** [comment]
Yes - it is.  Are you using images in your actionsheet?

**Comment by chrismcb** [comment]
Yes, I'm using images. As I mentioned I'm trying to use the sample which does the following:
`            var testImage = BitmapLoader.Current.LoadFromResource("icon.png", null, null).Result;

            for (var i = 0; i < 5; i++)
            {
                var display = (i + 1);
                cfg.Add(
                    "Option " + display,
                    () => this.Result($"Option {display} Selected"),
                    testImage
                );
            }
`

Yes the sample has icon.png in the Resources. But the problem happens on the call to `UserDialogs.Instance.ActionSheet(cfg)`
not on the LoadFromResource call.

**Comment by aritchie** [comment]
ok, but I mentioned, the sample is currently broken.  Just use it as a code base for the time being.
