### ISSUE TITLE
Toast that allows interaction with the view

### ISSUE THREAD

**Issue by jded76** [aritchie/userdialogs#144]
I would like to allow user input while showing a toast.

For example I want to show a toast message when user press the back button like this:
"Press back again to exit" and if he press back again in 2 seconds to exit the application.

I red on AndHUD : MaskType.None to allow interaction with views behind the HUD.

Is there any possibility to have this option? 

Thank you for your great work anyway.

**Comment by aritchie** [comment]
Use the appcompat version of user dialogs, it shouldn't block

**Comment by jded76** [comment]
I cannot. 
I'm using XLabs and I can't switch to appcompat yet...

**Comment by aritchie** [comment]
You ah e a few choices then
- you can override the functionality for the toast on android
- play with the samples and see if you can get your test case to work.  Submit a PR and I'll see about putting it into the library
- break the dependency you have somehow

**Comment by jded76** [comment]
I saw that on Android implementation you don't use the background property of the config at all. 

What do you think if we change that to check if background color is transparent set the 	AndroidHUD.MaskType.Black to MaskType.None or else leave as it is? 

Change only line 246 on src/Acr.UserDialogs.Android/UserDialogsImpl.cs

**Comment by rubgithub** [comment]
According to this post https://github.com/XLabs/Xamarin-Forms-Labs/issues/998 there is no issues using XLabs and appcompact, did you test it?

I'm testing XLabs (very initial testing) and it is working fine.

**Comment by aritchie** [comment]
I'm changing the MaskType to none in any case for the next version
