### ISSUE TITLE
Acr.Support 2.0.2 pushed to Nuget, but Acr.UserDialogs depends on < 2.0

### ISSUE THREAD

**Issue by PelleRavn** [aritchie/userdialogs#145]
1) Please check all of the platforms you are having the issue on
[x] iOS
[x] Android
[] WP81
[] WP8
[] UWP
[] PCL

2) Please state the issue to the best of your ability below
You recently published Acr.Support 2.0.2 to Nuget, but UserDialogs still depends on less than 2.0.

**Comment by aritchie** [comment]
Why is this a problem?

**Comment by PelleRavn** [comment]
It's not exactly a problem, but the result is that you can't update to the Acr.Support 2.0.2 nuget, because Acr.UserDialogs prevents you, since it only depends on < 2.0.0. 
Just mentioning it, because it seems odd, and in case it was a mistake.

**Comment by aritchie** [comment]
I use the support library for several of my internal libraries.  User dialogs will catch up shortly.
