### ISSUE TITLE
Toasts sometimes get stuck

### ISSUE THREAD

**Issue by highplains** [aritchie/userdialogs#147]
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
[X] iOS
[] Android
[] WP81
[] WP8
[] UWP
[] PCL

2) Please state the issue to the best of your ability below
Toasts sometimes get stuck when navigating between views and wont disappear until tapped.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.
- NO crash.

Is there a way to forcibly dismiss the active toast?

**Comment by aritchie** [comment]
The toasts are supposed to dismiss themselves.  Do you have a test case to reproduce this?

**Comment by aritchie** [comment]
No reply with test case.  Please reopen with test case
