### ISSUE TITLE
Custom Dialogs

### ISSUE THREAD

**Issue by ChaseFlorell** [aritchie/userdialogs#15]
Hey Allan, I'm wondering about the possibility to create custom dialogs for xamarin forms. Have you attempted this? Is it even possible? Essentially I want to create an editor with two fields, but have it display similar to an action sheet. Thoughts?

**Comment by aritchie** [comment]
Hi Chase.  This doesn't really fit into what I do with this library.  This library needs to live for single purpose, single line calls for a response.  What you are asking for is more of a full viewmodel binding setup.  

Making a custom dialog in any of the platform (or via custom renderers in xamarin forms) is pretty straight forward though.

**Comment by ChaseFlorell** [comment]
yep, I agree. I've done a few custom renderers, but I've never done native dialogs, so I'm not sure where I'd begin.
