### ISSUE TITLE
UWP Only a single ContentDialog can be open at any time

### ISSUE THREAD

**Issue by alinapopa** [aritchie/userdialogs#152]
UWP only allows one ContentDialog to be open at any time.
When using ACR User Dialogs on UWP, how can I control the number of ContentDialogs that are open in my application?

**Comment by aritchie** [comment]
not really sure how to answer this since there are many ways to go about that, but they would be external to anything this library does

**Comment by aritchie** [comment]
The library doesn't control what you open/close.  That responsibility lies with the app.  If you are trying to open loading dialogs within contentdialogs, this could be an issue obviously.  I'm looking into ways in the future to show the overlays better.
