### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by balivo** [aritchie/userdialogs#153]
1) Please check all of the platforms you are having the issue on
[x] WP81

4.3.4 version

An exception of type 'System.TypeLoadException' occurred in XXXXXX.WinPhone.ni.EXE but was not handled in user code

Additional information: Could not load type 'Acr.UserDialogs.Acr_UserDialogs_WP81_XamlTypeInfo.XamlMetaDataProvider' from assembly 'Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by aritchie** [comment]
Please read the readme.md.  I do not support wp8

**Comment by balivo** [comment]
Tks @aritchie but, at Nuget Package description WP81 is supported, any plans to offer WP81 support?

**Comment by aritchie** [comment]
No.  Useless platform to me
