### ISSUE TITLE
Android build errors with latest stable release of Xamarin Forms 

### ISSUE THREAD

**Issue by dommoore** [aritchie/userdialogs#155]
Hi
I've just upgraded to the latest stable version of Xamarin Forms (2.2.0.31 from 2.1.0.6529) and my previously working Android project now fails to build. There are about 114 build errors of the type:
```
_\Resources\Resource.Designer.cs 
error CS0117: 'Resource.Styleable' does not contain a definition for 'Theme_windowMinWidthMajor'_
```
The ResourceDesigner itself shows missing references such as:

`global::Acr.UserDialogs.Resource.Styleable.Theme_windowMinWidthMinor = global::PrismFormsPlayground.Droid.Resource.Styleable.Theme_windowMinWidthMinor`

All missing resources relate to the Acr.UserDialogs.
I have the latest Android SDKs and so on. 
If I uninstall Acr.UserDialogs then everything builds again.

Could this be an issue with the userdialogs dependencies?

Thanks

**Comment by dommoore** [comment]
Forgot to mention the obvious: the versions of Xamarin.Android.Support.v4 et. al. are also upgraded as part of the update.

**Comment by aritchie** [comment]
Please read the numerous dupes on this and the readme.  This library has nothing to do with xamarin forms.

**Comment by aritchie** [comment]
Use v5 that was just released.  It should solve this once and for all.

**Comment by dommoore** [comment]
v5 works great. Thank you.
