### ISSUE TITLE
iOS back ground problems

### ISSUE THREAD

**Issue by schiari** [aritchie/userdialogs#158]
I have installed version 5 and I'm using Xamarin.Forms Version 2.2.
When I use UserDialogs.Instance.ShowSuccess or UserDialogs.Instance.ShowError, on Android a dark backgroud is displayed, on iOS is NOT displayed which makes this alert message pretty unreadable when the page behind is mostly white.
On iOS I just get the message and the icon in the center of the screen but no dark background.

Example code on iOS:
UserDialogs.Instance.ShowSuccess("Data saved correctly");

How can I solve it ?

**Comment by aritchie** [comment]
This will be available in 5.1
