### ISSUE TITLE
App Crashed when 'await UserDialogs.Instance.ConfirmAsync(config);'

### ISSUE THREAD

**Issue by yz1311** [aritchie/userdialogs#161]
Platform:Android(called in PCL)
I call 'await UserDialogs.Instance.ConfirmAsync(config);' in  a async method 

Library Version:
5.0.1(5.0)  ---   App Crashed
4.2.1   ----  Everything is OK

Exception:
`UnhandledException:Java.Lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <filename unknown>:0 
  at Android.Runtime.JNIEnv.CallObjectMethod (IntPtr jobject, IntPtr jmethod) [0x00069] in <filename unknown>:0 
  at Android.App.AlertDialog+Builder.Show () [0x00049] in <filename unknown>:0 
  at Acr.UserDialogs.UserDialogsImpl.Show (Android.App.Builder builder) [0x00005] in <filename unknown>:0 
  at Acr.UserDialogs.UserDialogsImpl.Confirm (Acr.UserDialogs.ConfirmConfig config) [0x00040] in <filename unknown>:0 
  at Acr.UserDialogs.AbstractUserDialogs.ConfirmAsync (Acr.UserDialogs.ConfirmConfig config) [0x00023] in <filename unknown>:0 `

**Comment by aritchie** [comment]
What version of android did this occur on?  Everything is wrapped in the usual main thread request.

**Comment by yz1311** [comment]
The version of the OS is v4.4.4. Here is the code:

`private ICommand _submitCommand;
		public ICommand SubmitCommand
		{
			get{ 
				return _submitCommand??(_submitCommand=new Command(
					async ()=>{
						await Task.Run(async ()=>{
							var loading=UserDialogs.Instance.Loading("正在提交...");
							loading.Show();
							loading.Title="正在验证数据...";
					
							var config = new ConfirmConfig()
							{
								Title = "提示",
								Message = "是否提交?",
								OkText = "提交",
								CancelText = "取消"
							};
							var confirmResult = await     UserDialogs.Instance.ConfirmAsync(config);
}});}`

**Comment by aritchie** [comment]
You're actually spawning 2 tasks here.  Try removing the Task.Run and just use the async from the command.  That may help.  

This is still a defect in user dialogs in any case

**Comment by aritchie** [comment]
I have been unable to reproduce this.  However, I have made some updates to the ui thread management.  Try 5.1 and let me know please.  If the problem persists, please reopen this thread with any new info.

**Comment by yz1311** [comment]
Removing Task.Run works,but there are too much places to modify ,so i still use v4.2.1.
I just tried v5.1,the issue still exists.
The command is synchronized ,i use Task.Run to do a heavy work,I come to know that it is not necessary to put  the heavy work  in Task.Run,just behind loading.Show();
Thanks for your excellent work!
