### ISSUE TITLE
iOS: Wrong icons on ShowSuccess and ShowError methods

### ISSUE THREAD

**Issue by timbrand** [aritchie/userdialogs#162]
1) Please check all of the platforms you are having the issue on
[X] iOS
[] Android
[] UWP
[X] PCL

2) Please state the issue to the best of your ability below
ShowSuccess() and ShowError() are probably using the wrong icon since 5.1.0. I guess it shows a progress indicator (circle that fills).

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

Just use one of the following lines to see the issue.
`UserDialogs.Instance.ShowSuccess ("Test");`
`UserDialogs.Instance.ShowError ("Test");`

**Comment by timbrand** [comment]
a temporary 'fix' is to add the success* and error* images from https://github.com/nicwise/BTProgressHUD/tree/master/BTProgressHUD to your recources folder.

**Comment by aritchie** [comment]
It looks like xamarin changed the way the bundles are brought in at some point.  I have internalized btprogresshud in 6.1 to fix this issue

**Comment by Spierki** [comment]
@aritchie this error already exist in last nuget package : 6.3.1

**Comment by aritchie** [comment]
There isn't much I can do to fix this currently.  Use the workaround listed above.
