### ISSUE TITLE
Error compiling my XF project (Only Android / Release)

### ISSUE THREAD

**Issue by acaliaro** [aritchie/userdialogs#163]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
[] iOS
[X] Android
[] UWP
[] PCL

2) Please state the issue to the best of your ability below
I have a XF project with Android and iOS. In Android /Debug it works. If I switch to Release and try to recompile, I have this error (see above)

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

[https://www.dropbox.com/s/yx5acp08n4u56ty/Screenshot%202016-05-09%2023.58.00.png?dl=0](https://www.dropbox.com/s/yx5acp08n4u56ty/Screenshot%202016-05-09%2023.58.00.png?dl=0)

**Comment by karlwan1010** [comment]
Same issue happens here, but fails for both Debug/ Release build. I have used the "Don't Link" option to skip the issue temporarily for the development.

**Comment by acaliaro** [comment]
@karlwan1010 "Don't Link" in Release mode works but Archive is not created.

**Comment by acaliaro** [comment]
@aritchie have you an eta for this?

**Comment by aritchie** [comment]
Never come on here and ask for ETAs!  If you can't wait, downgrade or fix it yourself.  

As it is, this fix was part of a larger update was pulled due to a Xamarin iOS defect that can't be fixed at the moment.  You can try 5.2-beta1 or downgrade to 5.0.1.

**Comment by acaliaro** [comment]
Adam it was only a question

**Comment by aritchie** [comment]
I find it very inconsiderate to ask this of any OSS project.  I do my best to read every defect & feature request that comes through here as quickly as possible.  I ask for nothing and give my time to support all of these libraries.  These types of questions are not welcome here in the future.  

In any case, you have potential workarounds to this issue.
