### ISSUE TITLE
Login Dialog, just enable the password entry

### ISSUE THREAD

**Issue by Lug16** [aritchie/userdialogs#168]
Hi everyone,

First of all congrats for your library it is really nice.

I'm using the following library Acr.UserDialogs.4.2.1 and maybe it is not an issue just a feature.
It is possible to enable just the password entry and disable(lock) the userName entry in the login dialog? 
And, can I indicate the Keyboard type of the password (for example Numeric)?

Thanks

**Comment by aritchie** [comment]
Not the login dialog.  however you can use the prompt dialog with the input type of NumericPassword to accomplish your use case.  Take a look at the samples to see how to accomplish this

**Comment by Lug16** [comment]
You're absolutely right, Thank you aritchie
