### ISSUE TITLE
[iOS] DatePicker DatePromptConfig.SelectedDate is not taken in consideration

### ISSUE THREAD

**Issue by IlSocio** [aritchie/userdialogs#170]
1) Please check all of the platforms you are having the issue on 
 [x] iOS
 [ ] Android
 [ ] UWP
 [ ] PCL

2) Please state the issue to the best of your ability below
On iOS the DatePromptConfig.SelectedDate parameter is ignored when showing the dialog.
The dialog shows the current date without taking in consideration the input parameter.

**Comment by aritchie** [comment]
Please refrain from these defects for now since the code isn't actually enabled right now.  This code was removed from iOS for a reason.  Some of these are duplicates of my internal list.

**Comment by aritchie** [comment]
released with 5.2
