### ISSUE TITLE
iOS: ShowSuccess is masking/dimming the background

### ISSUE THREAD

**Issue by timbrand** [aritchie/userdialogs#171]
1) Please check all of the platforms you are having the issue on
 
 - [X] iOS
 - [] Android
 - [] UWP
 - [X] PCL

2) Please state the issue to the best of your ability below
- I just switched to 5.2.0-beta1 and now the ShowSuccess method is dimming the background. Which it didn't before.
I prefere to not dim the background, or to have the option to change this (shared or method option).

**Comment by aritchie** [comment]
There is only so many options I have with the current HUD.  This is likely going to be the behaviour for now

**Comment by timbrand** [comment]
Oke.
I just switched back to check it, and noticed in the previous releases the background was dimming too, but way lighter then it is now.
So if it's possible to easily bringing back the previous 'color' would be enough.

Thanks!

**Comment by aritchie** [comment]
I have turned down the alpha to 0.7 in 5.2
