### ISSUE TITLE
Exception using LoginDialog on iOS 7.1

### ISSUE THREAD

**Issue by hgiritzer** [aritchie/userdialogs#173]
1) Please check all of the platforms you are having the issue on
 
 - [X] iOS
 - [] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below
Exception occurs on iOS 7.1 (not on iOS 9, not on Android) when calling:
var result = await Acr.UserDialogs.UserDialogs.Instance.LoginAsync(
    new Acr.UserDialogs.LoginConfig() { Message = "Login", LoginPlaceholder = "Name" });

Nuget packages installed:
Xamarin.Forms v2.2.0.31
Acr.Support v2.0.2
Acr.XamForms.UserDialogs v5.0.0
Acr.UserDialogs v5.0.1         --> causes exception stack trace # 1, see below
Acr.UserDialogs v5.2.0-beta1   --> causes exception stack trace # 2, see below

Device: iPad 2 running iOS 7.1

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.
exception stack trace # 1
```
System.NullReferenceException: Object reference not set to an instance of an object
at Acr.UserDialogs.UserDialogsImpl.Login (Acr.UserDialogs.LoginConfig config) [0x00042] 
in C:\dev\modules\userdialogs\src\Acr.UserDialogs.iOS\UserDialogsImpl.cs:95 
at Acr.UserDialogs.AbstractUserDialogs.LoginAsync (Acr.UserDialogs.LoginConfig config) [0x00023] 
in C:\dev\modules\userdialogs\src\Acr.UserDialogs.Interface\AbstractUserDialogs.cs:197 
at MyApp.DetailLegalPage+<OnLoginClicked>d__3.MoveNext () [0x00018] 
c:\MyProjects\MyApp\DetailLegalPage.xaml.cs:55
```
exception stack trace # 2
```
System.NullReferenceException: Object reference not set to an instance of an object
at Acr.UserDialogs.UserDialogsImpl.Login (Acr.UserDialogs.LoginConfig config) [0x00042] 
in C:\dev\modules\userdialogs\src\Acr.UserDialogs.iOS\UserDialogsImpl.cs:104 
at Acr.UserDialogs.AbstractUserDialogs.LoginAsync (Acr.UserDialogs.LoginConfig config, Nullable`1 cancelToken) [0x00023] 
in C:\dev\modules\userdialogs\src\Acr.UserDialogs.Interface\AbstractUserDialogs.cs:230 
at MyApp.DetailLegalPage+<OnLoginClicked>d__3.MoveNext () [0x00018] in 
c:\MyProjects\MyApp\DetailLegalPage.xaml.cs:55
```

**Comment by aritchie** [comment]
I'm only really supporting iOS8 and iOS9 at this point.  Too many use cases to support.

**Comment by hgiritzer** [comment]
The release notes of v5.0.0 mentioned the drop of iOS 6 support, so I hoped that iOS 7 would be still fine. 
Well, I understand your point, and I like to thank you for your great work.

**Comment by aritchie** [comment]
That is actually a mistake.  I'm inly working with uialertcontroller which is actually 7, not 6
