### ISSUE TITLE
[Android] Warning TargetFrameworkVersion for Acr.UserDialogs.dll v6.0.99

### ISSUE THREAD

**Issue by IlSocio** [aritchie/userdialogs#174]
1) Please check all of the platforms you are having the issue on 
[] iOS
[x] Android
[] UWP
[] PCL

2) Please state the issue to the best of your ability below
I'm using UserDialogs v5.0.1 in a project which target API v23 and I'm getting the warning below.
I suppose you've compiled the library using the API v23 N preview, or some other alpha sdk release.
As my understanding, in order to properly provide backward compatibility, you should compile the UserDialog library against the lowest API level which is supported by your library.
Otherwise, the users of your library will be forced to compile their projects using the very latest sdk.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

Warning		
The $(TargetFrameworkVersion) for Acr.UserDialogs.dll (v6.0.99) is greater than the $(TargetFrameworkVersion) for your project (v6.0)
You need to increase the $(TargetFrameworkVersion) for your project.

**Comment by aritchie** [comment]
It is rarely a big deal anymore.  We're running this on a 4.0 device without issue.  5.2 is being compiled against stable, but the xamarin stable isn't very stable right now on the iOS side which is why 5.2 isn't out

**Comment by IlSocio** [comment]
The issue is more related to the fact that some methods are not available on lower API levels, so, if you're compiling the library with the API 23 you'll risk to use some methods that are not present in api 22 / 21 / 20 / 19

As more concrete example, the methods TimePicker.Hour and TimePicker.Minute you're using on UserDialog v5.2:
https://github.com/aritchie/userdialogs/blob/v5.2/src/Acr.UserDialogs.Android/Builders/TimePromptBuilder.cs#L23
were introduced only in api 23:
https://developer.android.com/reference/android/widget/TimePicker.html#setHour(int)
So, the TimePicker provided by the UserDialog v5.2 will crash when will be used on any application compiled for lollipop, kit kat, jellybean...
In order to use the UserDialog v5.2 TimePicker, the application will be forced to set marshmellow as compilation target, because your library is using methods from API v23.

If, on UserDialog v5.2 you want to support also applications compiled for lollipop, kit kat, jellybean, you'll need to set a lower api level... and use the TimePicker.CurrentHour and TimePicker.CurrentMinute


As general rule, according to the best practices below, you should compile the UserDialogs using the very minimum API level:
https://developer.xamarin.com/guides/android/application_fundamentals/understanding_android_api_levels/
"When creating an Android library – If you are creating an Android library for use by other applications, be sure to set its target framework setting to the minimum API level that it needs in order to compile."
By compiling using the minimum API level you want to support, you'll be sure you're not using any methods that have been introduced only in higher API level.
