### ISSUE TITLE
Android Init() and MVVMCross

### ISSUE THREAD

**Issue by IlSocio** [aritchie/userdialogs#18]
Hello,
how can I use this updated UserDialogs in MVVMCross?
Probably, I'm not initializing properly the UserDialog instance...

I tried the code below and I get the userdialog instance from the viewmodel, but dialog is not shown in the UI...
in setup.cs:
  UserDialogs.Init(() => (Activity)Android.App.Application.Context);
  builder.RegisterInstance(UserDialogs.Instance).As<IUserDialogs>();

in viewmodel.cs:
            InvokeOnMainThread(() => 
                {
                IUserDialogs dlg = Mvx.Resolve<IUserDialogs>();
                if (dlg == null)
                    return;
                dlg.ShowLoading();
                });

I successfully integrated the MVVMCross specific plugin and it works properly: https://www.nuget.org/packages/Acr.MvvmCross.Plugins.UserDialogs/ 
but I would prefer using this generic and updated version.

Thanks,
Marco.

**Comment by aritchie** [comment]
UserDialogs.Init(() => Mvx.Resolve<IMvxAndroidCurrentTopActivity>().Activity);

**Comment by aritchie** [comment]
As an FYI, all of the user dialog methods will invoke on the main thread themselves

**Comment by IlSocio** [comment]
Thank you Ritchie! :)

Actually, we had to add the InvokeOnMainThread() because the iOS version of ProgressDialog seems to miss the: UIApplication.SharedApplication.InvokeOnMainThread
https://github.com/aritchie/userdialogs/blob/8706f18898f1a057b9b838e61081df69c675e98c/src/Acr.UserDialogs.iOS/ProgressDialog.cs

**Comment by aritchie** [comment]
btprogresshud does it internally

**Comment by IlSocio** [comment]
Thank you Ritchie! It properly works! 
For further reference, in the current MVVMCross v3.5 I had to initialize the dialog with the code below:
UserDialogs.Init(() => Mvx.Resolve<IMvxAndroidCurrentTopActivity>().Activity;

**Comment by IlSocio** [comment]
Ritchie, FYI, on iOS, there is an UIKitThreadAccessException when showing the progress dialog from a background thread... 
It happens because the access to the UIScreen.MainScreen, is still done on background thread:
https://github.com/nicwise/BTProgressHUD/blob/master/BTProgressHUD/ProgressHUD.cs#L189

I just opened the issue below:
https://github.com/nicwise/BTProgressHUD/issues/37

**Comment by aritchie** [comment]
I have an update coming that will wrap the calls in UI thread dispatcher.

Great find on this.  Thanks

**Comment by IlSocio** [comment]
Thank you Richie, but actually, my suggestion was to remove all the InvokeOnMainThread / RunOnUiThread calls from UserDialogs (and removing them from BTProgressHUD too)

The developers should take care of switching to the main thread when using UserDialogs control, like we already do when using any other gui controls which is embedded in the framework.
Doing it inside UserDialogs, kills the performances and it's not needed, because in any case, the developers will have to switch on the main thread just to update a simple label...

**Comment by aritchie** [comment]
I would normally agree to that, but the whole MVVM architectures delegate UI thread dispatching as well.  This library should match that behaviour.  

Performance shouldn't really ever be an issue (at least with regards to what you would do with this library), so it is the argument of simplicity vs performance.
