### ISSUE TITLE
Prompt fired from Actionsheet stops working (API 16)

### ISSUE THREAD

**Issue by Lug16** [aritchie/userdialogs#182]
Hi everyone,

I hope you can reproduce this: I have an **ActionSheet with 4 buttons**, everyone of them fires a Promp for some input (**NumericPassword**). The ActionSheet works fine displaying every Promp with no problem, but the issue is when I want to write inside the promp (NumericPassword), the **keyboard only shows up for the first and second button** from the ActionSheet, after that none of the Promp windows display the keyboard.

It is happening in Api 16+, but is working fine in API 23+

Hope you can take a look on the issue.

Thank you

**Comment by aritchie** [comment]
Run an task delay of 500ms inside of the action sheet callback and see what happens.

**Comment by Lug16** [comment]
Nope... the same..

`        Action OnLogin()
        {
            var users = data.GetItems<User>().Select(r => new UserExtension(r));

            var options = users.Select(
                r => new Acr.UserDialogs.ActionSheetOption(r.User.Name,
                    async () =>
                    {
                        await Task.Delay(500);
                        SetLoginWindow(r.User, () => { PromptUser(r.User); });
                    },
                    BitmapLoader.Current.LoadFromResource(r.Icon, null, null).Result)).ToList();

            return () =>
            {
                Acr.UserDialogs.UserDialogs.Instance.ActionSheet(new Acr.UserDialogs.ActionSheetConfig
                {
                    Title = Properties.Resources.Login,
                    Options = options,
                    Cancel = new Acr.UserDialogs.ActionSheetOption(Properties.Resources.Cancel)
                });
            };
        }

        private void SetLoginWindow(User user, Action onSuccess)
        {
            //Si el usuario esta en el rol de Attendant y no esta conectado no le deja loguearse
            var userrole = data.GetItems<UserRole>().Where(r => r.IdUser == user.Id).First();
            var role = data.GetItems<Role>().Where(r => r.Id == userrole.IdRole).First();

            if (role.Name == PrintLink.Properties.Resources.Attendant && !isConnected)
            {
                Acr.UserDialogs.UserDialogs.Instance.ShowError(Properties.Resources.ConnectToDeviceFirst);
                return;
            }

            Acr.UserDialogs.UserDialogs.Instance.Prompt(new Acr.UserDialogs.PromptConfig()
                {
                    InputType = Acr.UserDialogs.InputType.NumericPassword,
                    IsCancellable = true,
                    Message = string.Format(Properties.Resources.InsertPasswordOf, user.Name),
                    Placeholder = Properties.Resources.Password,
                    OnResult = (e) =>
                        {
                            if (e.Text != user.Password)
                                Acr.UserDialogs.UserDialogs.Instance.ErrorToast(Properties.Resources.LoginInvalid);
                            else
                                onSuccess.Invoke();
                        }
                });
        }`

**Comment by aritchie** [comment]
You should see some sort of warning in logcat.. Please copy/paste that.  Also, what does the current activity inherit from where you call this code?

**Comment by Lug16** [comment]
Right! there is a message...

06-02 15:37:50.888 V/InputMethodManagerService(  547): SoftKeypad Hide Broadcast

06-02 15:39:06.249 W/InputMethodManagerService(  547): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@42a32c30 attribute=null


But I dont know what it is...

**Comment by aritchie** [comment]
What are you inheriting from at your top level activity where you are calling this from?

**Comment by Lug16** [comment]
This is called from a normal ContentPage, in its main thread.
I mean, it is working great in API >= 23, but in 16 stoped to work for those Prompts fired from the 3d button in an ActionSheet.

**Comment by aritchie** [comment]
That is not what I'm asking.  Since you're using forms, what is your main activity inheriting from?

**Comment by Lug16** [comment]
My bad,

In Android:
`public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsApplicationActivity, IDataConsumer`

In Forms
`public class MainPage : NavigationPage`

Hope this answer your question...

**Comment by aritchie** [comment]
That's what I needed.  I'll take a look.  No promises.. This looks more like a droid defect.  You can try setting an even longer delay (1 second).  The main goal is to make sure the action sheet is fully closed and that its fade animation has finished

**Comment by aritchie** [comment]
While I can reproduce this issue, it does appear to be an issue due to android, so there isn't really much I'm willing to do to fix this.  I don't consider the use case something I would ever do anyhow.

Sorry... Best of luck

**Comment by Lug16** [comment]
Ok aritchie, when The OS is the enemy not that much to do. Thank you so much for taking the time to take a look on it.

God bless
