### ISSUE TITLE
Edittext padding in Prompt

### ISSUE THREAD

**Issue by KennethKr** [aritchie/userdialogs#183]
1) 
 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

2) 

The EditText component have no padding in the prompt dialog, making it ugly.

![promptpadding](https://cloud.githubusercontent.com/assets/1160628/15776860/3af3c024-298b-11e6-85cf-3a4d985af117.png)

One solution to customization in general (in addition to fixing the default dialog) could be to enable users to config a default theme for UserDialogs in Android. For example in the init method, or in one of the static config classes.

**Comment by aritchie** [comment]
You can theme appcompat dialogs without any changes here.   http://stackoverflow.com/questions/29797134/how-to-use-and-style-the-new-alertdialog-from-appcompat-22-1-and-above
