### ISSUE TITLE
Problem finding Top ViewController since Dialogs 5.2.2., Support 2.0.2 (iOS)

### ISSUE THREAD

**Issue by MartHugh** [aritchie/userdialogs#184]
I started adding this issue here.  

http://forums.xamarin.com/discussion/68253/5-2-2-update-to-acr-dialogs-breaks-existing-code#latest

Basically, since doing the packages update trying to use the code shown in the link above causes a null reference exception, suggesting that ACR.Support cannot get hold of the top ViewController.

Code is being called from within a UIViewController ViewDidLoad event, which in turn was loaded by a UITabBarController which is the top view controller.

There is no issue with earlier libraries, I can switch projects to just before I did the update and it works OK. 

Many thanks for any suggestions.

**Comment by aritchie** [comment]
Can you provide a reproducible case please.  I use this in a bunch of places with uitabcontrollers (even the sample is in one) and i haven't had this issue

**Comment by MartHugh** [comment]
Hi Allan.  I was just in the middle of doing this and I noticed a smoking gun in my code.  For some reason the TabController is receiving TWO ViewDidLoad events at startup.   I just bet that the second one would dereference the original objects in the hierarchy, which might make it look like the top viewcontroller has been dereferenced.   

So I don't think this is a problem with your library, although, I have read in the Apple docs that all code needs to be able to handle multiple ViewDidLoad events, because it is at the discretion of the framework as to how many it may send, if that causes problems for obtaining the handle to the top UIViewController than that may be something you want to look at ?

Thanks again for your response.
