### ISSUE TITLE
Can't override the implementation in android (ver.5.22)

### ISSUE THREAD

**Issue by tmclouisluk** [aritchie/userdialogs#185]
When build the solution, error occurs: 
`'Acr.UserDialogs.UserDialogsImpl' does not contain a constructor that takes 0 arguments
`

I override public class CustomUserDialogs : UserDialogsImpl and set UserDialogs.Instance = new Services.CustomUserDialogs(); in MainActivity.

**Comment by aritchie** [comment]
So add the required parameter to your constructor and pass it to the base implementation.
