### ISSUE TITLE
Method 'IUserDialogs.ActionSheet' not found

### ISSUE THREAD

**Issue by LWChris** [aritchie/userdialogs#187]
1) Please check all of the platforms you are having the issue on
 
 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] PCL

2) I'm trying to open an ActionSheet via UserDialogs.Instance.ActionSheet(ActionSheetConfig).

This issue came into being after updating the NuGet packages via NuGet package manager.

Changes in the PCL project references, according to SVN:
- **Acr.UserDialogs.4.2.1** updated to **Acr.UserDialogs.5.2.2** for _Acr.UserDialogs_ and _Acr.UserDialogs.Interface_

Changes in the Android project references, according to SVN:
- **Acr.Support.1.1.1** updated to **Acr.Support.2.1.0** for _Acr.Support.Android_
- **Acr.UserDialogs.4.2.1** updated to **Acr.UserDialogs.5.2.2** for _Acr.UserDialogs_ and _Acr.UserDialogs.Interface_
- **Acr.UserDialogs.4.2.1** changed to **AndHUD.1.2.0** for _AndHUD_

3) Exception details from the "Output" window:

> System.MissingMethodException: Method 'IUserDialogs.ActionSheet' not found.

- Smartphone: HUAWEI Y550-L01, Android 4.4, API 19
- App was running fine just before the package update.

**Comment by aritchie** [comment]
Make sure you uninstall the appcompat Nuget package as it is no longer required.  Best bet is to uninstall all Acr.userdialog packages and reinstall

**Comment by LWChris** [comment]
Are you talking about the Xamarin.Android.Support.v7.AppCompat library? Isn't that required by Xamarin.Forms?

**Comment by aritchie** [comment]
No.  Just uninstall all Acr libraries and reinstall.

**Comment by LWChris** [comment]
I now uninstalled Acr.XamForms.UserDialogs, Acr.UserDialogs and Acr.Support (in that order); Acr.UserDialogs.Android.AppCompat was not installed if you referred to that.

I then carefully rebuilt all my projects in their dependency order.

My findings: when I build them and run the app in "Release" mode, it works. When I build the projects and run the app in "Debug" mode, the error occurs.

**Comment by aritchie** [comment]
Delete your bin/obj folders.  This is a typical thing with xamarin.  And with that, I do consider this a case closed as your issue is external to this library
