### ISSUE TITLE
ArgumentNullException in UWP

### ISSUE THREAD

**Issue by LSMadsen** [aritchie/userdialogs#188]
**1) Please check all of the platforms you are having the issue on**
 - [x] UWP
 - [x] PCL

**2) Please state the issue to the best of your ability below**
I have just added UWP to my Xamarin-project, but I get some wierd behavior from Acr.UserDialogs.

When using PromptAsync and Confirm I get 2 ArgumentNullExceptions.
How can I fix these?

I am using these NuGet packages (in UWP project)

    Acr.UserDialogs                              v5.2.2
    Acr.XamForms.UserDialogs                     v5.0.0
    Microsoft.NetCore.UniversalWindowsPlatform   v5.1.0
    MR.Gestures                                  v1.3.4
    SQLite.Net-PCL                               v3.1.1
    Xam.Plugins.Settings                         v2.1.0
    Xamarin.Forms                                v2.2.0.45
    Xamarin.Insights                             v1.12.3
    XLabs.Forms                                  v2.2.0-pre02

I hope for your help.

**3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.**

Exception thrown: 'System.ArgumentNullException' in mscorlib.ni.dll
Exception thrown: 'System.ArgumentNullException' in mscorlib.ni.dll

When running e.g.

    return await UserDialogs.Instance.PromptAsync(new PromptConfig
    {
       Title = title,
       Message = message,
       OkText = positiveText,
       CancelText = negativeText,
       InputType = InputType.Default,
       IsCancellable = !String.IsNullOrWhiteSpace(negativeText)
    }, CancellationToken.None);

**Comment by aritchie** [comment]
I need the entire stacktrace of your exception please

**Comment by LSMadsen** [comment]
I got this from Immediate Window

    Message: "Value cannot be null."
    ParamName: null
    Source: "mscorlib"
    StackTrace: "   at System.StubHelpers.HStringMarshaler.ConvertToNativeReference(String managed, HSTRING_HEADER* hstringHeader)\r\n   at Windows.UI.Xaml.Controls.TextBox.put_PlaceholderText(String value)\r\n   at Acr.UserDialogs.UserDialogsImpl.SetDefaultPrompt(ContentDialog dialog, StackPanel stack, PromptConfig config)\r\n   at Acr.UserDialogs.UserDialogsImpl.Prompt(PromptConfig config)\r\n   at Acr.UserDialogs.AbstractUserDialogs.PromptAsync(PromptConfig config, Nullable`1 cancelToken)"

**Comment by aritchie** [comment]
Fixed in 5.3/6.0beta

**Comment by LSMadsen** [comment]
When are you going to release 5.3 as NuGet stable?

**Comment by aritchie** [comment]
Whenever I have time to finish it
