### ISSUE TITLE
PromptAsync's OK-button executes Button on page

### ISSUE THREAD

**Issue by LSMadsen** [aritchie/userdialogs#189]
**1) Please check all of the platforms you are having the issue on**
 - [X] UWP
 - [X] PCL

**2) Please state the issue to the best of your ability below**
I have a simple page where a PromptDialog is shown above a button on the page. When I press OK, the button on the page is executed too.
Do I have to create a boolean to prevent it from running? Or is there another workaround?
It is running fine on Android and iOS. 

**3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.**
None

**Comment by aritchie** [comment]
It is a simple message dialog.  It is more likely picking up a double tap issue which isn't really anything I can solve.  Button click closes dialog, secondary click is catching on your screens

**Comment by LSMadsen** [comment]
No, I only click once, when this happens.

**Comment by aritchie** [comment]
It is a dialog box and is blocking all other content underneath it.  I can't reproduce this in the sample code either and this has an overlap like what you are describing.  Feel free to provide a reproducible case or suggestion.  I don't have the time to investigate this further otherwise.

**Comment by LSMadsen** [comment]
I figured out, it is a bug in MR.Gestures Tapped event on the Grid below
