### ISSUE TITLE
UserDialogs and Universal Apps (WinRT)

### ISSUE THREAD

**Issue by IlSocio** [aritchie/userdialogs#19]
Hello,
just a quick question... :) does UserDialogs supports Universal Apps too?

I'm asking because when some nuget component does not support a particular target platform, I get an error when trying to install the nuget package.
For UserDialogs I didn't get any errors when installing the nuget package on an Universal Apps project, but it doesn't seem to provide an implementation for WinRT.

Thanks,
Marco.

**Comment by aritchie** [comment]
I'm planning to release winrt support very soon

**Comment by PenaPP** [comment]
Amazing, I'm looking forward to use it :)

**Comment by Vinnie1991** [comment]
I can't wait! I'm now busy with a WP8.1 project

Love your Library @aritchie!

**Comment by astrazzari72** [comment]
Great. We are building an app for Android, iOS & Win tablets. It will be very useful.
Great library!

**Comment by aritchie** [comment]
Waiting for official UWP to be released, but if anyone has any great extension libraries they could point me to OR a full PR with the implementation, it would be appreciated

**Comment by aritchie** [comment]
This is now in beta-ish format in v4.0
