### ISSUE TITLE
Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by LWChris** [aritchie/userdialogs#191]
1) Issue currently on Android 4.4.4.

2) In reference to issue #161 - I'm getting the same error from the title after updating from 4.2.1 to 5.2.2. The issue over there was closed although this is obviously not fixed yet. Here is a detailed view into the method structure, hopefully this helps to provide a testcase.

The call stack:
```
PCL ctor {
  Task.Factory.StartNew(Start);
}

async void Start() {
  await OpenPage();
}

async Task OpenPage() {
  page.OnLoad();
}

void OnLoad() {
  StartInitialization();
}

async void StartInitialization() {
  await AlertAsync();
}

async Task AlertAsync() {
  await UserDialogs.Instance.AlertAsync();
}
```

UserDialogs.Init(this); is called before the PCL ctor.

3) Exception is the same as in issue #161 : UnhandledException:Java.Lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()

**Comment by aritchie** [comment]
Please provide a test case and the full stack trace.  #161 was closed because there wasn't really enough info and the case with a task on task was weird.

**Comment by aritchie** [comment]
By test case, I mean full sample showing the issue.

**Comment by LWChris** [comment]
Okay, I will try to set up a minimalistic testcase. My actual app startup code is very complex.

As a hint though: replacing the `Task.Factory.StartNew(Start);` with a simple `Start();` solved the issue. I guess, since the UserDialogs code is called from (and therefore most likely runs in) the task factory thread context - which does not call `Looper.prepare()` - the exception is thrown. Adding `if (Looper.MyLooper() == null) { Looper.Prepare(); }` to the Android code might help.

Alternatively, you can save the scheduler context from the `UserDialogs.Init(this);` in a member variable and switch to that threading context before calling the UI actions:

In Init(): `m_Scheduler = TaskScheduler.FromCurrentSynchronizationContext();`
Before calling UI stuff: `Task.Factory.StartNew(() => { Your_Code_Here }, CancellationToken.None, TaskCreationOptions.None, m_Scheduler);`

**Comment by aritchie** [comment]
What is your top level activity when you call for the dialog?  Please include your full stack trace as it would be very helpful 

I've been using the same uithread code for a few years without issue including 4.x.  It doesn't look at the task sync context and I have no intention of passing it into the function.  It is more likely to do with how the fragments work internally

**Comment by LWChris** [comment]
Good morning, the fullest stack trace (i. e. the most complete one I have observed) when I got the exception is:
```
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod
Android.App.AlertDialog.Builder.Show
Acr.UserDialogs.UserDialogsImpl.Show
Acr.UserDialogs.UserDialogsImpl.Alert
Acr.UserDialogs.AbstractUserDialogs.AlertAsync
AppFramework.Services.DialogService.AlertAsync
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<AppFramework.Services.DialogService.<AlertAsync>d__11>
AppFramework.Services.DialogService.AlertAsync
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<AppFramework.Services.DialogService.<AlertAsync>d__10>
AppFramework.Services.DialogService.AlertAsync
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<AppFramework.Pages.InitializationPage.<StartInitialization>d__11>
AppFramework.Pages.InitializationPage.StartInitialization
AppFramework.Services.NavigationService.OpenPage
System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext
System.Threading.ExecutionContext.RunInternal
System.Threading.ExecutionContext.Run
System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction
System.Threading.Tasks.Task.FinishContinuations
System.Threading.Tasks.Task.FinishStageThree
System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult
System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult
System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult
System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult
AppFramework.Services.NavigationService.OpenPage
System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext
System.Threading.ExecutionContext.RunInternal
System.Threading.ExecutionContext.Run
System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run
System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem
System.Threading.ThreadPoolWorkQueue.Dispatch
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback
```

The stack trace when the task for the `async` method is created, which calls the awaitable method `AppFramework.Services.NavigationService.OpenPage` you find the stack trace above:
```
AppProject.AppProject..ctor
System.Reflection.MonoCMethod.InternalInvoke
System.Reflection.MonoCMethod.InternalInvoke
System.RuntimeType.CreateInstanceMono
System.RuntimeType.CreateInstanceSlow
System.RuntimeType.CreateInstanceDefaultCtor
System.Activator.CreateInstance
AppFramework.Droid.AppFrameworkActivity.OnCreate
Android.App.Activity.n_OnCreate_Landroid_os_Bundle_
object.8fc4ff34-87fe-4f5e-865c-e1669b4b1797
```

The navigation stack contained one page when the exception occured.
