### ISSUE TITLE
SuccessToast and ShowSuccess crashes on UWP

### ISSUE THREAD

**Issue by LSMadsen** [aritchie/userdialogs#193]
**1) Please check all of the platforms you are having the issue on**
 - [X] UWP
 - [X] PCL

**2) Please state the issue to the best of your ability below**
When running `SuccessToast` I get this Exception `An exception of type 'System.Exception' occurred in Coding4Fun.Toolkit.Controls.dll but was not handled in user code
Additional information: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))` .
After running it in Immediate Window this shows up
`UserDialogs.Instance.SuccessToast("Test", timeoutMillis: 1500);
'UserDialogs.Instance.SuccessToast("Test", timeoutMillis: 1500)' threw an exception of type 'System.Exception'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2147417842
    HelpLink: null
    InnerException: null
    Message: "The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))"
    Source: "Windows"
    StackTrace: "   at Windows.UI.Xaml.Controls.Control..ctor()\r\n   at Coding4Fun.Toolkit.Controls.ToastPrompt..ctor()\r\n   at Acr.UserDialogs.UserDialogsImpl.Toast(ToastConfig config)\r\n   at Acr.UserDialogs.AbstractUserDialogs.Toast(ToastEvent toastEvent, String title, String description, Int32 timeoutMillis)\r\n   at Acr.UserDialogs.AbstractUserDialogs.SuccessToast(String title, String description, Int32 timeoutMillis)"`

I also tried with `ShowSuccess` that fails with `An exception of type 'System.Exception' occurred in Acr.UserDialogs.dll but was not handled in user code
Additional information: The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))`
And Immediate Window shows `UserDialogs.Instance.ShowSuccess("Test", 1500);
'UserDialogs.Instance.ShowSuccess("Test", 1500)' threw an exception of type 'System.Exception'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2147417842
    HelpLink: null
    InnerException: null
    Message: "The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))"
    Source: "Windows"
    StackTrace: "   at Windows.UI.Xaml.Controls.StackPanel..ctor()\r\n   at Acr.UserDialogs.UserDialogsImpl.Show(IBitmap image, String message, Color bgColor, Int32 timeoutMillis)\r\n   at Acr.UserDialogs.UserDialogsImpl.ShowSuccess(String message, Int32 timeoutMillis)"`

**Comment by aritchie** [comment]
Honestly, I'm not really good with UWP and the functions you're commenting on are things I'd like to get rid of in any case.  Are you able to provide a PR with a fix?  Otherwise, you may be waiting for a while as my primary concerns are around iOS & Android at the moment.

**Comment by NPadrutt** [comment]
Hi
I was just playing around with the library and  here none of the Toasts seems to work. All throw an Exception with the message: 
The parameter is incorrect.
reference

And the Exception: Value does not fall within the expected range.

I Tried this call:

            var dialogs = Mvx.Resolve<IUserDialogs>();
            dialogs.Toast(new ToastConfig(ToastEvent.Warn, "Test"));

Resolving works. Is this related to this issue or something completly else?
