### ISSUE TITLE
Android - crash when calling ProgressDialog.Hide()

### ISSUE THREAD

**Issue by gonzobrains** [aritchie/userdialogs#194]
1)  This problem occurs on Android using PCL.

2)  My app crashes occasionally when calling Acr.UserDialogs.ProgressDialog.Hide().

3) Exception trace:

View=com.android.internal.policy.impl.PhoneWindow$DecorView{11c78500 G.E..... R.....ID 0,0-469,297} not attached to window manager at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <filename unknown>:0 at Android.Runtime.JNIEnv.CallVoidMethod (IntPtr jobject, IntPtr jmethod) [0x00068] in <filename unknown>:0 at Android.App.Dialog.Dismiss () [0x00049] in <filename unknown>:0 at AndroidHUD.AndHUD+<DismissCurrent>c__AnonStorey4.<>m__0 () [0x0001c] in <filename unknown>:0 at AndroidHUD.AndHUD+<DismissCurrent>c__AnonStorey4.<>m__1 (System.Object state) [0x00000] in <filename unknown>:0 at Android.App.SyncContext.Send (System.Threading.SendOrPostCallback d, System.Object state) [0x00025] in <filename unknown>:0 at AndroidHUD.AndHUD.DismissCurrent (Android.Content.Context context) [0x0005a] in <filename unknown>:0 at AndroidHUD.AndHUD.Dismiss (Android.Content.Context context) [0x00001] in <filename unknown>:0 at Acr.UserDialogs.ProgressDialog.<Hide>b__26_0 () [0x00005] in <filename unknown>:0 at Acr.Support.Android.Extensions.RequestMainThread (System.Action action) [0x00019] in <filename unknown>:0 at Acr.UserDialogs.ProgressDialog.Hide () [0x00007] in <filename unknown>:0 at DYMO.Forms.Controls.DYMOProgressDialog.Dispose () [0x00000] in <filename unknown>:0 at DM.App+<OnResume>c__async0.MoveNext () [0x000cb] in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <filename unknown>:0 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in <filename unknown>:0 at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <filename unknown>:0 at Java.Lang.IRunnableInvoker.n_Run (IntPtr jnienv, IntPtr native__this) [0x00009] in <filename unknown>:0 at (wrapper dynamic-method) System.Object:1b8b5c44-fea7-415b-b680-f83502ffbf16 (intptr,intptr) --- End of managed exception stack trace --- java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{11c78500 G.E..... R.....ID 0,0-469,297} not attached to window manager

**Comment by aritchie** [comment]
Please provide a test case for this issue.  It is strange that it can open, but that it can't close.

**Comment by gonzobrains** [comment]
I think this happens when I navigate away from my app (i.e., go do
something in Android Settings) and then come back to the app (OnResume).

**Comment by aritchie** [comment]
Ok, provide some code please.  That isn't what I meant by test case.  Though with it, I can guess what is going on... you aren't cleaning up your loading window before navigating away.

**Comment by aritchie** [comment]
Please reopen issue if you can provide more info
