### ISSUE TITLE
Prompt Not Showing Keyboard Automatically

### ISSUE THREAD

**Issue by parkerhillius** [aritchie/userdialogs#196]
I'm using the below code. It puts the cursor in the textbox but does not automatically open the keyboard.

```
var result = await UserDialogs.Instance.PromptAsync(new PromptConfig {
    Title = "Password",
    InputType = InputType.Password				
});
```

**Comment by aritchie** [comment]
You need to add a lot more detail than that!  Platform, library version, if android - what is your top level activity inheriting from

**Comment by parkerhillius** [comment]
Platform: Android. Code above is being called from a Xamarin Forms PCL.
NuGet Package: Acr.UserDialogs 5.2.2

SplashActivity inherits from Activity.
MainActivity inherits from FormsApplicationActivity

**Comment by aritchie** [comment]
What is the android version?  Does the sample show the keyboard for you on the same device?

**Comment by parkerhillius** [comment]
Test Device is 5.0.1
Targeting 4.3 (API 18) to 5.1 (API 22)
Compiling using 5.1

**Comment by aritchie** [comment]
Does the sample code from this project show the keyboard?

**Comment by aritchie** [comment]
Wrong defect closed

**Comment by parkerhillius** [comment]
I can't seem to get Samples.Droid to build...

Visual Studio:
![image](https://cloud.githubusercontent.com/assets/11996814/16310676/1afbbb84-3933-11e6-9211-61fbe5458af0.png)

Xamarin Studio:
![image](https://cloud.githubusercontent.com/assets/11996814/16310749/64b7102a-3933-11e6-8fcc-1d9f8c329769.png)

**Comment by aritchie** [comment]
The visual studio issue is a common thing with Xamarin.  Clean solution and rebuild usually works.  As for the one in Xamarin Studio, it looks like an old version or something.  I haven't seen that before

**Comment by parkerhillius** [comment]
Do you happen to have, or is it easy for you to make an .apk for the Samples.Droid project? At least then I could test it on the device.

**Comment by aritchie** [comment]
It is, but it defeats the purpose.  If you aren't seeing the dialog on your device, perhaps it is a device issue that needs to be accounted for

**Comment by parkerhillius** [comment]
I'm not sure where to go from here, I've tried cleaning and rebuilding in both Visual Studio and Xamarin Studio, same errors.

Other inputs within the application on the same phone, pull up the keyboard just fine.

**Comment by aritchie** [comment]
try building with the latest master.  there were issues with the support libraries and the latest xamarin release.

**Comment by parkerhillius** [comment]
Got it to build, and run on my device. Keyboard opens as expected. I'll update my app's dependencies and report back.

**Comment by aritchie** [comment]
There is no fix specific to whatever issue you are experiencing

**Comment by aritchie** [comment]
Please send additional info if you are still encountering issues

**Comment by parkerhillius** [comment]
After upgrading to latest Xamarin.Forms and Acr.UserDialogs. This appears to be resolved.
