### ISSUE TITLE
Only one ContentDialog a time

### ISSUE THREAD

**Issue by LSMadsen** [aritchie/userdialogs#197]
**1) Please check all of the platforms you are having the issue on**
 - [X] UWP
 - [X] PCL

**2) Please state the issue to the best of your ability below**
When showing 2 dialogs (one after another) I often get this exception in UWP (it is on Danish so I tried to translate it) `System.Runtime.InteropServices.COMException: An async operation was not properly started.
There can only be one ContentDialog open a time.
   at Windows.UI.Xaml.Controls.ContentDialog.ShowAsync()
   at Acr.UserDialogs.ProgressDialog.<Show>b__34_0()
   at Acr.UserDialogs.ProgressDialog.<>c__DisplayClass50_0.<Dispatch>b__0()`.

Is there a fix for this?

**Comment by aritchie** [comment]
This library doesn't do dialog management.  Best suggestion is to put a delay between your dialogs (500ms or so)
