### ISSUE TITLE
await ActionSheetAsync .. closes with no result...

### ISSUE THREAD

**Issue by stephenhauck** [aritchie/userdialogs#198]
1) Please check all of the platforms you are having the issue on
 
 - [X] iOS
 - [] Android
 - [] UWP
 - [X] PCL

2) Please state the issue to the best of your ability below
I have code that is awaiting a call to ActionSheetAsync.
The code runs and the action sheet shows correctly.
If I select an option I get the return code form the action sheet correctly.
When the user clicks outside the action sheet it disappears and I am not notified it has gone away.

Am I trying to use the library incorrectly ?

**Comment by aritchie** [comment]
It is very likely a bug.  My suggestion is to use the non asynchronous version in any case.  It is much better suited for the action sheet use case

**Comment by stephenhauck** [comment]
OK, thanks.

**Comment by aritchie** [comment]
A cancel action is automatically added to the async option now as part of 6.0
