### ISSUE TITLE
Change Background color and text color of Alert or Prompt Dialogs in android

### ISSUE THREAD

**Issue by abhishekswaraj** [aritchie/userdialogs#199]
Change Background color and text color of Alert or Prompt Dialogs in android

Want to customise the alert box specifically background color, text color or buttons image/color.

**Comment by aritchie** [comment]
You can style appcompat dialogs through the convention android styles

**Comment by abhishekswaraj** [comment]
Can u provide a example .actually in my scenario i have to change the color of background and text based on certain condition.Is there any cross platform method to do it  ?

**Comment by aritchie** [comment]
You can't style iOS dialogs, so no xplat way to do that.  As for the android styling, google it.  

There is a way to set the android style ID dynamically coming in v6 of this library which I should be releasing within the next few weeks.
