### ISSUE TITLE
ActionSheet on iOS 7

### ISSUE THREAD

**Issue by charlenni** [aritchie/userdialogs#2]
Hello,

I encounter problems after converting my dialogs to this new version.

Could it be, that the following code for iOS is wrong?

	config.Options.ToList().ForEach(x => action.AddButton(x.Text));
	if (config.Destructive != null)
	{
		action.AddButton(config.Destructive.Text);
		action.DestructiveButtonIndex = config.Options.Count + 1;
	}
	if (config.Cancel != null)
	{
		action.AddButton(config.Cancel.Text);
		action.CancelButtonIndex = config.Options.Count + 2;
	}

I don't use any Destructive. With this, no destructive button is added and `action.CancelButtonIndex = config.Options.Count + 2` throws a OutOfRange exception.

**Comment by aritchie** [comment]
Hi @charlenni 
That is definitely what is wrong.  Horrible code on my part.  I will deploy a patch sometime today.  Thanks

**Comment by charlenni** [comment]
I changed the above code to the following, which solved the problem.

	config.Options.ToList().ForEach(x => action.AddButton(x.Text));
	var count = config.Options.Count;
	if (config.Destructive != null)
	{
		action.AddButton(config.Destructive.Text);
		action.DestructiveButtonIndex = count++;
	}
	if (config.Cancel != null)
	{
		action.AddButton(config.Cancel.Text);
		action.CancelButtonIndex = count++;
	}

Perhaps you could change this.
