### ISSUE TITLE
ShowSuccess, ShowError, Hide...

### ISSUE THREAD

**Issue by bscheiman** [aritchie/userdialogs#20]
Hi there,

I'm using your libraries for several apps + some bootstrappers I'm generating. I'd like to add a couple methods to this lib, mostly:

- ShowSuccess(message, timeout)
- ShowError(message, timeout)
- Hide()

I'd also add a BlockingToast, but I see you've got that with one of your latest commits.

Wanted to check if you're accepting PRs before I sent them.

EDIT: Oops, meant to add this issue to the XamForms version - but I guess the same idea applies here.

**Comment by aritchie** [comment]
The xamforms library is deprecated in favour of this library.  This library can be used with xamforms, mvx, etc

I added these methods as part of the 3.3 release I plan on making.  I am missing an implementation for wp8, so if you've got that, please PR away

**Comment by bscheiman** [comment]
I'll update my libraries then. Any chance you add an explicit call to
Hide() ? Use scenario: long activity in background w/ a blocking toast.
Once the activity/task finishes, call Hide.

**Comment by aritchie** [comment]
The loading dialog is what you should use for cases like this.  Making this requirement would require patches to one of the underlying libraries and I'm not really a really a fan of using a toast popup in this fashion.

**Comment by bscheiman** [comment]
You're right. Might want to make the activity indicator optional (though
defaulting to visible - unless that's what "show" does) and allow changing
success/error images as well.

Noticed some strange behavior the other day. I'll let you know once I'm
able to debug it.
