### ISSUE TITLE
SuccessToast does not work properly

### ISSUE THREAD

**Issue by fcogutierrez** [aritchie/userdialogs#200]
1) Please check all of the platforms you are having the issue on
 
 - [x] iOS

2) Please state the issue to the best of your ability below

I see **strange behaviors** when I call to the  **SuccessToast**. Sometimes this toast does not appear, and sometimes this toast appears but too too quickly (much less than the default 3000 miliseconds).

I couldn't specify where it happens each issue, but the behavior is not quite good.

Thanks in advance :).

**Comment by aritchie** [comment]
This issue is no longer relevant with v6 as SuccessToast has been eliminated and a new control is now used.
