### ISSUE TITLE
Best way to unit test VM's that call UserDialogs.Instance?

### ISSUE THREAD

**Issue by mrbelk** [aritchie/userdialogs#201]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [x] Android
 - [] UWP
 - [x] PCL

2) Please state the issue to the best of your ability below
This is more of a question than a problem: is there a good "best practice" for unit testing viewmodels that call UserDialogs.Instance.xxx? There doesn't seem to be a good unit-testing practice when Xamarin.Forms is in the picture, but it has to be if we call UserDialogs from our viewmodels.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

**Comment by aritchie** [comment]
You should never use UserDialogs.Instance in your app period other than when registering it will an ioc container.  I inject IUserDialogs into every viewmodel I use it in.  From there, I can use mocks.  

However, there is nothing to stop you from mocking IUserDialogs and setting that on userdialogs.instance for each test

**Comment by mrbelk** [comment]
Perfect.  Thanks.  We'll do some refactoring around the IUserDialogs.  We're already using ninject in the project.  Follow-on question: what do you actually bind to IUserDialogs? Do you use a method injection to return UserDialogs.Instance?

**Comment by aritchie** [comment]
UserDialogs.Instance is a get/set. 

var mock = new Mock<IUserDialogs>();  
... setup what methods you want to mock on IUserDialogs if any
UserDialogs.Instance = mock.Object;

**Comment by mrbelk** [comment]
trying to use Moq with IUserDialogs and my test runner in VSTS chokes because it can't find Mono.Android.dll. I am only referencing the portable version of Acr.UserDialogs.Interface.dll in my unit test project and all my tests run successfully in Xamarin Studio. Any ideas?

**Comment by aritchie** [comment]
If you need UserDialogs.Instance in your unit tests, you will also have to include the PCL version of Acr.UserDialogs.dll.  Why android libs are involved is beyond me.  Nothing to do with this library.  In any case, this is now outside of what I'm willing to support.  Best of luck

**Comment by mrbelk** [comment]
We're not testing UserDialogs.Instance, just IUserDialogs.  The android stuff is perplexing.  Thanks for your help today.
