### ISSUE TITLE
v5.3 Alert dialog not showing in task continuation

### ISSUE THREAD

**Issue by tyjen** [aritchie/userdialogs#203]
I upgraded to package version 5.3 and have observed a strange issue for Android (5.1 Lollipop, API 22). If you call Instance.Alert(message) from within a task continuation, nothing shows up. Only a log message stating  `Assembly Ref addref Acr.UserDialogs -> Xamarin.Android.Support.v4`

I can successfully show and hide the loading popup, that works as expected, but alert is broken.

My code looks like this (obviously simplified for examples sake)

```
private void SubmitAction()
{
    UserDialogs.Instance.ShowLoading(message);
    MyService.DoSomethingAsync().ContinueWith(this.DoSomethingCompleted);
}

private void DoSomethingCompleted(Task t)
{
    UserDialogs.Instance.HideLoading();
    UserDialogs.Instance.Alert(someMessage); // Dialog doesn't show in v5.3!
}
```

Now if I revert back to package version 4.3.4, everything works as expected. I also found that if I called Alert from within a function that is called immediately after a page is loaded, it displays as expected which leads me to believe there is something funky happening with the async nature of the calls.

**Comment by aritchie** [comment]
There should be some output in logcat that may give some info.  Also, what is your top level activity inheriting from?

**Comment by aritchie** [comment]
Please try the 6.0-beta4 on nuget.  I don't recall any fix specific to this, but I have run a test case in the samples that works fine.

**Comment by tyjen** [comment]
There really isn't much in logcat that looks helpful, this is what I found:

```
07-06 11:51:03.419 D/Mono    ( 1619): Assembly Ref addref SpareChange.Mobile.Android[0xb40f1ca0] -> Splat[0xb43a56a0]: 4
07-06 11:51:03.464 V/WindowManager(  396): not Base app: Adding window Window{200758a0 u0 com.sparechange/md5651c0eddf56a7de30e438e8235511390.MainActivity} at 5 of 10
07-06 11:51:03.499 W/EGL_xap ( 1619): eglSurfaceAttrib not implemented
07-06 11:51:03.499 W/OpenGLRenderer( 1619): Failed to set EGL_SWAP_BEHAVIOR on surface 0x98694ba0, error=EGL_SUCCESS
07-06 11:51:05.477 D/Mono    ( 1619): Assembly Ref addref Acr.UserDialogs[0xb42df0a0] -> Xamarin.Android.Support.v4[0xb43a5c40]: 8
```

My activity inherits from `XFormsApplicationDroid`

I'm using v2.0.5782 of XLabs and v2.2.0.45 of Xamarin.Forms

**Comment by tyjen** [comment]
I should also mention that the original function is being executed via a Command from a button press. Interestingly, everything works as expected if I wrap the call to display the Alert in Device.BeginInvokeOnMainThread
