### ISSUE TITLE
Back navigation during showing the confirmation doesn't close await.Monitor

### ISSUE THREAD

**Issue by fedotovsi** [aritchie/userdialogs#204]
**Step to reproduce:**
1. Show ConfirmAsync
2. Press back button
**Actual result:**
Thread Monitor await remains and next line of code is never achieved 
**Expected result:**
ConfirmAsync returns null and next line of code executed
**Conditions:** 
version 5.2.2, Android.

**p.s.** I think it works in this way because of TaskCompletionSource and Back navigation is not handled.
I have no idea how to fix it, I would appreciate any of help.

**Comment by aritchie** [comment]
You can pass a cancellation token to all of the async methods.  If you are using sync versions, everything is disposable.  I'm trying to stay out of dialog management due to potential complexities.

**Comment by fedotovsi** [comment]
yes, I know about this possibility but I didn't know how to cancel only in the moment when user click back button.

**Comment by aritchie** [comment]
Wire up to onback, cancelsource.Cancel()?

**Comment by fedotovsi** [comment]
yes, I saw only this way, but it seems quiet difficult to make works on .Core, ok I will try this approach if this won't be in lib.

**Comment by aritchie** [comment]
It likely will at some point.  I'm just not sure how to go about it.  Wiring your viewmodels up to onresume, onpause, & onback is pretty easy.  Create a base activity and wire up to onresume/onpause/onback.  Create an interface with the same state events and implement in your viewmodel.  Have the base activity now call those state methods.  I usually just use onpause and cancel my token source here

**Comment by fedotovsi** [comment]
I tried your solution and, unfortunately, none of these events fire on back pressed when confirm dialog is open. I googled it and java developers suggest to listen keys pressed and verify if the the back button pressed, in this case it works, but one case difficult to determine: on prompt text input, because on first back it close keyboard and on second back pressed it should close the dialog. I am not sure if was explain please ask me the question I will try to explain myself more properly.

**Comment by aritchie** [comment]
Share some code and we'll go from there

**Comment by fedotovsi** [comment]
I tried  onresume/onpause/onback, keyDown, keyUp events on Activity and they don't fire when Dialog is open, so it seems this issue can be solved only to attach directly to dialog KeyPress event, to verify for back button and return null or false, theoretically this should solve the situation.
Sorry, but it's difficult to share code, because I tried on my own application.

**Comment by fedotovsi** [comment]
In the end I made in this way: 
I create my own implementation of UserDialogsImpl and AbstractBuilderAppCompatDialogFragment
where I handle dialog.KeyPress :
e.Handled = false; 
if (e.KeyCode == Keycode.Back)
{
   e.Handled = true;
   OnBackPressed();//some additional logic in derived classes, is optional, I use in my app.
}

**Comment by aritchie** [comment]
This is fixed in the upcoming 6.1
