### ISSUE TITLE
Latest Nuget Doesn't install on Xamarin.Forms Android

### ISSUE THREAD

**Issue by hokituh** [aritchie/userdialogs#206]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [X] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below
Failed when installing using npm targeting android project. I am using Xamarin.Android.Support.Design version 23.4.0.1
3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.
Unable to find a version of 'Xamarin.Android.Support.Design' that is compatible with 'Acr.UserDialogs 6.0.0 constraint: Xamarin.Android.Support.Design (>= 23.3.0 && < 24.0.0)', 'BottomNavigationBar 1.1.3 constraint: Xamarin.Android.Support.Design (>= 23.4.0)', 'Xamarin.Forms 2.3.0.107 constraint: Xamarin.Android.Support.Design (= 23.3.0)'.

**Comment by aritchie** [comment]
Your issue is with bottom navigation bar (requires 23.4) and xamarin forms requires 23.3
