### ISSUE TITLE
iOS: Toast top position on statusbar hidden

### ISSUE THREAD

**Issue by ilker55** [aritchie/userdialogs#207]
I have an app with the statusbar hidden, but it doesn't show the toast at the top of the screen.
Is it possible to set the top position of the toast?

![img_0490](https://cloud.githubusercontent.com/assets/3458122/16874764/84f636da-4a9b-11e6-9d6e-62ad52a71dfe.jpg)

**Comment by aritchie** [comment]
It wasn't really designed to go over top of the status bar.
