### ISSUE TITLE
Samples: TimePrompt in iOS not returning user selected time

### ISSUE THREAD

**Issue by airboss001** [aritchie/userdialogs#208]
1) Please check all of the platforms you are having the issue on
 
 - [X] iOS
 - [] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below

In iOS the TimePrompt does not return user set time in either standard or 24hr, instead returning the current system time set when the prompt was opened. Works fine in Android.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.
No exceptions, just wrong information returned.

**Comment by airboss001** [comment]
Corrected by changing AIDatePickerController.cs
`
button.TouchUpInside += async (s, e) =>
			{
			    SelectedDateTime = datePicker.Date.ToDateTime(); //<-- was missing
                await this.DismissViewControllerAsync (true);
				Ok?.Invoke(this);
			};
`

**Comment by aritchie** [comment]
thanks for the fix & report.  live on nuget under 6.0.1

**Comment by airboss001** [comment]
Thank you for putting this all together!
