### ISSUE TITLE
iOS ShowError not disabling underlying page controls

### ISSUE THREAD

**Issue by praga** [aritchie/userdialogs#209]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [x] iOS
 - [] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below
Till 5.0.1 ShowError disables the underlying controls when it is displayed. Since the update it does not disable the controls. Pressing a control which triggers the same ShowError multiple times adds another layer of semi transparent black mask which does not disappear even after the dialog disappears.

Sample video attached
[sample.zip](https://github.com/aritchie/userdialogs/files/368310/sample.zip)

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.
None

**Comment by aritchie** [comment]
This was the intent of these overlays with btprogresshud

**Comment by aritchie** [comment]
though I have removed the black overlay effect for 6.1

**Comment by praga** [comment]
Thanks for the update.

**Comment by lucascc26** [comment]
I've seen people asking for different behaviors (disable/enable interaction, dim background etc) for ShowError and ShowSuccess methods... Is it possible to pass a mask as a parameter to those methods?

Thank you!

**Comment by aritchie** [comment]
I'll be honest, these methods are such a pain in the ass for such little gain.  I don't use them because I find the end result uninformative and ugly.  They are a maintenance cost that I don't want.  I'm at the stage where I'm probably just going to remove them

**Comment by lucascc26** [comment]
I understand. What would you recommend to show error and success? I'd like to dim and block interaction in the background.

**Comment by MrBasque** [comment]
Looking fo the same as @lucascc26. 

There seems to be no way to show a dimmed background with ShowError.

As an alternative i've tried to use the Show() method with MaskType instead, but in that case the spinner is always visible, which is not what I want.

**Comment by aritchie** [comment]
I'm will be removing showerror and show success in the next major version.  They have tons of bugs, I don't use them personally, and in my opinion, are horrible for end users.  I'll take PRs if people want to keep them.

**Comment by MrBasque** [comment]
Thanks for your quick reaction @aritchie, point taken.
As an alternative, would it be possible to make the progress-spinner configurable?

**Comment by aritchie** [comment]
Progress spinner already has a show/hide.  Please post a feature request if you feel there is an area that can be improved.

**Comment by MrBasque** [comment]
Sorry, I mean the spinner which is shown within the Show() method.
