### ISSUE TITLE
iOS Extensions and UIApplication.SharedApplication

### ISSUE THREAD

**Issue by kspearrin** [aritchie/userdialogs#211]
1) Please check all of the platforms you are having the issue on
 
 - [x] iOS
 - [] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below

Currently the iOS implementation uses `UIApplication.SharedApplication` to get the top-most view controller to display alerts on. I would like to use UserDialogs in some common code that is shared with both my main application and action extension. `UIApplication.SharedApplication` is unavailable in iOS extensions so this doesn't work and I have to write custom conditional code.

Is there a way we could drop the dependency on `UIApplication.SharedApplication` so that this could support both the main application as well as iOS extensions?

**Comment by aritchie** [comment]
Breaking that dependency won't be too hard.  Supporting all of the use cases could be difficult

**Comment by kspearrin** [comment]
I'm thinking that you allow and `Init` to pass in a `ViewController` or delegate `Func<ViewController>` and we can specify a way to resolve the view controller ourselves.

From my action extension `ViewController` I would just register it like so:

    UserDialogs.Init(this);

OR

    UserDialogs.Init(() => { return this; });

You can make the `Init` optional and default to `UIApplication.SharedApplication.GetTopViewController()` like you do today in order to make it backwards compatible.
