### ISSUE TITLE
Can't compile when targeting a physical device

### ISSUE THREAD

**Issue by rampyodm** [aritchie/userdialogs#212]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [x] iOS
 - [] Android
 - [] UWP
 - [] PCL

With version 6.0.1, I can't compile when targeting a physical device. The error is /Users/rampanmj/Projects/KwikTrip/KwikList/MTOUCH: Error MT2002: Failed to resolve assembly: 'BTProgressHUD, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' (MT2002) (KwikList). 

I have BTProgressHUD installed and it works fine when targeting the simulator. I'm using Xamarin.iOS with Xamarin Studio.

**Comment by aritchie** [comment]
It sounds like a linker issue.  You could try reinstalling it

**Comment by rampyodm** [comment]
I figured it out. For some reason the hintpath was wrong for BTProgressHUD in the csproj file. It was looking for it inside the AcrUserDialogs folder instead of BTProgressHUD.
