### ISSUE TITLE
Selected date in date picker is not showing correctly when i try to reopen second time

### ISSUE THREAD

**Issue by chanti-github** [aritchie/userdialogs#214]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [] Android (Yes)
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below

When the first time open the datepicker it is showing the current date then i manualy select date when i am trying to select open the picker the selected date is not showing it is showing some different date.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

**Comment by aritchie** [comment]
I have been unable to reproduce this.  Please send a reproducible sample
