### ISSUE TITLE
TimePicker has no Title on Android (Light Theme)

### ISSUE THREAD

**Issue by Strifex** [aritchie/userdialogs#215]
1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [X] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below

Android's Time Picker doesn't display a Title in Light Theme.  When using Theme.AppCompat.Light.NoActionBar, the TimePicker Dialog will not display its title, even when explicitly set in TimePromptConfig.  When using Theme.AppCompat.NoActionBar instead, everything is displayed.  Essentially it looks like the title is styled to be white font regardless of the theme, so in Theme.AppCompat.Light, you won't ever see the Title Text.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

N/A

**Comment by Strifex** [comment]
I'm also seeing an issue where the text for the numbers on the dialog are also far too light for this theme, making it illegible.  I don't believe the TimePickerDialog is usually styled that way by default...

**Comment by aritchie** [comment]
I don't touch theming at all in the dialog library.

**Comment by Strifex** [comment]
Ah, interesting...that's strange, I find it hard to believe by default the "light" theme TimePicker would have white text on white background hmmm I'll have to do more digging on my own thanks
