### ISSUE TITLE
iOS: No icons for ShowError/ShowSuccess

### ISSUE THREAD

**Issue by xabre** [aritchie/userdialogs#216]
1) Please check all of the platforms you are having the issue on
 
 - **[X] iOS**
 - [] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below
After updating to 6.0.1 ShowError/ShowSuccess dosen't show any icons in ios. Instead they only show a plain (ugly) message.

Tested also with the **sample app** and got the same effect. Will attach some screenshots below. 

![simulator screen shot 21 jul 2016 16 40 52](https://cloud.githubusercontent.com/assets/6204446/17027049/a698cb7e-4f62-11e6-83e2-1d9ddda529d6.png)
![simulator screen shot 21 jul 2016 16 40 49](https://cloud.githubusercontent.com/assets/6204446/17027051/a9667590-4f62-11e6-8b3a-96978024338f.png)

**Comment by ilker55** [comment]
There is a temporary fix: https://github.com/aritchie/userdialogs/issues/162#issuecomment-219707753

**Comment by aritchie** [comment]
Please refer to #162
