### ISSUE TITLE
Android: MessageTextColor is ignored in Toasts

### ISSUE THREAD

**Issue by strebbin** [aritchie/userdialogs#217]
1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [X] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below

In Android the MessageTextColor of the given ToastConfig is ignored while creating Toasts. So it is not possible to change the color of texts dynamically depending on the Message. It is possible to set the BackgroundColor, but setting the background without the ability to set the color of the message seams a bit disadvantageous.

To add the ability for setting the message-text-color of Toasts you could add something like: 
```cs
            var textColor = cfg.MessageTextColor ?? ToastConfig.DefaultMessageTextColor;
            if (textColor != null)
            {
                var viewGroup = snackBar.View as ViewGroup;
                if (viewGroup != null)
                {
                    for (var i = 0; i < viewGroup.ChildCount; i++)
                    {
                        var child = viewGroup.GetChildAt(i);
                        var textView = child as TextView;
                        textView?.SetTextColor(textColor.Value.ToNative());
                    }
                }
            }
```
to the Android Implementation in the ToastAppCompat method.

**Comment by aritchie** [comment]
Is fixed in 6.1
