### ISSUE TITLE
ToastConfig Options Gone with 6.0

### ISSUE THREAD

**Issue by hvaughan3** [aritchie/userdialogs#218]
1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [] Android
 - [] UWP
 - [X] PCL

2) Please state the issue to the best of your ability below

Before version 6.0 ToastConfig had options such as `SuccessTextColor`, `SuccessBackgroundColor` and more for errors and for warnings. Those properties are not available anymore. I also do not see the properties after doing a quick GitHub search of the repo. Though I do see the properties listed under `PromptConfig` in the readme but they are not available in code.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

Cannot resolve symbol 'SuccessTextColor'

**Comment by aritchie** [comment]
They have been removed as part of the new controls used.  I haven't had time to update the documentation.
