### ISSUE TITLE
Use Appcompat for Android dialogs

### ISSUE THREAD

**Issue by martijn00** [aritchie/userdialogs#22]
I would like to use the new AppCompatDialogs so my dialogs are material styled: https://developer.android.com/reference/android/support/v7/app/AlertDialog.html

Would it be possible to somehow override the android implementation so i can use this?

**Comment by aritchie** [comment]
You can supply your own instance by using UserDialogs.Instance = new YourImpl();

**Comment by martijn00** [comment]
I saw you made a start on this. What issue's are you facing?

**Comment by martijn00** [comment]
How is the progress on this? Can i help somehow?

**Comment by aritchie** [comment]
Pick up the library and try it yourself.  The implementation is there.

**Comment by martijn00** [comment]
I did try to get it running, but i couldn't figure out how to use it. Do you have a sample?

**Comment by aritchie** [comment]
This is up for grabs to the community.  The only condition is that the PR must work with xamarin forms or independently.

**Comment by aritchie** [comment]
This is now up in 4.0.0-beta1 on nuget
