### ISSUE TITLE
Error Toast title is not wrapped on IOS (v5)

### ISSUE THREAD

**Issue by escamoteur** [aritchie/userdialogs#220]
1) Please check all of the platforms you are having the issue on
 
 - [x] iOS

2) On iOS a longer Title is not wrapped like on Android. But using Title and Description doesn't look good on Android either because the Title is the same style as the descritopn besides beeing centered 

![nonwrapping](https://cloud.githubusercontent.com/assets/16635729/17135920/99ccdf38-5332-11e6-9504-b08f881da20a.jpg)

![toast android](https://cloud.githubusercontent.com/assets/16635729/17136010/27f05cae-5333-11e6-85a8-d7bfa583aee9.png)

**Comment by aritchie** [comment]
This is part of an old version which I no longer support.  You can take the last v5 from the tags though

**Comment by escamoteur** [comment]
Oh, I'm really sorry somehow my VS fooled me that I thought I already  had 6.01
