### ISSUE TITLE
[iOS] DatePickerAsync Background is solid black.

### ISSUE THREAD

**Issue by rdaniel0** [aritchie/userdialogs#221]
Hello, I am using this on a PCL project, I've setup userdialogs with mvvm/ioc.
I created a new dialog as follows:
`await _dialogs.DatePickerAsync("title goes here");`

I was expecting to see a darkened screen of the current view with the title message somewhere.
Here is a screenshot of what I see instead.
![d2381942a5](https://cloud.githubusercontent.com/assets/18712717/17160696/354322d0-53ea-11e6-9c57-fa878e85449e.png)

Works fine on android build so I know it's not the PCL

**Comment by highplains** [comment]
I'm getting this as well. Not sure considering the alpha is set to 0.7

https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs.iOS/AIDatePickerController.cs#L59

**Comment by aritchie** [comment]
There is no title on this control.  I will look into the solid black background
