### ISSUE TITLE
Call methods synchronously/inline without async?

### ISSUE THREAD

**Issue by cfahrenholz** [aritchie/userdialogs#222]
First, thank you very much for your efforts and great work on this library and to share this with the community!

We have common legacy source code (orginally based on a winforms app) that we now share between different platforms (Android, iOS, Winforms). We have an interface for user messages and some methods return a result from the user decision. We tried to use ACR UserDialogs in the interface implementation, but on Android if we call a non-async method, e.g. IUserDialog.Confirm(...) it gets asynchronous anyway since on Android you put the UserDialog on the UI main thread. I have read some stackoverflow posts about this and it seems this by design on Android.
I know if we change our code to use the async methods of IUserDialog, we get it synchronized. But we do not want to do that, since we have a lot of places to adapt to be async and even worse the shared code must be compatible to .net 3.5 which would lead to a lot of compiler constants and mentaining double method signatures/calls.

Do you have any recommandation or workaround to be able to call the non-async IUserDialog methods synchronously on Android?

**Comment by aritchie** [comment]
You can try using .Result off of the task, though I suspect it will simply deadlock on you.  
Beyond that, I really can't say much because I really think it would be a bad idea to force anything down this path
