### ISSUE TITLE
What happened to WarnToast, ErrorToast, InfoToast?

### ISSUE THREAD

**Issue by janniksam** [aritchie/userdialogs#224]
Hey,

what happened to UserDialogs.Instance.WarnToast(title, description); ? 
Were those breaking chances from 4.0 to 5.0?

Do I have to use .Toast() now? But what about the title and description? I can only see a title or a message parameter, not both anymore.

How do I use it now? Liked the way it was, but it doesnt matter, how do I get back to the behaviour I had before the update?

Thanks in advance

Jannik

**Comment by aritchie** [comment]
This was a change that was made with v6.  If you don't like the change, stick with v5.

**Comment by janniksam** [comment]
So, there is no possibillty to let them look exactly like in v5? What was the reason it was changed?

**Comment by aritchie** [comment]
No.  I needed something that behaved like a snackbar, so the API was changed slightly to accommodate this.  The only thing warn/error/success did was configure a color.  It wasn't something that I wanted to keep in the library.

**Comment by flyingxu** [comment]
Use .Toast() now?
I also see .ShowError() , ShowSuccess(), etc. Which now is recommended to replace WarnToast, ErrorToast, InfoToast?

**Comment by aritchie** [comment]
Use Toast.  Code your own extensions for WarnToast, ErrorToast - as they are simply for color choices.  ShowError & ShowSuccess are on their way out in v7 anyhow
