### ISSUE TITLE
ShowLoading not appearance

### ISSUE THREAD

**Issue by angelSwp** [aritchie/userdialogs#226]
Hello @aritchie ,
I'm using UserDialogs.Instance.Progress and is running normal, but when I use UserDialogs.Instance.ShowLoading, does not have anything, how can I solve this?

**Comment by aritchie** [comment]
You haven't filed this with a platform, exception, nothing!!

**Comment by angelSwp** [comment]
presents no error, simply does not appear.

`UserDialogs.Instance.ShowLoading ("Carregando");
                await saveService.ApagarBackup ("bck");`

**Comment by aritchie** [comment]
You need to supply the platform and some code with the issue then!  I'm not psychic and this works everywhere I use it.
