### ISSUE TITLE
DatePrompt: Shows with wrong date. Title ignored and hardcoded 'locale'

### ISSUE THREAD

**Issue by highplains** [aritchie/userdialogs#227]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [C] iOS
 - [] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below
await UserDialogs.Instance.DatePromptAsync(new DatePromptConfig {Title = "Select Date Written", SelectedDate = new DateTime(2016,8,8)});

When the prompt comes up it shows as "August 7 2016" so provided date -1;
Also title is ignored.
Can we also provide the locale instead of using a hardcoded value of "nl"

https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs.iOS/AIDatePickerController.cs#L46

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.
 No crash just odd behavior.

![screen shot 2016-08-05 at 3 14 18 pm](https://cloud.githubusercontent.com/assets/1825076/17450750/4d92a9f0-5b1f-11e6-914d-c0cfacfccc05.png)

**Comment by aritchie** [comment]
File these as separate defects in the future please!!

1) if you don't want the NL, don't use 24 hour set to true
2) verify your datetime.kind please
3) There is no title property on iOS right now

**Comment by highplains** [comment]
new DateTime() = DateTimeKind.Unspecified in my Xam.Forms setup.

**Comment by aritchie** [comment]
Specify the kind then.  The code works with utc or local

**Comment by highplains** [comment]
Easy enough, but I feel you will get more people asking this in the future considering serializing json -> .net DateTime ignores the "Kind". 

But I can adjust. Thanks.
