### ISSUE TITLE
Toast not compatible with previous coding syntax

### ISSUE THREAD

**Issue by calbert52** [aritchie/userdialogs#228]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [] Android
 - [] UWP
 - [x] PCL

2) Please state the issue to the best of your ability below

Previous coding usage of Toast does not work with this version 6.1.1.

Example call to Toast method:
Toast(ToastEvent.Error, Result.Message, 5);

void Toast(ToastEvent @event, String Message, Int32 DurationSeconds)
{
      UserDialogs.Instance.Toast(new ToastConfig(@event, @event.ToString(), Message)
      {
          Duration = TimeSpan.FromSeconds(DurationSeconds)
      });
 }
3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

**Comment by aritchie** [comment]
It's not supposed to be.  This is why I released a new major version

**Comment by calbert52** [comment]
How is it used now, do you have a sample?

**Comment by aritchie** [comment]
There is a folder right in the repo called samples.  The API isn't complex either, look at intellisense

**Comment by calbert52** [comment]
Yes, I found that and come up with the below, but the background of the message is not Red as indicated in my code

UserDialogs.Instance.Toast(new ToastConfig("Error"))
{
    BackgroundColor = System.Drawing.Color.Red,
    Duration = TimeSpan.FromSeconds(3),
    Message = Result.Message,
    MessageTextColor = System.Drawing.Color.White
});
