### ISSUE TITLE
Cannot check if it already initialized on Android

### ISSUE THREAD

**Issue by jded76** [aritchie/userdialogs#23]
I'm trying to use this
if (UserDialogs.Instance == null) {
        UserDialogs.Init(() => (Activity)Forms.Context);
}
on Android in the MainActivity with the latest version of UserDialogs and I'm always getting an exception "Android requires that you pass an activity factory function to Init() from your main activity" on this "UserDialogs.Instance == null"

What I'm doing wrong?

Thank you for your effort.

**Comment by aritchie** [comment]
Fixed in 3.3.3

**Comment by jded76** [comment]
It's working. Thank you!
