### ISSUE TITLE
Not get event in PromptConfig class

### ISSUE THREAD

**Issue by risingworld777** [aritchie/userdialogs#231]
var pc = new PromptConfig();
pc.Title = "Please enter comment";
pc.OnResult += delegate (PromptResult result){
	// in here or somewhere
        // is it possible to get click event of OK or Cancel button and get inputted text
};

Device.BeginInvokeOnMainThread(delegate
{
	UserDialogs.Instance.PromptAsync(pc);
});

**Comment by aritchie** [comment]
1) You can't use OnResult and Async together.  The async just overwrites your OnResult
2) You don't need BeginInvokeOnMainThread, the dialogs are marshalled automatically
3) The PromptResult has an an .Ok (true for ok button, false for cancel) and a .Value property.  

var result = await UserDialogs.Instance.PromptAsync("Please enter a comment");
if (result.Ok) 
{
    //result.Value
}

**Comment by risingworld777** [comment]
Great
This resolved my issue :)
Thank you
