### ISSUE TITLE
DatePrompt on Android 4.x with XF AppCompat should not open the soft keyboard

### ISSUE THREAD

**Issue by rafaelsteil** [aritchie/userdialogs#232]
1) Please check all of the platforms you are having the issue on

 - [x] Android

2) Please state the issue to the best of your ability below
`DatePrompt` on any project with Xamarin.Forms using `FormsAppCompatActivity` running on Android 4.x opens the soft keyboard, when it shouldn't. The problem does not happen on Android >= 5, or 4.x using `FormsApplicationActivity`

It appears to be caused by `dialog.Window.SetSoftInputMode(SoftInput.StateVisible);`  on `AbstractAppCompatDialogFragment`, as if I change it to `SoftInput.StateHidden` the keyboard does not appear. 

I tested it using the latest source code on the date this issue was created. For me the most obvious fix was to override `SetDialogDefaults` on `DateDalogFragment.cs` and change the keyboard state. I attached the diff to this issue, I'd be happy to create a pull request if necessary. However, I didn't go deep on _why_ it only appens with appcompat and on android 4.x. 

[DateDialogFragment.cs.txt](https://github.com/aritchie/userdialogs/files/415716/DateDialogFragment.cs.txt)

**Comment by aritchie** [comment]
Thanks for the report and fix.  I'll look into it further as this likely causes grief for time as well
