### ISSUE TITLE
OnConfirm not working in 6.0

### ISSUE THREAD

**Issue by nologinatgit** [aritchie/userdialogs#233]
I try to use Acr.UserDialogs 6.0.1 with my Android (and Windows Phone 8.1) Xamarin.Forms project.
I use this version because _6.1.x breaks compatibility with Windows Phone 8.1 (it always shows that I should use the PCL version of the library)._

**Acr.UserDialogs 6.0.1 shows dialogs both on Android and Windows Phone 8.1.**

However, the following code never calls its callback on Android and Windows Phone 8.1:

```csharp 
await UserDialogs.Instance.ConfirmAsync(new ConfirmConfig { Message = "Delete?", CancelText = "No", OkText = "Yes", Title = "Delete Confirm", OnConfirm = async (res) =>await DeleteItem(res) });`
```

```csharp
public async Task DeleteItem(bool delete)
{ ...}

```
I tried Acr.UserDialogs 6.1.2 and it calls the callback in Android but also breaks Windows Phone 8.1 compatibility.

Am I doing something the wrong way?

**Comment by aritchie** [comment]
Don't use OnConfirm with async.  The async has the reply you need.  

Also, if you read the README, I don't officially support anything with wp8 at all.  I don't deal with the platform ever.

**Comment by nologinatgit** [comment]
But you support Android.
I tried it without async but no change, the callback is not working on Android. What else should I try?

**Comment by aritchie** [comment]
Yes - I support Android, but you had two platforms (1 I support, 1 I do not)

// notice I don't set OnConfirm because the await result does that
var result = await UserDialogs.Instance.Confirm(new ConfirmConfig { Message = "Delete?", CancelText = "No", OkText = "Yes", Title = "Delete Confirm");
if (result.Ok) 
{
    DeleteItem(res);
}

**Comment by nologinatgit** [comment]
Thanks, I'll try that.
