### ISSUE TITLE
Toast (Snackbar) on Android overlaps FAB (Floating action button)

### ISSUE THREAD

**Issue by rvsonar** [aritchie/userdialogs#234]
Toast (Snackbar) on Android overlaps FAB (Floating action button).

There should be a way to pass the parent layout to be used while displaying snackbar.

**Comment by UmakantSharma** [comment]
Can you please provide solution for that. As it is a usability issue.

**Comment by aritchie** [comment]
I don't have one.  I'm open to suggestions and PRs
