### ISSUE TITLE
Loading and ShowLoading method shows up an extra 0 (zero) on UWP

### ISSUE THREAD

**Issue by Brosten** [aritchie/userdialogs#235]
1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [] Android
 - [x] UWP
 - [] PCL

2) Please state the issue to the best of your ability below
Just call UserDialogs.Instance.Loading("I am loading"); (or ShowLoading) under UWP.
It will show the message, but with an extra 0 on a new line under the message.

**Comment by aritchie** [comment]
fixed in 2.3.7
