### ISSUE TITLE
iOS TimePicker always opens with the current time and ignores 'SelectedTime'

### ISSUE THREAD

**Issue by EGoverde** [aritchie/userdialogs#239]
The iOS implementation of the TimePicker is not using the 'SelectedTime' from the TimeConfig if it is given. Instead it always defaults to the current time. It does set this property after choosing the date. I'll submit a pull request with a fix for this shortly.

**Comment by airboss001** [comment]
Yeah! Thanks @EGoverde for fixing this one. Was an big annoyance for what I was trying to do!
