### ISSUE TITLE
ActionSheetAsync cancel by touch not desired

### ISSUE THREAD

**Issue by tbalcom** [aritchie/userdialogs#241]
1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

2) The dialog displayed using `ActionSheetAsync()` can now be canceled by touching outside of the dialog in version 6.2.0.  Please provide a way to disable this new behavior.  I'm passing `null` to the cancel argument but it makes no difference.

**Comment by aritchie** [comment]
This is by design.  There must be a cancel option for actionsheetasync and touching outside runs cancel actions now.  

If you want to have an action sheet that cannot be cancelled, use the sync version which is more appropriate in any case

**Comment by tbalcom** [comment]
> There must be a cancel option for actionsheetasync

There are already two ways to close the dialog: the user can touch the cancel button, or the user can press the Android back button.  None of the other dialogs in this library are forcing me to implement cancel on touch.  I'm not using the bottom sheet mode.

**Comment by GU0L** [comment]
Having the same problem, did you find any solution?
