### ISSUE TITLE
ActionSheetAsync cancel by touch doesn't close await.Monitor

### ISSUE THREAD

**Issue by tbalcom** [aritchie/userdialogs#242]
1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

2) If I call `ActionSheetAsync` and tap outside of the dialog the `Task` doesn't complete.  Cancelling via the cancel button in the dialog or Android back button works as expected.  This appears to be the same issue as #204.

**Comment by aritchie** [comment]
My answer from #241 is still very applicable to this.
