### ISSUE TITLE
IOS: Success/Error images not showing

### ISSUE THREAD

**Issue by gmwilhelm** [aritchie/userdialogs#243]
1) Please check all of the platforms you are having the issue on
 
 - [x] iOS
 - [] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below

Version 6.2.0 from nuget doesn't show the images for success or error on iOS.

The sample app does show the images, but when i remove the references to the lib projects and add the nuget package, the images don't show up anymore. 

According to https://github.com/aritchie/userdialogs/issues/162 you fixed this in 6.1, but it looks like this fix is not in the nuget 6.2?

**Comment by aritchie** [comment]
It is obviously some weird linker issue.  At this point, I'm pretty sick of these methods as I don't use them anywhere and I'm marking them as deprecated
