### ISSUE TITLE
[UWP][ProgressDialog] Cancel text is not set

### ISSUE THREAD

**Issue by bbougot** [aritchie/userdialogs#244]
Whenever I create a progress dialog like so

```
ProgressDialogConfig.DefaultCancelText = "Cancel";
var progressConfig = new ProgressDialogConfig
{
AutoShow = true,
CancelText = "Cancel",
IsDeterministic = false,
MaskType = MaskType.Gradient,
OnCancel = OnCancel,
Title = $"Launching {game.Name}, please wait...",
};

var progress = UserDialogs.Instance.Progress(progressConfig);
```

Cancel text is left blank.

**Comment by Magic73** [comment]
Yes, I confirm.
Here's the cause:
Error: BindingExpression path error: 'Complete' property not found on 'Acr.UserDialogs.ProgressDialog, Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. BindingExpression: Path='Complete' DataItem='Acr.UserDialogs.ProgressDialog, Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; target element is 'Windows.UI.Xaml.Controls.ProgressBar' (Name='ProgressBar'); target property is 'Value' (type 'Double')
Error: BindingExpression path error: 'CancelText' property not found on 'Acr.UserDialogs.ProgressDialog, Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. BindingExpression: Path='CancelText' DataItem='Acr.UserDialogs.ProgressDialog, Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; target element is 'Windows.UI.Xaml.Controls.Button' (Name='null'); target property is 'Content' (type 'Object')

**Comment by Magic73** [comment]
inside the class Acr.UserDialogs.Uwp/ProgressDialog.cs

these two properties, are missing:

```
public double PercentComplete { get .. set ... }
public string CancelText { get... set ... }
```
        
and inside the constructor:
      `    this.CancelText = config.CancelText;`
 should be called also.
