### ISSUE TITLE
backgroundcolor of a toast, during scanning with ZXing

### ISSUE THREAD

**Issue by riclo** [aritchie/userdialogs#245]
I  can't get this done ... 

the backgroundcolor stays black and the messagecolor white.

i am using this during the scanproces with the ZXing barcodescan-module.

in IOS it's working well

Acr.UserDialogs.ToastConfig tc = new Acr.UserDialogs.ToastConfig (App.ScriptResponse);					System.Drawing.Color backclr = System.Drawing.Color.FromArgb (red, green, blue);
System.Drawing.Color frontclr = System.Drawing.Color.FromArgb (red2, green2, blue2)	;				tc.Message = "Testing";
tc.SetMessageTextColor (frontclr);
tc.SetBackgroundColor (backclr);
tc.SetDuration (1250);
Acr.UserDialogs.UserDialogs.Instance.Toast (tc);

**Comment by riclo** [comment]
I  can't get this done ... 

the backgroundcolor stays black and the messagecolor white.

in IOS it's working well

Acr.UserDialogs.ToastConfig tc = new Acr.UserDialogs.ToastConfig (App.ScriptResponse);					System.Drawing.Color backclr = System.Drawing.Color.FromArgb (red, green, blue);
System.Drawing.Color frontclr = System.Drawing.Color.FromArgb (red2, green2, blue2)	;				tc.Message = "Testing";
tc.SetMessageTextColor (frontclr);
tc.SetBackgroundColor (backclr);
tc.SetDuration (1250);
Acr.UserDialogs.UserDialogs.Instance.Toast (tc);

**Comment by aritchie** [comment]
It works only if you're current activity (the one that you are on when calling the toast) inherits from AppCompatActivity.  In the case where this does not exist, it reverts to an old mechanism where the toast colors are not supported.   I would guess that the ZXing activity doesn't inherit from this.

**Comment by riclo** [comment]
working now. thanks!

**Comment by shoeIT** [comment]
Hey, riclo I have a similar problem, the toast does not adapt colors, what did you do to solve the problem?
