### ISSUE TITLE
NRE in Xamarin Forms iOS calling UserDialogs.Instance.ShowError

### ISSUE THREAD

**Issue by lidi** [aritchie/userdialogs#246]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [x] iOS
 - [] Android
 - [] UWP
 - [] PCL

2) Please state the issue to the best of your ability below
In my app (Xamarin Forms Android and iOS) I am checking for internet connectivity and if there is none notifying a user - UserDialogs.Instance.ShowError("No connection", 3000);
When iOS starts up the above throws NRE. I have tried to try and catch it and can verify that NRE only thrown when app starts but shows error notification after it.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

StackTrace	"  at BigTed.ProgressHUD.PositionHUD (Foundation.NSNotification notification) [0x000cf] in C:\\dev\\acr\\userdialogs\\src\\Acr.UserDialogs.iOS\\ProgressHUD.cs:788 \n  at BigTed.ProgressHUD.ShowProgressWorker (Single progress, System.String status, MaskType maskType, Boolean textOnly, ToastPosition toastPosition, System.String cancelCaption, System.Action cancelCallback, Double timeoutMs, Boolean showContinuousProgress, UIKit.UIImage displayContinuousImage) [0x0023f] in C:\\dev\\acr\\userdialogs\\src\\Acr.UserDialogs.iOS\\ProgressHUD.cs:327 \n  at BigTed.ProgressHUD+<>c__DisplayClass18_0.<Show>b__0 () [0x00000] in C:\\dev\\acr\\userdialogs\\src\\Acr.UserDialogs.iOS\\ProgressHUD.cs:109 \n  at Foundation.NSActionDispatcher.Apply () [0x00000] in /Users/builder/data/lanes/3539/f37444ae/source/maccore/src/Foundation/NSAction.cs:57 \n  at (wrapper managed-to-native) ObjCRuntime.Messaging:void_objc_msgSend_IntPtr_IntPtr_bool (intptr,intptr,intptr,intptr,bool)\n  at Foundation.NSObject.InvokeOnMainThread (System.Action action) [0x00007] in /Users/builder/data/lanes/3539/f37444ae/source/maccore/src/Foundation/NSObject2.cs:556 \n  at BigTed.ProgressHUD.Show (System.String status, Single progress, MaskType maskType, Double timeoutMs) [0x0002a] in C:\\dev\\acr\\userdialogs\\src\\Acr.UserDialogs.iOS\\ProgressHUD.cs:109 \n  at BigTed.ProgressHUD.ShowImageWorker (UIKit.UIImage image, System.String status, TimeSpan duration) [0x00033] in C:\\dev\\acr\\userdialogs\\src\\Acr.UserDialogs.iOS\\ProgressHUD.cs:372 \n  at BigTed.ProgressHUD+<>c__DisplayClass26_0.<ShowImage>b__0 () [0x00000] in C:\\dev\\acr\\userdialogs\\src\\Acr.UserDialogs.iOS\\ProgressHUD.cs:156 \n  at Foundation.NSActionDispatcher.Apply () [0x00000] in /Users/builder/data/lanes/3539/f37444ae/source/maccore/src/Foundation/NSAction.cs:57 \n  at (wrapper managed-to-native) ObjCRuntime.Messaging:void_objc_msgSend_IntPtr_IntPtr_bool (intptr,intptr,intptr,intptr,bool)\n  at Foundation.NSObject.InvokeOnMainThread (System.Action action) [0x00007] in /Users/builder/data/lanes/3539/f37444ae/source/maccore/src/Foundation/NSObject2.cs:556 \n  at BigTed.ProgressHUD.ShowImage (UIKit.UIImage image, System.String status, Double timeoutMs) [0x00022] in C:\\dev\\acr\\userdialogs\\src\\Acr.UserDialogs.iOS\\ProgressHUD.cs:156 \n  at BigTed.ProgressHUD.ShowErrorWithStatus (System.String status, Double timeoutMs) [0x00000] in C:\\dev\\acr\\userdialogs\\src\\Acr.UserDialogs.iOS\\ProgressHUD.cs:150 \n  at BigTed.BTProgressHUD.ShowErrorWithStatus (System.String status, Double timeoutMs) [0x00000] in C:\\dev\\acr\\userdialogs\\src\\Acr.UserDialogs.iOS\\BTProgressHUD.cs:51 \n  at Acr.UserDialogs.UserDialogsImpl.ShowError (System.String message, Int32 timeoutMillis) [0x00000] in C:\\dev\\acr\\userdialogs\\src\\Acr.UserDialogs.iOS\\UserDialogsImpl.cs:171 \n ...

**Comment by aritchie** [comment]
It looks like you've cut the top portion of the exception out.  In any case, it looks like the usual issue where the dialog is being called for before the view is available.  Please review the FAQ in the readme!

**Comment by lidi** [comment]
You are absolutely right! My bad and thanks to the tip.
