### ISSUE TITLE
null reference exception on uwp

### ISSUE THREAD

**Issue by AlmaJensen** [aritchie/userdialogs#247]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [] Android
 - [x] UWP
 - [] PCL

2) Please state the issue to the best of your ability below

I was using the following code snippet on UWP and was getting a null reference issue when trying to open a prompt.  I fixed the issue by adding the lines that are commented out.    Might I suggest making these strings have an empty value rather than null as a default.  I had a similar issue popping up a toast on UWP but that worked fine on iOS and Android.         

var config = new PromptConfig
            {
                //Text = "",
                //Title = "Clone Pallet",
                //Placeholder = "",
                InputType = InputType.Number,
                Message = "Enter number of times to clone Pallet",
                CancelText = "Cancel",
                OkText = "Ok",
                OnAction = (sender) =>
                {
                    HandleCloneResult(sender, pallet);
                }

            };
            dialog.Prompt(config);

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

**Comment by aritchie** [comment]
Please include exceptions!

**Comment by AlmaJensen** [comment]
Exception thrown: 'System.ArgumentNullException' in mscorlib.ni.dll

**Comment by AlmaJensen** [comment]
Exception thrown: 'System.ArgumentNullException' in mscorlib.ni.dll

Sorry accidentally closed the issue.

**Comment by aritchie** [comment]
The full exception with stack trace please.

**Comment by AlmaJensen** [comment]
Sorry but there wasn't much more helpful.

MSMobile.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\AJensen\Source\Repos\Convoy\WMSMobile\WMSMobile\WMSMobile.UWP\bin\x86\Debug\AppX\System.Xml.XmlDocument.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WMSMobile.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\AJensen\Source\Repos\Convoy\WMSMobile\WMSMobile\WMSMobile.UWP\bin\x86\Debug\AppX\System.Xml.XmlSerializer.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WMSMobile.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\AJensen\Source\Repos\Convoy\WMSMobile\WMSMobile\WMSMobile.UWP\bin\x86\Debug\AppX\Version.Plugin.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WMSMobile.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\AJensen\Source\Repos\Convoy\WMSMobile\WMSMobile\WMSMobile.UWP\bin\x86\Debug\AppX\Version.Plugin.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WMSMobile.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\AJensen\Source\Repos\Convoy\WMSMobile\WMSMobile\WMSMobile.UWP\bin\x86\Debug\AppX\WMSMobile.dll'. Symbols loaded.
'WMSMobile.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\AJensen\Source\Repos\Convoy\WMSMobile\WMSMobile\WMSMobile.UWP\bin\x86\Debug\AppX\Xamarin.Forms.Platform.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WMSMobile.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Users\AJensen\Source\Repos\Convoy\WMSMobile\WMSMobile\WMSMobile.UWP\bin\x86\Debug\AppX\Xamarin.Forms.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x2f74 has exited with code 0 (0x0).
The thread 0x3a40 has exited with code 0 (0x0).
The thread 0x2eb4 has exited with code 0 (0x0).
The thread 0x3418 has exited with code 0 (0x0).
'WMSMobile.UWP.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
Client Count 29
The thread 0x1630 has exited with code 0 (0x0).
The thread 0x3094 has exited with code 0 (0x0).
The thread 0x2aec has exited with code 0 (0x0).
Exception thrown: 'System.ArgumentNullException' in mscorlib.ni.dll
The thread 0x3910 has exited with code 0 (0x0).
The thread 0x26c4 has exited with code 0 (0x0).
The thread 0x2964 has exited with code 0 (0x0).
The thread 0x2c94 has exited with code 0 (0x0).
