### ISSUE TITLE
solved 

### ISSUE THREAD

**Issue by slayer35** [aritchie/userdialogs#248]
I always get this error when I try to show error message,or show loading by forexample;
using (UserDialogs.Instance.Loading(...)) {
/// do you async stuff here,  
}

"Java.Lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference"

**Comment by aritchie** [comment]
First off, the title is very inappropriate if you want help.   Put something descriptive next time please.  
Secondly, you need to give me far more context about your issue by
a) including the full stacktrace of the exception!
b) what is the code around this?  It it running in the constructor, in a command, etc?  
c) have you called the Init method from your launcher activity?  If so, how?
