### ISSUE TITLE
iOS UIAlertController Styling

### ISSUE THREAD

**Issue by ghost** [aritchie/userdialogs#249]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
- [X] iOS
- [] Android
- [] UWP
- [] PCL

2) Please state the issue to the best of your ability below
No Issue. Was wondering if I submitted a pull request that offered.
a. Background color
b. Text color.
c. Font

If you would be interested in that. 

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

**Comment by aritchie** [comment]
Absolutely.  I don't guarantee they get in, but I'm happy to take a look

**Comment by highplains** [comment]
Ok, ill try giving it a whirl. thanks
