### ISSUE TITLE
Application name forced to $projectname$

### ISSUE THREAD

**Issue by Don2** [aritchie/userdialogs#25]
After including your nuget package into my android application suddenly my application name has changed to $projectname$ as I use the same string resource key "ApplicationName" inside my app.

Can you remove these unused resources

**Comment by aritchie** [comment]
You should enter your application name in your android manifest.  These resources are created by default and have never given me an issue.

**Comment by Don2** [comment]
I have but I use the same resource key as yours, if you don't require them then why not remove them. I understand I can simple use another resource key.

It's just simple a suggestion.

**Comment by aritchie** [comment]
I will remove the resources.  That's no problem.  I'm just not doing a release for it right away.  It will go with other things

**Comment by Don2** [comment]
Ya, of course I fully understand that.
