### ISSUE TITLE
ActionSheetConfig does not provide a way to set message

### ISSUE THREAD

**Issue by Cheesebaron** [aritchie/userdialogs#250]
1) Please check all of the platforms you are having the issue on
- [x] iOS
- [ ] Android
- [ ] UWP
- [x] PCL

2) Please state the issue to the best of your ability below

`ActionSheetConfig` does not provide any way to set the message of the, and currently just sets it to `null`: https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs.iOS/UserDialogsImpl.cs#L233

Would really like a way to set this to a value, even though it might not be possible on all platforms.

**Comment by Cheesebaron** [comment]
At the same time it would be great to be able to change the UIAlertControllerStyle to Alert as well. Since Prompt does not allow setting destructive options currently.

**Comment by aritchie** [comment]
There wasn't a nice way to apply message to the droid side of things.  With the bottom sheet soon to be mainstream, this will prove even more of an issue.  

As for the second part of this request, were you looking for the centered dialog with multiple buttons (ie positive/negative/neutral)?  If so, I was thinking about this across all the alert styled dialogs for the next major release.

**Comment by Cheesebaron** [comment]
I am just thinking whether it would be OK to just have a Message property in the Config class? If the particular platform does not support the message it will simply not be shown. You could probably document your way out of it. However, I am not sure what you mean that there is no nice way to apply the message on droid. As far as I can see it is a custom Fragment you present for the ActionSheet, so you are in control what your view contains, no?

For the second part. Exactly. Normal UIAlertView on iOS does not support painting the destructive button red, which UIAlertController does, when using UIAlertControllerStyle.Alert. Then it behaves like UIAlertView, just with cancel, neutral and destructive buttons.

**Comment by shmoogems** [comment]
Just curiously @Cheesebaron and @aritchie  are you aware if this is being worked on? I might put it on my todo list if not.

**Comment by higher-faster-better** [comment]
any progress in messaging issue in android? I want to be sure if I need to customize anything or not for it.
