### ISSUE TITLE
UserDialogs.Instance.Progress auto hide when tap it

### ISSUE THREAD

**Issue by imicer** [aritchie/userdialogs#252]
1) Please check all of the platforms you are having the issue on
 
 - [x] PCL

2) Please state the issue to the best of your ability below

version:
Acr.UserDialogs  version=6.2.0
usage:
`using (var dlg = UserDialogs.Instance.Progress(Constants.FILE_UPLOADING, onCancel: () =>
{DoCancel();}, cancelText: Constants.CANCEL))
{
        //Do Something
}`

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

Details and screenshot as follow:

![issue](https://cloud.githubusercontent.com/assets/17045801/18409123/0a66904a-7773-11e6-80d3-60e10b774d98.png)

**Comment by aritchie** [comment]
Why are you expecting a cancel message?  The oncancel action is just to say the user presses the cancel button

**Comment by imicer** [comment]
I need cancel a httpclient upload task.

**Comment by aritchie** [comment]
Setting oncancel adds a cancel button that you can react to.  If you don't want to have that, don't set oncancel.

**Comment by aritchie** [comment]
If you do want to have the cancel button then I'm not sure what the issue is here???

**Comment by imicer** [comment]
I know how to use oncancel.
My issue is when I tapped the "cancel button" outside  area,i have not tap cancel button,why the progress hide and task was canceled?

**Comment by aritchie** [comment]
Please in the future, specify the platform and the exact detail you just did.  Your screenshot arrow is pointing at the cancel button and it says no message was shown.  

Your issue was actually that you can press anywhere on the dialog and cancel was called.  The answer to this is that this is how btprogresshud (ios) and andhud (android) behave.
