### ISSUE TITLE
[iOS]loading.Hide() effect Toast,make it disappeared fastly in spite of timeoutMillis

### ISSUE THREAD

**Issue by yz1311** [aritchie/userdialogs#253]
Platform: iOS
Library Version: 5.3.0

in android,there is no need to call loading.hide(),because .toast(....) will do it
but is ios,i must call loading.hide() to hide the loading dialog  and it affect toast and make it disappeared fastly in spite of timeoutMillis

**Comment by aritchie** [comment]
The toast defect is address in 6.x.  Please note that I only support the latest version.  

Also note, that you should always close a previous dialog before showing a new one.  This library does not operate as a manager.
