### ISSUE TITLE
PickerPrompt - feature

### ISSUE THREAD

**Issue by airboss001** [aritchie/userdialogs#254]
Hi @aritchie,

Not sure where to put this so "I choose you!" [in his best Pokemon Trainer voice]

**Edit: Forgot to mention this is iOS only right now.**

I have forked the project and created a new prompt type of PickerPrompt that allows you to define 1 or more pickers for selection.

I am looking for feedback on what else I need to do, or any specific changes you might want or think should be done before submitting a pull request (and I will need help in figuring out how to do that as I haven't done that before)

Its located here: https://github.com/airboss001/userdialogs

I basically copied what was done for the TimePrompt and adjusted as needed, then added to the samples.

It uses a PickerPromptConfig to setup the sources and set the selected indices.

```
public class PickerPromptConfig
    {
        public static string DefaultOkText { get; set; } = "Ok";
        public static string DefaultCancelText { get; set; } = "Cancel";

        public string Title { get; set; }
        public string OkText { get; set; } = DefaultOkText;
        public string CancelText { get; set; } = DefaultCancelText;
        public IList<IList<string>> PickerCollections { get; set; }
        public IList<int> SelectedItemIndex { get; set; }

        public Action<PickerPromptResult> OnAction { get; set; }
        public bool IsCancellable { get; set; } = true;
    }
```

For each IList in PickerCollections it will add a picker and populate it, then set the picker items.
For each PickerCollections there must be a corresponding item in the SelectedItemIndex collection.
For example if you had defined 3 picker collections, you would need 3 indexes in the index collection.

The PickerViewModel keeps a local copy of the selected indices and that gets updated on the closing actions.

```
 public class PickerViewModel : UIPickerViewModel
        {
            private IList<IList<string>> _collections;
            public IList<int> SelectedItems;
            public PickerViewModel(PickerPromptConfig ppc)
            {
                _collections = ppc.PickerCollections;
            }
            public override nint GetRowsInComponent(UIPickerView pickerView, nint component)
            {
                return _collections[(int)component].Count;
            }

            public override string GetTitle(UIPickerView pickerView, nint row, nint component)
            {
                return _collections[(int)component][(int)row];
            }

            public override nint GetComponentCount(UIPickerView pickerView)
            {

                return _collections.Count;
            }

            public override void Selected(UIPickerView picker, nint row, nint component)
            {
                SelectedItems[(int)component] = (int)row;
            }
        }
```

Here is how the values are returned in the Ok action

```
            button.TouchUpInside += async (s, e) =>
            {
                SelectedItems = ((PickerViewModel)picker.Model).SelectedItems;
                await this.DismissViewControllerAsync (true);
                Ok?.Invoke(this);
            };
```

Those are passed back in the usual PickerPromptResult

```
    public class PickerPromptResult : AbstractStandardDialogResult<IList<int>>
    {
        public PickerPromptResult(bool ok, IList<int> selectedValues) : base(ok, selectedValues)
        {
        }

        public IList<int> SelectedValues => this.Value;
    }
```

**Comment by airboss001** [comment]
Two enhancements I can think of right now that would be nice are:

- Configuring a separator character that would go between each picker, for instance . (dot) or : (colon)
- Setting a flag to set it up for a spinner like in the time prompt to rotate forward and backward.

**Comment by aritchie** [comment]
I love it.  If you can get it on android, I will bring it in for sure

Two bits of feedback:
- I would likely call this MultiSelectPrompt or MultiPickerPrompt to make it a bit more known.  Picker usually implies single selection to me anyhow.

- the use of two collections (selecteditems and values) is usually something I stay away from.  Use of a state object is usually safer for the end dev.  The state object would simply be a Boolean (IsSelected) and the string (Value).  The same object could be used in the result.

Great PR so far.  Thanks!

**Comment by airboss001** [comment]
So I have updated the fork to use MultiPickerPrompt, as well as added the ability to set IsSpinner in the configuration that will automatically add multiple copies of the passed in collection and set the selected value in the middle similar to how time or date can be rotated forward or backward.

I am not sure what you are asking for on the state object.
Are you saying the passed in collection should consist of objects that contain a bool IsSelected, and the Value, and then when that is passed back you would have to enumerate over all the lists to figure out what was selected? That doesn't seem to efficient from what I am thinking or easier to use. I would expect that if I passed in 2 lists to select a value from, I would get results that would have the two selections, and not the same list back.
I think I must be missing something here and hopefully you can set me straight.

**Comment by airboss001** [comment]
Here is a video of it in action:
https://youtu.be/4hjYZcD0NiA

**Comment by airboss001** [comment]
The Android version is beyond my skills. I asked for help over on the Xamarin forums here, but no responses.
https://azure.microsoft.com/en-us/documentation/articles/service-fabric-get-started/

**Comment by aritchie** [comment]
I'm going to close this for now as it requires implementations for UWP and Android.  This isn't a dialog I would specifically use, so I can't devote any time to it myself.  If you ever do get it fully implemented, I would be happy to integrate it.  Just reopen this case at that time.

**Comment by airboss001** [comment]
I understand, 

I am surprised no one on android needed something like this and wanted to contribute. I don't have time here right now,, but will see if I can do something for UWP as soon as I can if no one else picks up the baton for that.

**Comment by JordanGout** [comment]
Hi @airboss001 & @aritchie 

Here my android implementation
