### ISSUE TITLE
Unit Test fails on ToastConfig

### ISSUE THREAD

**Issue by mrtnkrstn** [aritchie/userdialogs#255]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [] Android
 - [] UWP
 - [x] PCL

2) Please state the issue to the best of your ability below:

Unit Testing (Nunit) a Xamarin PCL, specifically a ViewModel that uses a Toast with a ToastConfig:

`UserDialogs.Toast(new ToastConfig($"Login failed. {ex.Message}")
{
	Duration = TimeSpan.FromSeconds(4),
	BackgroundColor = Color.Red
});`

where `UserDialogs` is an instance of `IUserDialogs` that is instantiated via IoC.

The problem is that when I run a Unit Test that hits the above code, it freezes at `BackgroundColor = Color.Red`. If I take out that line, the Unit Test works perfectly. Also, Unit Tests that hit `UserDialogs.ShowLoading()` and `UserDialogs.HideLoading()` work fine.

Perhaps I need an extra step in configuring the Unit Tests?

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

None

**Comment by aritchie** [comment]
This would be an issue with splat if anything.  I run unit tests in other projects where color is used though.  I'd take a look at the splat repo to see what may be going on

**Comment by mrtnkrstn** [comment]
This works:

`UserDialogs.Toast(new ToastConfig($"Login failed. {ex.Message}").SetDuration(TimeSpan.FromSeconds(4)).SetBackgroundColor(Color.Red));`
