### ISSUE TITLE
Alert: Prevent from closing

### ISSUE THREAD

**Issue by zonkzen** [aritchie/userdialogs#259]
Is there a way to prevent closing the Alert?

It's being dismissed automatically when OK button is pressed. It would be great to have this behaviour conditional.

**Comment by aritchie** [comment]
I'm sorry - this feature request does not make any sense to me.  Why would you want to block them from closing the window?  It is contextual information. 

You could technically use the Loading method (indeterministic loader) to potentially accomplish this.
