### ISSUE TITLE
Wrapping Text on Toasts

### ISSUE THREAD

**Issue by BlueFire-LLC** [aritchie/userdialogs#265]
Is is possible to add text wrapping on toasts? And to narrow the height of the toasts to the text (including wrapped lines)?

**Comment by aritchie** [comment]
On what platform?

**Comment by BlueFire-LLC** [comment]
All three (Android, iOS, UWP) but most importantly UWP.

**Comment by aritchie** [comment]
Why is UWP most important?  

I definitely won't change the heights much between what they currently are.  Android likely won't facilitate large amounts of text and it does currently wrap the text to two lines.

**Comment by BlueFire-LLC** [comment]
I have been using the Toasts.Forms.Plugin for toasts and yours for alerts but EgorBor has changed to conform with the native platform which I don't like so I'd like to use yours now for both toasts and alerts, UWP is more important because I can still use an older version of Toasts.Forms.Plugin that works just for Android and iOS but not for UWP. But I would rather use the same for all platforms so if you could modify your UWP to support multi-line that would be great.

The reason for reducing the size of the toast box in UWP is to make it look similar to the others that do not have any padding around the text.

Also, I use color to distinguish between toasts (info, warning, error, success). Any chance you can add text foreground and background colors to Android?

Thanks BTW for a good addin. It has helped me a lot and allowed me to concentrate more on my app's functionality.

**Comment by aritchie** [comment]
I have added some basic word wrapping to UWP in 6.2.4
