### ISSUE TITLE
Sync ActionSheet with no Cancel action is still being dismissed on tap outside (works only on appcompatactivity)

### ISSUE THREAD

**Issue by darcon77** [aritchie/userdialogs#266]
1) Please check all of the platforms you are having the issue on
- [] iOS
- [*] Android
- [] UWP
- [] PCL

2) Please state the issue to the best of your ability below

I'm on 6.2.3 version of Acr.UserDialogs and displaying synchronous version of ActionSheet dialog. The source shows that if Cancel is not set in the config, dialog is marked as non-cancelable and close on tap outside is set to false, but my dialog still is dismissed on tap outside. How do I prevent this from happening?

```
var cfg = new ActionSheetConfig().SetTitle("My Action Sheet");
var btIcon = BitmapLoader.Current.LoadFromResource("my_icon.png", null, null).Result;
foreach (var item in listItems)
    {
        cfg.Add(item.Name, () => callback(item), btIcon);
    }
this.Dialogs.ActionSheet(cfg);
```

**Comment by aritchie** [comment]
What is your root activity?  I only ported this new logic into the AppCompatActivity version.

**Comment by darcon77** [comment]
It's MvxSplashScreenActivity

**Comment by aritchie** [comment]
How about the activity that is active at the time of calling for the dialog?

**Comment by darcon77** [comment]
SplashScreen is active. In my implementation I check for certain things before firing InitializationComplete

**Comment by aritchie** [comment]
ahh - I'm afraid for now you'll have to live with this as it will go into the backlog of requests (or you can submit a PR).  You can also "hijack" the cancel button and replace it will a default option

**Comment by darcon77** [comment]
How would "hijacking" work? I don't want to display cancel button.

Also, is there a way to detect when the dialog is dismissed without any button callback ever being triggered?

**Comment by aritchie** [comment]
The cancel button doesn't have to be cancel.  You can rename the button.  If you simply don't want the button or the dismiss, you'll have to implement yourself or wait until I get around to it.

Not at the moment.  Since dismiss essentially equals cancel on other platforms

**Comment by darcon77** [comment]
Okay, thanks!

**Comment by chrismcb** [comment]
Am I understanding your comment correctly? On Android, there is currently no way to detect if the dialog is dismissed when the user taps outside the dialog? I don't care if the user clicks cancel or taps outside the dialog, I'm trying to figure out when the dialog goes away. Right now if you can bring up "multiple" dialogs by quickly tapping my button (there aren't really multiple, but the second one pops up as soon as the first one is dismissed)

**Comment by aritchie** [comment]
@chrismcb  - Yes - use an AppCompatActivity and you won't have the issue or add a Cancel option.  The cancel option will be called when the dialog goes away.

**Comment by chrismcb** [comment]
Thanks for the response. I don't want to hijack this issue, I only asked the question here because of your answer to the question about detecting the dismissal. So I opened a new issue about the problem I'm having. I have implemented a work around that works. But the behaviour I'm seeing is not what you claim I should be seeing.

**Comment by cipriancoj** [comment]
Hi, i have the same issue

**Comment by aritchie** [comment]
This is fixed in 6.5.1.  @cipriancoj - please post additional info in the future.  +1's are completely useless for OSS maintainers

**Comment by cipriancoj** [comment]
Thanks @aritchie but even with the 6.5.1 the ActionSheet is still being dismissed on tap outside.

This is a piece of code where I call the ActionSheet
```
var values = new string[] { "a", "b" };
var result = new string[values.Length];
var canceled = false;
var userDialogs = UserDialogs.Instance;

var actionSheetConfig = new ActionSheetConfig()
.SetTitle("ciao")
.SetCancel("cancella", () => { canceled = true; }, null)
.SetMessage("ook")
.SetUseBottomSheet(false);

foreach (var val in values)
{
      actionSheetConfig.Add(
      val,
      () =>{  result = new string[] { val }; },
      null);
}

var dialogResult = userDialogs.ActionSheet(actionSheetConfig);

```

**Comment by aritchie** [comment]
@cipriancoj You have a cancel option, so it is designed to cancel when you tap outside.  This issue is for when you DO NOT have a cancel option in which case it blocks

**Comment by cipriancoj** [comment]
Sorry, I got the wrong issue!
