### ISSUE TITLE
Add more Entry prompt

### ISSUE THREAD

**Issue by tonogueira2** [aritchie/userdialogs#268]
Good afternoon, I would like to know how trim add more than one Entry at the prompt to make a kind of User Registration or Similar?

**Comment by aritchie** [comment]
You can use the login prompt I guess.  It isn't ideal.  You really should put this in a screen with a viewmodel though.  This library is designed for quick and easy dialogs, not full blown business screens

**Comment by tonogueira2** [comment]
Thank you for quick return, it makes the community stronger, congratulations ...
But what I have in a financial register, within the system have a screen with details of the financial. My need is to have a button for fast access, which I enter.

Description, Date, Value, Location!

and quickly is included in my detail, today I do on another page, but would be better and easier if I put the Dialog for this rapid insertion.

what would be the best option and how do I do?

I used the User's registration as an example !!

**Comment by aritchie** [comment]
For this specific need, this is not the library you want

**Comment by tonogueira2** [comment]
Okay, so in any case they do not exist as I put more than one Entry in dialogs?

**Comment by aritchie** [comment]
I do not support more than one entry field
