### ISSUE TITLE
Can't delete characters on Android in LoginAsync()

### ISSUE THREAD

**Issue by SimonSimCity** [aritchie/userdialogs#270]
1) Please check all of the platforms you are having the issue on
 
 - [?] iOS
 - [X] Android
 - [?] UWP
 - [?] PCL

2) Please state the issue to the best of your ability below

When calling LoginAsync(), I get a dialog, to enter a username and password, but I can't delete any character I typed in.

I tested it with the latest version (6.2.3), 6.1.x and got it finally working again by getting back to 6.0.1

**Comment by aritchie** [comment]
Thanks - this is fixed in 6.2.4
