### ISSUE TITLE
call ActionSheet of another Actionsheet

### ISSUE THREAD

**Issue by tonogueira2** [aritchie/userdialogs#271]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
 
 - [] iOS
 - [] Android
 - [] UWP
 - [x] PCL

2) Please state the issue to the best of your ability below

I am implementing the ActionSheet, all OK.
but I can call another ActionSheet starting from ActionSheet.

Example:

ActionSheet: Edit Category

Call

ActionShett: Add or Remove?

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

cfg.Add("Categoria!", () => cfgCategoria, editpenPNG);
or
Cant convert Action

Only Assigment, call, increment... ... ...

**Comment by aritchie** [comment]
Just create a new actionsheet config and display.
