### ISSUE TITLE
Latest Xamarin.Android.Support.Design v24 is not supported yet

### ISSUE THREAD

**Issue by IlSocio** [aritchie/userdialogs#273]
1) Please check all of the platforms you are having the issue on

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

2) 
Acr.UserDialogs v6.2.5 does not support yet the [Xamarin.Android.Support.Design v24.2.1-rc1](https://www.nuget.org/packages/Xamarin.Android.Support.Design/24.2.1-rc1)

3) 
When installing the [Xamarin.Android.Support.Design v24.2.1-rc1](https://www.nuget.org/packages/Xamarin.Android.Support.Design/24.2.1-rc1) the Acr.UserDialog v6.2.5 will be automatically uninstalled and downgraded to Acr.UserDialog v4.1.4

Addendum:
Unfortunately, some material features, like the [Password Visibility Toggle](http://codevscolor.com/2016/08/android-material-design-tutorial-10-password-visibility-toggle/), are available only on Design v24

**Comment by aritchie** [comment]
The issue template explicitly requests that library update requests are not requested.  That line seems to have been conveniently removed.

Please show some respect for this guideline in the future.  In any case, I'm not taking the time to investigate a beta/rc lib update.

**Comment by IlSocio** [comment]
Please accept my apologies, my intention was just to report the issue and patiently wait for any future improvements.

**Comment by IlSocio** [comment]
Xamarin.Android.Support.Design v 24.2.1 is now final:
https://www.nuget.org/packages/Xamarin.Android.Support.Design/24.2.1

Updating to the latest v24.2.1 causes UserDialog to be downgraded to v4.1.4

**Comment by aritchie** [comment]
You still ignored my response back to you and the issue template.  I'm well aware of library updates.  I have nuget too
