### ISSUE TITLE
On iOS 10.0 the activity indicator never goes away

### ISSUE THREAD

**Issue by tad442** [aritchie/userdialogs#276]
Winphone 8 is not supported
Please refrain from +1's, nuget library update requests (this is not an issue with the library), and requesting timelines for something.  Please also make sure you have read the FAQ section on the README

1) Please check all of the platforms you are having the issue on
- [x] iOS
- [] Android
- [] UWP
- [x] PCL

2) Please state the issue to the best of your ability below

I am using this package in my xamarin forms cross-platform app and it has worked great. On login I use: using (UserDialogs.Instance.Loading(message))
This has worked fine on iOS devices up till iOS10.0. On iOS 10.0 the activity indicator never goes away. Are you familiar with this problem. I am using version 6.2.5 and version 2.1.0 of acr.support. Thanks!

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

**Comment by aritchie** [comment]
It works fine for me.  Please supply a test case and try the sample app to make sure it works for you as well

**Comment by aritchie** [comment]
Since you have not replied to this thread, I am closing this issue.
