### ISSUE TITLE
UserDialogs does not work when I set manually the App.Current.MainPage

### ISSUE THREAD

**Issue by fcogutierrez** [aritchie/userdialogs#277]
I am having issues with UserDialogs when I set manually the `App.Current.MainPage`.

For example, I am in a Login page, when I do login and I want to navigate to a MasterPage (removing the LoginPage in the navigation), what I do is something like:

`App.Current.MainPage = new MyMasterPage();`

Then, in this MasterPage, I am using the `ShowLoading()` method for an asyncronous operation but **this is not displayed**. For example the `Toast()` works perfectly. Am I doing something wrong?

Thanks in advance.

**Comment by aritchie** [comment]
You shouldn't use ShowLoading at all if you can avoid it.  You should always use Loading and control the scope of when it displays and disappears.  

using (UserDialogs.Loading("I'm loading stuff")) 
{
// do some stuff here
}

As to why you're having the issue, I would need a test sample.  I suspect if you use the method above that I suggest, things will work.

**Comment by aritchie** [comment]
I am closing this issue as no additional details have been supplied as requested.

**Comment by fcogutierrez** [comment]
Hello @aritchie, I have tried to use:

```
using (UserDialogs.Loading("I'm loading stuff")) 
{
    // do some stuff here
}
```

But is still not working...

**Comment by aritchie** [comment]
Provide a full sample case then.
