### ISSUE TITLE
PromptConfig.SetMaxLength seems to be ignored on Android

### ISSUE THREAD

**Issue by tbalcom** [aritchie/userdialogs#278]
1) Please check all of the platforms you are having the issue on
- [] iOS
- [x] Android
- [] UWP
- [] PCL

2) Please state the issue to the best of your ability below

I'm trying to limit the maximum number of digits a user can input into the prompt dialog.  I've called `SetMaxLength(6)` but it seems to be ignored because I can still input more than 6 digits.  I'm using version 6.2.6.  This is how I'm showing the dialog:

```
var startingOdometer = await UserDialogs.PromptAsync(new PromptConfig()
                    .SetTitle("Starting Odometer")
                    .SetMessage("Input the 6 digit starting odometer.")
                    .SetInputMode(InputType.Number)
                    .SetMaxLength(6));
```

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

N/A

**Comment by aritchie** [comment]
It appears to be ignored in numeric input types

**Comment by aritchie** [comment]
This isn't something that can be fixed as nicely as I was hoping.  There is a validate feature coming soon that will allow you to manage this yourself
