### ISSUE TITLE
Modal within a Modal fails to display dialogs in iOS

### ISSUE THREAD

**Issue by bob3695** [aritchie/userdialogs#28]
When you open a modal from a modal in iOS and try and display a dialog (tested an alert in this case with MvvmCross) the call silently fails and hangs up execution (or in the case of using the async call stops execution on that line but leaves app responsive). The reason for this is the implementation of finding the presented view controller. https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs.iOS/UserDialogsImpl.cs line 348 needs to become recursive searching the view controller with a null PresentedViewController. You can accomplish this with this code (tested in my solution and worked like a champ):

```c#
protected UIViewController GetCorrectPresentedViewController(UIViewController viewController)
{
    if (viewController.PresentedViewController != null)
        return this.GetCorrectPresentedViewController (viewController.PresentedViewController);
    return viewController;
}
```

and changing line 348 to be:

```c#
return this.GetCorrectPresentedViewController (root.PresentedViewController);
```

I apologize for not creating a pull for this but I couldn't get the solution to build in the short time I tried and opted for putting the implementation for iOS directly in my project and modified the code to get around this issue until it is resolved.

**Comment by bob3695** [comment]
I worked out my issue with the build and created pull request. https://github.com/aritchie/userdialogs/pull/29

Feel free to reject it if you have another way in mind but the code is there for you if you want to take my approach to the fix.

**Comment by jeffdoolittle** [comment]
any updates on this this bug fix will be in included in an upcoming release?

**Comment by aritchie** [comment]
This has been issued to nuget.  Version 3.4

**Comment by jeffdoolittle** [comment]
Thanks, cheers!
