### ISSUE TITLE
Cannot validate a PromptDialog's input

### ISSUE THREAD

**Issue by avinabmalla** [aritchie/userdialogs#282]
I have been using this library for a few days for porting an Android app to Xamarin, and found it to be very useful.

I could not find a method that would prevent the prompt dialog from being dismissed once the "Ok" button is pressed. So, the dialog needs to be shown again in the case of an invalid input, which doesn't look very good as compared to just showing a toast message.

**Comment by aritchie** [comment]
These are designed to be simple dialogs.  Not replacements for viewmodels/full views.  If validation and disabling buttons is something you need, I would suggest using a full view

**Comment by aritchie** [comment]
I've rethought this request out and I will look to add something in the next release

**Comment by aritchie** [comment]
Released in 6.3

**Comment by aritchie** [comment]
PromptConfig.OnTextChanged = args => { args.IsValid = true/false; }
