### ISSUE TITLE
On ANDROID Cancelling an ActionSheetAsync by tapping outside the Action Sheet results in no longer being able to call up the ActionSheet

### ISSUE THREAD

**Issue by SOFSPEEL** [aritchie/userdialogs#284]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [X] PCL

## Version of OS(s) listed above with issue
Running ios 10 SDK

## Version of ACR UserDialogs Library
6.3 but think this problem is also in some earlier version

## Expected Behaviour
When using the **_non async_** ActionSheet the behavior works properly as the action sheet does not go away when the area outside the action sheet is tapped.

## Actual Behavior

- Press a button that results in the following async call.
- Call var optionText = await ActionSheetAsync("", Dialogs.Constants.Cancel, null, options);
- Action sheet with multiple options and a cancel button is raised as expected.
- Tap anywhere on screen and dialog goes away.
- Try pressing the button again, then ActionSheet no longer shows up.

Note that if the cancel button is pressed then there are no issues when the button is again pressed (i.e. action sheet is displayed once more). 
     

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Please provide a test sample.  I ran this exact case through the sample app located within this repo and it works fine.

**Comment by SOFSPEEL** [comment]
Will generate a sample, erroneously put down IOS as being the issue, Android is the problem though, putting together sample now.

**Comment by SOFSPEEL** [comment]
K, So I isolated the issue, see my repo Please find the repo here: [https://github.com/SOFSPEEL/App2]  to reproduce. Note that I use ACR.UserDialogs with MvvMCross and more specific to this issue, my buttons are tied to MvxAsyncCommand's,

I think the **_root cause_** of the issue is that cancelling the action sheet (by clicking outside the dialog) leaves the AsyncCommand in a running state (see IsRunning=true below), so subsequent button pushes don't result in another Async command execution. Note that it is very common to use MvxCommand and MvxAsyncCommand's, particularly when binding in MvvMCross
 
<img width="715" alt="bug" src="https://cloud.githubusercontent.com/assets/1612646/19943523/0a0c0066-a0f5-11e6-94e0-2f65342e3593.png">

**Comment by SOFSPEEL** [comment]
Note too that I recognize there are several workarounds, to this issue, like for example newing up the MvxAsyncCommand on each button push, but would doing this leave "Running" commands around?

**Comment by SOFSPEEL** [comment]
One other thing that may be relevant to this issue, is that if ActionSheet is used (as opposed to ActionSheetAsync) then tapping outside results in the dialog **_not_** being dismissed. If you could make the async action sheet work the same way then the above problem will probably go away.

**Comment by aritchie** [comment]
Just use the sync version for now.  I may deprecate the actionsheetasync.  I brought it over because Xamarin forms used this signature, but I find it inflexible.

**Comment by duzenko** [comment]
Bumped into this too.
It should be good to mark the function as obsolete or something because under these conditions it never returns and is leads to tap locks .

**Comment by aritchie** [comment]
Fixed in 6.5.1

**Comment by acaliaro** [comment]
@aritchie I am using 6.5.1 on Android 4.1.1

This is my code

            string funzioneSelezionata = await UserDialogs.Instance.ActionSheetAsync("FUNZIONE", "Annulla", "", null, _funzioni);
		
if I tap outside the popup, I can't press again the button that I have used to display the popup. Button is disabled...

**Comment by aritchie** [comment]
@acaliaro I already stated in this defect to use the sync version.  The async version will likely be gone in v7.
