### ISSUE TITLE
Calling ShowLoading() is not causing loading indicator in UI on each case in Android.

### ISSUE THREAD

**Issue by Szymaniuk** [aritchie/userdialogs#290]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [*] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue

Android 5.1 as well as 7.0 (seems to be each Android release).
Xamarin.Forms newest release - 2.3.2.127. Android SDK newest - up to Android 7.0.

Tested on three Android devices, from different manufactures.

## Version of ACR UserDialogs Library

6.3.1.
Issue occured in past also in previous ACR UserDialogs release versions.

## Expected Behaviour

Invoking *ShowLoading()* should cause showing loading indicator in UI, till *HideLoading()* is invoked.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

Invoking *ShowLoading()*, mostly in non-async codes (but also in some async codes), cause missing loading indicator in UI - app UI seems to be freezed.
On iOS *ShowLoading()* works just perfectly! No issue there. Only Android seems to be buggy.
Example?
UI *ListView* with some items collection behind.
Some button in UI, that cause items collection re-ordering/sorting (whatever), that will trigger reloading *ListView* in UI (via Binding).

Default code - buggy:
https://dl.dropboxusercontent.com/u/95300926/Default_code.mp4
Default code + calling *await Task.Delay(100);*, right after *ShowLoading()*:
https://dl.dropboxusercontent.com/u/95300926/Default_code_plus_Task_Delay.mp4
Even if in second case - added calling dummy *await Task.Delay(100);* cause some strange "handing" of UI (loading indicator is not "running" as it should), at least user, that uses app can see, that there is something working/processing behind.

Seems, that such crappy *await Task.Delay();* works only, if miliseconds parameter is higher that around *35* (putted *100* for above example).

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
1) please copy/paste your Init code
2) where are you calling for showloading?  In your constructor? 
3) please provide a test case that causes the issue so I can debug the issue.

**Comment by Szymaniuk** [comment]
1) You mean *MainActivity* UserDialogs Init code?

`        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            Forms.Init(this, bundle);

            UserDialogs.Init(() => (Activity)Forms.Context);

            Telerik.XamarinForms.Common.Android.TelerikForms.Init();
            var app = new App();

            LoadApplication(app);
        }`

2) I'm not calling *ShowLoading()* in any case in any constructor - already read about that in FAQ, or somewhere :).
I got "clickable" label in UI, that cause *Command* being invoked, which calls some void method, let say *RefreshList()*, and at the beginning here, I'm calling *ShowLoading()*:
`        private async Task Refresh(bool revertSorting = false)
        {
            UserDialogs.Instance.ShowLoading();

            //await Task.Delay(100);

            // some list sorting/ordering logic here (not async logic)
            UserDialogs.Instance.HideLoading()
        }`

3) Currently, I cannot prepare whole solution, that you could reproduce, but if needed, I'd try in next days.

**Comment by aritchie** [comment]
First, your video shows the loading being very jumpy because you are likely blocking the main thread with your sync call.  Remove the delay and wrap your sync call in Task.Run or something.  It is likely that you are blocking the initial render before calling it to hide.  The delay just gives the UI a moment to get the loader up.

**Comment by Szymaniuk** [comment]
Any real working example?
I've already tried with some:
```
*Task.Run(() => {
// some list sorting/ordering logic here (not async logic)
});*
```
also
```
*await Task.Factory.StartNew(() =>{
// some list sorting/ordering logic here (not async logic)
});*
```

etc.
Each and every time, it's invoking fine (means code is beeing invoked), but no changes in case of loading indicator - it's just not appearing

**Comment by aritchie** [comment]
This works fine in real world for me and I use it everywhere.  At this point, I need a test case if I'm going to be able to help you

**Comment by aritchie** [comment]
Please reopen if you find new info or teens a test case with the issue

**Comment by stavrianos** [comment]
i have the same issue in 2 different android devices with 4.4 and 6.0. i use the code like that 
```
UserDialogs.Instance.ShowLoading();
 //long waiting code 
UserDialogs.Instance.HideLoading();
```

i have change the code to 
```
using (UserDialogs.Instance.Loading("Loading", () => 
{ 
//code
}))
```
but again nothing happens.
i have use 6.3.8,6.3.11, 6.4.1,6.5.1 versions .

**Comment by aritchie** [comment]
@stavrianos Please provide additional details or a reproducible case.  Simply reiterating code that I've seen isn't going to do anything for me to be able to help you.

**Comment by alexytiger** [comment]
I have the same issue also , here is an example of the code

This on is working:
UserDialogs.Instance.ShowLoading();
await Task.Delay(3000);
UserDialogs.Instance.HideLoading();

But this one is not:
UserDialogs.Instance.ShowLoading();
using (var ctx = _contextCreator())
                {
                    TotoItems.Clear();

                    var result = await ctx.TodoItems.ToListAsync();
                    TotoItems = new ObservableCollection<TodoItem>(result);

                }
UserDialogs.Instance.HideLoading();

**Comment by alexytiger** [comment]
I noticed also that when 'long waiting code' is happen too fast 
UserDialogs.Instance.ShowLoading();
 //long waiting code 
UserDialogs.Instance.HideLoading();

you may not get a chance to see the loading indicator in emulator, so i use to put some delay on the top of it :
UserDialogs.Instance.ShowLoading();
 //long waiting code 
await Task.Delay(2000);
UserDialogs.Instance.HideLoading();
