### ISSUE TITLE
How to check if UserDialog is valid to call?

### ISSUE THREAD

**Issue by jamesatgithub** [aritchie/userdialogs#291]
Hi I have some code which is triggered by push notification, it's ok when the app in foreground, while the app in background below code would cause a crash, as per the stack trace I understand that the activity window is not available when in background, is there a way that I know if it's valid or not before to call below method thus avoid the crash?

`Acr.UserDialogs.UserDialogs.Instance.ConfirmAsync(new Acr.UserDialogs.ConfirmConfig() { Title = "eDocine", Message = message, OkText = "OK", CancelText = "Cancel" })`

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [Y] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
Android 6.0

## Version of ACR UserDialogs Library
5.3.0

## Expected Behaviour
I expect the lib can detect if activity is available to show the dialog or not thus avoid the crash

## Actual Behavior

11-14 19:13:58.185 I/MonoDroid( 9713): UNHANDLED EXCEPTION:
11-14 19:13:58.186 I/MonoDroid( 9713): Java.Lang.RuntimeException: Unable to add window -- token android.os.BinderProxy@8e73913 is not valid; is your activity running?
11-14 19:13:58.187 I/MonoDroid( 9713):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <1a0c54f94a964b6dbc38405420e2b659>:0 
11-14 19:13:58.187 I/MonoDroid( 9713):   at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00084] in <8d01f8f047f64c73a12ce66ed815a1b8>:0 
11-14 19:13:58.187 I/MonoDroid( 9713):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002f] in <8d01f8f047f64c73a12ce66ed815a1b8>:0 
11-14 19:13:58.187 I/MonoDroid( 9713):   at Android.App.Dialog.Show () [0x0000a] in <646a21f7ba6e403c97121288c71b9bd9>:0 
11-14 19:13:58.187 I/MonoDroid( 9713):   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in <646a21f7ba6e403c97121288c71b9bd9>:0 
11-14 19:13:58.187 I/MonoDroid( 9713):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <646a21f7ba6e403c97121288c71b9bd9>:0 
11-14 19:13:58.187 I/MonoDroid( 9713):   at (wrapper dynamic-method) System.Object:f0b00a01-d9e6-44e3-8687-aba040a71009 (intptr,intptr)
11-14 19:13:58.187 I/MonoDroid( 9713):   --- End of managed Java.Lang.RuntimeException stack trace ---

**Comment by aritchie** [comment]
This library does not provide a way of detecting backgrounding.  You can wrap the call in a try/catch or use something like Acr.DeviceInfo to detect if you are in the background
