### ISSUE TITLE
Calling HideLoading() during page navigations, against *OnDisappearing()* of "previous" page, is not hiding loading indicator in "perfect moment"/hiding too fast in Android, if page, that we are navigating to, is complex.

### ISSUE THREAD

**Issue by Szymaniuk** [aritchie/userdialogs#292]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [*] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue

Android 5.1 as well as 7.0 (seems to be each Android release).
Xamarin.Forms newest release - 2.3.2.127. Android SDK newest - up to Android 7.0.

Tested on three Android devices, from different manufactures.

## Version of ACR UserDialogs Library

6.3.1.
Issue occured in past also in previous ACR UserDialogs release versions.

## Expected Behaviour

Invoking *HideLoading()* from *ContentPage* -> *OnDisappearing()* method should cause (in case of *Page1* -> *Page2* navigation) hiding loading indicator, right after *Page2* will appear (*Page2* -> *OnAppearing()*), and *Page1* will dissapear  (*Page2* -> *OnDisappearing()*).
Debugged, that *Page2* -> *OnDisappearing()* is invoked right after *Page2* -> *OnAppearing()* is invoked.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

Invoking *HideLoading()* in above example, mostly in case of "second" page complex view, cause, that real hiding of loading indicator, is somehow done too fast:
https://dl.dropboxusercontent.com/u/95300926/Page_navigation_loading_issue.mp4
You can observe it between 8-11 seconds.
Of course it's not looking so crappy, but in case of more complex UI, indicator hides aroud 1-2 seconds too fast, which don't looks good :/

On iOS *HideLoading()* works just perfectly! No issue there - indicator is hiding perfectly - there is no missing indicator some around 1-2 seconds at on Android, everything is smooth. Only Android seems to be buggy.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
You really shouldn't use show/hide loading.  You should use the recommended 

using (UserDialogs.Instance.Loading())
// do your asynchronous here

If you wrap your calls this way, it will cleanup better and do it when it should, not in OnDisappearing

Please keep in mind that this is not a window manager.  You are hitting this in cases where android is not ready.  This library cannot help you with that

**Comment by Szymaniuk** [comment]
Actually it gives me exactly the same behaviour:
```
using (Acr.UserDialogs.UserDialogs.Instance.Loading())
{
         await _navigationService.NavigateTo(pageTransition.Page);
}
```

I love this plugin, because of simplicity to use, but it's also a little bit annoying, is that it behaves differently against Android and iOS (I know, it uses different plugins per platform) :/.

**Comment by aritchie** [comment]
First off, I don't want to hear about you being annoyed.  I try hard to service all of the use cases and I'm often asked to play psychic.  I don't need those kind of comments here thank you!

Secondly, the FAQ specifically says not to do a loading around a navigation (point # 3)
