### ISSUE TITLE
How can I manage the OnCancel action in ProgressDialogConfig

### ISSUE THREAD

**Issue by fcogutierrez** [aritchie/userdialogs#293]
Hi guys.

I want to use **ProgressDialogConfig** for a cancelable task.

What I am doing is:

    var dialogConfig = new ProgressDialogConfig
    {
        CancelText = "Cancel",
        IsDeterministic = false,
        Title = "Connecting",
         OnCancel = () =>
        {
            operationCancelled = true;
        }
    };

    using (dialog = _userDialogs.Progress(dialogConfig))
    {
        try
        {
            var transactionInfo = await _apiService.ProcessPayment();
        }
        catch (Exception ex)
        {
            exceptionCaught = ex;
        }
    }

    // More operations....

When I click on **Cancel** the action is executed, but it doesn't continue to the **//More operations**...it waits in background until there is a reply/timeout from the client and then it continues.

How should I use the control? Probably I am not using it correctly. Thanks in advance.

**Comment by aritchie** [comment]
Take a look here: https://github.com/aritchie/userdialogs/blob/master/src/Samples/Samples/ViewModels/ProgressViewModel.cs#L118

Basically, the OnCancel is just the action for the click of the cancel button.  You still need to cancel your inner async stuff.

**Comment by fcogutierrez** [comment]
Thank you @aritchie, I was not using the `CancellationTokenSource`.

It works perfectly :)
