### ISSUE TITLE
.netstandard support (question)

### ISSUE THREAD

**Issue by alexrainman** [aritchie/userdialogs#294]
Are you planning moving to .NET Standard Platform?

**Comment by aritchie** [comment]
Yes.  Waiting for some additional mac side fixes before I do this.

**Comment by alexrainman** [comment]
Great! Thanks.

**Comment by aritchie** [comment]
Done in 6.5

**Comment by LGFox** [comment]
@aritchie, Could this library use lower NETStandard version?
