### ISSUE TITLE
Back Button Cancels ConfirmConfig on Android

### ISSUE THREAD

**Issue by simon-wainy** [aritchie/userdialogs#296]
Clicking 'back' when a ConfirmConfig is displayed dismisses the dialog box and returns false.

For example, using the ConfirmConfig for prompting whether to save or not, a 'back' click would instantly return a false and changes would be lost.

Would it be possible to return that 'back' has been clicked rather than false?

**Comment by aritchie** [comment]
This is something I'm not willing to add as it is android specific.  I will add the ability to block the cancel/back operation in the near future

**Comment by JigarM** [comment]
@aritchie  Do you have any plan to add the ability to block the cancel/back operation?
