### ISSUE TITLE
iOS Dialog.ShowSuccess needs a frame shadow or ability to set color.

### ISSUE THREAD

**Issue by rdaniel0** [aritchie/userdialogs#297]
- [x] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
iOS 10

## Version of ACR UserDialogs Library
ACR 6.3.1

Is there a way to modify the default white box with black text+tick icon?
Currently, the showsuccess dialog doesn't look good when it pops up.
Best outcome would be blurred background (like with most of ios's prompts), with optional frame shadow OR view masking like with your other dialogs/prompts. If I can change the color of the text/tick image that would be a nice addition.

**Comment by dleinius** [comment]
+1

**Comment by dleinius** [comment]
+1

**Comment by aritchie** [comment]
ShowSuccess will be gone.  You can use ShowImage going forward.
