### ISSUE TITLE
On Droid，back activty

### ISSUE THREAD

**Issue by cctvbnm1111** [aritchie/userdialogs#30]
[MonoDroid] at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/1502/7402e0b6/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
[MonoDroid] at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/1502/7402e0b6/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Java.Lang.IRunnable.cs:71
[MonoDroid] at (wrapper dynamic-method) object.1cfac28a-1349-4909-8e09-3af2aa629421 (intptr,intptr) <IL 0x00011, 0x00027>
[MonoDroid]   --- End of managed exception stack trace ---
[MonoDroid] android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@52a0af48 is not valid; is your activity running?
[MonoDroid] 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:532)
[MonoDroid] 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
[MonoDroid] 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
[MonoDroid] 	at android.app.Dialog.show(Dialog.java:286)
[MonoDroid] 	at android.app.AlertDialog$Builder.show(AlertDialog.java:951)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[MonoDroid] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:733)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:136)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:5001)
[MonoDroid] 	at java.lang.reflect.Method.invokeNative(Native Method)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Method.java:515)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
[MonoDroid] 	at dalvik.system.NativeStart.main(Native Method)
[AndroidRuntime] Shutting down VM

**Comment by aritchie** [comment]
All dialogs have setcancellable(false).  I see this issue when a backgrounded activity (or view model) starts calling for dialogs before the activity has resumed

**Comment by aritchie** [comment]
Since no additional info has been reported, this is being closed.  Reopen if you have additional information
