### ISSUE TITLE
Overload of ActionSheetAsync that takes ActionSheetConfig is missing so can not show BottomSheet on Android

### ISSUE THREAD

**Issue by ksachdeva** [aritchie/userdialogs#300]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue

All supported versions

## Version of ACR UserDialogs Library

All versions

## Expected Behaviour

Would like to use the ActionSheetAsync overload that is capable of showing BottomSheet in Android

I have locally wrapped it using TaskCompletionSource but it would be nice to have it provided as part of library for consistency.

**Comment by aritchie** [comment]
I can add a boolean for the bottomsheet.  ActionSheetConfig won't be exposed to the async version though because we're essentially turning the actionsheet into nothing more than a picker with the async version.
