### ISSUE TITLE
Missing method exception in Android although Init is present.

### ISSUE THREAD

**Issue by MrCapuchino** [aritchie/userdialogs#301]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android x
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
7

## Version of ACR UserDialogs Library
6.3.1

## Expected Behaviour
Show loading dialog

## Actual Behavior
Hi Alan,
Thanks for the library I use it in all my projects.
Dialog displays correctly in UWP but not in android. In MainActivity I have 
UserDialogs.Init(() => (Activity)Forms.Context);
The application does not start (I cannot debug in any part of the app, the error comes before)
I tried different linker options, disable fast deploy but behavior is the same but somehow something tells me is either a bug or something very easy to fix but haven't found the solution yet.

12-07 16:44:00.535 E/mono    ( 1913): Unhandled Exception:
12-07 16:44:00.535 E/mono    ( 1913): System.MissingMethodException: Method 'Acr.UserDialogs.UserDialogs.Init' not found.
12-07 16:44:00.535 E/mono-rt ( 1913): [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Acr.UserDialogs.UserDialogs.Init' not found.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Try uninstalling acr.userdialogs from all of your projects and reinstalling.  You could also delete all bin/obj folders before recompiling.  This is likely some compiler bug as I haven't had any issues like this before.

If that still doesn't work, please provide a reproducible sample

**Comment by MrCapuchino** [comment]
Hi,

Reinstalling the libraries fixed it. Thank you. I will close the issue.

Regards
