### ISSUE TITLE
Toast throws System.NullReferenceException on Android

### ISSUE THREAD

**Issue by Brosten** [aritchie/userdialogs#303]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
4.4 and 5.0

## Version of ACR UserDialogs Library
6.3.2

## Expected Behaviour
A Toast

## Actual Behavior
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by aritchie** [comment]
Can you please supply the entire stack trace.

**Comment by Brosten** [comment]
Sorry, my bad!
It turned out that the reference to AndHUD for some reason was missing. It existed in Nuget-references, but under "References" it was missing. Reinstalled AndHUD nuget and it started to work again.
