### ISSUE TITLE
[docs] Screenshots

### ISSUE THREAD

**Issue by jerone** [aritchie/userdialogs#304]
Very interesting project, but I was hoping you could add screenshots for the controls in this package. That saves me and potential other new users the time to download, compile and test all controls on all platforms.

**Comment by davidtavarez** [comment]
+1

**Comment by JeanCollas** [comment]
100% agree. 
Even if it is screenshots for only 1 platform, it would give an idea for each control.

Example: I am looking for a popup with several buttons (list of choices), I have no idea if one of the controls provided can handle that.

**Comment by aritchie** [comment]
ActionSheet is what you need - please don't +1 here.  I will get around to screenshots sometime in the future.

**Comment by JeanCollas** [comment]
I found what I needed. Just that screenshots is the 1st thing I check when I look at a 3rd party library. 
Your work is great, screenshots would show that to the world :)

**Comment by davidtavarez** [comment]
I'll try to submit a PR if that's Ok @aritchie

**Comment by aritchie** [comment]
PRs are always welcome :)

**Comment by dbolak** [comment]
Screenshots ?

**Comment by aritchie** [comment]
The +1 won't matter any longer guys.  Unless someone wants to contribute, don't count on ever seeing this.  This library is a wrapper around the standard dialogs which have a million screenshots via google.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.
