### ISSUE TITLE
Crash on date picker on certain Samsung devices.

### ISSUE THREAD

**Issue by c04x** [aritchie/userdialogs#306]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
5.0
5.1

## Version of ACR UserDialogs Library
Any

## Expected Behaviour
Opening datepicker dialog, tapping current date, getting back returned value.

## Actual Behavior
Opening datepicker dialog, tapping current date, application crashes.

Stack trace: 
java.util.IllegalFormatConversionException: %d can't format java.lang.String arguments
java.util.Formatter.badArgumentType()Formatter.java:1489
java.util.Formatter.transformFromInteger()Formatter.java:1689
java.util.Formatter.transform()Formatter.java:1461
java.util.Formatter.doFormat()Formatter.java:1081
java.util.Formatter.format()Formatter.java:1042
java.util.Formatter.format()Formatter.java:1011
java.lang.String.format()String.java:1803
android.content.res.Resources.getString()Resources.java:643
android.content.Context.getString()Context.java:389

Happens only on certain Samsung devices, on android 5.0 and 5.1 with certain locale.

**Comment by aritchie** [comment]
Please provide the full stack trace.  The current message does not say anything about where user dialogs is involved.

**Comment by c04x** [comment]
Full stack trace [here](http://pastebin.com/nEwX4ik9)

Also submited a "kind of" fix for those devices.

**Comment by aritchie** [comment]
Ok so I'm not going to use the PR.  The IsBrokenSamsungDevice will return true for all samsung devices (you have a double positive statement in there) and it is way too specific of a case.  Perhaps you could let me know the device/model # where you found the issue?

In any case, you should be able to accomplish this with the default style property which I noticed is NOT implemented on the date picker currently.  I will implement this which allow you to input the logic how you see fit.  Example:

// if your android project
if (IsBrokenSamsungDevice)
    DateConfig.DefaultAndroidStyle = <whatever resource ID you want>;

**Comment by aritchie** [comment]
Released a few versions ago
