### ISSUE TITLE
Simple Example of Userdialogs ?

### ISSUE THREAD

**Issue by Bluebeerd** [aritchie/userdialogs#309]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] PCL

## Version of ACR UserDialogs Library
Latest version

Have you got an easy example project that shows how to use your library ?
We are trying to get Toasts to work in Xamarin.Forms on Android and iOS and can't see how they work.

Your project looks great, so a simple example would give your average user a much greater chance of being able to use it

**Comment by Dexyon** [comment]
You mean these:
https://github.com/aritchie/userdialogs/tree/master/src/Samples

Everything is well documented and these were very easy to find..

**Comment by Bluebeerd** [comment]
My apologies, but I still can't see a C# example there.
Could you be more specific please ?

**Comment by Dexyon** [comment]
https://github.com/aritchie/userdialogs/blob/master/src/Samples/Samples/ViewModels/ToastsViewModel.cs

**Comment by aritchie** [comment]
Thanks @Dexyon

**Comment by srikanthj10** [comment]
I am using ACR User Dialog in my Xamarin PCL Application for Popup and Progress Indicators. it works well in IOS but got Exception in Android. For Andorid it needs Supporting Library of ACR Support and Splat. In Android the Instance which is Showing the Exception as follows.

{System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not resolve type with token 01000023 (from typeref, class/assembly Splat.Resource, Splat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null)

Can you anyone help on this?

**Comment by aritchie** [comment]
@srikanthj10 Please post a proper defect using "New Issue" and fill out the template.  Please note that as of v7, splat is no longer required.  As of v6.5.1 (the lowest version I'll help with) was .NET Standard based, not PCL
