### ISSUE TITLE
Alert under Loading

### ISSUE THREAD

**Issue by Guytoune** [aritchie/userdialogs#31]
On iPhone 5 / iOS 8, an AlertAsync launched after a ShowLoading is displayed under the loading panel and therefore not accessible.

**Comment by aritchie** [comment]
There isn't much I can do or would be willing to do for something like this.  The only thing I can suggest is to leave a pause after the alert is dismissed.

**Comment by Guytoune** [comment]
Isn't there a way to always display the alerts on top of the loading panel ?
![0](https://cloud.githubusercontent.com/assets/1745480/7943615/dc8ce696-0965-11e5-9025-989f77c741dc.png)

**Comment by aritchie** [comment]
No.  You have to dismiss either the loading or the alert

**Comment by Guytoune** [comment]
Ok. I'm just gonna hide the loading and show it again after the alert is closed.
