### ISSUE TITLE
AlertAppCompatDialogFragment runs the wrong builder method

### ISSUE THREAD

**Issue by bentmar** [aritchie/userdialogs#310]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
5.1

## Version of ACR UserDialogs Library
6.3.3

## Expected Behaviour
 public class AlertAppCompatDialogFragment : AbstractAppCompatDialogFragment<AlertConfig>
....
....
 protected override Dialog CreateDialog(AlertConfig config)
        {
            return new AlertBuilder().Build(this.Activity, config); <------
        }

this method doesnt build the dialog using the AppCompatApcitivty method, im guessing this is due to some compiler magic. However casting like this solves the problem. 
" return new AlertBuilder().Build((AppCompatActivity)this.Activity, config);"
Since this will allway be a AppCompatActivity I dont see any problem with this cast. And the code does what it is expected to do.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
it runs the build method for Android.App.Activity

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by bentmar** [comment]
I found this issue when i was trying to figure out why my dialog wasnt themed (I passed a theme resource). 
Why dont you include the resource in AlertBuilder.Builder()? its only included in AppCompatAlertDialog.Builder().

**Comment by aritchie** [comment]
fixed in https://github.com/aritchie/userdialogs/commit/77156d90b7da5022e19e0ba250d31bfec58f96cf (referenced wrong defect)
