### ISSUE TITLE
Progressbar inside a Task crashes on UWP project. Android works fine

### ISSUE THREAD

**Issue by marcelojaf** [aritchie/userdialogs#311]
Hi Allan, here's one issue that I got in UWP project.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [X] UWP
 - [X] PCL

## Version of ACR UserDialogs Library
6.3.3

## Expected Behaviour
Progress bar

## Actual Behavior
On Android, runs perfectly. I did not tested for iOS. But for UWP, the app crashes when try to execute the following line:

`using (var dlg = UserDialogs.Instance.Progress("Downloading Inventory..."))`

I believe the problem is because this method is inside a task. I created a new project and this code generates the same error. I need to run inside a task to update the ProgressBar Title because I'm doing a bulk insert on database. Once again, for Android works fine:

`private async void btnProgress_Clicked(object sender, EventArgs e)
        {
            await Task.Run(() => synchronize());
        }

        private async Task synchronize()
        {
            using (var dlg = UserDialogs.Instance.Progress("Downloading..."))
            {
                dlg.PercentComplete = 0;
                while (dlg.PercentComplete < 100)
                {
                    await Task.Delay(TimeSpan.FromMilliseconds(500));
                    dlg.PercentComplete++;
                    dlg.Title = "Downloading " + dlg.PercentComplete + " of 100";

                }
            }
        }`

Error message:
"The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))"

Stacktrace:
"   at Windows.UI.Xaml.Controls.ContentDialog..ctor()\r\n   at Acr.UserDialogs.ProgressDialog..ctor(ProgressDialogConfig config)\r\n   at Acr.UserDialogs.UserDialogsImpl.CreateDialogInstance(ProgressDialogConfig config)\r\n   at Acr.UserDialogs.AbstractUserDialogs.Progress(ProgressDialogConfig config)\r\n   at Acr.UserDialogs.AbstractUserDialogs.Progress(String title, Action onCancel, String cancelText, Boolean show, Nullable`1 maskType)\r\n   at TracRite.Optimum.Mobile.Invent.UI.Views.InventoryListPage.<syncronizeDataBaseBulk>d__20.MoveNext()"

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
You need to include the exception with the stack trace if you want me to have any hope of figuring out what the actual issue is

**Comment by marcelojaf** [comment]
Sure... sorry about that... =P

**Comment by EricB84** [comment]
Hi
There is the same problem with ShowLoading :
The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))

Could you tell us when the V7.0 will be release ?

Thanks

**Comment by aritchie** [comment]
You can get around this by managing the return to the main thread yourself.  ShowLoading uses the exact same code as Loading.  An easy workaround is to wrap your call for ShowLoading in a dispatcher call yourself.

As for v7, I don't give timelines.  It is done when it is done.

**Comment by EricB84** [comment]
OK
thanks for your work aritchie, i was just wondering if i need to workaround or if the v7 is near of arrival.

I will try your workaround.

thanks again.
