### ISSUE TITLE
Splat 2.0

### ISSUE THREAD

**Issue by jjsan** [aritchie/userdialogs#312]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [X] Android
 - [X] UWP
 - [X] PCL

## Version of OS(s) listed above with issue

all

## Version of ACR UserDialogs Library

6.3.4

## Expected Behaviour

works with Splat 2.0

## Actual Behavior
I can't update Splat to 2.0 (currently running on 1.6.2)

**Comment by aritchie** [comment]
Please read the code of conduct (that seems to have been removed from your filing)
