### ISSUE TITLE
No icon on iOS

### ISSUE THREAD

**Issue by jjsan** [aritchie/userdialogs#313]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue

iOS 10

## Version of ACR UserDialogs Library

6.3.4

## Expected Behaviour

confirmation dialog will show also picture (on android id does)

## Actual Behavior

only text is shown

**Comment by aritchie** [comment]
I have no idea what the defect is that your are trying to describe.  Please share some code with what you are trying to do.

**Comment by jjsan** [comment]
sorry my bad

UserDialogs.Instance.ShowSuccess(LocalizationResources.BTFound, 1000);

on Android I can see a green success sign. But not on iOS

thanks

**Comment by aritchie** [comment]
This was something Xamarin did months ago with loading images up in external packages.  If you copy the images from Acr.Userdialogs.iOS library into your iOS app resources, it will work.

You should use ShowImage instead as ShowError & ShowSuccess are going away in v7

**Comment by BenDevelopment** [comment]
Can you share a example explaining how to use ShowImage for success or error in a cross plateform way?

**Comment by aritchie** [comment]
Please take a look at the documentation for the "splat" library for how to load an image since that is the argument ShowImage takes.

**Comment by lhughey** [comment]
@aritchie could you tell me where i could get the resources you referred to in your response on Jan11?  The resources are no longer included with the ios project.  Thanks!
