### ISSUE TITLE
Change the dialog size

### ISSUE THREAD

**Issue by marcelojaf** [aritchie/userdialogs#314]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] PCL

## Version of ACR UserDialogs Library
6.3.3

## Expected Behaviour
The dialog with a fixed size.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
I need to download some grouped items. My dialog is showing like this:

==================
               SPINNER
           Getting Items...
               3 of 1388
==================

========================
                      SPINNER
    Getting Inventory Group Items...
                     100 of 970
========================

I have a lot of different groups and the dialog keeps dancing on the screen. My client complained to me about this.
My question is: it is possible to fix the dialog size? I tried to insert blank space at the beginning and at the end of title but seems the dialog trims the string.

Thank you very much.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This isn't something I would plan to do.  The progress dialog simply wasn't meant to be a huge control and it truncates intentionally to prevent this.  You are welcome to submit a PR if you would like to see this implemented in some fashion.
