### ISSUE TITLE
DefaultAndroidStyleId not used for ConfirmConfig

### ISSUE THREAD

**Issue by LeRondPoint** [aritchie/userdialogs#315]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] PCL

Anything else left to say?

**Comment by LeRondPoint** [comment]
Didn't mean to offend you...  I didn't have time for a PR...  Sorry for reporting the bug...

**Comment by aritchie** [comment]
fixed in 6.3.5

https://github.com/aritchie/userdialogs/commit/09936678279ef72e75db36a8d3114851d8829064
