### ISSUE TITLE
System.InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by tbalcom** [aritchie/userdialogs#316]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue

6.0.1

## Version of ACR UserDialogs Library

Affects 6.3.5, 6.3.4. The problem goes away after reverting to 6.3.3 (and earlier).

## Expected Behaviour

The prompt dialog should appear as it has with 6.3.3 and earlier.

## Actual Behavior

An InvalidCastException is thrown when the dialog is triggered.  The code to trigger the dialog is as follows:

                var startingOdometer = await UserDialogs.PromptAsync(new PromptConfig()
                    .SetTitle("Starting Odometer")
                    .SetMessage("Input the 6 digit starting odometer.")
                    .SetInputMode(InputType.Number)
                    .SetMaxLength(6)
                    .SetOnTextChanged(args =>
                    {
                        args.IsValid = args.Value?.Length == 6;
                    }));

Here is the exception:

01-13 14:29:19.896 I/MonoDroid(14415): UNHANDLED EXCEPTION:
01-13 14:29:19.904 I/MonoDroid(14415): System.InvalidCastException: Specified cast is not valid.
01-13 14:29:19.905 I/MonoDroid(14415):   at Acr.UserDialogs.Builders.PromptBuilder+<>c__DisplayClass2_0.<HookTextChanged>b__0 (System.Object sender, System.EventArgs args) [0x00011] in C:\dev\acr\userdialogs\src\Acr.UserDialogs.Android\Builders\PromptBuilder.cs:97 
01-13 14:29:19.905 I/MonoDroid(14415):   at Android.Content.IDialogInterfaceOnShowListenerImplementor.OnShow (Android.Content.IDialogInterface dialog) [0x0000d] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Content.IDialogInterface.cs:782 
01-13 14:29:19.905 I/MonoDroid(14415):   at Android.Content.IDialogInterfaceOnShowListenerInvoker.n_OnShow_Landroid_content_DialogInterface_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_dialog) [0x00011] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Content.IDialogInterface.cs:747 
01-13 14:29:19.905 I/MonoDroid(14415):   at (wrapper dynamic-method) System.Object:38dec8fe-7c8f-40af-997e-1759eabc62e4 (intptr,intptr,intptr)
01-13 14:29:19.913 D/Mono    (14415): Assembly Ref addref HockeySDK.AndroidBindings[0x7f85315e00] -> System[0x7f6ff1ae80]: 20

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by Dids** [comment]
@aritchie Is there an ETA on when the fix gets pushed to Nuget? It's still on 6.3.5.
