### ISSUE TITLE
Xamarin.iOS Dialog doesn't appear when you change RootViewController

### ISSUE THREAD

**Issue by rcappello** [aritchie/userdialogs#318]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
iOS 10.2

## Version of ACR UserDialogs Library
6.3.6

## Expected Behaviour
If we change RootViewController, ShowLoading Methods should continue to work.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

before:

UserDialogs.Instance.ShowLoading(AppResources.Zones_Loading);
...do something
UserDialogs.Instance.HideLoading();

All is ok. 
After I change the RootViewController:

UIApplication.SharedApplication.Windows[0].RootViewController = controller;
UIApplication.SharedApplication.Windows[0].MakeKeyAndVisible();

UserDialogs.Instance.ShowLoading(AppResources.Zones_Loading);
...do something
UserDialogs.Instance.HideLoading();

The Loading dialog is not shown.

**Comment by aritchie** [comment]
Try using the KeyWindow property instead.  I've never actually reset the root view controller this way.

Behind the scenes, I'm using this core logic to determine the "display" controller:
[https://github.com/aritchie/support/blob/master/Acr.Support.iOS/Extensions.cs](https://github.com/aritchie/support/blob/master/Acr.Support.iOS/Extensions.cs)

You can call UserDialogs.Init(() => your top view controller resolving logic)  <= optional call on iOS to change this logic.

**Comment by aritchie** [comment]
No feedback or

**Comment by harshdeeps878** [comment]
just for ios, you can use  **~~ Device.BeginInvokeOnMainThread(new Action(FunctionName));~~** for loading data on UI thread without getting any exception.. I just tried that and it worked. And for using the dialogs, just change Device.BeginInvokeOnMainThread(**~~UserDialogs.Instance.ShowLoading()~~**) like this and change inside of function accordingly
