### ISSUE TITLE
PROBLEM NUGET VISUAL STUDIO XAMARIN.FORMS

### ISSUE THREAD

**Issue by 86simonepenna** [aritchie/userdialogs#319]
Hello,

I have a visual studio project (Xamarin.Forms + PRISM)

PCL Have this configuration (standard configuration when i add new project Xamarin.form(portable)):
- TargetFrameworkVersion : v4.5
- TargetFrameworkProfile: Profile259

When I add the package ACR.UserDialog  #(6.3.6) from nuget, the system print one error:

**Could not install package 'Splat 1.6.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author**

Any Solution?

**Comment by aritchie** [comment]
The PCL profile this library supports is 259.  I believe the profile the default forms project sets up is 111.  Change your profile accordingly.

**Comment by 86simonepenna** [comment]
It needs to correct the readme file.

Thank you very mutch

![image](https://cloud.githubusercontent.com/assets/18145780/22105306/a20af63e-de43-11e6-9186-9c1b12387472.png)

**Comment by 86simonepenna** [comment]
My Profile is 259

**Comment by aritchie** [comment]
I don't know what to tell you then.  I have this installed in a ton of PCL projects right now that are 259 which also includes splat.

**Comment by 86simonepenna** [comment]
Have you these framwork?

![image](https://cloud.githubusercontent.com/assets/18145780/22107237/04c5262e-de4d-11e6-8760-d68aba0eadb8.png)

**Comment by aritchie** [comment]
I'm not sure why you're asking me this... but yes.  The issue you are having won't have anything to do with what you're showing me.  If you want, you can send me your project and I'll take a look.  I installed 6.3.6 into a fresh project this morning without issue.  There is either something with your VS/nuget package manager or your project.

**Comment by 86simonepenna** [comment]
it's all OK. It was a caching problem NuGet :-(
