### ISSUE TITLE
PromptConfig.SetMaxLength seems to be ignored

### ISSUE THREAD

**Issue by tbalcom** [aritchie/userdialogs#320]
## Please check all of the platforms you are having the issue on

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
6.1

## Version of ACR UserDialogs Library
6.3.6

## Expected Behaviour
If I call `PromptConfig.SetMaxLength(6)` then the user should only be allowed to input up to 6 characters into the prompt dialog.  The prompt dialog is currently allowing me to input many more than 6 characters. This has worked correctly in previous versions of this library. I'm using AppCompat activities.

## Actual Behavior
Showing a prompt dialog like this allows the user to bypass `PromptConfig.MaxLength` and input more than 6 digits:

    var startingOdometer = await UserDialogs.PromptAsync(new PromptConfig()
                    .SetTitle("Starting Odometer")
                    .SetMessage("Input the 6 digit starting odometer.")
                    .SetInputMode(InputType.Number)
                    .SetMaxLength(6)
                    .SetOnTextChanged(args =>
                    {
                        args.IsValid = args.Value?.Length == 6;
                    }));

**Comment by aritchie** [comment]
You already filed this defect and I told you that it wasn't fixable.  The number input type doesn't work well with maxlength.

https://github.com/aritchie/userdialogs/issues/278

**Comment by tbalcom** [comment]
Are you sure this is caused by using `InputType.Number`? MaxLength isn't working for **any** `InputType` I pass in to `PromptAsync`.

Is this validation function you mentioned in #278 currently in the library?

**Comment by aritchie** [comment]
Yes - you're using it with SetOnTextChanged.  You can also change the text there (as a maxlength workaround).

**Comment by aritchie** [comment]
If you skip the input type altogether does maxlength work for you?

**Comment by tbalcom** [comment]
I've simplified the call as much as possible but MaxLength is still not enforced:

    var startingOdometer = await UserDialogs.PromptAsync(new PromptConfig()
		            .SetTitle("Starting Odometer")
		            .SetMessage("Input the 6 digit starting odometer.")
		            .SetMaxLength(6));

**Comment by aritchie** [comment]
I found it.  Fix will be out today in 6.3.7.

**Comment by aritchie** [comment]
6.3.7 on nuget.  Give that a try and let me know.  Thanks

**Comment by tbalcom** [comment]
It's working great now. Thank you.
