### ISSUE TITLE
OnTextChanged raised with empty args.Value

### ISSUE THREAD

**Issue by mjeronimoa** [aritchie/userdialogs#321]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
iOS 10.2 and Android 6.0

## Version of ACR UserDialogs Library
6.3.7

## Actual Behavior
Launching a PromptDialog raise a OnTextChanged 
 event with an empty args.Value even if Text property has been set, causing the disabling of the ok button if the empty string desn't fit the OnTextChanged validation

## Expected Behaviour
OnTextChanged event is raised with the value set in the Text proerty.

## Sample code

```
var saveDialog = new PromptConfig
            {
                Title = "Save",
                Message = "Enter filename",
                Text = "MyConfigName",
                OnTextChanged = args => args.IsValid = IsValidFileName(args.Value),
                OkText = "Save"
            };

            var result = await UserDialogs.Instance.PromptAsync(saveDialog);

private bool IsValidFileName(string filename)
        {
            bool result = true;

            if (String.IsNullOrWhiteSpace(filename))
            {
                result = false;
            }
            else if (filename.IndexOfAny(Path.GetInvalidFileNameChars()) != -1)
            {
                result = false;
            }
            return result;
        }
```

If you need any more information, please let me know

**Comment by aritchie** [comment]
This is actually by design.  I fire it to see if you want to disable the ok button from the start

**Comment by mjeronimoa** [comment]
Thanks for your quick response.
But shouldn't it be fired with the current value in the "Text" property instead of an empty string?
In my opinion if it is supposed  to be like that, it makes more sense that also another event is raised with the default value set in the property.
