### ISSUE TITLE
PCL - ConfirmConfig - Set Custom Font to Message

### ISSUE THREAD

**Issue by swathi1111** [aritchie/userdialogs#322]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [*] PCL

## Version of ACR UserDialogs Library

6.3.5

## Expected Behaviour

While using ConfirmConfig with PCL ViewModel, How can set Custom Font.

Here is the code sample, I am using in my ViewModel, on a button click:

return new MvxCommand(async
                    () =>
                    {
                        ConfirmConfig cc = new ConfirmConfig();
                        cc.UseYesNo();
                        cc.Message = "Are you sure, you want to sign out?";
                    });

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

Not found a way to get the style applied in ViewModel

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
You can't.  If you're on android, you can look into setting it through styles if you're using appcompat.

I have been investigating ways to do this in future versions, but iOS does not like you changing its UIAlertController
