### ISSUE TITLE
.AlertAsync shows behind .Loading on iOS

### ISSUE THREAD

**Issue by leo-mck** [aritchie/userdialogs#323]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
10.2

## Version of ACR UserDialogs Library
6.3.7

## Expected Behaviour
.AlertAsync show on top of .Loading

## Actual Behavior
Maybe this is a iOS thing but since this works on android maybe there is some way to change this behavior.

This code:
```
 using (Acr.UserDialogs.UserDialogs.Instance.Loading("Test"))
 {
       await Acr.UserDialogs.UserDialogs.Instance.AlertAsync("Message", "Title");
 }
```
works fine on android but on iOS, the alert appear behind the loading overlay. If I do not wait for it it works but my use case is a little more complex. Is there something I can do other than replace .Loading with .ShowLoading/.HideLoading or manually hiding/disposing it?

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This is definitely not a bug.  You should only ever have one active dialog at any given time.  User dialogs won't function as a window manager either which means you should structure your code accordingly.

This is how I would handle something like this:

```csharp
try
{
    MyObject result = null; 
    using (UserDialogs.Instance.Loading()) 
    {
        result = await task;
    }
    UserDialogs.Instance.Alert(result.MyProperty);
}
catch (Exception ex)
{
    UserDialogs.Instance.Alert("Error");
}
```
