### ISSUE TITLE
OnBackButtonPressed event invalidated by Toast.

### ISSUE THREAD

**Issue by jcruizsebastian** [aritchie/userdialogs#326]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
4.4 or later

## Version of ACR UserDialogs Library
6.3.7

## Expected Behaviour
OnBackButton must be triggered when pressing the back button while a toast is showing.

## Actual Behavior
While toast is visible, OnBackButtonPressed isn't raising.

        async void OnShowToastClicked(object sender, EventArgs e)
        {
            Acr.UserDialogs.UserDialogs.Instance.Toast("Showing toast!");
        }        

        protected override bool OnBackButtonPressed()
        {
            base.OnBackButtonPressed();
            return false;
        }

**Comment by aritchie** [comment]
I'm using a standard snackbar on appcompat.  There's nothing specific I'm doing to block the back button.

**Comment by aritchie** [comment]
Please send a demo project with the issue or take a look at the code to see what you think may be blocking the back button.

**Comment by jcruizsebastian** [comment]
In the attached example you can see previously commented behaviour.

[Xamarin.Forms.zip](https://github.com/aritchie/userdialogs/files/736875/Xamarin.Forms.zip)

Thanks you.

**Comment by aritchie** [comment]
The scenario appears to work fine in native.  I suggest you contact the Xamarin forms guys.  I'm not doing anything to block back
