### ISSUE TITLE
Please add custom dialog where we can include our own xaml

### ISSUE THREAD

**Issue by abdu292** [aritchie/userdialogs#327]
It will be great to have a dialog that can show XAML in a modal popup page. Adding that to this library will make Acr.UserDialogs a one stop library for all dialog needs on a Xamarin.Forms app.

**Comment by aritchie** [comment]
This functionality already exists in Xamarin forms: https://developer.xamarin.com/guides/xamarin-forms/user-interface/navigation/modal/

Second, the focus of this library was to be completely abstract from Xamarin forms.  Most of my professional apps are native view based

**Comment by abdu292** [comment]
The built in modal doesn't look like a real modal dialog. I meant something like this
https://github.com/rotorgames/Rg.Plugins.Popup

I think for now "Rg.Plugins.Popup" may be the option for this kind of requirements.

Thanks!
