### ISSUE TITLE
Windows 8.1 Support

### ISSUE THREAD

**Issue by wesoos** [aritchie/userdialogs#329]
Is Windows 8.1 supported?  I have been using this in all my other projects, but get an error with Windows 8.1.

Thanks
Wessel

**Comment by aritchie** [comment]
Look at the readme right on the very first page you visit!!!

**Comment by wesoos** [comment]
Well that wasn't very nice Allan.  Was just checking if you have maybe added it or are experimenting with it.  A lot of these 3rd party controls readme's are outdated...

On Jan 30, 2017 5:40 PM, Allan Ritchie <notifications@github.com> wrote:

Look at the readme right on the very first page you visit!!!

**Comment by aritchie** [comment]
If you can't be bothered to read the readme or look at the code then don't waste my time the future.
