### ISSUE TITLE
inputType: InputType.NumericPassword does not work on Windows Phone

### ISSUE THREAD

**Issue by Garpo001** [aritchie/userdialogs#33]
NumericPassword on Windows Phone does not work correctly. See the screenshots on the various platforms with the following code:

```csharp
var pin = await UserDialogs.Instance.PromptAsync("Please enter your pin", title: "Verification", inputType: InputType.NumericPassword);
```

![android](https://cloud.githubusercontent.com/assets/4099702/8206022/165eef18-14f6-11e5-9058-d0e9cbe080a1.png)
![iphone](https://cloud.githubusercontent.com/assets/4099702/8206024/1666ba72-14f6-11e5-8549-5526c98c8db6.png)
![windows phone](https://cloud.githubusercontent.com/assets/4099702/8206023/16646ce0-14f6-11e5-9ea5-7e408ec73625.jpg)

**Comment by aritchie** [comment]
This is resolved in the upcoming 4.1.0

**Comment by Garpo001** [comment]
Upgraded to 4.1.1 and the behaviour on Windows Phone 8/8.1 is sill the same with full keyboard as opposed to numeric keyboard with { inputType: InputType.NumericPassword } as on iOS and Android

**Comment by aritchie** [comment]
Sorry.  I knew I misfiled something.  This actually can't be fixed as the passwordbox doesn't accept an inputscope
