### ISSUE TITLE
I can't get Toasts to work on Android 7.1.1

### ISSUE THREAD

**Issue by WiteCastle** [aritchie/userdialogs#330]
## Platforms

 - Android
- PCL

## Version of OS(s) listed above with issue
7.1.1

## Version of ACR UserDialogs Library
Latest

## Expected Behaviour
A toast message should popup near the bottom of the screen with my set text.

## Actual Behavior
Nothing happens. I don't see anything in the logs. All the other dialogs seem to work as intended (loading, alert, etc.) I just can't get the Toast to work. I used this in an async command:

```
Dialogs.Toast(new ToastConfig("GPS Coordinate Recorded")
         .SetDuration(TimeSpan.FromSeconds(10))
         .SetAction(x => x
         .SetText("Action Text")
         .SetAction(() => Dialogs.Alert("You clicked the primary button"))
         ));
```

**Comment by aritchie** [comment]
Are you using appcompat?  Is this native or xamarin forms app?

**Comment by WiteCastle** [comment]
This is a Xamarin.Forms app and I have Xamarin.Android.Support.v7.AppCompat v24.2.1 installed (dependency of Xamarin.Forms). Is that the AppCompat nuget you're talking about?

**Comment by aritchie** [comment]
What is your main activity inheriting from?  Can you also copy/paste how you are calling Init

**Comment by WiteCastle** [comment]
My main activity inherits from `global::Xamarin.Forms.Platform.Android.FormsApplicationActivity` and I use `UserDialogs.Init(this);`. I see that Forms requires `UserDialogs.Init(() => (Activity)Forms.Context)` now. I'll try this when I get home and update this issue.

**Comment by aritchie** [comment]
thanks for the update.  Just an FYI, you aren't using appcompat because you've inherited from the wrong activity.  Mot a big deal, just let's me know what the function trail is.

Secondly, you should definitely change your Init call to the xamarin forms one OR put the exact Init call you have now in an Application class (android application, not xamforms)

**Comment by WiteCastle** [comment]
Yup, that was indeed the issue. Thanks for the help and for putting me on the AppCompat, my app's design thanks you for it 😄
