### ISSUE TITLE
Icons for actionsheet are not displaying in xamarin ios

### ISSUE THREAD

**Issue by GK1995** [aritchie/userdialogs#331]
## Platforms

 - iOS

## Version of OS(s) listed above with issue
10.0

## Version of ACR UserDialogs Library
Latest Version

## Expected Behaviour
Actionsheet should display icons

## Actual Behavior
Boxes were shown instead of icons. It works fine in android.

**Comment by aritchie** [comment]
It works in a project I have right now.  How are you attaching your images in the actionsheetconfig.  Also, are your images in your iOS resources and have the proper build properties setup on them?

Please... in the future define some sort of context via code sample, source files, or exception.

**Comment by GK1995** [comment]
I downloaded your sample app then run on a device. I properly checked the resource images and it's bundle property. Attached is the screenshot on the action sheet.
![img_0025](https://cloud.githubusercontent.com/assets/25498915/22574914/179fc302-e9ed-11e6-9525-3a3863680498.PNG)

**Comment by aritchie** [comment]
The sample app isn't wired up properly for this right now.  I never bothered to fix it.  Focus on your code here if you want help.

**Comment by GK1995** [comment]
This is my code snippet:

ActionSheetConfig options = new ActionSheetConfig();
                    options.SetTitle("Choose Action");
                    options.SetCancel();

                    options.Add("Add", () =>
                    {
                       showAdd();
                    }, BitmapLoader.Current.LoadFromResource("add.png", null, null).Result);

                    options.Add("Modify", () =>
                    {
                        showModify();
                    }, BitmapLoader.Current.LoadFromResource("modify.png", null, null).Result);

                    options.Add("Delete", () =>
                    {
                        showDelete();
                    }, BitmapLoader.Current.LoadFromResource("delete.png", null, null).Result);

                    dialog.ActionSheet(options);

**Comment by GK1995** [comment]
Can i have your sample code snippet on how you implemented icons for actionsheet in xamarin forms especially in xamarin ios?

**Comment by c04x** [comment]
Judging by your screenshot, I think your images for iOS are wrong. They should be single color (I use white) with transparency.

**Comment by GK1995** [comment]
@c04x The images i used for android and iOS were the same. Android works fine, but when I built it in iOS, blue box were displayed instead of the icon. I tried different icon images, but still the same. I used xamarin form shared.

**Comment by aritchie** [comment]
@GK1995 Your code is loading correctly.  Make sure you image is stored in your iOS platform project as a BundleResource.
