### ISSUE TITLE
Android support latest Xamarin.Android.Support and Splat packages

### ISSUE THREAD

**Issue by steeletechservices** [aritchie/userdialogs#333]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of ACR UserDialogs Library
6.3.7

## Expected Behaviour
Can install userdialogs 

## Actual Behavior
https://api.nuget.org/v3/index.json	-	23.11 sec
Attempting to resolve dependencies for package 'Acr.UserDialogs.6.3.7' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'Splat 2.0.0' is not compatible with 'Acr.UserDialogs 6.3.7 constraint: Splat (>= 1.6.2 && < 2.0.0)'.

I tried to remove the Splat and downgrade it but then end up with conflicts about the version of Xamarin.Android.Support packages

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I don't support splat 2.  You are having a nuget versioning problem which is not something I can really help you with.  My suggestion is to uninstall everything with acr, splat, and support libs to start again.

**Comment by HEBOS** [comment]
Yes, true.
It also says that:
Xamarin.Android.Support.Design 25.1.0' is not compatible with 'Acr.UserDialogs 6.3.7 constraint: Xamarin.Android.Support.Design (>= 23.3.0 && < 25.0.0)'.

**Comment by aritchie** [comment]
Guys - read the code of conduct!!  I don't care about android support library for 25.1 has been in release form for a total of 3 days.  Just chill and wait as I think I'm one of the better community supporters for this stuff.

**Comment by weitzhandler** [comment]
@aritchie 
Hi,
I'm trying to add the NuGet to my project (WUP, Droid, iOS), and here's the error I'm getting:
Unable to find a version of 'Xamarin.Android.Support.v7.RecyclerView' that is compatible with 'Xamarin.Android.Support.Design 23.3.0 constraint: Xamarin.Android.Support.v7.RecyclerView (= 23.3.0)'.	

What do I have to change in my project to be able to install this package? Here's what my NuGet looks like:  
![](https://camo.githubusercontent.com/e315ce83980dba19d090c34112f9b182de7c25f9/687474703a2f2f692e696d6775722e636f6d2f337a4b516658542e706e67)

**Comment by aritchie** [comment]
The latest version only supports 25.3.1.  You'll have to update it.

**Comment by weitzhandler** [comment]
What?

**Comment by weitzhandler** [comment]
@aritchie 
>supports 25.3.1

What?

**Comment by weitzhandler** [comment]
@aritchie 
>supports 25.3.1. You'll have to update it.

Hi and thanks for your response, I didn't understand, what only supports 25.3.1? Update what to what version.
Sorry but I didn't get it, can you please explain?

**Comment by weitzhandler** [comment]
K I got it working by installing dependencies manually then install `UserDialogs` with ignore dependencies flag on.
