### ISSUE TITLE
[UWP] Date and Time dialogs aren't centered

### ISSUE THREAD

**Issue by c04x** [aritchie/userdialogs#334]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [x] UWP
 - [] PCL

## Version of OS(s) listed above with issue
UWP

## Version of ACR UserDialogs Library
6.3

## Expected Behaviour
Opening Date and Time dialog popups displays them on center of page

## Actual Behavior
Opening Date and Time dialog popups displays them in top left corner

Is there a workaround for this, and/or planned fix ?

**Comment by c04x** [comment]
I've tested two different approcahes for this, first one i showing the datepicker in ContentDialog, which will show it in center. Second is setting horizontal and vertical offset on popup creation (I think the sizes of pickers are constant so it shouldn't be a problem), but it can also be set when the popup is loaded (which would require keeping a reference to popup).

I can create a PR with solutions if you want.

**Comment by aritchie** [comment]
Send away.  I will evaluate and post an update if it works out.

**Comment by AbhijeetChowdhury** [comment]
Hi @aritchie ,

Any update on this? The problem still exist on UWP plattform.

**Comment by aritchie** [comment]
@AbhijeetChowdhury the defect would be closed if there was.  Please be respectful of the code of conduct.  If you are waiting for a fix, why not contribute instead?
