### ISSUE TITLE
Disable OK button in prompt dialog if Text lenght is = 0

### ISSUE THREAD

**Issue by alexrainman** [aritchie/userdialogs#34]
Is it possible? I think this could be enhancement ...

**Comment by aritchie** [comment]
It likely is possible with a fair degree effort.  On iOS and Android, I have to go crawling through the views to find the button.  Apple isn't a big fan of you touching their internal views during their approvals either.  This isn't a particular case I want to get into based on those facts alone.

**Comment by alexrainman** [comment]
K, thanks
