### ISSUE TITLE
NullReferenceException with Prism

### ISSUE THREAD

**Issue by saadfarooq** [aritchie/userdialogs#340]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] UWP
 - [x] PCL

## Version of OS(s) listed above with issue
All I've tried

## Version of ACR UserDialogs Library
5.0.0

## Expected Behaviour
Doesn't crash

## Actual Behavior
I get the standard NullReferenceException on Android and a similar crash on iOS when including userdialogs in a Xamarin Forms app with Prism. I realize this is a common problem, but unlike the FAQ, I get this as soon as I put `IUserDialogs` into the constructor of a ViewModel, I don't even have to be referencing it.
I'm pretty sure this has something to do with Prism, but I'm not experienced enough to diagnose. As far as I know, by including it in the constructor Prism should invoke the `DependencyService.Get<IUserDialogs>()` method and provide that instance.
Are you aware of any reason that might not be working?

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
The full exception would be helpful.  I have absolutely no idea what your issue is at the moment.  I also have no idea about what prism does for dependency injection.  Did you register userdialogs on its service locator?

**Comment by saadfarooq** [comment]
Yeah, I suspected it was something with Prism. Was just wondering if you had run into it. The exception is below if it helps, otherwise, I'll do some more research around Prism:

`02-18 20:06:59.302 I/MonoDroid( 5173): UNHANDLED EXCEPTION:
02-18 20:06:59.303 I/MonoDroid( 5173): System.NullReferenceException: Object reference not set to an instance of an object.
02-18 20:06:59.303 I/MonoDroid( 5173):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.LayoutRootPage (Xamarin.Forms.Page page, System.Int32 width, System.Int32 height) [0x0005d] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:279 
02-18 20:06:59.303 I/MonoDroid( 5173):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.Platform.Android.IPlatformLayout.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00003] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:196 
02-18 20:06:59.303 I/MonoDroid( 5173):   at Xamarin.Forms.Platform.Android.PlatformRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x0000e] in C:\BuildAgent2\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\PlatformRenderer.cs:73 
02-18 20:06:59.303 I/MonoDroid( 5173):   at Android.Views.ViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00009] in /Users/builder/data/lanes/4009/c9880f98/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Views.ViewGroup.cs:3427 
02-18 20:06:59.303 I/MonoDroid( 5173):   at (wrapper dynamic-method) System.Object:066ec521-dcc4-4253-abbd-38fbd5c18ad3 (intptr,intptr,bool,int,int,int,int)
02-18 20:06:59.312 W/art     ( 5173): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
02-18 20:06:59.314 D/Mono    ( 5173): DllImport searching in: '__Internal' ('(null)').
02-18 20:06:59.314 D/Mono    ( 5173): Searching for 'java_interop_jnienv_throw'.
02-18 20:06:59.314 D/Mono    ( 5173): Probing 'java_interop_jnienv_throw'.
02-18 20:06:59.314 D/Mono    ( 5173): Found as 'java_interop_jnienv_throw'.
02-18 20:07:00.062 E/mono    ( 5173): 
02-18 20:07:00.062 E/mono    ( 5173): Unhandled Exception:
02-18 20:07:00.062 E/mono    ( 5173): System.NullReferenceException: Object reference not set to an instance of an object.
02-18 20:07:00.062 E/mono-rt ( 5173): [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
referenceTable GDEF length=814 1
`

**Comment by saadfarooq** [comment]
Yeah, so this definitely seems like a Prism issue. I can get `UserDialogs.Instance` to work directly, so the instance registration with Unity is the problem. I'll take it up elsewhere. Feel free to close.

**Comment by saadfarooq** [comment]
I found the solution. Since the library doesn't follow the conventional Xamarin Forms plugin pattern, Prism cannot find it automagically and the dependency instance must be explicitly registered using: `Container.RegisterInstance<IUserDialogs>(UserDialogs.Instance)`

**Comment by elusiven** [comment]
I have the exact same error but with INavigationService.

**Comment by aritchie** [comment]
@elusiven I think you have the wrong repo.  INavigationService has nothing to do with this project.
