### ISSUE TITLE
Android full screen validation

### ISSUE THREAD

**Issue by mjeronimoa** [aritchie/userdialogs#342]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
Android 7.1

## Version of ACR UserDialogs Library
6.3.7

## Actual Behavior
When you are using an Android phone in landscape mode, Android will swap to full screen input UI.
In this case, the validation will not take effect and will be always possible to accept the dialog.
Can be reproduced with the sample app.

## Expected Behaviour
Validation takes effect and disable the accept button.

**Comment by aritchie** [comment]
There was a fix made in 6.3.8 around the accept button.  Can you try the update?  I'll take a look in any case

**Comment by mjeronimoa** [comment]
Test it with the latest version and still happening.
I'm not sure about the possibility of disabling the done button once you are in full screen mode.
Maybe the option is disable this mode with something like:
android:imeOptions="flagNoExtractUi"

**Comment by aritchie** [comment]
It should be fine.  It is likely a state restoration problem.  I'm assuming you are using appcompat?  Also, please share the code that you used just so I can see if there is anything else going on.

**Comment by mjeronimoa** [comment]
You can reproduce the problem with the sample project.
Go to the standard tab/Prompt Text Validate.
Then rotate the device (it has to be a phone, not a tablet).
Full screen input is opened and you can write whatever you want.
Press done and you leave the dialog with Result.Ok == true
