### ISSUE TITLE
Android - state restoration and fragments can lead to a crash

### ISSUE THREAD

**Issue by sledderGIT** [aritchie/userdialogs#343]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
6.0.1
4.4.4

## Version of ACR UserDialogs Library
6.3.7

## Expected Behaviour
After restoring the app from background the Alert dialog should be appeared.

## Actual Behavior
Application crashes

_If applicable, please include entire exception - type, message, stacktrace_

Caused by: android.runtime.JavaProxyThrowable: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
03-01 17:02:50.558 15291 15291 E AndroidRuntime:   at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x00021] in <2f4e091071e147db85c8b531e653aeba>:0 
03-01 17:02:50.558 15291 15291 E AndroidRuntime:   at Acr.UserDialogs.Fragments.ConfigStore.Pop[T] (Android.OS.Bundle bundle) [0x0000d] in <74ea0cacc10942059c2f2e1dc6aab924>:0 
03-01 17:02:50.558 15291 15291 E AndroidRuntime:   at Acr.UserDialogs.Fragments.AbstractAppCompatDialogFragment`1[T].OnCreateDialog (Android.OS.Bundle bundle) [0x00013] in <74ea0cacc10942059c2f2e1dc6aab924>:0 
03-01 17:02:50.558 15291 15291 E AndroidRuntime:   at Android.Support.V4.App.DialogFragment.n_OnCreateDialog_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <27c17fe440cf491ba8255bcefade6e02>:0 
03-01 17:02:50.558 15291 15291 E AndroidRuntime:   at (wrapper dynamic-method) System.Object:1e0553ac-733e-4b5a-aa52-516b1c0d0daf (intptr,intptr,intptr)

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

Steps to reproduce
1) Run the app
2) Call Alert
3) After popup has been appeared minimize the application.
4) Open 10 or more applications
5) Restore the app

**Comment by aritchie** [comment]
Use the contribution guide (the one you deleted before entering your text) if you want help please.

Also, please include any code you are using.

**Comment by sledderGIT** [comment]
I've fixed the description, please review the issue.

**Comment by aritchie** [comment]
You should use the cancellation token within the async method OR dispose of the dialog (sync version) when the app goes to the background.  This will be a good workaround until I get around to fixing this

**Comment by sledderGIT** [comment]
Thank you very much for your reply. I'll try the workaround you suggested.
