### ISSUE TITLE
Show loading message in async operation after loading view

### ISSUE THREAD

**Issue by rodrigojuarez** [aritchie/userdialogs#344]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
Xamarin.iOS   10.4.0.123 (35d1ccd)

## Version of ACR UserDialogs Library
6.3.8

## Expected Behaviour
Show loading UI

## Actual Behavior
Don't show loading UI

```

// this code is in my controller, called from another controller
// when the view loads I need to show the loading message
// while running my async LoadInfo method

// I was trying with the override for ViewDidLoad too, but don't work

        public override async void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            NavigationItem.HidesBackButton = true;

            using (UserDialogs.Instance.Loading("loading"))
            {
                await LoadInfo();
            }
        }




```

**Comment by aritchie** [comment]
The method you need is ViewDidLoad.  I am going to need something more than this (debug logs, how you are "calling this from another controller", what your async task is doing, etc).  I make this exact call all the time without issue.

**Comment by rodrigojuarez** [comment]
You are right, it's working fine
The problem is my LoadInfo method with some async code called synchronously
Sorry and thanks for the prompt reply
