### ISSUE TITLE
ShowSuccess(ShowError) change background color 

### ISSUE THREAD

**Issue by yuyongmao** [aritchie/userdialogs#345]
#### 1.Please check all of the platforms you are having the issue on
 -  iOS

 - Version of ACR UserDialogs Library 6.38

#### 2. Expected Behaviour

I want to change the background color when I show success or error message use the ShowSuccess or ShowError method
And now ShowSuccess and ShowError method just show the message with the white background color and not Success and Error Image

**Comment by aritchie** [comment]
These methods are being deprecated in the next version.  I would suggest using a toast instead
