### ISSUE TITLE
toast error on xamarin.android with mvvmcross

### ISSUE THREAD

**Issue by azraelrabbit** [aritchie/userdialogs#347]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)
 
 - [] Android
 - [] PCL

## Version of OS(s) listed above with issue
 android 4.4.4

## Version of ACR UserDialogs Library
6.3.9

## Expected Behaviour
normal show toast message.

## Actual Behavior
03-13 00:38:40.977 I/MonoDroid( 1983): UNHANDLED EXCEPTION:
03-13 00:38:40.977 I/MonoDroid( 1983): Java.Lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to android.widget.Button
03-13 00:38:40.977 I/MonoDroid( 1983):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
03-13 00:38:40.977 I/MonoDroid( 1983):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a8] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11687 
03-13 00:38:40.977 I/MonoDroid( 1983):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0006b] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:355 
03-13 00:38:40.977 I/MonoDroid( 1983):   at Android.Views.LayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root, System.Boolean attachToRoot) [0x00054] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Views.LayoutInflater.cs:653 
03-13 00:38:40.977 I/MonoDroid( 1983):   at MvvmCross.Binding.Droid.Views.MvxLayoutInflater.Inflate (System.Int32 resource, Android.Views.ViewGroup root, System.Boolean attachToRoot) [0x0003e] in <6a0c851a22864d0993089d65320a630c>:0 
03-13 00:38:40.977 I/MonoDroid( 1983):   at Android.Views.LayoutInflater.n_Inflate_ILandroid_view_ViewGroup_Z (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 resource, System.IntPtr native_root, System.Boolean attachToRoot) [0x00011] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Android.Views.LayoutInflater.cs:638 
03-13 00:38:40.977 I/MonoDroid( 1983):   at (wrapper dynamic-method) System.Object:57b7e7af-738f-488f-811b-a05c253b01a6 (intptr,intptr,int,intptr,bool)
03-13 00:38:40.977 I/MonoDroid( 1983):   --- End of managed Java.Lang.ClassCastException stack trace ---
03-13 00:38:40.977 I/MonoDroid( 1983): java.lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to android.widget.Button
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.support.design.widget.Snackbar$SnackbarLayout.onFinishInflate(Snackbar.java:726)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:763)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at mvvmcross.binding.droid.views.MvxLayoutInflater.n_inflate(Native Method)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at mvvmcross.binding.droid.views.MvxLayoutInflater.inflate(MvxLayoutInflater.java:50)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.support.design.widget.Snackbar.<init>(Snackbar.java:193)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.support.design.widget.Snackbar.make(Snackbar.java:220)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.app.Activity.runOnUiThread(Activity.java:4743)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:30)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.view.View.performClick(View.java:4438)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.view.View$PerformClick.run(View.java:18422)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.os.Handler.handleCallback(Handler.java:733)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.os.Looper.loop(Looper.java:136)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at android.app.ActivityThread.main(ActivityThread.java:5080)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
03-13 00:38:40.977 I/MonoDroid( 1983): 	at dalvik.system.NativeStart.main(Native Method)
03-13 00:38:40.981 D/Mono    ( 1983): DllImport searching in: '__Internal' ('(null)').
03-13 00:38:40.981 D/Mono    ( 1983): Searching for 'java_interop_jnienv_throw'.
03-13 00:38:40.981 D/Mono    ( 1983): Probing 'java_interop_jnienv_throw'.
03-13 00:38:40.981 D/Mono    ( 1983): Found as 'java_interop_jnienv_throw'.
03-13 00:38:41.053 W/dalvikvm( 1983): JNI WARNING: JNI function CallObjectMethodA called with exception pending
03-13 00:38:41.053 W/dalvikvm( 1983):              in Lmvvmcross/binding/droid/views/MvxLayoutInflater;.n_inflate:(ILandroid/view/ViewGroup;Z)Landroid/view/View; (CallObjectMethodA)
03-13 00:38:41.053 W/dalvikvm( 1983): Pending exception is:
03-13 00:38:41.053 I/dalvikvm( 1983): java.lang.ClassCastException: android.support.v7.widget.AppCompatTextView cannot be cast to android.widget.Button
03-13 00:38:41.053 I/dalvikvm( 1983):   (raw stack trace not found)
03-13 00:38:41.053 I/dalvikvm( 1983): "main" prio=5 tid=1 NATIVE
03-13 00:38:41.053 I/dalvikvm( 1983):   | group="main" sCount=0 dsCount=0 obj=0x42af3bd8 self=0x42ae1560
03-13 00:38:41.053 I/dalvikvm( 1983):   | sysTid=1983 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=1073893472
03-13 00:38:41.053 I/dalvikvm( 1983):   | state=R schedstat=( 1672138852 235811531 5964 ) utm=22 stm=144 core=1
03-13 00:38:41.057 I/dalvikvm( 1983):   #00  pc 000bd7c6  /system/lib/libdvm.so (dvmDumpNativeStack(DebugOutputTarget const*, int)+86)
03-13 00:38:41.057 I/dalvikvm( 1983):   #01  pc 000983a3  /system/lib/libdvm.so (dvmDumpThreadEx(DebugOutputTarget const*, Thread*, bool)+1155)
03-13 00:38:41.057 I/dalvikvm( 1983):   #02  pc 00098696  /system/lib/libdvm.so (dvmDumpThread(Thread*, bool)+86)
03-13 00:38:41.057 I/dalvikvm( 1983):   #03  pc 0004d0a7  /system/lib/libdvm.so (ScopedCheck::checkThread(int)+455)
03-13 00:38:41.057 I/dalvikvm( 1983):   #04  pc 0005eaa5  /system/lib/libdvm.so
03-13 00:38:41.057 I/dalvikvm( 1983):   #05  pc 000088f7  /data/app-lib/com.zp.afors.test-1/libmonodroid.so (java_interop_jnienv_call_object_method_a+55)
03-13 00:38:41.057 I/dalvikvm( 1983):   #06  pc 0000f1f3  <unknown>
03-13 00:38:41.057 I/dalvikvm( 1983):   at mvvmcross.binding.droid.views.MvxLayoutInflater.n_inflate(Native Method)
03-13 00:38:41.057 I/dalvikvm( 1983):   at mvvmcross.binding.droid.views.MvxLayoutInflater.inflate(MvxLayoutInflater.java:50)
03-13 00:38:41.057 I/dalvikvm( 1983):   at android.support.design.widget.Snackbar.<init>(Snackbar.java:193)
03-13 00:38:41.057 I/dalvikvm( 1983):   at android.support.design.widget.Snackbar.make(Snackbar.java:220)
In mgmain JNI_OnLoad03-13 00:38:41.057 I/dalvikvm( 1983):   at mono.java.lang.RunnableImplementor.n_run(Native Method)

03-13 00:38:41.057 I/dalvikvm( 1983):   at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
03-13 00:38:41.057 I/dalvikvm( 1983):   at android.app.Activity.runOnUiThread(Activity.java:4743)
03-13 00:38:41.057 I/dalvikvm( 1983):   at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
03-13 00:38:41.057 I/dalvikvm( 1983):   at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:30)
03-13 00:38:41.057 I/dalvikvm( 1983):   at android.view.View.performClick(View.java:4438)
03-13 00:38:41.057 I/dalvikvm( 1983):   at android.view.View$PerformClick.run(View.java:18422)
03-13 00:38:41.057 I/dalvikvm( 1983):   at android.os.Handler.handleCallback(Handler.java:733)
03-13 00:38:41.057 I/dalvikvm( 1983):   at android.os.Handler.dispatchMessage(Handler.java:95)
03-13 00:38:41.057 I/dalvikvm( 1983):   at android.os.Looper.loop(Looper.java:136)
03-13 00:38:41.057 I/dalvikvm( 1983):   at android.app.ActivityThread.main(ActivityThread.java:5080)
03-13 00:38:41.057 I/dalvikvm( 1983):   at java.lang.reflect.Method.invokeNative(Native Method)
03-13 00:38:41.057 I/dalvikvm( 1983):   at java.lang.reflect.Method.invoke(Method.java:515)
03-13 00:38:41.057 I/dalvikvm( 1983):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
03-13 00:38:41.057 I/dalvikvm( 1983):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
03-13 00:38:41.057 I/dalvikvm( 1983):   at dalvik.system.NativeStart.main(Native Method)
03-13 00:38:41.057 I/dalvikvm( 1983): 
03-13 00:38:41.057 E/dalvikvm( 1983): VM aborting
03-13 00:38:41.057 F/libc    ( 1983): Fatal signal 6 (SIGABRT) at 0x000007bf (code=-6), thread 1983 (m.zp.afors.test)

**Comment by aritchie** [comment]
Uninstall/Reinstall all ACR libraries.  

This happens when there is a conflict with xamarin android support libraries.

**Comment by horacehylee** [comment]
I am also having the same issue even after reinstalling all ACR libraries. Please help!!

**Comment by aritchie** [comment]
@horacehylee open a new issue with DETAILS.  Don't just beg for help without giving me something to work with.

**Comment by horacehylee** [comment]
I figured out. I just need to update all Xamarin Vector Drawable plugins. Thanks
