### ISSUE TITLE
UserDialogs crashing on android 4 only

### ISSUE THREAD

**Issue by EmilAlipiev** [aritchie/userdialogs#351]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
Android 4.2 and all android 4 versions

## Version of ACR UserDialogs Library
6.3.10

## Actual Behavior
It crashes **only** on android 4 versions

it is hard to describe how and why is it crashing. thats why i created a test project where you can repo this crash. This small project is working on all android 5 and above versions but crashing on all android 4 versions with an exception

test project: https://1drv.ms/u/s!AgZqrFQ_ee-vjRGTbTLoOLvCW3om

**Steps to reproduce:**
There is only 1 page with a listview and picker. change the picker value and you will see that it crashes on the line 411 in ViewModel.cs where I initialize ShowLoading.
If you remove this line, It works fine.
 That Occurs on Android 4 emulators. I tested on a real device as well and same crash. 

03-22 18:29:27.096 D/Mono    ( 1205): Unloading image System.Linq.dll [0xb9f40f80].
03-22 18:29:27.096 D/Mono    ( 1205): Image addref System.Linq[0xb9f78900] -> System.Linq.dll[0xb8f0dd30]: 7
03-22 18:29:27.096 D/Mono    ( 1205): Config attempting to parse: 'System.Linq.dll.config'.
03-22 18:29:27.096 D/Mono    ( 1205): Config attempting to parse: '/Users/builder/data/lanes/4009/3a62f1ea/source/monodroid/builds/install/mono-x86/etc/mono/assemblies/System.Linq/System.Linq.config'.
03-22 18:29:27.096 D/Mono    ( 1205): Assembly Ref addref [0xb8d12230] -> System.Linq[0xb8f0e740]: 5
03-22 18:29:27.100 D/Mono    ( 1205): Assembly Ref addref Acr.UserDialogs[0xb8cf8670] -> AndHUD[0xb8cee110]: 3
03-22 18:29:27.184 F//system/bin/app_process( 1205): stack corruption detected: aborted

**Comment by aritchie** [comment]
It looks like part of the stack trace is missing.  I really don't have the time to be going through this rather large sample to reproduce the issue.  IF I had to make a guess, you may be calling for the loading too early in the loading cycle.  Your Init() sets the selected gender which fires off your find() method.

**Comment by EmilAlipiev** [comment]
I dont have any urgency as I  already had a workaround. I am not really good into that but the way i implement is quite simple indeed, I have list view and picker filters it and i just wrapped the filter function with loading action. Sample project is super small. If you will have time later, you can take a look. Thanks

**Comment by EmilAlipiev** [comment]
@aritchie I know you closed this ticket for no reason but i figured out that Userdialogs not working on android 4 versions at all. Simpple usage below is even causing it to crash. I believe this is a bug if I am not understanding usage wrong but I think that many people will try what i am doing below.

    ```
   private Database.Model.Item selectedItem;
        public Database.Model.Item SelectedItem
        {
            get
            {

                return selectedItem;
            }
            set
            {
                if (value != null)
                {
                    _userDialogs.ShowLoading(Resx.AppRes.Loading);
                    selectedItem = value;
                    dosomething(value);            

                   _userDialogs.HideLoading();

                }
            }
        }

```

**Comment by aritchie** [comment]
I closed it for very good reason.  I was looking for the entire stack trace and I wasn't going through the huge wad of code you sent me.  Also, I have run the test app on an android 4 emulator without issue. 

If you want help, you have to provide a very basic & small sample OR a full stack trace.
