### ISSUE TITLE
How to Implement custom alert in ACR User Dialog ?

### ISSUE THREAD

**Issue by Mushtaq123** [aritchie/userdialogs#352]
It is very helpful that to show XAML in a modal popup page. I have tried the suggestion provided by you in [issue #327](https://github.com/aritchie/userdialogs/issues/327). But which does not provide the look as like as alert dialogs in Android and iOS. 

Please suggests me, if there is any way to implement the custom alert in xamarin forms.

**Comment by aritchie** [comment]
As I said in your mentioned issue, this library has nothing to do with Xamarin forms.  I diffuser talking to people on forums.xamarin.com
