### ISSUE TITLE
PromptConfig without ViewModels

### ISSUE THREAD

**Issue by shaheed0** [aritchie/userdialogs#353]
Hello I'm developing Xamarin forms with (android and ios)

and I want to use this library without  using ViewModels

I want to use it like this

`
var prompt = new PromptConfig
            {
                Title = "feedback",
            };
dialogs.Prompt(prompt);
`

when I used this code nothing happened

**Comment by aritchie** [comment]
Come on man.... do a little bit of due diligence before filing things like this!  Use the samples project!  You aren't even close to using the library properly.

**Comment by shaheed0** [comment]
when I use it with binding and command it work successfully.

but my question is how to use it within method code?

**Comment by aritchie** [comment]
You can call for a dialog anywhere using this library so long as a view is available (rendered).  

However, if you want help beyond that, you need to send more than a line of code.  Maybe some logs with an issues, some surrounding code, etc.  Next time, please don't delete the contribution guide in the issue template.
