### ISSUE TITLE
Toast Crash

### ISSUE THREAD

**Issue by maxdiable** [aritchie/userdialogs#354]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
Xamarin Forms v4.0.30319

## Version of ACR UserDialogs Library
6.3.10

## Expected Behaviour
i put just:
this.Dialogs.Toast(new ToastConfig("pippo")
                .SetDuration(1000)
            );

and my visual studio debug show:
Java.Lang.ClassCastException: android.widget.RelativeLayout cannot be cast to android.support.design.widget.Snackbar$SnackbarLayout

any Help?

br
Max

**Comment by aritchie** [comment]
Uninstall acr.userdialogs from all your projects and reinstall.
This usually happens when the android support libraries are updated.
