### ISSUE TITLE
Format datepicker in DatePromtConfig

### ISSUE THREAD

**Issue by GuillermoGuevara** [aritchie/userdialogs#355]
Hello!
Is it possible to set the format of the date selector on DatePromtConfig? I need the user to only select a month or a year, is this possible?

**Comment by aritchie** [comment]
It is not currently possible.

**Comment by aritchie** [comment]
You should technically use a picker (or actionsheet) for static data like that anyhow.

**Comment by GuillermoGuevara** [comment]
ok! thanks so much!

**Comment by aritchie** [comment]
I'm going to close this since your use-cases can easily be accomplished otherwise
