### ISSUE TITLE
Date AND Time picker combined?

### ISSUE THREAD

**Issue by sfmskywalker** [aritchie/userdialogs#356]
Although UserDialogs supports a Date and a Time picker, it appears it does not support a DateTime picker combined. In order to leverage iOs' UIDatePicker's `Mode` property to set it to `DateAndTime`, I essentially have subclass `UserDialogsImpl` and provide my own `PromptDateTimeAsync` method.

So my question is, would you be open for a PR where I provide a `PromptDateTime` version?
Or is the issue that other platforms (Android, Windows Phone) don't natively support a datetime picker like iOs does?

**Comment by aritchie** [comment]
I appreciate the offer, but iOS is really the only platform that would serve to benefit from this which means I have to respectfully decline.  If a piece of logic like that only hits one platform, it really defeats cross platform and the purpose of this plugin.  If it was something like a simple style ID or something, it would be different.

**Comment by sfmskywalker** [comment]
Yeah I was afraid that was the reason. Thanks for confirming.
