### ISSUE TITLE
Cancel Action isn't called on Android when dialog is dismissed by tapping outside of it

### ISSUE THREAD

**Issue by chrismcb** [aritchie/userdialogs#357]
Issue happens on Android 4.3 and 7.1.1
Using Acr.UserDialogs 6.3.10
Xamarin.Forms 2.3.2.127

## Expected Behaviour
Tapping outside of a popup to dismiss it should call the Cancel Action

According to a comment in another issue: "use an AppCompatActivity and you won't have the issue or add a Cancel option. The cancel option will be called when the dialog goes away."

## Actual Behavior
Clicking on cancel calls the cancel action. But tapping outside of the popup just dismisses it, and the cancel action is not called

   var cfg = new ActionSheetConfig().SetTitle("title");
   cfg.SetCancel(text: cancel, action: () => CancelAction());
   UserDialogs.Instance.ActionSheet(cfg);

This is in an async Task OnTapGesture in my xaml code behind.
The bug that I am trying to fix on my side is tapping the button multiple times will bring the actionsheet up multiple times in a row (this is very noticeable on my 4.3 phone as it is slow)
The solution is to ignore the second tap if the dialog is shown, or in the process of being shown.
But the call to ActionSheet is async, so it exits quickly. The plan is to set my block to false in the cancel call, except that doesn't happen on dismiss.

The main android action is FormsAppCompatActivity

My current work around is to add a small delay after the call to ActionSheet(cfg) and then set the block to false. This gives the ActionSheet a chance to display. While I don't like adding arbitrary delays, this isn't bad. Worst case scenario is the user brings the dialog up and dismisses it, then has to wait another second to show it again.

On iOs I use await page.DisplayActionSheet, and my code is called when then sheet is dismissed (no matter how it is dismissed)
I use UserDialogs on Android to get the icons. iOS doesn't support the icons, so I just use DisplayActionSheet

**Comment by aritchie** [comment]
Please share some code.  I'm not sure I'm completely following your issue here

**Comment by chrismcb** [comment]
Using the latest nuget package, and the sample. 
Run the sample.
Click on ACTIONSHEET (ASYNC)
Click on Cancel. Notice how a "Cancel" dialog pops up... GOOD.
Again Click on ACTIONSHEET (ASYNC)
This time click off the actionsheet. It disappears, but no "Cancel" dialog pops up.

In fact if you set a breakpoint after the await ActionSheetAsync call, it will never be hit if you dismiss the dialog in this way.

This also happens with the ACTIONSHEET. Clicking on Cancel pops up the dialog that says "cancel selected" while clicking outside the dialog just dismisses the dialog, but doesn't do anything else.
