### ISSUE TITLE
Entry keyboard fires Completed event after ShowLoading/HideLoading

### ISSUE THREAD

**Issue by mrbelk** [aritchie/userdialogs#36]

**Comment by mrbelk** [comment]
I'm trying to use the UserDialogs.ShowLoading and .HideLoading in a form on which I have an Entry.  I have a "Completed" event handler on the Entry. This works fine when the page first displays, but after I've gone through a show/hide cycle of the loading view (I trigger that show/hide via an IsBusy property on my viewmodel), the entry's keyboard will just pop up and go away instantly and the "Completed" event fires even though I have not typed anything new in the Entry.

**Comment by aritchie** [comment]
Test case please.  I have no clue what you are talking about.  Why are you using isbusy to trigger a user dialog from a viewmodel?  The whole point of this library is to get access to all of these things from the viewmodel

**Comment by mrbelk** [comment]
Give me a bit to strip down what I have. I realize that my problem description isn't exactly clear.

**Comment by mrbelk** [comment]
Here you go: https://github.com/mrbelk/UserDialogsTest

**Comment by aritchie** [comment]
I'm sorry... honestly... this is not designed properly at all.  Why are you hooking up to a completed event when it could be wired up directly through the MVVM binding?

This is what the viewmodel should resemble:

    public class MainViewModel : INotifyPropertyChanged
    {
        public MainViewModel ()
        {
            ConnectCommand = new Command(async () => {
                using (Acr.UserDialogs.Loading("Working...")) 
                    await Task.Delay(3000);
            });
        }

        public event PropertyChangedEventHandler PropertyChanged;


        private void OnNotifyPropertyChanged([CallerMemberName] string property="") {
            if (PropertyChanged != null)
                PropertyChanged (this, new PropertyChangedEventArgs (property));
        }


        private string _barcode;
        public string Barcode {
            get { return _barcode; }
            set {
                if (_barcode == value)
                    return;

                _barcode = value;
                OnNotifyPropertyChanged ();
            }
        }

        private string _status;
        public string Status {
            get { return _status; }
            set {
                if (_status == value)
                    return;

                _status = value;
                OnNotifyPropertyChanged ();
            }
        }
    }

**Comment by mrbelk** [comment]
I’m just getting started with Xamarin and figuring out how to port some legacy .NET Compact Framework code, so I don’t profess at all to be any sort of expert; I just noticed this odd behavior that was stumping me.

This little test attempts to perform some of the same tasks that my app will need to perform: establish a connection to a small industrial computer that controls the pump hardware on a fuel truck (that’s exposed via an ASP.NET WebAPI and which uses some Win32 libraries provided by the pump manufacturer) and once that connection is established and the truck is now in “host mode” being controlled by my system, the app can respond to the operator scanning barcodes and then issue more commands to the truck’s web service to open and close the pump solenoid and read the volume of product pumped off the truck.

I used the command in the form that I did (and used the ShowLoading and HideLoading) because in “real life” a message, for lack of a better word (but not a “MessagingCenter” message), is sent to a service (expressed as an infinite loop running inside a Task) that could take an indeterminate amount of time to complete because there are various tests that need to be performed prior to a successful connection. The service fires some events to indicate that this process has completed, and so what I really do is handle those events and then hide the loading message and update the UI to reflect that the operator can now interact with the hardware being connected to.

I realize that the architecture of this “service" probably needs to be rethought to be more async, but this is code that targets the .NET Compact Framework v3.5 and which runs on industrial Windows Mobile devices.

The “completed” event handler on the Entry is because I’m trying to emulate the behavior that might exist when a user scans a barcode, either using your barcodes plugin or calls to a specific barcode scanner API from someone like Honeywell, Motorola, Panasonic, etc. What is the correct way of determining that the entire barcode text has been entered (especially when I have no intention of using a keyboard “wedge” scanner.  I know that I could bind directly to the view model from the view, but I don’t think that’s necessarily right since I have to know when the barcode is completely entered and then ultimately make sure that the barcode is “correct” before interacting with the rest of the application.

Anyway, what I noticed is that once I invoke the “ShowLoading()” and then hide it with “HideLoading()” that the “completed” event handler fires before I have a chance to change the value.

________________________
Matthew Belk
ph. 678-287-3315

From: Allan Ritchie
Reply-To: aritchie/userdialogs
Date: Thursday, June 25, 2015 at 3:41 PM
To: aritchie/userdialogs
Cc: Matthew Belk
Subject: Re: [userdialogs] Entry keyboard fires Completed event after ShowLoading/HideLoading (#36)


I'm sorry... honestly... this is not designed properly at all. Why are you hooking up to a completed event when it could be wired up directly through the MVVM binding?

This is what the viewmodel should resemble:

public class MainViewModel : INotifyPropertyChanged
{
    public MainViewModel ()
    {
        ConnectCommand = new Command(async () => {
            using (Acr.UserDialogs.Loading("Working..."))
                await Task.Delay(3000);
        });
    }

    public event PropertyChangedEventHandler PropertyChanged;


    private void OnNotifyPropertyChanged([CallerMemberName] string property="") {
        if (PropertyChanged != null)
            PropertyChanged (this, new PropertyChangedEventArgs (property));
    }


    private string _barcode;
    public string Barcode {
        get { return _barcode; }
        set {
            if (_barcode == value)
                return;

            _barcode = value;
            OnNotifyPropertyChanged ();
        }
    }

    private string _status;
    public string Status {
        get { return _status; }
        set {
            if (_status == value)
                return;

            _status = value;
            OnNotifyPropertyChanged ();
        }
    }
}

**Comment by aritchie** [comment]
Ok, so from your "completed" event for barcodes, I get...

ScanCommand = new Command(async () => {
    var result = await BarCodes.Instance.ReadAsync();
    if (!result.Success)
        return;

    Barcode = result.BarCode;
    using (UserDialogs.Instance.Loading("Connecting...")) {
         await DoSomeNetworkCall(Barcode);
    }
});


In any case, the way this is done is completely off.  There is no reason the dialogs would cause the event to fire twice.  Take a look at the examples I gave you perhaps
