### ISSUE TITLE
Splat 2.0.0 is not compatible with Acr.UserDialogs 6.3.10

### ISSUE THREAD

**Issue by frode** [aritchie/userdialogs#361]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue

MacOS

## Version of ACR UserDialogs Library

6.3.10

## Expected Behaviour

Upgrade Splat library to 2.0.0

## Actual Behavior

Unable to resolve dependencies. 'Splat 2.0.0' is not compatible with 'Acr.UserDialogs 6.3.10 constraint: Splat (>= 1.6.2 && < 2.0.0)'

**Comment by aritchie** [comment]
What's the first thing it says in the "code of conduct"?  The thing you deleted...!  

I'm not ready to move this library to .NET standard which splat 2.0 is.

**Comment by frode** [comment]
Allright, thanks for pointing out my error! I'll be watching the repo for updates.
