### ISSUE TITLE
Progress Loader is not showing in Android

### ISSUE THREAD

**Issue by guntidheerajkumar** [aritchie/userdialogs#363]
We are using FreshMVVM and I have registered the dependency. 
### FreshIOC.Container.Register(DependencyService.Get<IUserDialogs>());

In Android Main Activity i am using 
### UserDialogs.Init(this); 

It was showing in iOS as expected, but not in android. Please let me know if anything i missed.

I am calling like this in the respective pages
### UserDialogs.Instance.ShowLoading("Loading", MaskType.Black);

**Comment by aritchie** [comment]
Use the template when filing, you have included no exception or any sort of detail I can use to figure out your issue.  FreshMvvm and Xamarin Forms also have nothing to do with this library.

Seeing as though I've answered the likely issue you are facing numerous times, please read the FAQ.  The answer you seek is there.
