### ISSUE TITLE
Keyboard is still visible after Prompt Dialog disappears

### ISSUE THREAD

**Issue by HEBOS** [aritchie/userdialogs#365]
- [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
7.0

## Version of ACR UserDialogs Library
6.3.10

## Expected Behaviour
Prompt Dialog should hide the keyboard after dialog dissapears (both on OK or Cancel result).

## Actual Behavior
Keyboard is still visible after user clicks OK or Cancel button in Prompt Dialog.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I could not reproduce this.  Please provide code with all the feature set you are using.

**Comment by aritchie** [comment]
No response to issue.

**Comment by aritchie** [comment]
@ElteHupkes I really need a reproducible sample and some device details like OS, Android version, etc.  If you are able to supply these, please open a new issue with the full issue template.

**Comment by ElteHupkes** [comment]
@aritchie Yes, I understand. If and when I manage to reproduce this in a way that is useful (so far I haven't - my sample project works just fine) I will do just that. For now I figured I'd just make a mention of the problem being real so other people running into it won't [feel too alone](https://xkcd.com/979/)...
