### ISSUE TITLE
Feature request - Location picker

### ISSUE THREAD

**Issue by galadril** [aritchie/userdialogs#366]
Maybe you could add a location picker to this library.
That's something im looking for right now :)

![screenshot](https://cloud.githubusercontent.com/assets/14561640/25124823/27529d68-242d-11e7-9e65-44a808ad9a58.gif)

**Comment by aritchie** [comment]
I appreciate the request, but this isn't something that will ever fly with this library for a number of reasons
- an external dependency with a bunch of boilerplate setup
- one size of API will never fit all scenarios
- It isn't really a dialog.  This is best done in your apps UI
