### ISSUE TITLE
ToastConfig.DefaultMessageTextColor is not working.

### ISSUE THREAD

**Issue by brittonbeckham** [aritchie/userdialogs#367]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
7.1.2 (only OS tested)

## Version of ACR UserDialogs Library
6.3.10

## Expected Behaviour
Toast message color should match what is set in the `ToastConfig.DefaultMessageTextColor` property.

## Actual Behavior
Instead uses the color defined as the `PrimaryTextColor` of the activity theme. This only started happening in v6.3.10. This was working in previous versions with no problem... only started seeing it with the version mentioned above.

**Comment by aritchie** [comment]
Is your activity at the time you call for the dialog using AppCompat?  
What version of the android support libraries are you using?  (this is actually likely the problem)

**Comment by brittonbeckham** [comment]
Yes to first question, and using the latest 25.1.1 for AppCompat libraries.

**Comment by brittonbeckham** [comment]
Any update on this? Did you need more information than what I have provided?

**Comment by aritchie** [comment]
Please read the code of conduct.  It will be looked at when I have time.  The code is there so you are welcome to debug and submit a PR
