### ISSUE TITLE
LoadFromResource() not respecting width/height adjustments

### ISSUE THREAD

**Issue by aaronwJordan** [aritchie/userdialogs#369]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
7.1

## Version of ACR UserDialogs Library
6.3.10

## Expected Behaviour
ShowImage() displays the resource (in this case, .png) at the width and height specified

## Actual Behavior
ShowImage() displays the image but it is very small. I've tried passing in higher width and height parameters to BitmapLoader.Current.LoadFromResource() but it stays the same size regardless.

Example:
var overlay = BitmapLoader.Current.LoadFromResource("overlay.png", width, height).Result;
Width being my device's width and height being my device's height. I have tried high random values as well but the image stays static in its size.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This is likely an issue to send over to the splat project as I'm just using the image functions from it.
