### ISSUE TITLE
Loading dialog in Xamarin.Forms not shown while executing "using"-block

### ISSUE THREAD

**Issue by jzmmrmnn** [aritchie/userdialogs#371]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [X] PCL

## Version of OS(s) listed above with issue
iOS 10.3 (simulator)
Android API23

## Version of ACR UserDialogs Library
6.3.10

## Expected Behaviour
A loading/saving, ... dialog is shown while executing code block.

## Actual Behavior
Actually, the loading/saving/... dialog is shown for only a short period of time after code block surrounded by "using" has finished execution and not during the whole code block execution.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I'm slightly guessing as to what you're saying here:

using (dialog)
{
} > dialog is still visible for a moment after this

And yes, it will be in some cases because it has to hop on to the main thread to remove it from the view.  There isn't much I can do about this though.

**Comment by jzmmrmnn** [comment]
The problem is that the dialog is not showing DURING the execution of the using-block but after that.

If you are doing something like

using(dialog)
{
// load some stuff from web server via REST 
}

the dialog is not shown while accessing the web server but after web access has been finished. Which means that you are not able to indicate the user that something is still loading even if loading is very slow.

**Comment by aritchie** [comment]
The dialog should show on the following line after the using statement unless something is blocking the main thread which in this case is what it sounds like is happening.

I usually do 
using (dialog)
{
    await Call();
}

**Comment by jzmmrmnn** [comment]
OK, that was the solution. Calls to web accesses are now done in a background task, so dialogs are not blocked anymore. Thanks al lot.
