### ISSUE TITLE
Toast Background color not working

### ISSUE THREAD

**Issue by maxdiable** [aritchie/userdialogs#372]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [
![immagine](https://cloud.githubusercontent.com/assets/211283/25495858/26a8abb0-2b7f-11e7-8f08-8af98353ee51.png)
] iOS
 - [x] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
windows 10

## Version of ACR UserDialogs Library
Acr.UserDialogs.6.3.10

## Expected Behaviour
i set the background color but not working, toast not show color setting:

this is my code:

var toastCfg = new ToastConfig("Test");
toastCfg.BackgroundColor = System.Drawing.Color.White;
toastCfg.MessageTextColor = System.Drawing.Color.Black;
this.dialog.Toast(toastCfg);

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
On Android, it only works if you are using appcompat.  For iOS, it works fine for me.  Please send the code you are using.

**Comment by aritchie** [comment]
Thanks for the updated info, but it doesn't tell me what your activity type is at the time you call for the toast.  It must inherit from AppCompatActivity

**Comment by maxdiable** [comment]
hi,
i send you my code in zip files?
br
Max
[activity.zip](https://github.com/aritchie/userdialogs/files/963658/activity.zip)

**Comment by aritchie** [comment]
Your activity was inheriting from appcompat.  

There does not appear to be a problem with the background color, but there was an issue with the message text color on the latest support libraries.
