### ISSUE TITLE
Support the Xamarin.Forms.Element.AutomationId property for all components

### ISSUE THREAD

**Issue by thisisthekap** [aritchie/userdialogs#374]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [X] Android
 - [] UWP
 - [X] PCL

## Version of OS(s) listed above with issue
iOS 10.3, Android 7.1

## Version of ACR UserDialogs Library
6.3.11

## Expected Behaviour
When creating a new alert, the AlertConfig should contain an AutomationId property, which is then usable to test the application.

## Actual Behavior
The AutomationId property is not included.

**Comment by aritchie** [comment]
This library has nothing to do with xamarin forms.  You can't even set resourceIDs on some of the elements on android anyhow.  I'm not even sure about the other platforms.  You should just run a mocked version of user dialogs to facilitate this
