### ISSUE TITLE
Toast Fails to Appear on Initial Screen on iOS

### ISSUE THREAD

**Issue by adamhill** [aritchie/userdialogs#377]
# IF YOU DO NOT USE THIS TEMPLATE - YOUR ISSUE WILL BE CLOSED.  PLEASE READ THE FAQ AND THE CODE OF CONDUCT BELOW!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
iOS - 10.3.1
Android - 5.1

## Version of ACR UserDialogs Library
6.4.1

## Expected Behaviour

I am using the new Userdialogs 6.4.1 Nuget with the iOS fix for Toast. (Thanks!) It works great in iOS in all places *except* when the app starts up. On the very first screen I try to pop up a Toast with config info. On this one page it does not work. All all other pages in iOS, Toast is working fine.

The only difference I can ascertain is that it is the first page that comes up. I am using a PCL project & it is set as the MainPage in the App.xaml.cs, I am *not* Navigating to it. I am using the latest version of Xamarin.Forms.

On the Android version of the App, same code, the Toast appears on the first screen just fine.

## Actual Behavior

Toast does not appear on initial screen on iOS device / simulator. Does appear on Android device/simulator.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Works fine for me.  Where in your code are you calling for the toast to display?

**Comment by aritchie** [comment]
no response - closing issue
