### ISSUE TITLE
Add snapshots of the dialogs in the three platforms in wiki. 

### ISSUE THREAD

**Issue by iitr-ankur** [aritchie/userdialogs#38]
It will be easier to visualize and decide if any control is of interest. 
Thanks for the good work.

**Comment by catlin0123** [comment]
I would like this as well.

**Comment by aritchie** [comment]
These are standard controls built into the system.  Only the progress dialogs are custom.  You can look at BTProgressHUD and AndHUD.  If you want to see beyond that, clone the samples and take a look.
