### ISSUE TITLE
no documentation on how to show toast 

### ISSUE THREAD

**Issue by Duraiamuthan** [aritchie/userdialogs#381]
I am trying to find a way to show a toast but I am not able to find it

**Comment by Duraiamuthan** [comment]
@aritchie if you don't mind can you share some example on how to show toast ?

**Comment by aritchie** [comment]
I closed this for several reasons
1) you didn't use the template
2) there is a sample app in this repo
3) the API is simple intentionally.  If you use intellisense, you should be able to figure it out
4) The repo and myself, are not support channels.  The source code is all right there.  You can do a little bit of research yourself before asking for help/docs.

If you have a feature request (besides documentation as that is not a feature or issue with the library itself) or an issue, I will be happy to help.
