### ISSUE TITLE
AlertConfig.OnAction Is Set After First Use

### ISSUE THREAD

**Issue by hvaughan3** [aritchie/userdialogs#382]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [x] Android
 - [] UWP //Did not test on UWP
 - [x] PCL

## Version of OS(s) listed above with issue
iOS 8.4 - Used emulator
Android 7.1.0 - Used Genymotion Emulator

## Version of ACR UserDialogs Library
6.3.10

## Expected Behaviour
`AlertConfig.OnAction` should stay null after the first use of it within `AlertAsync()`.

## Actual Behavior
Perhaps we are not meant to reuse the `AlertConfig` object for multiple `AlertAsync()` calls. If that is the case, please let me know and close this one out.

I tried putting an `AlertAsync()` call within a`while` loop to annoy my users as quickly as possible with the fewest lines of code.

Initially I new'ed up an `AlertConfig` each time I called `AlertAsync()`. I decided it would be even quicker if I pulled the `AlertConfig` out of the `while` loop and used it over and over again. 

On the first go around of the `while` loop, the `AlertAsync()` runs fine, but on the second run, something assigns an `Action` to `AlertConfig.OnAction`, which, as expected, produces an `ArgumentException`, when the `while` loop runs a second time, since it is an `async` call.

StackTrace :
[UserDialogStackTrace.txt](https://github.com/aritchie/userdialogs/files/1017175/UserDialogStackTrace.txt)

Code used:

    private static async Task ShowUpdateMessage() {
        AlertConfig config = new AlertConfig {
            Message  = "Are you annoyed?",
            OkText   = "Yes I am annoyed",
            Title    = "QUESTION"
        };

        while(true) {
            await UserDialogs.Instance.AlertAsync(config);
        }
    }

Before first `AlertAsync()` is called:

<img width="679" alt="userdialog_beforefirstcall" src="https://cloud.githubusercontent.com/assets/6466876/26285929/ce492b7c-3e1e-11e7-84b4-d97dcc682ba4.png">

Immediately after first `AlertAsync()` call is returned:

<img width="790" alt="userdialog_afterfirstcall" src="https://cloud.githubusercontent.com/assets/6466876/26285932/d2345734-3e1e-11e7-83dc-3674cee06486.png">

**Comment by aritchie** [comment]
The config objects were not meant to be reused
