### ISSUE TITLE
PromptAsync doesn't work on iPad from modal - Xamarin.Forms

### ISSUE THREAD

**Issue by eclipsed4utoo** [aritchie/userdialogs#383]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue

iOS 9.3
iOS 10.2
iOS 10.3

## Version of ACR UserDialogs Library

6.4.1

## Expected Behaviour

PromptAsync should work on the iPad as it does on the iPhone.

## Actual Behavior

On the iPad, PromptAsync doesn't work. It works fine on the iPhone. This is an a Xamarin.Forms application(running version XF 2.3.4.231), where `PushModalAsync` is used to show the views.

Error:  
`Warning:` Attempt to present <UIAlertController: 0x11fa871f0> on <Plugin_Media_MediaPickerController: 0x11e739c00> whose view is not in the window hierarchy!`

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
The current mechanism for determining the top viewcontroller will not look at modals, nor should it. An alert on top of a modal is not going to be a great end result.  

If you still decide to go this route, you can call UserDialogs.Init along with your own mechanism for providing the top viewcontroller.

**Comment by eclipsed4utoo** [comment]
Just as an FYI, my issue was that I was trying to do PromptAsync immediately after the media chooser to get images. So it seems that the system was trying to show the prompt from the media chooser, which isn't right. I simply wait 1 second, then do PromptAsync and it works fine.
