### ISSUE TITLE
Alert title truncated in Android

### ISSUE THREAD

**Issue by SteveRealrider** [aritchie/userdialogs#384]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [Y] Android
 - [] UWP
 - [Y] NET Standard 1.1

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
The title should not be truncated with an ellipsis. It should show the full title without being truncated.

## Actual Behavior
The title is truncated with an ellipsis, making the title unreadable.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I defer to the native behavior for this one.  It isn't a bug with the library as I don't do anything special with the value.

My suggestion is to override this particular function in the plugin if you don't like the default behavior.
