### ISSUE TITLE
New version requires splat v2.0 

### ISSUE THREAD

**Issue by AlirezaAkbarix** [aritchie/userdialogs#385]
Forcing splat v2.0 in library v6.5.1, makes us unable to update the userdialogs lib, due to other libs are limited to earlier versions of splat ( < 2.0) and sadly their as useful as userdialogs (such as reactiveui).
Can you please set the splat lib to lower version please?

**Comment by aritchie** [comment]
These types of requests are not welcome here as per the code of conduct that you removed.

You can use 6.4.1, but 6.5 has moved ahead as I required a netstandard implementation
