### ISSUE TITLE
Title property has no effect with DatePromptAsync(DatePromptConfig)

### ISSUE THREAD

**Issue by StephenBeirlaen** [aritchie/userdialogs#386]
When using this code:

```
return Mvx.Resolve<IUserDialogs>().DatePromptAsync(
	new DatePromptConfig()
	{
		Title = translator.GetTranslation(titleKey),
		OkText = translator.GetTranslation("button_ok"),
		CancelText = translator.GetTranslation("button_cancel"),
		IsCancellable = true,
		MaximumDate = DateTime.Today
	}
);
```

The correct title isn't being shown. When I use the other constructor, without DatePromptConfig() object, the title is working as expected:

`return Mvx.Resolve<IUserDialogs>().DatePromptAsync("Test");`

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
Android 6.0

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
The title in a DatePrompt should show the correct string that was passed. 

## Actual Behavior
The string representation of the currently selected Date appears (updates as you change the date).

**Comment by kmustang** [comment]
The title is ignored on iOS completely. Looking at the code, there is no view created for it. This will so elegantly solve my problem, can anyone spare a few minutes to fix it? I tried, but I'm afraid I don't understand enough to be helpful.

**Comment by StephenBeirlaen** [comment]
I investigated the differences between the two DatePromptAsync overloads in the source code, and found that the issue happens when I set the MaximumDate. Apparently, by design the Title will be set initially with a string, but after selecting a date it should show the currently selected date, see updateTitle() in https://android.googlesource.com/platform/frameworks/base/+/56a2301/core/java/android/app/DatePickerDialog.java. Setting the MaximumDate also triggers a title update. In Acr, the title is set first, and then the maximumdate. That's why the title is being overriden.

When selecting a date, the latter behaviour happens with both overloads, the title changes to the selected date, as by design by Android (confirm?).

I don't really like this behaviour, since the selected date is already displayed directly below the title. So I wrote pull request #405 (this is my first PR, all feedback is welcome!).

**Comment by cyleleghorn** [comment]
I'm also noticing this issue on iOS 11.0.3 with an iPad.  I was not able to get the title to show up at all, whether using the DatePromptConfig constructor or the basic string constructor.  It doesn't even appear that there is an area for the title to go on iOS, and there is no place that the currently selected date appears as @StephenBeirlaen mentioned there is on Android.  I may have to create a custom dialog or modal page to have the message I want to show up on iOS, not sure.  

The latest 11.4 iOS update is downloading on the iPad, but that probably won't make any difference.  Will report back if it happens to change anything!  Thanks for this plugin, it's awesome!

**Comment by salgiza** [comment]
Just as some extra info, using Acr.UserDialogs 7.1.0.450 I have not been able to show the title (in Android) in any way. Even doing a simple 

            var result = await UserDialogs.Instance.DatePromptAsync(Title);

that should work according to the original ticket, the title is totally ignored (from reading the comments, I guess that today's date is selected by default and that is replacing the title?)
