### ISSUE TITLE
Missing buttons on Android confirm popup

### ISSUE THREAD

**Issue by appbureauet** [aritchie/userdialogs#388]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
7.1.1

## Version of ACR UserDialogs Library
6.5.0

## Expected Behaviour
Confirm dialog should show cancel / ok buttons.

## Actual Behavior
Confirm dialog does not show cancel / ok buttons.

When I try to create a confirm dialog on Android there are no buttons on the popup.
It works fine in the iOS project.
I am using Xamarin.Forms 2.3.4.247

```
UserDialogs.Instance.Confirm(new ConfirmConfig
      {
          Title = "Question?",
          Message = "Are you sure?"
      });
```

This is how it looks on my simulator: ![android](http://i.imgur.com/9c56Nur.png)

**Comment by aritchie** [comment]
It must be something to do with your theme.  I set default text on the ok & cancel.  I also can't reproduce this.  Is your base activity appcompat?  Are you setting any button text in your android theme?

**Comment by mofus** [comment]
Thank you for pointing me in the right direction 👍
It was indeed an embarrassing mistake in my theme.

I hadn't noticed that the accent color was white along with the background.

Sorry for the trouble and thanks for your help!

**Comment by aritchie** [comment]
No worries.  Happy it works

**Comment by JelleDamen** [comment]
@aritchie I'm having this same 'issue' I have a button style configured with White text and colored backgroundHint. This button style works on all my buttons in my activities/fragments, but for some reason the buttons that are showed by the Alert window are only 'respecting' the text color. Any suggestions?

**Comment by aritchie** [comment]
@JelleDamen This library doesn't touch themes or colors of the buttons.  Dialogs play by their own rules with most of the styling stuff.  There isn't much I can help you with here as it is simply ripping apart themes to find the offending value.

**Comment by JelleDamen** [comment]
@aritchie Is there a way to force the text color on the buttons on the alert dialogs? Thanks for your time!
