### ISSUE TITLE
[Android] Prompt textbox needs padding

### ISSUE THREAD

**Issue by veryhumble** [aritchie/userdialogs#389]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
Android 6.0.1 / 8.0

## Version of ACR UserDialogs Library
6.4.1

## Expected Behaviour
EditText should have default AlertDialogs Padding Left and Right

## Actual Behavior
Using a Prompt the EditText seems to have no padding on the left side in the displayed AlertDialog (Screenshot below).

I believe a possible solution would be to set the paddings manually while setting calling the `SetView()` Method on the dialog object [PromptBuilder.cs](https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs.Android/Builders/PromptBuilder.cs#L79). ([Stackoverflow Padding on AlertDialog](https://stackoverflow.com/questions/33074313/getting-default-padding-for-alertdialog))

What I am unsure of is how to handle different Android Versions (also Themes?) . Maybe I am also missing something and this actually works, if so, would be nice to point me in the right direction.

![screen](https://user-images.githubusercontent.com/13156014/27635585-e833a772-5c07-11e7-9f49-805bf064589f.png)

**Comment by vinicioslc** [comment]
Im having this behavior too .-.

**Comment by mattrichnz** [comment]
@aritchie Would you accept a fresh PR for this? We desperately would like this fix.
I'm happy to do the work even!
