### ISSUE TITLE
iOS: How to set autocapitalizationType=sentences to a prompt-dialog?

### ISSUE THREAD

**Issue by SimonSimCity** [aritchie/userdialogs#39]
I currently have tested a bit around, but can't see a way to manipulate the input field in the prompt dialog so that it has the same behavior as a field, where I assigned the setting `autocapitalizationType=sentences` to in Xcode. Is there a way to archive that? If not ... are you planning on adding that feature?

**Comment by aritchie** [comment]
I have no plans to add the feature.  You are welcome to submit a PR if you choose to implement it

**Comment by aritchie** [comment]
This is far too specific to android and not a feature I think I want to support going forward.  You can always override the Prompt method and create a custom IUserDialogs to deal with your usecase
