### ISSUE TITLE
Could not install package 'Splat 2.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author

### ISSUE THREAD

**Issue by asafgo** [aritchie/userdialogs#391]
Hi,

Trying to install  ACR User Dialogs Plugin for Xamarin... 6.5.1 from NuGet results with error:

Could not install package 'Splat 2.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I am using Xamarin PCL project.

Thanks for any help,
AG

**Comment by aritchie** [comment]
Please read the README or use the ISSUE template (you deleted it to file this issue) where it specifically states that everything moved to .NET standard.

Use userdialogs 6.4 for PCL
