### ISSUE TITLE
cancel click event ActionSheetAsync

### ISSUE THREAD

**Issue by sktdeepak** [aritchie/userdialogs#393]
is there any way to find  cancel click event ActionSheetAsync?
`UserDialogs.Instance.ActionSheetAsync("Title","Cancel","Ok",evente())`

**Comment by aritchie** [comment]
Actionsheetasync returns a string with the value.  This is for defects and feature requests only please.  Also, use the issue template in the future if you want a reply

**Comment by sktdeepak** [comment]
ok thanks, i got what i wanted. 

> This is for defects and feature requests only please. Also, use the issue template in the future if you want a reply
--- ok
