### ISSUE TITLE
AndHUD.dll load error

### ISSUE THREAD

**Issue by kartiksolanki** [aritchie/userdialogs#395]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - Android

## Version of ACR UserDialogs Library
6.3.10

## Expected Behaviour
Should create an android build.

## Actual Behavior
Giving error as below:

Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'AndHUD, Version=1.2.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'AndHUD.dll'
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference)
at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver) TimPapp.Droid

I already have AndHUD 1.2.0 package installed in NuGet. 
My iOS build works like a charm but I am facing this error while creating android build. Any idea how can I solve this?

**Comment by aritchie** [comment]
I would try reinstalling as that library shouldn't be missing.  I have it specified within the nuget package.

**Comment by kartiksolanki** [comment]
Trying since morning. I have also cleared cache...cleaned my project, delete bin and obj folders and tried to rebuild but it is still throwing me an error. If I uninstall the Acr.userdialog package then my android project gets build successfully.

**Comment by aritchie** [comment]
Did you try reinstalling it now though?  If so, did that work?

If not
* please verify what version from nuget you are installing.
* what is your android target framework

**Comment by kartiksolanki** [comment]
Yes I have been trying continuously reinstalling and rebuilding again. Still it is showing me the same error. I have cleared nuget cache as well. 

I am installing 6.3.10 version of Acr.UserDialogs
My android target framework is Android 6.0.

**Comment by kartiksolanki** [comment]
![image](https://user-images.githubusercontent.com/19630554/27930281-0bc953a0-6264-11e7-8d46-b01a36214d8a.png)

**Comment by kartiksolanki** [comment]
![image](https://user-images.githubusercontent.com/19630554/27930299-1ab33bec-6264-11e7-8c3b-b6a90dd0d0b4.png)

**Comment by kartiksolanki** [comment]
![image](https://user-images.githubusercontent.com/19630554/27930314-25b5328e-6264-11e7-9fb9-c970f89ff8e2.png)

**Comment by aritchie** [comment]
Check your references in your android project for Acr.Support and AndHub.  It looks like those libraries aren't being included for some reason.

**Comment by aritchie** [comment]
You should also up your target framework to android 7

**Comment by kartiksolanki** [comment]
It is there in references as well.

![image](https://user-images.githubusercontent.com/19630554/27930449-98917006-6264-11e7-9c53-bef3b1e86a4b.png)

**Comment by kartiksolanki** [comment]
But it should work in Android 6 as well. I have another project that uses same acr user dialogs and it is working in that. Strange!!

**Comment by aritchie** [comment]
Acr.Support.Android is not however.  Try creating a manual reference to it from the nuget package directory.

**Comment by kartiksolanki** [comment]
I am sorry but am new to this. Can you please guide me how can I provide manual reference ? Am not able to find Acr. Support.Android in Nuget Package Manager.

**Comment by kartiksolanki** [comment]
I got it. I have added there reference manually by browsing to my package folders. Lets see if I can build my project successfully.

**Comment by kartiksolanki** [comment]
Build Successful. Thanks a lot, Allan. I really appreciate your help. You made my day. Thanks again :)

**Comment by aritchie** [comment]
No problems.  Glad it works
