### ISSUE TITLE
UserDialogs.Instance.Loading changing Title causes a flicker

### ISSUE THREAD

**Issue by CesareSoldani** [aritchie/userdialogs#396]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
API 23

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
It would be nice to be able to change the title text without the control disappearing momentarily.

## Actual Behavior
Changing the Title of an existing Loading dialog causes noticable flicker.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

            using (var loading = UserDialogs.Instance.Loading("Authenticating...", null, null, true, MaskType.Black))
            {
                                await App.DataManager.Login(Username, Password)
                                loading.Title = "Loading Core Data...";
                                await App.DataManager.RefreshCoreData();
                                loading.Title = "Loading Data...";
                                var vm = new InspectionListViewModel();
                                await vm.Refresh();
           }

**Comment by aritchie** [comment]
It is likely due to resizing of the progress dialog from different size text.

However, you are hoping on/off the main thread (no ConfigureAwait(false) on your awaits).  Put ConfigureAwait(false) after each async call.

**Comment by CesareSoldani** [comment]
The most noticeable thing is the shaded background disappears then reappears each time you set the Title.

.ConfigureAwait(false) didn't help unfortunately.

**Comment by aritchie** [comment]
Looks like an issue with AndHud.  Honestly, I just wouldn't do it this way in any case as the dialog will be constantly resizing to fit the text.  Move to an intermediate screen between your login and main screen.
