### ISSUE TITLE
Cannot deploy UAP to appstore using ver 6.5.1

### ISSUE THREAD

**Issue by vertuxx** [aritchie/userdialogs#398]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [x] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
Windows 10 / Windows 10 Mobile

## Version of ACR UserDialogs Library
Acr.UserDialogs 6.5.1, 6.5.0 is Not correct.
Acr.User Dialogs 6.4.1 is OK.
I downgrade it now and use it.

## Expected Behaviour
It is necessary for the package to succeed for the Windows store.

## Actual Behavior
Cannot app packaging for Windows Store.

## Code of Conduct
Build Logs:

3>  Checking assembly 'C:\Repository\svn\AppName\trunk\AppName\obj\ARM\Release\ilc\in\Acr.UserDialogs.dll'. 
3>  Checking assembly 'C:\Repository\svn\AppName\trunk\AppName\obj\ARM\Release\ilc\in\Acr.UserDialogs.Interface.dll'. 
3>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\ARM\ilc\IlcInternals.targets(318,5): error : �n���h������Ă��Ȃ���O: OutOfMemoryException.
3>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\ARM\ilc\IlcInternals.targets(318,5): error : ILT0005: 'C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\ARM\ilc\tools\Gatekeeper.exe @"C:\Repository\svn\AppName\trunk\AppName\obj\ARM\Release\ilc\intermediate\gkargs.rsp"' returned exit code -532462766
3>  タスク "StartProcessTask" の実行が終了しました。 -- 失敗
3>  プロジェクト "Unnamed_1" 内のターゲット "RunGatekeeper" のビルドが終了しました。 -- 失敗
3>  プロジェクト "Unnamed_1" のビルドが終了しました。 -- 失敗
3>  ビルドに失敗しました。 (-> Build Failed.)

I think there is a problem with Acr.UserDialogs.Interface.dll.
thank you.

**Comment by aritchie** [comment]
You really have to give me more than this and stacktraces I can fully read.  This doesn't tell me a thing as to what the problem may be.  

The only difference between 6.4.x & 6.5.x is netstandard.

**Comment by vertuxx** [comment]
hello.
I attached the log when I failed the build.
But I can not get effective information from inside.
The log file is saved in text as the console output.
The log output level is detailed. (It is a Japanese log)

This part is garbled, so I do not know what it is.

`error : �n���h������Ă��Ȃ���O: OutOfMemoryException.`

The code is as follows.

```
private void InfoButton_Click(object sender, RoutedEventArgs e)
{
    var config = new ActionSheetConfig()
        .SetTitle(LocalizedStrings.Instance["Info"])
        .SetCancel(LocalizedStrings.Instance["Cancel"])
        .Add(LocalizedStrings.Instance["Info"], async () =>
        {
            var alert = new AlertDialog
            {
                AlertType = AlertDialog.Type.Info,
                AlertTitle = "HogeHoge!!",
                AlertMessage = "PiyoPiyo!!",
                SecondaryButtonText = LocalizedStrings.Instance["OK"]
            };
            await alert.ShowAsync();
        })
        .Add(LocalizedStrings.Instance["About/HogeHoge"], async () =>
        {
            var uri = new Uri("https://example.com/foo/bar/hoge/piyo");
            var success = await Windows.System.Launcher.LaunchUriAsync(uri);
        });

    ((App)Application.Current).dialog= UserDialogs.Instance.ActionSheet(config);
}
```

Thank you.

[MyApp_Windows10Mobile_build_20170711_log.txt](https://github.com/aritchie/userdialogs/files/1143877/MyApp_Windows10Mobile_build_20170711_log.txt)

**Comment by aritchie** [comment]
Ok.... we've got several issues here.  You have just given me the same log that tells me absolutely nothing.  You have also given me a log that is in Japanese.... is there a single character of Japanese anywhere else on any of my repos that suggest I understand a word of it!???  

Again, the likely problem is .NET standard.  You are using VS2015 which isn't very good with netstandard.  Try in VS2017.

This is as far as I go with this issue unless you can provide something that I can work with.

**Comment by vertuxx** [comment]
VS2017 is fine works.

Thank you advice!
