### ISSUE TITLE
Message dialog pops up behind the progress dialog

### ISSUE THREAD

**Issue by duzenko** [aritchie/userdialogs#399]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS

## Version of OS(s) listed above with issue

9.3.5

## Version of ACR UserDialogs Library

6.5.1

## Expected Behaviour

Message boxes should appear on top of the existing progress dialog

## Actual Behavior

Message boxes appear behind the existing progress dialog

![image](https://user-images.githubusercontent.com/1481807/28112411-9cab764a-6701-11e7-9c02-a4400724ea39.png)

```
		public ICommand ViolationItemSelectedCommand {
			get {
				return new AsyncLockedCommand<ViolationListItemViewModel>( async (item) => {
					try {

			using ( UserDialogs.Instance.Loading( "Loading violation..." ) ) {
				var page = await Task.Run( () => {
                                          // exception raised here
                                } );
			}
					} catch ( Exception ex ) {
			UserDialogs.Instance.Alert("An error occured. Log file has been updated.");
					}
				} );
			}
		}
```

**Comment by aritchie** [comment]
I have this exact test case in the sample app that is working just fine.
Are you navigating or something inside of the loading call you have there?

**Comment by duzenko** [comment]
Sorry, is Alert called from an exception handler in the sample app?

**Comment by aritchie** [comment]
yes

**Comment by aritchie** [comment]
sorry, not an exception handler, but I do a loading with a delay and then I bring up an alert immediately following the loading operation.

**Comment by aritchie** [comment]
no feedback from question - closing
