### ISSUE TITLE
Make all methods asynchronous 

### ISSUE THREAD

**Issue by catlin0123** [aritchie/userdialogs#40]
I am running into race conditions when I call 

```
UserDialogs.Instance.HideLoading(); 
var action = await DisplayAlert(); 
```

specifically on Xamarin.Forms.iOS. It would be great if you could make at least HideLoading async, but I could see the use cases for others to be async as well.

**Comment by aritchie** [comment]
All dialogs are asynchronous accept progress.  Follow the samples for progress with a sync.  Show/hide loading are legacy that I only added by request

**Comment by catlin0123** [comment]
Your other methods don't work well with the mvvm structure I have, or I would use them. I need to be able to Show and Hide based upon a property. Thanks for your quick response.

**Comment by aritchie** [comment]
There is no relevant reason to make the show/hide asynchronous.  Alert already has an async counterpart in alertasync.

**Comment by catlin0123** [comment]
Thanks for your time.
