### ISSUE TITLE
IOS Prompt dialog is moving bottom relative to the keyboard.

### ISSUE THREAD

**Issue by denizz-ryzhkov** [aritchie/userdialogs#403]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
IOS 10.3.1

## Version of ACR UserDialogs Library
6.5.1

## Actual Behavior
IOS Prompt dialog is appearing in center between keyboard and top of screen, but after small delay is moving bottom relative to the keyboard. When application is started from background (dialog opened in this moment), dialog is moving to center as it should be

![prompt_dialog](https://user-images.githubusercontent.com/1655314/28529996-eae92d46-709a-11e7-8b6e-6b54210873fb.gif)

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I have never seen this issue before.  Does the sample app do this for you?  Can you provide a reproducible sample?

**Comment by denizz-ryzhkov** [comment]
I have no a reproducible sample in current time, but  I can try to implement it and share with you when it will be done.

**Comment by denizz-ryzhkov** [comment]
I tried to reproduce the issue with native IOS alert and seen same result. I can sum up what the issue reason not lay in ACR. Sorry for troubling, you can close it
