### ISSUE TITLE
Doesn't work on Initial ViewController

### ISSUE THREAD

**Issue by VetaLioSTV** [aritchie/userdialogs#406]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [+] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
Xamarin.iOS 10.3

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
Show loading bar and toast on initial view controller

## Actual Behavior
Actually `UserDialogs.Instance.ShowLoading()` crashes with 

> Object null reference

and for **Toast**, i got this message in output  :

> TTGSnackbar needs a keyWindows to display.

**Comment by aritchie** [comment]
Please include a sample reproducing the issue. please also include the full exceptions you are getting

**Comment by VetaLioSTV** [comment]
@aritchie What sample you expecting :) ? Just make blank project **Xamarin.iOS** and drop on `ViewDidLoad `method of rootviewcontroller this snippet of code : `UserDialogs.Instance.ShowLoading();`  
It crashes.

**Comment by aritchie** [comment]
I don't have this error in any of my apps (Xamarin Forms & MvvmCross apps) which includes the sample app in this repository.  If you want to reply with this kind of answer and not supply the requested info, don't expect help from me :)

**Comment by VetaLioSTV** [comment]
@aritchie yes,but as i said,its **Xamarin.iOS** project, no **Xamarin.Forms** or **MVVM**. 
How can i upload here source project?
