### ISSUE TITLE
UserDialogs is throwing an NullReferenceException when after calling ShowLoading it navigates to another ViewModel

### ISSUE THREAD

**Issue by SMavr** [aritchie/userdialogs#408]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [+] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
10.3.1

## Expected Behaviour
It does not throw a NullReferenceException

## Actual Behavior

If the app is showing a loading indicator while navigating to another view it will crash

## Code of Conduct

This happened after updating to MvvmCross 5

```csharp
async Task DoContinueAsync()
{
     UserDialogs.ShowLoading(this["Login_Title_EnteringGinloProcess"]);
     UserDialogs.HideLoading();
     await NavigationService.Navigate<MainViewModel>();

}
```
This will crash inside `void PositionHUD (NSNotification notification)` inside `ProgressHUD` method. The reason is the `Window` property is null. If I put a null check of `Window` that returns in case of null it will work without problem.

**Comment by aritchie** [comment]
Please read FAQ

**Comment by SMavr** [comment]
@aritchie I am not getting this NullReferenceException because nothing is rendered yet. Lets say I am in the StartViewModel and I show this loading indicator and the I want to navigate to the MainViewModel. The method `PositionHUD` is triggered and the I get this NullReferenceException. There are two ways to prevent this: Either I add this null checker inside this method or add an 
`await Task.Delay(1000)` between `UserDialogs.HideLoading` and navigation to the new ViewModel.
