### ISSUE TITLE
Problem with windows phone 8/8.1 no instance

### ISSUE THREAD

**Issue by angelcalvasp** [aritchie/userdialogs#41]
I was having the problem with Initiating with 

UserDialogs.Init();

saying that it shouldn't be called from PCL, then I read on the Nuget package update 
that inititation was only necessary for Android, but when I use UserDialogs.Instance its null, what am I missing btw this problem also was happening in windows phone 8 I'm currently using the latest version of the NuGet packages

**Comment by aritchie** [comment]
Honestly, I'm not really inclined to help you much when you are basically taking my source code one to one and rebranding it your own.  

https://github.com/angelcalvasp/Blacksun.XamForms/tree/master/Blacksun.Mvvm
https://github.com/angelcalvasp/Blacksun.XamForms/tree/master/Blacksun.XamForms.UserDialogs

**Comment by angelcalvasp** [comment]
The Mvvm part I did to de couple it from the Acr XamForms library and the UserDialogs well that was an idea to expand your control but that was before this Acr UserDIalogs came by I forgot to get rid of it I will remove it inmedietly

**Comment by EmilAlipiev** [comment]
how did you solve this problem? I cant figure out how to initialize on WP8.1. Can you please help me?

**Comment by aritchie** [comment]
First off - there is no Init for any other platform but android.  Secondly, post an error or something.  What "doesn't work"?

**Comment by EmilAlipiev** [comment]
![image](https://cloud.githubusercontent.com/assets/10422347/13558123/bd0dcbec-e3fc-11e5-8304-a6d0a6501721.png)

I tried directly accessing UserDialogs.Instance.ShowLoading(); as well as injecting the dependency as i do on my android but I am getting following message in the image. 

Windows.UI.Xaml.Markup.XamlParseException was unhandled by user code
  HResult=-2144665590
  Message=XAML parsing failed.
  Source=Windows
  StackTrace:
       at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
       at Acr.UserDialogs.ProgressContentDialog.InitializeComponent()
       at Acr.UserDialogs.ProgressDialog..ctor()
       at Acr.UserDialogs.UserDialogsImpl.CreateDialogInstance()
       at Acr.UserDialogs.AbstractUserDialogs.Progress(ProgressDialogConfig config)
       at Acr.UserDialogs.AbstractUserDialogs.Loading(String title, Action onCancel, String cancelText, Boolean show, Nullable`1 maskType)
       at Acr.UserDialogs.AbstractUserDialogs.ShowLoading(String title, Nullable`1 maskType)
       at myApp.CategoryPageModel.set_SelectedItem(Result value)
  InnerException:

**Comment by aritchie** [comment]
Alright, so this is the exact same error that is going on in defect #112.  It will be fixed sometime in the near future.  Watch that defect and wait for a fix.  As an FYI, I am dropping ALL WP8 support very soon as well.

**Comment by EmilAlipiev** [comment]
but one thing I don't understand how people claim to work it in  #112 if it is bug.

**Comment by aritchie** [comment]
Just watch #112 and wait.  It is related.

**Comment by EmilAlipiev** [comment]
UWP is working fine now but why are you dropping support for WP81? Is there any version working for it?

**Comment by aritchie** [comment]
No.  A contributor brought it in, but didn't do any sort of testing or support after that.  I have never really worked with WP8.1, nor do I have any plans to do so.  UWP is the only thing of any real interest and it isn't priority yet.
