### ISSUE TITLE
[Android] Prompt: Set selected text

### ISSUE THREAD

**Issue by Ikarus76** [aritchie/userdialogs#410]
- [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

It would be nice, if the default text can be selected via PromtConfig. The user can type the value w/o deleting the default text.

**Comment by Ikarus76** [comment]
As I saw in the source, the text should be selected by default. I don't know, why it's not selected.

**Comment by rogerjak** [comment]
I'd like this too, please.
The code seems right, but I'm not that experienced with Android/Xamarin to fix it myself.
