### ISSUE TITLE
Prompt: InputType numeric or decimal should accept comma

### ISSUE THREAD

**Issue by Ikarus76** [aritchie/userdialogs#411]
- [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
Android 6.0

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
On InputType.DecimalNumber, comma should be accepted.

## Actual Behavior
Neither on InputType.Numeric nor InputType.DecimalNumber, a comma is accepted.

**Comment by aritchie** [comment]
Honestly, this isn't a feature I ever want to take on.  You can use the current validate event and reformat the text there if you want.

**Comment by aritchie** [comment]
It just add further complexity to a dialog that in my opinion, should be simple.  You can do this in a page with an entry control under your direct control much better.

**Comment by Ikarus76** [comment]
Ok, then what is the difference between InputType.Numeric and InputType.Decimal? As I saw in the source, the comma should be accepted when InputType = Decimal. Or did I miss something?

**Comment by aritchie** [comment]
One allows a decimal point, the other does not.  It will show up on the keyboard, but that's androids behavior.   Decimal does not mean comma, it means the period/dot.  

If you don't like this behavior and you are digging through the source, you are welcome to send a PR.  The only deal is that the functionality needs to work for all platforms.

**Comment by Ikarus76** [comment]
Ok. Sorry for the confusion. With 'comma' I meant some kind of decimal separation. Neither point nor comma is working here.

**Comment by aritchie** [comment]
With decimal, you can have a decimal/dot.  With number, you can have 0-9.  I have tested both cases and they are fine.  This issue is closed. I would ask that you read the android docs going forward with stuff like this

**Comment by EmilAlipiev** [comment]
@aritchie  he actually means that coma is expected for decimal when using any other culture than English/American Culture.  If an application support for example, German or Spanish language, Prompt is not useful as decimal.

**Comment by EmilAlipiev** [comment]
anyone who is looking for a solution here. this is actual bug report and it looks like fixed already 
https://bugzilla.xamarin.com/show_bug.cgi?id=32871
