### ISSUE TITLE
[Android] Does not compile with support libraries >=25.4.x

### ISSUE THREAD

**Issue by wesoos** [aritchie/userdialogs#413]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue

I am compiling against the latest Android 7.1 with target set to 7.1, API 25

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
Compile successfully

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

Below is error thrown when compiling, with the main piece being
```
Could not resolve reference to Android.Support.Design.Widget.BottomSheetDialog' 
(defined in assembly 'Acr.UserDialogs
```

```
The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Support.Design.Widget.BottomSheetDialog' (defined in assembly 'Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.Design, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Support.Design.Widget.BottomSheetDialog
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Run(Pipeline pipeline, LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	
```

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This is something weird with the linker, not this library.  What version of the android support libraries are you using?

**Comment by wesoos** [comment]
I just upgraded everything to the latest.  So support libraries would be 25.4.0.1

**Comment by aritchie** [comment]
Did it compile before the 25.4.0.1?

**Comment by wesoos** [comment]
Yeah, I haven't upgraded my packages in a while.  I just did it yesterday, which is when I started encountering this little issue.  I tried downgrading your package, but didn't work, and didn't know where else the problem could be.  I will downgrade the support packages and try again.  Is that where linker issues will be?

**Comment by aritchie** [comment]
No - the issue is obviously that the support packages after 25.x onward (which were supposed to maintain a level of backwards compatibility that even xamarin forms is opening the gates on >= 25.3.1).  Clearly, this is still not the case. 

If you change the support packages, you have to flush your bin/obj directories and restart VS usually

**Comment by santosbj** [comment]
Hi,

I have de same problem, after delete bin/obj, restar VS the problem persist!!

Another option?

Thanks!

**Comment by aritchie** [comment]
@santosbj did you downgrade your android support library to 25.3.1?  ALL of them

**Comment by wesoos** [comment]
Downgrading support libraries to 25.3.1 worked.  Thanks

**Comment by Szymaniuk** [comment]
Same for me - working fine at 25.3.1 Xamarin.Android.**** libs, not not working at 25.4.0.1 - exact same issue Could not resolve reference to Android.Support.Design.Widget.BottomSheetDialog'

**Comment by Szymaniuk** [comment]
Related issue https://github.com/xamarin/AndroidSupportComponents/issues/61

**Comment by PhilJenson** [comment]
Had the same problem. Worked in debug, failed in release build. Downgrading to 25.3.1 solved it.

**Comment by BlueFire-LLC** [comment]
Guess we have to wait for Xamarin.Android.Support.v4 version 25.3.2.

**Comment by closetoyou293** [comment]
Have same problem if option linking with sdk assembly. There's something wrong with Android.Support.Design.Widget.BottomSheetDialog
I'm using latest android support library(version="25.4.0.1").
_

> Error		The "LinkAssemblies" task failed unexpectedly.
> Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Support.Design.Widget.BottomSheetDialog' (defined in assembly 'Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')

_

**Comment by aritchie** [comment]
This issue is solved by installing 25.4.0.2

**Comment by ironworkshop** [comment]
Thanks aritchie, this solved my issues which has been a problem for me for a while :)

**Comment by mofadevs** [comment]
Hi aritchie
First of all, great piece of work, that is really helping us in development. 
Unfortunately, at this stage we can not downgrade Android Support packages. We are using 25.4.0.1 and UserDialogs Plugin version 6.3.8 and we are having the same problem in release mode. 
Is there any other way around?

**Comment by ironworkshop** [comment]
I believe if you follow aritchie’s last comment above mine the issue is fixed if you upgrade your support libraries to 25.4.0.2. I applied this solution to my project a couple months ago and it worked. As you mention you are using 25.4.0.1 you need to upgrade not downgrade :)

I will double check my support library versions tomorrow morning and post back.

**Comment by mofadevs** [comment]
Thanks
please  let me know.

**Comment by mofadevs** [comment]
Just to update you on this, I tried upgrading support libraries to
25.4.0.2, but it broke many other things that are in the application. So I
have to stick with 25.4.0.1. Is there any other way out?

**Comment by aritchie** [comment]
@mofadevs you need to upgrade to 25.4.0.2 as there was a bug in 25.4.0.1.  You need to make sure you update ALL android support libraries when you update one of them.  You should then close VS, delete all bin/obj folders, restart VS and compile as I stated above.  

Best of luck

**Comment by Genfood** [comment]
I still getting this Exception with version 27.0.2.1 and above. Any Ideas what I could?
I guess downgreade to version 25.4.0.2 isnt a deal anymore?

**Comment by aritchie** [comment]
@Genfood this issue is almost 2 years old.  The error won't be the same and you haven't given me any details with said error.  Open a new defect with actual details please
