### ISSUE TITLE
ActionSheet does not properly cancel when background or back button are pressed in Android

### ISSUE THREAD

**Issue by twinee** [aritchie/userdialogs#414]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] NET Standard 1.1

## Version of OS(s) listed above with issue
5.0.1

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
When the back button or background is pressed when an ActionSheet is visible (called using ActionSheetAsync), the Task returns the 'Cancel' string

## Actual Behavior
When the back button or background is pressed, the ActionSheet disappears, but the associated Task<string> does not return at all, causing code to stall at the 'await ActionSheetAsync(...)' line, and any cancel actions to not be executed.

**Comment by aritchie** [comment]
Use the synchronous version.  It is better for these scenarios.

**Comment by twinee** [comment]
I'm trying now, any idea why this is happening?:

`08-11 16:44:11.701 E/mono-rt (20799): [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Acr.UserDialogs.IUserDialogs.ActionSheet' not found.`

**Comment by twinee** [comment]
The Synchronous version has the exact same problems, the Cancel action is not called.

**Comment by aritchie** [comment]
I'll look into the back button on android 5 at some point in the future.

Backgrounding is something you pretty much have to be responsible for.

**Comment by ebicoglu** [comment]
Same problem over here

**Comment by rrvind** [comment]
@twinee did you find a workaround or a solution to this?

**Comment by twinee** [comment]
@rrvind no, sorry, i just ended up making a custom popup page with a listview. turned out to actually provide a lot more flexibility (it returns any type of object instead of just strings, custom view cells for the listview, etc.). it's obviously a bit slower than a native action sheet but not annoyingly so.

**Comment by cbenoist** [comment]
Is there any update on this issue?  I have actionsheets working on iOS perfectly as they should with a cancel  action firing on tapping off the action sheet at the bottom.  On android it doesn't fire the action doing the same thing.

**Comment by aritchie** [comment]
I dunno @cbenoist - do you have a PR or something?
