### ISSUE TITLE
"No Resource Found" error in Android project when using NetStandard shared library

### ISSUE THREAD

**Issue by FrozenKiwi** [aritchie/userdialogs#415]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [x] NET Standard 1.1

## Version of OS(s) listed above with issue
7.1

## Version of ACR UserDialogs Library
Latest (6.5.1)

## Expected Behaviour
No difference between PCL & NetStandard

## Actual Behavior
Cannot compile Android project referencing a NetStandard shared library if the NetStandard1.4 library references UserDialogs.

Its very weird, the change in shared code somehow propagates downstream and causes compiler errors in Android version (errors not seen in iOS/UWP).  This is in a relatively fresh project (busy porting PCL library to NetStandard)

Any ideas?

2>C:\src\TADevelopment\OA2 - Copy\OrrinityApp\OrrinityApp.Droid\obj\Debug\resourcecache\02C53A9FFF09984EAD64A0F415EEBDD5\res\values\values.xml(165): error APT0000:  Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.Light.ActionButton'.
2>C:\src\TADevelopment\OA2 - Copy\OrrinityApp\OrrinityApp.Droid\obj\Debug\resourcecache\02C53A9FFF09984EAD64A0F415EEBDD5\res\values\values.xml(169): error APT0000:  Error retrieving parent for item: No resource found that matches the given name 'Widget.AppCompat.ActionButton'.
2>C:\src\TADevelopment\OA2 - Copy\OrrinityApp\OrrinityApp.Droid\Resources\values\styles.xml(2): error APT0000:  Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
2>C:\src\TADevelopment\OA2 - Copy\OrrinityApp\OrrinityApp.Droid\Resources\values\styles.xml(3): error APT0000:  Error: No resource found that matches the given name: attr 'colorAccent'.
2>C:\src\TADevelopment\OA2 - Copy\OrrinityApp\OrrinityApp.Droid\Resources\values\styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'colorPrimary'.
2>C:\src\TADevelopment\OA2 - Copy\OrrinityApp\OrrinityApp.Droid\Resources\values\styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
2>C:\src\TADevelopment\OA2 - Copy\OrrinityApp\OrrinityApp.Droid\Resources\values\styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'windowActionBar'.
2>C:\src\TADevelopment\OA2 - Copy\OrrinityApp\OrrinityApp.Droid\Resources\values\styles.xml(4): error APT0000:  Error: No resource found that matches the given name: attr 'windowActionModeOverlay'.
2>C:\src\TADevelopment\OA2 - Copy\OrrinityApp\OrrinityApp.Droid\Resources\values\styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'windowNoTitle'.
2>C:\src\TADevelopment\OA2 - Copy\OrrinityApp\OrrinityApp.Droid\Resources\values\styles.xml(4): error APT0000:  Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'.
2>C:\src\TADevelopment\OA2 - Copy\OrrinityApp\OrrinityApp.Droid\Resources\values\styles.xml(4): error APT0000:  Error: No resource found that matches the given name: attr 'colorAccent'.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
The error has nothing to do with netstandard/pcl.  It more likely has to do with your android support library version

**Comment by FrozenKiwi** [comment]
Pardon the question (I'm don't do much mobile dev) - but is it possible that referencing in UserDialogs brings in a competing version of the android support library, and this messes things up?  Which version *should* I be referencing (or how can I find out which version?)

The project compiles/runs fine without UserDialogs, but as soon as I add that reference to my shared library - *boom*.

**Comment by aritchie** [comment]
This has already been answered in detail on #413
