### ISSUE TITLE
Cleartext Storage of Sensitive Information in Memory Warning

### ISSUE THREAD

**Issue by mingxli** [aritchie/userdialogs#417]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
iOS 10.3.3

## Version of ACR UserDialogs Library
6.4.1

## Actual Behavior

Thank you very much for the great library! I am using Acr.UserDialogs 6.4.1 for our mobile product. We just did a static scan with Veracode and the analyze reported that in loginconfig.cs and credentials.cs (under acr.userdialogs.interface) there's were couple of "Cleartext Storage of Sensitive Information in Memory" flaws. 

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Don't use the function then??  It isn't something I plan to do anything as I only ever used it for prototyping once upon a time.
