### ISSUE TITLE
Xamarin.Android.Support.Design >= 25.3.1 required

### ISSUE THREAD

**Issue by gercobrandwijk** [aritchie/userdialogs#419]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
At least Android 4.0.3 and higher

## Version of ACR UserDialogs Library
6.3.12 and above

## Expected Behaviour
That I can use the latest version in combination with Xamarin Forms.

## Actual Behavior
From version 6.3.12 this library requires MonoDroid which requires Xamarin.Android.Support.Design (>= 25.3.1). This is not possible in combination with Xamarin Forms, because it is strongly not adviced to update Xamarin.Android.Support packages seperately from an update of Xamarin Forms (https://developer.xamarin.com/guides/xamarin-forms/troubleshooting/). Currently this means that I (and all the other Xamarin Forms users) cannot update this library to a higher version than 6.3.10. I think that verison 6.5.1. does not really requires Xamarin.Android.Support.Design >= 25.3.1, so can the dependency number be lowered? Or is there another possibility to get this working together?

**Comment by aritchie** [comment]
The dependency for Xamarin.Forms on droid is Xamarin.Android.Support.Design (>= 23.3.0) for MonoAndroid 7.  You can set your compile target to android 7+ and the nuget packages will install just fine.  

Please be respectful of the code of conduct in the future (the one you deleted from the issue template)!  This library is not associated with Xamarin Forms in any way, nor will the dependencies of said library dictate the dependencies of this library.
