### ISSUE TITLE
User dialogs not working when modals on top of UITabBarController

### ISSUE THREAD

**Issue by RTodorov** [aritchie/userdialogs#42]
When you have more than one modal stacked up your UITabBarController, user dialogs won't work because GetTopViewController() will return the wrong IUIViewController.

Scenario:

|- UITabBarController
    |--- UINavigationController (modal)
           |------ UIViewController
                  |--------- UINavigationController (modal)
                         |------------ UIViewController (<--- won't work here)

I'll open a PR in a few minutes with a fix.

**Comment by aritchie** [comment]
Released in 3.4.2 on nuget

**Comment by RTodorov** [comment]
Thanks a lot @aritchie !
