### ISSUE TITLE
How to do ShowImage in UWP for XF?

### ISSUE THREAD

**Issue by EmilAlipiev** [aritchie/userdialogs#420]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [x] UWP
 - [] NET Standard 1.1

## Version of ACR UserDialogs Library
latest

## Expected Behaviour
I was using showsuccess but it is deprecated now and I need to change to use showImage which works fine with the code below. But it throws exception in UWP desktop. It throws exception BitmapLoader but It looks like Splat is not supported for UWP. How can we achieve this in cross platform project with splat or without?

```
     string ImageUri = "icon.png";

                        var Image = await Splat.BitmapLoader.Current.LoadFromResource(ImageUri, null, null);
                        _userDialogs.ShowImage(image: Image, message: message, timeoutMillis: 3000);
```

**Comment by aritchie** [comment]
It is the library throwing the exception.  I don't support this on UWP.
