### ISSUE TITLE
ShowLoading flickers on Android if you call it multiple times with different titles

### ISSUE THREAD

**Issue by Brosten** [aritchie/userdialogs#422]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
7.0

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
A non flickering Loading-dialog

## Actual Behavior
A flickering dialog. It dissapperas and directly appers again.

## Code of Conduct
UserDialogs.Instance.ShowLoading("1 of 3 items loaded");
// Do some stuff
UserDialogs.Instance.ShowLoading("2 of 3 items loaded");
// Do more stuff
UserDialogs.Instance.ShowLoading("All done");

This code on iOS creates a nice loading dialog where the text is updated with new information after each step. However, on Android you get an annoying flicker. Seems like the loading dialog is removed and then added back again with the new text. Is it possible to get it as smooth on Android as it is on iOS?

**Comment by aritchie** [comment]
Please take a little bit of time to review the source code in the future!!

https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs.Interface/AbstractUserDialogs.cs#L66

**Comment by Brosten** [comment]
Sorry, well in the source, it's obvious that the dialog is closed and then reopened. However, it would be very nice to have a way of updating the text of a current Loading dialog. But this might be the wrong place to request such a feature?

**Comment by aritchie** [comment]
ShowLoading is going away.  This is what you want: https://github.com/aritchie/userdialogs/blob/master/src/Samples/Samples/ViewModels/ProgressViewModel.cs#L74

You can update the instance title.  Note that it may still flicker a bit during the resize.  I won't be fixing this in the near future.

**Comment by Brosten** [comment]
Thank's! I'll move over to Progress....
