### ISSUE TITLE
Feature request: Add AutomationId's to dialog constructor

### ISSUE THREAD

**Issue by michelmoorlag** [aritchie/userdialogs#423]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [x] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
not applicable 

## Version of ACR UserDialogs Library
not applicable 

## Expected Behaviour
It would be nice if you could set the AutomationId of some elements in the dialogs like buttons, entry's etc. This would make more accurate ui tests possible. For example I want to test if a certain confirmation dialog comes up and want to press a certain button. Maybe it is possible to add some overloaded dialog constructors where you can set the AutomationId for certain elements like the ok button, cancel button etc. 
Now I test by looking for translated text but that makes my ui test very depended on the translation and very fragile.

## Actual Behavior
There is no overloaded dialog constructor that takes AutomationId's for certain elements or any way settings automationId's is missing.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This can't actually be done due to the way android works.  I'm afraid you'll have to continue doing what you're doing.
