### ISSUE TITLE
System.IO.PathTooLongException: The specified path, file name, or both are too long.

### ISSUE THREAD

**Issue by rrvind** [aritchie/userdialogs#427]
## Platforms 

 - [x] iOS
 - [x] Android

## Version of OS(s) listed above with issue
All

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
Build... :-\ sorry. this might be an extreme case but i really hope you can help.

## Actual Behavior
Due to "Company policy" (ARGH!) i have some pretty long solution and branch names (20 to 40 each) charecters and is forced to have my projects at x:\Workspace \soluition-name\banch-name\...

This makes my setup incompatible with Acr.UserDialogs since it also have some long paths and in builing the project. over 248 chars long.... 
All other add-on's i use work fine, but i understand if this is an too edge case for you to help me. 

Do you have any idea in how i could get UserDialogs to work? is it posible for me to somehow change the nuget pachage names or somethig :/ hope you can help. 

stacktrace:
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018: System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at System.IO.PathHelper.GetFullPathName()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Xamarin.Tools.Zip.ZipEntry.DoExtract(IntPtr zipFile, String destinationPath, FileMode outputFileMode, EntryExtractEventArgs args)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Xamarin.Tools.Zip.ZipEntry.Extract(String destinationDir, String destinationFileName, FileMode outputFileMode)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Xamarin.Android.Tools.Files.ExtractAll(ZipArchive zip, String destination, Action`2 progressCallback)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

**Comment by aritchie** [comment]
I'm not really sure what or how you expect me to help?  This is very much outside of a library problem

**Comment by rrvind** [comment]
I was hoping that you had run into a problem like this before, you do have one og the most popular addons for forms ;)  But i know it was a long shot. I¨m sorry to have wasted your time.

**Comment by zany1** [comment]
well I know this is closed but I am facing this problem too, I tried moving my project to c:\ but it didn't help, the problem started immediately after installing this library. Enabled long names in windows 10 didnt help my case , @rrvind if you found a solution please share. [https://forums.xamarin.com/discussion/104373/long-path-error-my-dev-has-come-to-a-stand-still-please-help#latest](url)

**Comment by rrvind** [comment]
@zany1 I have not found a good solution on this and i dont think i will before windows supports longer file path or xamarin change the way they build projects... 

i got around it temporary by mounting the root folder for the project as a network drive (giving it a drive letter) but i hate it.... i have tried to write Xamarin support but im getting stonewalled....

**Comment by zany1** [comment]
@rrvind Your solution sounds very fancy,  unfortunately even after removing this library in vs2015, i was getting this problem tried cleaning etc didn't work my project broke. I just installed the new vs2017 and I have enabled longpath through group policy and everything is fine now.

**Comment by Micahel55** [comment]
I suggest that you use LongPathTool its an amazing tool google it and will solve your problem.
