### ISSUE TITLE
Keyboard not showing automatically

### ISSUE THREAD

**Issue by drznathou** [aritchie/userdialogs#428]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] Android

## Version of OS(s) listed above with issue
Android 7.0, 6.0.1
## Version of Xamarin Forms 
2.3.4.267

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
When using PromptAsync like this:
`var input = await UserDialogs.Instance.PromptAsync("", null, "Rechercher", "Annuler", "numero de boucle (4 chiffres min)", InputType.Number);`
**I'm expecting the keyboard to show up in the same time as the dialog shows up.** 

## Actual Behavior

Only dialog shows up, but not the keyboard unless the user Tap the text input
                

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

## GOOD JOB ALLAN RITCHIE

**Comment by wolfmanu** [comment]
I would like to have this feature too
