### ISSUE TITLE
The text isn't showed in ConfirmAsync if text has more symbols than ~ 14000 - 15000

### ISSUE THREAD

**Issue by artmon** [aritchie/userdialogs#429]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [♣] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue

10.3

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
The text is showed in ConfirmAsync

## Actual Behavior
The text isn't showed in ConfirmAsync if text has more symbols than ~ 15000

**Comment by aritchie** [comment]
This is likely a platform limitation.  A good one in my opinion.  I'd suggest showing this data some other way.
