### ISSUE TITLE
ACR User Dialogs 6.5.1 can't install on Xamarin Forms PCL Profile 78 - Unable to install Splat

### ISSUE THREAD

**Issue by pfaucon** [aritchie/userdialogs#435]
## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
should install properly with dependencies.

Regressed to 6.1.2 used previously and it works fine, the break is likely to have occurred in [6.5.0](https://github.com/aritchie/userdialogs/blame/79352bdb9efc4ee74ab7df2f052736b56fcd4913/nuspec/Acr.UserDialogs.nuspec#L39)

**Comment by aritchie** [comment]
It isn’t a break.  As documented, this library is .net standard based (using profile 1.1 which I believe adheres to pcl 111)
