### ISSUE TITLE
ActionSheetAsync method not showing Cancel Text on IPad

### ISSUE THREAD

**Issue by akhare22sandeep** [aritchie/userdialogs#437]
![image-2017-10-18-14-42-11-544](https://user-images.githubusercontent.com/12301696/31831359-35456162-b591-11e7-9f52-92938f151245.png)
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 [] iOS

## Version of OS(s) listed above with issue
11.0.2

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
It should show provided action items with Cancel Text at the bottom

## Actual Behavior
Issue is in IPad only IPhone works fine.

Below is the code i am using 

```
`  
   var action = await DialogService.ShowActionSheetAsync("Select receipt from", "Cancel", string.Empty, capabilities);

public async Task<string> ShowActionSheetAsync(string message, string cancel, string distrcutive, List<string> optoions)
        {

            return await UserDialogs.Instance.ActionSheetAsync(message, cancel,null,null, optoions.ToArray());
        }`
```

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
iPads don't display the cancel button because you can tap anywhere else on the screen.  This is the way apple enforces it and has nothing to do with the calls this library makes (or can make)
