### ISSUE TITLE
how to use Acr.UserDialogs in xamarin shared project.

### ISSUE THREAD

**Issue by NadirHussainDasti** [aritchie/userdialogs#438]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 1.1

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Install in platforms and use.

Please note this area is for issues and feature requests, not support.  Please use Xamarin forums for support
