### ISSUE TITLE
Splat and .NET Standard

### ISSUE THREAD

**Issue by MKuckert** [aritchie/userdialogs#439]
The library works fine with my .NET Standard 2.0 library, but the Splat dependency is a problem. Both Splat and .NET Standard contains the class `System.Drawing.Color`. This prevents me from setting any Colors in my .NET Standard library because of this assembly conflicts (`Color` is defined in both assemblies).

Is it possible to abstain from using Splat?

**Comment by libin85** [comment]
@aritchie : Hi Allan, I am also facing the same issue. I believe its beause with the new dotnet, we have the System.Drawing assembly, and splat has the same assembly too.  It looks like the shims for these classes has been removed. Can we please get the splat reference changed? 

https://github.com/reactiveui/splat/issues/152

**Comment by ASloth** [comment]
Is this actually a bug or am i missing something?

**Comment by aritchie** [comment]
Guys - quick hassling me about this.  I use Splat... I'm going to continue using splat unless someone is going to contribute the large sum of work splat performs.  When splat changes their namespacing (which they are working on), I will also adapt this library for said update.

**Comment by ASloth** [comment]
@aritchie thanks for the clarification. I was just wondering if there is a workaround im not aware of since everyone who is using .netstandard(2?) and your plugin should have problems at the moment. I will wait for the splat guys then.

**Comment by ElteHupkes** [comment]
@ everyone else who's interested in this: the 7.0 version which rather silently came out a couple of days ago removes the Splat dependency. I'm using it successfully in my .NETstandard 2.0 project without the previous assembly conflicts :D.

**Comment by aritchie** [comment]
@ElteHupkes it didn’t silently come out at all.  I announced it on twitter @allanritchie911 as I always have.  I also maintain a public changelog that states this change as well - https://github.com/aritchie/userdialogs/blob/master/docs/changelog.md

**Comment by ElteHupkes** [comment]
@aritchie Haha sorry, I wasn't implying you tried to keep it a secret ;). I was running 6.4.1 until yesterday which started to give me weird issues, and it personally took me quite a while to realize there was a new version (I only noticed this on NuGet, don't do Twitter, that's my problem of course), then indeed I saw the changelog, and then all my problems vanished. Long story short I was rather happy and wanted to save any other people that might end up here the time. Thanks for your work!

**Comment by vesselintodorov** [comment]
Any solutions on this problem? Can't really change the color of my toasts.

**Comment by ElteHupkes** [comment]
Well, if you read any of the previous - yes, you update to Acr.UserDialogs 7.0.0. Then you remove Splat.

**Comment by vesselintodorov** [comment]
Didn't really want to remove Splat but if there's no other option I'll have to try. Thanks.
