### ISSUE TITLE
ActionSheetAsync - CancellationToken not working

### ISSUE THREAD

**Issue by salamoun** [aritchie/userdialogs#441]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
iOS 11.0.3

## Version of ACR UserDialogs Library
6.4.1

## Expected Behaviour
I'm trying to cancel/hide ActionSheet using CancelationToken.
When token is canceled, ActionSheet hide, it's ok, but code never continues, await thread is never ended.
I asume that when token is canceled, ActionSheetAsync returns "Cancel" value and code can continue.

This example shows ActionSheet, that is after 2sec hidden but code never continues to log.Debug...

```
string result;
using (var _cts = new CancellationTokenSource())
{
 _cts.CancelAfter(2000);
 result = await UserDialogs.Instance.ActionSheetAsync(title, cancel, destr, _cts.Token, buttons);
 log.Debug("UserDialog ActionSheetAsync finished.");
}
```

**Comment by aritchie** [comment]
Don't use this method.  I'll be getting rid of it in a future release.  The sync version will work fine
