### ISSUE TITLE
Android project fails just after adding Acr.UserDialogs packages, style.xml issue?

### ISSUE THREAD

**Issue by Ph0b0x** [aritchie/userdialogs#443]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
API 23

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
Project should build and execute on Android Emulator

## Actual Behavior
Hello, first of all, thanks for UserDialogs. I have use it before and really like it. Also, i am using Visual Studio for MAC and i am working on a Xamarin Forms app that will be deployed on iOS and Android. I just added AcrUserDialogs through Nuget. I have not added any User Dialogs references other than the Android MainActivity Init as instructed in the home page. My iOS project builds and executes find however my Android project does not build. After it fails it opens the file "styles.xml" for some reason but nothing else.

Here's the stacktrace:
_Build FAILED.

/Users/dxccas/Documents/Spirit/CertificationCheck/packages/Microsoft.Bcl.Build.1.0.21/build/Microsoft.Bcl.Build.targets(243,5): warning : All projects referencing CertificationCheck.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.
/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(2003,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
Resources/values/styles.xml : error APT0000: 1: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
Resources/values/styles.xml : error APT0000: 2: error: Error: No resource found that matches the given name: attr 'colorAccent'.
Resources/values/styles.xml : error APT0000: 1: error: Error: No resource found that matches the given name: attr 'colorPrimary'.
Resources/values/styles.xml : error APT0000: 1: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
Resources/values/styles.xml : error APT0000: 1: error: Error: No resource found that matches the given name: attr 'windowActionBar'.
Resources/values/styles.xml : error APT0000: 3: error: Error: No resource found that matches the given name: attr 'windowActionModeOverlay'.
Resources/values/styles.xml : error APT0000: 1: error: Error: No resource found that matches the given name: attr 'windowNoTitle'.
Resources/values/styles.xml : error APT0000: 3: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'.
Resources/values/styles.xml : error APT0000: 3: error: Error: No resource found that matches the given name: attr 'colorAccent'.
    2 Warning(s)
    9 Error(s)_

**Comment by Ph0b0x** [comment]
Update:

I updated a few Android packages and now i only got these 2 errors:

__/Xamarin.Android.Support.v7.AppCompat/library_project_imports/res/values-v26/values-v26.xml : error APT0000: 1: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
Xamarin.Android.Support.Design/library_project_imports/res/values-v26/values-v26.xml : error APT0000: 1: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.



Although i am not sure this is related to UserDialogs.

**Comment by aritchie** [comment]
This has nothing to do with this library.  You likely don't have your android targets setup right OR you haven't installed all of the latest android SDKs.

**Comment by Ph0b0x** [comment]
Thanks, you are right.

For UserDialogs 6.5.1 I needed Xamarin.Android.Support.v7.AppCompat v 26.1.0.1 and all its dependencies along with Andoid SDK 8.0. I hope this helps anyone with the same issue which is not related directly to the package.

Regards.
