### ISSUE TITLE
Could not install package 'Acr.UserDialogs 6.5.1'

### ISSUE THREAD

**Issue by DiomedesDominguez** [aritchie/userdialogs#444]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
iOS 10
Android API 23

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
To be installed on the PCL project.

## Actual Behavior
I'm getting this error message:
Could not install package 'Acr.UserDialogs 6.5.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by aritchie** [comment]
This has been answered many times and is even stated on the readme.  This library is .NET standard based.  It will work with PCL profile 111, but I will not support it if you have issues
