### ISSUE TITLE
ios 11 onCancel action progress dialog

### ISSUE THREAD

**Issue by RickyHa** [aritchie/userdialogs#447]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
11.3

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
UserDialogs.Instance.Progress(title, onCancel, cancelText);
the action onCancel is called.
## Actual Behavior
the action onCancel is not called

**Comment by bsloehr** [comment]
Was there any resolution to this issue? I am seeing the same behavior.
