### ISSUE TITLE
Unhandled exceptions Xamarin Live Player for Android

### ISSUE THREAD

**Issue by DeerSteak** [aritchie/userdialogs#449]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
7.0, 7.1, 8.0

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
No exceptions in Xamarin Live Player for Android.

The app is a Xamarin Forms app. My MainActivity has "UserDialogs.Init(this);" per the setup instructions. It runs fine on actual hardware or when deployed via the tethered debugger in Visual Studio 2017 (Windows 15.4). But when trying to run the app through the (admittedly preview) Xamarin Live Player, the app crashes at first use of anything in the library, for example UserDialogs.Instance.ShowLoading() method. 

I have used the Live Player on a Galaxy S7, a Moto X Play, and a Pixel 2 all with the most recent firmware updates. 

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
[Acr.UserDialogs] In android, you must call UserDialogs.Init(Activity) from your first Activity OR UserDialogs.Init(App) from your custom application OR provide a factory function to get teh current top activity via UserDialogs.Init(() => supply top activity) (ArgumentException)

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This is obviously something to do with live player (which I don't use).  I'll go as far to test in a simulator and a real device, beyond that, I would suggest talking to the other vendor.

**Comment by DeerSteak** [comment]
Xamarin Live Player is the tool announced by the Xamarin team at Microsoft Connect on Wednesday. It's meant for faster rebuild/test cycles without having to deploy the app. It's part of Visual Studio 15.4 on Windows and Visual Studio Preview on Mac.

**Comment by aritchie** [comment]
I’m aware of what it is, but this lib works on devices and emulators without issue, so if it doesn’t work in Xamarin live player - talk to them

**Comment by NiklasTeich** [comment]
I can reproduce this issue ... have the same setup and error.
I'm also using the Xamarin Live Player for faster and better testing.
What can we do?

**Comment by DeerSteak** [comment]
I've come to the conclusion that since you have to call UserDialogs.Init() in the platform-specific code, and since the player is only running what's in the PCL, that I need to spend a few minutes and figure out how to call the platform-specific UserDialogs.Init() from the PCL. Probably from the App constructor using Device.RuntimePlatform, but I haven't messed with it much.

**Comment by NiklasTeich** [comment]
So @DeerSteak , you don't have it actually running? Then we have to try more ... i will also try a few others things.
