### ISSUE TITLE
Object reference not set to an instance of an object (after update to 4.0)

### ISSUE THREAD

**Issue by davidtavarez** [aritchie/userdialogs#45]
(*I upgrade everything to WarnToast, ErrorToast, SuccessToast*). Now I'm receiving NullPointerException in all my Toast.

  at MessageBar.MessageView.Draw (CGRect rect) [0x000ee] in <filename unknown>:0 
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, IntPtr principal, IntPtr delegate) [0x00005] in /Users/builder/data/lanes/1962/8b265d64/source/maccore/src/UIKit/UIApplication.cs:63 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/1962/8b265d64/source/maccore/src/UIKit/UIApplication.cs:47 
  at memmo.Application.Main (System.String[] args) [0x00008] in /Users/david/Projects/memmo/iOS/Main.cs:17 

![screen shot 2015-08-11 at 9 48 53 am](https://cloud.githubusercontent.com/assets/337107/9199064/4688c054-400e-11e5-9136-a8e857da1c2c.png)
![screen shot 2015-08-11 at 9 48 37 am](https://cloud.githubusercontent.com/assets/337107/9199065/4696864e-400e-11e5-908e-81d1acf20add.png)
![screen shot 2015-08-11 at 9 48 08 am](https://cloud.githubusercontent.com/assets/337107/9199066/46a48370-400e-11e5-8b46-65d102c58dd7.png)

**Comment by aritchie** [comment]
It looks like you're calling this outside of a viewcontroller (before the viewcontroller is available).

**Comment by davidtavarez** [comment]
I did not change anything in my code, everything was working perfect before 4.0
Like I said, I just change all my methods.

**Comment by aritchie** [comment]
You've upgraded to the toasts, so that is a change

**Comment by davidtavarez** [comment]
What can I do? :'(

**Comment by aritchie** [comment]
Where are you running this code?  Even in v3 of user dialogs, you are running this code in a really weird spot.  It does look like you are running this before anything is ready to render.

**Comment by davidtavarez** [comment]
I'm using Xamarin Forms. The code is inside a ContentPage.

**Comment by aritchie** [comment]
I'm guessing you're doing the call in the constructor of the contentpage then.  You can only show dialogs for onappearing.  The progress and toasts will not work until they have a fully loaded view to work with.

**Comment by davidtavarez** [comment]
Why is was working before 4.0?

**Comment by aritchie** [comment]
It wasn't.  Toasts didn't exist in 3.x.  Loading never would have worked from the constructor on the starting page.

**Comment by aritchie** [comment]
At least the new pretty toasts didn't exist.  They need a view to drive them.  You can't render view stuff from a constructor of a viewmodel because the view just isn't ready.  Use onappearing and all will be good

**Comment by davidtavarez** [comment]
Great, I'll reproduce the error on a gist.

**Comment by aritchie** [comment]
Why?  I'm only willing to help fix this IF you are making the calls at or after OnAppearing.  It isn't a bug otherwise.

**Comment by davidtavarez** [comment]
BTW, the code is inside a View displayed on a ContentPage and the Toast is called on a Click Event of a button.

You're still thinking that the call is inside the constructor :/

**Comment by aritchie** [comment]
Because you haven't told me otherwise and I haven't seen any code yet.

**Comment by aritchie** [comment]
I won't need the gist.  I just need what your navigation controller is (tabs, master detail, etc)

**Comment by aritchie** [comment]
Can you try 4.0.1 (on nuget) and let me know if that fixes things for you

**Comment by davidtavarez** [comment]
Thanks! Now it works. Just one last question. 

ErrorToast() and WarnToast() should display different icons?

![ios simulator screen shot aug 11 2015 2 09 15 pm](https://cloud.githubusercontent.com/assets/337107/9205887/b3b50c36-4032-11e5-863b-e97561190c74.png)
![ios simulator screen shot aug 11 2015 2 09 10 pm](https://cloud.githubusercontent.com/assets/337107/9205888/b3d35de4-4032-11e5-8adb-ac9d7e81f55d.png)

**Comment by aritchie** [comment]
I have sent 4.0.2 to deal with this as well.  Thanks for the help.

If you like the plugins, I'd appreciate an mvp vote with xamarin - https://xamarin.com/mvp

**Comment by davidtavarez** [comment]
Thanks. I just nominated aritchie as Xamarin MVP :)
