### ISSUE TITLE
iOS [Acr.UserDialogs] This is the bait library, not the platform library. You must install the nuget package in your main executable/application project

### ISSUE THREAD

**Issue by trilm208** [aritchie/userdialogs#450]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
Real device (iOS 11.1.1,iOS 11.1.2...)

## Version of ACR UserDialogs Library
7.0.0-beta2 (Xamarin Form .NET Standard 2.0)
(Acr.UserDialogs is installed both .NET Standard project and iOS project)
## Expected Behaviour
Launch application after splash screen on TestFlight devices( iOS simulators are fine)
## Actual Behavior
[Acr.UserDialogs] This is the bait library, not the platform library. You must install the nuget package in your main executable/application project

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This has been answered many times.  Please read the install instructions.

**Comment by Szymaniuk** [comment]
I have exactly the same issue, but it occured only within 7.0.0-beta2 version.
ACR.UserDialogs with all "linked" packages, are installed at PCL project, as well as Android and iOS projects. Till 6.5.1 it works fine, but it's throwing mentioned error at 7.0.0-beta2, only at iOS. Cleaning all bin/obj/packages folders, clearing whole solution, restarting and rebuilding didn't solves the issue.

**Comment by Szymaniuk** [comment]
Re-tested with 7.0.0-beta3 - issue fixed, everything works fine also at iOS.
Thanks
