### ISSUE TITLE
Login dialog username and password fields layout

### ISSUE THREAD

**Issue by vangras** [aritchie/userdialogs#455]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
4.4 to 6.0

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
Username and password fields aligned left and right with the title and message fields above and the bottons below. 

## Actual Behavior
The username and password fields have a very small left and right margin compared to the title and message fields and the bottons below. Not sure if it's desired or not.

**Comment by aritchie** [comment]
If you're looking to nitpick the UI, I would suggest not using this dialog at all.  This specific dialog is more for prototyping things
