### ISSUE TITLE
Determine if Loading Dialog is Running

### ISSUE THREAD

**Issue by aherrick** [aritchie/userdialogs#456]
Is there a way in code to determine if the Loading Dialog is running/up?

`UserDialogs.Instance.IsLoading` ?

**Comment by aritchie** [comment]
No - use:
var dispose = UserDialogs.Instance.Loading(...); 

you can control it yourself that way.

**Comment by aherrick** [comment]
Thanks! Would be nice to have a property hanging off Instance so I don't have to manage a local... but this will get me by.
