### ISSUE TITLE
Dialog customization

### ISSUE THREAD

**Issue by epazas** [aritchie/userdialogs#457]
This is a generic question regarding customization capabilities that userdialogs offer. I wonder whether there is a way to define colors, fonts and styling for userdialogs. The bet is to offer a look and feel that complies with the my application. Can you please elaborate?

**Comment by aritchie** [comment]
Please take a look at the source code before posting general questions like this in the future.  I usually only accept feature requests/defects.  

The main goal of this library is to provide the native dialogs without too much alteration.  The android dialogs (appcompat versions) do allow customization through the android themes.  However, iOS doesn't really allow you to play with these things and there are rumours that they will decline your app if you do so.

You can always inherit the user dialog implementation on iOS and override the methods you want to change
