### ISSUE TITLE
[iOS] ActionSheet position on iPad

### ISSUE THREAD

**Issue by Sebastian1989101** [aritchie/userdialogs#458]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
11.1, 11.2

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
Some way to control the positioning and the arrow direction of an ActionSheet.

## Actual Behavior
The ActionSheet is always displayed at the bottom with a down pointing arrow.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I have no way of knowing where to hook the dialog.  This library really wasn't meant for ipad.  It can function, but you need to pick your battles

**Comment by Sebastian1989101** [comment]
There is a PR on the Plugin.Share which solves the same issue. Maybe it is an option for the Arc.UserDialogs as well: https://github.com/jguertl/SharePlugin/pull/55
