### ISSUE TITLE
Need Android Progress without percentage

### ISSUE THREAD

**Issue by henrikweimenhog** [aritchie/userdialogs#459]
I like this nuget alot! I use it frequently! 
However, quite often I am unable to provide progress updates to the progress hud and so in Android it just sits at 0%. In iOS there is no percentage shown so no problem there.

I would love if there was a parameter for using the progress hud without the percentage albel being shown.

Thanks!
Keep up the great work!

**Comment by aritchie** [comment]
Use the Loading method
