### ISSUE TITLE
Allow for adding title and description to toasts.

### ISSUE THREAD

**Issue by highplains** [aritchie/userdialogs#46]
Please and thanks!

**Comment by aritchie** [comment]
The android snackbar implementation is holding me hostage on this.  I don't want to expose a title and description because I'll never display the title on droid. 

I'm open to ideas or PR's on how to deal with this

**Comment by aritchie** [comment]
This will be part of 4.0.3

**Comment by highplains** [comment]
Awesome, thanks!
