### ISSUE TITLE
Not show loading dialogs on xamarin.forms

### ISSUE THREAD

**Issue by mamcx** [aritchie/userdialogs#462]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue

Xamarin.iOS
Version: 11.6.1.2 (Visual Studio Community)

Xamarin.Android
Versión: 8.1.0.24 (Visual Studio Community)
Android SDK: /Users/mamcx/Library/Developer/Xamarin/android-sdk-macosx
	Versiones de Android admitidas:
		7.0 (nivel de API 24)
		7.1 (nivel de API 25)
		8.0 (nivel de API 26)

## Version of ACR UserDialogs Library

6.5.1

## Expected Behaviour

To show the dialogs

## Actual Behavior
I try to show the dlg while calling some external APIs. I put them inside a async handler.

Using https://github.com/EgorBo/Toasts.Forms.Plugin it show fine without any effort.

let makeLogin() =
...
....
        let doUpload() =
            let dlg = UserDialogs.Instance.Loading("Subiendo archivos..")
            showToast "Subiendo archivos.."
            DropBoxAPI.uploadFiles()
            |> ignore

        let doLogin x =
            if validateEmpty(login.toDict, labels) then
                use dlg = UserDialogs.Instance.Loading("Sincronizando...")
                showToast "Sincronizando..."
                UserDialogs.Instance.ShowLoading() <-- Is this necesary?

                let task = async {
                    let result = SyncApi.syncData(login.url, login.zone, login.user, login.pwd) 
                    match result with
                    |Some(msg) -> failwith msg
                    | None -> ()
                }

                task
                |> Async.Catch
                |> Async.RunSynchronously
                |> fun x -> 
                      match x with
                      | Choice1Of2 x ->
                        doUpload()
                        UserDialogs.Instance.HideLoading()
                        rootPage.Navigation.PopToRootAsync(true) |> ignore
                      | Choice2Of2 ex -> 
                          UserDialogs.Instance.HideLoading()
                          showMsgError(ex.Message)
            else
                ()

**Comment by aritchie** [comment]
Did you use Init?  If so, which one?  Are you calling this function from the constructor or did you attach to state somewhere?

**Comment by mamcx** [comment]
Yes, I have init. Other dialogs from the library work. Is not a constructor, is from a button...

**Comment by aritchie** [comment]
Ok listen - you can't just keep saying "it works", "this works", etc... if you want my help, you need to give me details.  

I asked for the Init call you're making.  Please provide that.

**Comment by mamcx** [comment]
This is:

```
type MainActivity() =
    inherit Xamarin.Forms.Platform.Android.FormsApplicationActivity()
    override this.OnCreate (bundle: Bundle) =
        startAppCenter()

        base.OnCreate (bundle)

        Acr.UserDialogs.UserDialogs.Init(this)

        Xamarin.Forms.DependencyService.Register<ToastNotification>(); // Register your dependency
        ToastNotification.Init(this)

        Xamarin.Forms.Forms.Init (this, bundle)
        this.LoadApplication (new Cobros.App ())
```

**Comment by aritchie** [comment]
Since you're using Xamarin Forms - try switching to UserDialogs.Init(() => (Activity)Forms.Context);

Also, check if you're getting any warnings in the console

**Comment by mamcx** [comment]
I don't see a relevant warning. From where I get  `(Activity)Forms.Context`? ie: From what import?

**Comment by mamcx** [comment]
Not luck with that.  I put this below `Xamarin.Forms.Forms.Init (this, bundle)` because before this line cause a null exception.

**Comment by aritchie** [comment]
It shouldn't cause an NRE if you're initing properly.  You pass a function to it with a callback, so UserDialogs.Init(() => (Activity)Forms.Context);  

Everytime you call for a dialog, it will call into that function to get the current context.  If you're getting an NRE, something is calling for the dialogs way too early in the cycle.

**Comment by krishnapt123** [comment]
> (Android.App.Activity)Xamarin.Forms.Forms.Context

Working for me
