### ISSUE TITLE
Toasts Aren't Async and the First Time a Toast is used it takes a long time on Android

### ISSUE THREAD

**Issue by mzhukovs** [aritchie/userdialogs#463]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [2X] Android
 - [X] UWP
 - [X] NET Standard 1.1

## Version of OS(s) listed above with issue
iOS emulator iPhone 8
UWP FCU
Physical device: Galaxy S7 API 24

## Version of ACR UserDialogs Library
latest stable

## Expected Behaviour
Toast is Async and appears under a second even on first call.

## Actual Behavior
Slow, hanging a couple of seconds
until toast shows for the first time. Is smooth thereafter though

**Comment by aritchie** [comment]
Toasts will never be async in the fact that you can "await" them.  They are a fire and forget operation.  I've never seen the render to the UI slow though.  Can you send a reproducible sample?
