### ISSUE TITLE
IToast interface is not available on the Net standard/PCL  project

### ISSUE THREAD

**Issue by pedramp20** [aritchie/userdialogs#466]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [X] NET Standard 1.1

## Version of OS(s) listed above with issue
NET Standard 1.6

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
Be able to convert (IDisposable) object of UserDialogs.Instance.Toast(config) to IToast in order to call Dismiss function to hide the toast in code. 
Or suggest any alternative way that a shown toast can be hidden by code prior to duration timeout or action button trigger.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
There is no IToast interface.  Dispose of the disposable - that is the dismiss
