### ISSUE TITLE
Toasts TextAlignment

### ISSUE THREAD

**Issue by soile1991** [aritchie/userdialogs#467]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [*] Android
 - [?] UWP
 - [?] NET Standard 1.1

## Version of OS(s) listed above with issue
iOS, Android

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
it would be nice we can change Toasts TextAlignment

## Actual Behavior
TextAlignment always left

**Comment by jfversluis** [comment]
Yes +1!

Also, the default text-alignment right now is too close to the left IMHO

**Comment by VahidShir** [comment]
Any news about the ability to set TextAlignment of a Toast?

**Comment by aritchie** [comment]
@VahidShir Counter questions for you
1) Do you see it in the code base?
2) The issue was closed over a year ago.  Do you see a commit against it?
3) Did you submit a PR for it?

Once you answer those questions, you should have your answer.  Please don't post in closed issues!
