### ISSUE TITLE
[UWP] MaskType.Black does not work

### ISSUE THREAD

**Issue by JKennedy24** [aritchie/userdialogs#470]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [x] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue
Fall Creators update

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
Using ShowLoading("Test", MaskType.Black) on UWP should show a dark popup box with a loading animation

## Actual Behavior
it actually shows a white popup with loading animation

**Comment by aritchie** [comment]
You are welcome to submit a patch for this.  I do absolutely zero work with Uwp at this point

**Comment by JKennedy24** [comment]
No longer required
