### ISSUE TITLE
Unable to install 7.0.0

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [aritchie/userdialogs#472]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [*] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
iOS - 11
Android - Oreo
Xamarin.Android.Support - 26.1.0.1

![image](https://user-images.githubusercontent.com/10863510/34996222-ef2f789e-fafe-11e7-8504-21197741278a.png)

## Version of ACR UserDialogs Library
7.0.0.0

## Expected Behaviour
Not able to install.

## Actual Behavior
Throwing OpenTK-1.0 error.

![image](https://user-images.githubusercontent.com/10863510/34996056-6333c5e8-fafe-11e7-94c6-76ddb996acb0.png)

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
In your iOS project, right click "References", then click "Add Reference", go to "Assemblies" tab and look in the list for OpenTK-1.0 to ensure it is there.

**Comment by sawankumarbundelkhandi** [comment]
It worked after restating the Visual Studio. Thanks
