### ISSUE TITLE
V7.0 Install Failing

### ISSUE THREAD

**Issue by wmcainsh** [aritchie/userdialogs#473]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [x] NET Standard 2.0

## Version of ACR UserDialogs Library
7.0

## Expected Behaviour
NuGet Plugin Installs

## Actual Behavior
NuGet Install fails with this message:
Failed to add reference. The package 'Acr.UserDialogs' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
What kind of project are you trying to install this into?

**Comment by wmcainsh** [comment]
Xamarin forms app. It was failing to install into the Android project but I managed to get it to work by installing into each project individually. Strange but it's resolved now.

**Comment by universaldata-eu** [comment]
same problem here.
vs 2017 community, Xamarin.Forms app, update from Acr.UserDialogs 6.5.1 -> 7.0.1
trying to install every project individually didn't help. Android project gets error message:

Failed to add reference. The package 'Acr.UserDialogs' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
  Reference unavailable.

any suggestions?

**Comment by TingtingAn** [comment]
I got same issue.   Did you solve it?  @universaldata-eu

**Comment by aritchie** [comment]
Read the entire output of the error message.  You will likely see something about an android support library version conflict.  The top level of the error message is misleading.

**Comment by universaldata-eu** [comment]
now i tried again with pakage manager and now there is another error message appearing before:
Package 'Acr.UserDialogs.7.0.1 : AndHUD [1.2.0, ), Xamarin.Android.Support.Design [26.1.0.1, )' does not exist in project '***.Droid'

AndHUD 1.2.0 is installed
but Xamarin.Android.Support.Design version 27.0.2.1 is installed. do i have to go back to 261.0.1?

**Comment by cvasquez-github** [comment]
Fix:
- Update Visual Studio to 15.8.0
- Right click in References -> Migrate packages.config to PackageReference...
- Then update Acr.UserDialogs to 7.0.1

**Comment by universaldata-eu** [comment]
this worked for me!
thank you very much.
