### ISSUE TITLE
ShowError/ShowSuccess and ShowImage gone in V7

### ISSUE THREAD

**Issue by Mr-Pearce** [aritchie/userdialogs#474]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [x] UWP
 - [x] NET Standard 2.0

## Version of ACR UserDialogs Library

7

## Expected Behaviour

ShowImage will be there.

## Actual Behavior
ShowImage is gone.

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

In Version 6.5.1 ShowError() and ShowSuccess() said to use ShowImage because they will be gone in the next version.

Now in Version 7 ShowImage() is also gone. What is the alternative now?

**Comment by aritchie** [comment]
There isn’t one.  I don’t want to support that functionality any longer.  If you still need it, use 6.5.1

**Comment by themronion** [comment]
@aritchie so the only possible solution if a want these dialogs is to downgrade or create a custom one?
