### ISSUE TITLE
Error installing nuget Profile111

### ISSUE THREAD

**Issue by x4vl** [aritchie/userdialogs#476]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
iOS 11.2

## Version of ACR UserDialogs Library
7.0.0

## Actual Behavior
Could not install package 'Acr.UserDialogs 7.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This is a .NET standard 2 library, not PCL

**Comment by x4vl** [comment]
Sorry for my question but is then not possible to use it with xamarin forms anymore? If I choose .Net standard instead of PCL I can only choose `netstandard1.5` as newer library.

**Comment by aritchie** [comment]
You can use .NET standard 2.0 with xamarin forms.  The latest templates in VS2017 have it.
