### ISSUE TITLE
[Feature Request] Make Toast dismissal optional after action

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [aritchie/userdialogs#477]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [YES] iOS
 - [YES] Android 
 - [] UWP - Not tested
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Android- 4.4+ 
Support Library - 25
iOS - 10+

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
If you have a toast with a ToastAction attached to it, the toast is dismissed after you hit the button to do the action.

In the code you have

```
cfg.Action?.Action?.Invoke();
snackBar.Dismiss();
```

so this seems to be by design, but it shouldn't auto dismiss. In my use case I have a toast come up when the user doesn't have a wifi/cellular connection, the toast action brings them to the settings app, if they don't connect to wifi/enable cellular, then the toast shouldn't get dismissed. The fix is simple, I had to override the Toast function, copy your code, and just remove that dismiss line. But by default the toast shouldn't auto dismiss - if the developer wants to dismiss it, it's easier to just add the toast dismissal to the Toast Action, than to have to override and copy the whole toast display code. Maybe add a flag in the toast config instead?

## Actual Behavior
Toast is dismissed after the toast action is taken.

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by Paul-Brenner-Tangoe** [comment]
For Android, it looks like the snack bar auto dismisses it after the action is taken. So to make it not dismiss you have to set a dummy action so that action button shows, and then override the button's click to not include the dismissal.

```
snackBar.SetAction(cfg.Action.Text, x =>
{
// just to make button appear
});
```

`snackBar.Show();`

```
var actionButton = snackBar.View.FindViewById(Resource.Id.snackbar_action);
actionButton.Click += (ea, se) =>
{
cfg.Action?.Action?.Invoke();
};
```

**Comment by aritchie** [comment]
I thought about this, but I’m afraid this isn’t something I want in the library for several reasons:

1. It would be the only dialog with a button that doesn’t dismiss

2. I believe this functionality is better served by a view if you require static content that hangs around.  A toast is a fire and forget thing. 

3. It introduces an unnecessary complexity where you have to hack out the natural usage in things like android (as you identified)
