### ISSUE TITLE
iOS loader shifts up after opening the keyboard

### ISSUE THREAD

**Issue by etiennestrydom** [aritchie/userdialogs#478]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)

iOS Not linked to a specific version.

## Version of ACR UserDialogs Library

6.5.1

## Expected Behaviour

The loader stays centred on the page even after opening the iOS keyboard

## Actual Behaviour
_If applicable, please include entire exception - type, message, stacktrace_

The loader moves closer to the top of the page and stays there if iOS keyboard is opened, please see the images in the following link for a visual example of the problem:

https://drive.google.com/open?id=1hOERL1-5Y-V5JD-EoqTAcqT8YEZyMieJ

**Comment by aritchie** [comment]
This is actually by design.  The loader is designed to block all UI interactions

**Comment by etiennestrydom** [comment]
Hi Allan,

I know this loader blocks user interaction by design and that is exactly why I’m using it. The problem I have though is the first time I activate the loader the loader is entered in the middle of the screen. When I open the iOS keyboard and type something in an entry box, then close the keyboard, the loader appears more to the top of the screen every time it’s activated. That’s why I think something shifts it up? This behaviour will persist until I restart my app.

Kind regards,
Etienne.

On 22 Jan 2018, at 23:34, Allan Ritchie <notifications@github.com<mailto:notifications@github.com>> wrote:


This is actually by design. The loader is designed to block all UI interactions
