### ISSUE TITLE
The new Log class breaks build of a huge project

### ISSUE THREAD

**Issue by duzenko** [aritchie/userdialogs#479]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] NET Standard 2.0

## Version of ACR UserDialogs Library
7.0

## Expected Behaviour
Project builds

## Actual Behavior
Hundreds of compile errors:
'Log' is an ambiguous reference between 'xxx.Portable.Utilities.Log' and 'Acr.UserDialogs.Log'

Please consider that 'Log' identifier is commonly used and of course everyone already has some kind of Log in their projects. Simply adding it out of the blue breaks builds with a ton of work to do to clean this mess.

**Comment by aritchie** [comment]
I don't appreciate the tone of this issue.  I can add whatever I want to this library whenever I want.  If you're going to come here with an entitled attitude, just don't come at all please. 

I try not to break anything on anyone, but I certainly don't know every project structure out there and I'm happy to change it for respectful requests.

**Comment by duzenko** [comment]
Can I ask what the Log class is supposed to achieve in the UserDialogs package?

**Comment by aritchie** [comment]
I intend to use it going forward for support requests.

**Comment by duzenko** [comment]
What would you recommend for code like
```
using MyOwnLog;
using Acr.UserDialogs;
...
Log.Error( ... );
```
?

I work around with 
`using Log = SmartwebsCrossPlatform.Portable.Utilities.Log;`
But I have to do it in every single source file.


Log.DoS

**Comment by aritchie** [comment]
You seriously think I want to help you at this point?  I saw the Log.DoS shit too.  No one said you have to upgrade... so go back to what worked for you.
