### ISSUE TITLE
[UWP] Esc/enter keys accept or dismiss dialog

### ISSUE THREAD

**Issue by velocitysystems** [aritchie/userdialogs#480]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [*] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
N/A.

## Version of ACR UserDialogs Library
Latest.

## Expected Behaviour
Can keyboard events be added for **Enter** and **Esc** keys on UWP?
ie. For Prompt, Login controls:
- **Enter** key accepts prompt.
- **Esc** key dismisses prompt.

## Actual Behavior
Not currently implemented.
We would be happy to implement and submit a PR.

**Comment by aritchie** [comment]
PR on this would be great :)

**Comment by StephanBaltzer** [comment]
Would like to see this too

**Comment by 1Cor125** [comment]
So @aritchie I am about to start work on this and I hope to put up a PR soon. Would you be in favor of setting up a keyboard event handler in each method where it makes sense in UWP.UserDialogsImpl and then adding/removing the event handler in the Dispatch and Dispose action params? This way we keep the listener very localized and avoid global listeners that could live on beyond the lifetime of the dialog? So using Login as an example, something like this: 
`        public override IDisposable Login(LoginConfig config)
        {
            var vm = new LoginViewModel
            {
                LoginText = config.OkText,
                Title = config.Title ?? String.Empty,
                Message = config.Message ?? String.Empty,
                UserName = config.LoginValue,
                UserNamePlaceholder = config.LoginPlaceholder,
                PasswordPlaceholder = config.PasswordPlaceholder,
                CancelText = config.CancelText
            };
            vm.Login = new Command(() =>
                config.OnAction?.Invoke(new LoginResult(true, vm.UserName, vm.Password))
            );
            vm.Cancel = new Command(() =>
                config.OnAction?.Invoke(new LoginResult(false, vm.UserName, vm.Password))
            );
            var dlg = new LoginContentDialog
            {
                DataContext = vm
            };

            void onKeyDown(CoreWindow s, KeyEventArgs e)
            {
                var keyboardKey = e.VirtualKey;
                if (keyboardKey == VirtualKey.Enter)
                {
                    vm.Login.Execute(null);
                }
                else if (keyboardKey == VirtualKey.Escape)
                {
                    vm.Cancel.Execute(null);
                }
            }

            return this.DispatchAndDispose(
                () =>
                {
                    Window.Current.CoreWindow.KeyDown += onKeyDown;
                    dlg.ShowAsync();
                },
                () =>
                {
                    dlg.Hide();
                    Window.Current.CoreWindow.KeyDown -= onKeyDown;
                }
            );
        }`

Let me know. Thanks.

**Comment by aritchie** [comment]
That works.  There should be an option to control whether enter/esc keys are active in each config.

UwpCancelEscKey (boolean)
UwpActionEnterKey (boolean)

or something to that effect.

**Comment by 1Cor125** [comment]
Hi @aritchie. Sorry for the delay. I am back on this now. I notice you have done some work on this ticket against master. What is left? What can I do to help?

**Comment by 1Cor125** [comment]
@aritchie I think my work is ready but I am getting a method not found on UserDialogs.Instance trying to run the UWP Samples app.

**Comment by 1Cor125** [comment]
Hi @aritchie. Any feedback on PR #513? We are a couple weeks away from shipping the latest version of our product and would like to see if this could get in before that.

**Comment by mattrichnz** [comment]
Would really love to see this in the next release of the package, really useful and needed!
