### ISSUE TITLE
Error message 'Java.Interop' not found in the GAC when updating NuGet package

### ISSUE THREAD

**Issue by cbs-cbt** [aritchie/userdialogs#481]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - iOS
 - [x] Android
 - UWP
 - NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Error is before to run software
Xamarin.Android.Support.* v26.1.0.1
## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
No error message when updating package from NuGet manager in Visual Studio 2017.

## Actual Behavior
Updating NuGet package in Visual Studio 2017 from 6.5.1 to 7.0.1 in a Xamarin.Forms project.

All platforms are updated, except Android. Here is the complete NuGet message:

```
Attempting to gather dependency information for package 'Acr.UserDialogs.7.0.1' with respect to project 'PicusGeneric.Android', targeting 'MonoAndroid,Version=v8.0'
Gathering dependency information took 10.51 sec
Attempting to resolve dependencies for package 'Acr.UserDialogs.7.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Acr.UserDialogs.7.0.1'
Resolved actions to install package 'Acr.UserDialogs.7.0.1'
Found package 'Acr.UserDialogs 7.0.1' in 'C:\Users\Gasser\Desktop\PicusGenericXAM\packages'.
Removed package 'Acr.UserDialogs.6.5.1' from 'packages.config'
Successfully uninstalled 'Acr.UserDialogs.6.5.1' from PicusGeneric.Android
Package 'Acr.UserDialogs.7.0.1' already exists in folder 'C:\Users\Gasser\Desktop\PicusGenericXAM\packages'
Install failed. Rolling back...
Package 'Acr.UserDialogs.7.0.1 : AndHUD [1.2.0, ), Xamarin.Android.Support.Design [26.1.0.1, )' does not exist in project 'PicusGeneric.Android'
Package 'Acr.UserDialogs.6.5.1' already exists in folder 'C:\Users\Gasser\Desktop\PicusGenericXAM\packages'
Added package 'Acr.UserDialogs.6.5.1' to 'packages.config'
Executing nuget actions took 20.32 sec
Failed to add reference. The package 'Acr.UserDialogs' tried to add a framework reference to 'Java.Interop' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
  Reference unavailable.
Time Elapsed: 00:00:31.0550733
========== Finished ==========

```

**Comment by aritchie** [comment]
Switch to the new SDK style project <PackageReference> instead of packages.config.  It should get rid of this problem

**Comment by cbs-cbt** [comment]
Hello Ritchie,
Thank you for the support. Migrating to the new SDK style did the trick.

Greetings

J-D

**Comment by cbs-cbt** [comment]
Hello Ritchie,
Thank you for the support. Migrating to the new SDK style did the trick.

Greetings

J-D

**Comment by ebicoglu** [comment]
I'm getting the same error. Could you clarify exactly what should we do about switching to new SDK style?

**Comment by aritchie** [comment]
@ebicoglu I don't have documentation on it.  You'll need to google for that.  You can also use tools like this: https://marketplace.visualstudio.com/items?itemName=TaylorSouthwickMSFT.NuGetPackagetoProjectjsonConverter

Basically, packages.config exists inside the csproj file itself.
