### ISSUE TITLE
[iOS] Toast problem position top (Status bar text)

### ISSUE THREAD

**Issue by vallgrenerik** [aritchie/userdialogs#482]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
iOS 11.2

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
The toast to appear underneath Status bar text (Clock, signal and so on.)

## Actual Behavior
![capture](https://user-images.githubusercontent.com/26163937/35394987-6962ff0a-01e9-11e8-8d81-023bb3b7aa51.PNG)
(Sorry for the Swedish text in the app, I hope you understand the problem :) )

**Comment by vallgrenerik** [comment]
@aritchie Any feedback on this?

**Comment by aritchie** [comment]
When I have time I’ll look.  If you aren’t going to contribute then you need to be patient.  Please don’t bump posts in the future

**Comment by vallgrenerik** [comment]
@aritchie Thanks! :)

**Comment by aritchie** [comment]
@amalwankar timeline requests are not welcome here AT ALL!  Fix it yourself if you want updates.  I don't have a need for this on any of my projects right now, so I won't be fixing it until I do
