### ISSUE TITLE
Prompt doesn't work on Android

### ISSUE THREAD

**Issue by Captain97r** [aritchie/userdialogs#487]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

- Android

## Version of OS(s) listed above with issue

Android 5.0; 
Xamarin.Android.Support.v4

## Version of ACR UserDialogs Library

7.0.1

## Expected Behaviour

I'm using usual
UserDialogs.Instance.Prompt(new PromptConfig());
that should display usual dialog.

## Actual Behavior

I'm getting this:

Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

And this in stack trace:

JNIEnv.FindClass(Type) caught unexpected exception: Java.Lang.ClassNotFoundException: md55e799df28708ec485b59c5dc6920154a.PromptAppCompatDialogFragment ---> Java.Lang.ClassNotFoundException: Didn't find class "md55e799df28708ec485b59c5dc6920154a.PromptAppCompatDialogFragment" on path: DexPathList[[zip file "/data/app/com.companyname.App5-1/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.App5-1/lib/arm, /vendor/lib, /system/lib]]

**Comment by aritchie** [comment]
It’s a Xamarin bug.  Clean/rebuild - if that doesn’t work, close vs - delete bin/obj - restart vs and compile
