### ISSUE TITLE
NUget can't update the package

### ISSUE THREAD

**Issue by jwidht** [aritchie/userdialogs#488]
Could not install package 'Acr.UserDialogs 7.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile44', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Tried multiple platforms. The original (where nuget updates used to work) was "PCL 4.5 - Profile78"
But tried stripping everything except IOS and Android and still the same message upon the nuget update. I have plenty of packages in the PCL project, and the problem only occurs with two.
Acr.UserDialog and Splat.

 Investogating the forums, but , I think, you might be interested to know that the package is causing issues unlike some other packages.

Have a good one

**Comment by aritchie** [comment]
This package isn't causing any issues.  It uses .net standard 2, not PCL.  This has been stated many times.

**Comment by jwidht** [comment]
For those who might experience a similar issue: As a short term working solution, I downgraded Acr.UserDialogs to 6.5.1
Switching to .NET Standard yielded in a lot of error messages from other packages which don't support it yet.

**Comment by Vijay-Patole** [comment]
> For those who might experience a similar issue: As a short term working solution, I downgraded Acr.UserDialogs to 6.5.1
> Switching to .NET Standard yielded in a lot of error messages from other packages which don't support it yet.

This helped me.. Thanks
