### ISSUE TITLE
FAQ #4 is out of date - Acr.UserDialogs.UserDialogImpl not present in repository

### ISSUE THREAD

**Issue by borbmizzet** [aritchie/userdialogs#489]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [*] NET Standard 2.0

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
Please update Question #4 on the FAQ.  Acr.UserDialogs.UserDialogImpl does not exist in the repository.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I don't take requests for docs.  You see an issue, please submit a PR.  As it is, the implementation does exist on the platform level (iOS, Android, etc), not the .NET Standard level.  You can also just implement IUserDialogs, but that is quite large.
