### ISSUE TITLE
Splat reference error

### ISSUE THREAD

**Issue by ronpf** [aritchie/userdialogs#49]
Getting android release build error (After re-installation of 4.0.2):

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : Error executing task LinkAssemblies: error XA2006: Reference to metadata item 'Android.Graphics.Color Splat.ColorExtensions::ToNative(System.Drawing.Color)' (defined in 'Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') from 'Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved.

**Comment by aritchie** [comment]
Make sure you set android to latest android build target

**Comment by ronpf** [comment]
That was set. Release mode not building to real device or sim.
Debug builds fine (with warning)
I see the Splat reference in my iOS project but not my droid project
