### ISSUE TITLE
iOS Dialogs are not display after click outside Action sheet 

### ISSUE THREAD

**Issue by Thetyne** [aritchie/userdialogs#490]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
iOS simulator 11.2

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
Second dialog displaying after click outside first dialog.

## Actual Behavior

If i run this code and i select an element in actionsheet, it work.
But if i cancel by click outside action sheet view, the second dialog is never display.
the second dialog async task is blocked by internal exception and i can't use other dialog with your plugin. (it block also my mvvm async command because task is keep by exception).

output log:

> Warning: Attempt to present <UIAlertController: 0x7ff69a800000> on <UIAlertController: 0x7ff699bace00> whose view is not in the window hierarchy!

Code:
` var result  = await UserDialog.ActionSheetAsync("title", "Cancel", null, null, boutonArray);
await UserDialog.AlertAsync("my text", "title", "Valid");`

**Comment by aritchie** [comment]
Not much I can do about this due to the way I have to detect the top view controller.  You can add a pause between the action sheet and the alert to allow the action sheet to disappear.

**Comment by Thetyne** [comment]
Ok, i had a tempo (async Task.Delay(500)) and it work.
Thanks for your reply.
