### ISSUE TITLE
[IOS] The Loading is always above the QuickLook view.

### ISSUE THREAD

**Issue by Raystorm7** [aritchie/userdialogs#491]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
11.2

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
The loading should be below the QuickLook view.

## Actual Behavior
The loading is above the QuickLook view.

![](https://i.imgur.com/4ubTE5d.gif)

**Comment by aritchie** [comment]
This is due to the way I detect the top window/viewcontroller and the simple fact is that I can’t deal with all cases.  You can use UserDialogs.Init(pass function to your viewcontroller) and set it in each viewwillappear/viewdidload.

**Comment by Raystorm7** [comment]
Where I need to use UserDialogs.Init(pass function to your viewcontroller)?
Can you provide a simple code, please?

**Comment by sathishkumar1624** [comment]
Did you found any sample code for this issue

**Comment by bastianbecker21** [comment]
Why was this closed? I need to get the solution for this issue.
@aritchie Please provide the solution how to fix it in pcl for xamarin forms. Thanks

**Comment by aritchie** [comment]
Guys - I've already stated the answer.  You can init with the viewcontroller you want to be to the "top" using UserDialogs.Init(this) within the viewcontroller viewwillappear

@bastianbecker21 I can close any defect I feel has been answered.  If you need a solution, the source code is all here.
