### ISSUE TITLE
[IOS] The Loading change its position after the first showing

### ISSUE THREAD

**Issue by Raystorm7** [aritchie/userdialogs#492]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
11.2

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
The loading should be always in the center of the screen.

## Actual Behavior
The first time the loading is in the correct position.
After it is shown other times, it remains closer to the upper edge.

**First time:**
![](https://i.imgur.com/1V4F5MN.jpg)

**After the first:**
![](https://i.imgur.com/HbYQQRX.jpg)

**Comment by aritchie** [comment]
This is related to your first post in #491 so I’m closing this
