### ISSUE TITLE
Could not add Acra.UserDialogs

### ISSUE THREAD

**Issue by gravitpt** [aritchie/userdialogs#493]
Hi, iIt is not possible to install de UserDialogs in my project (Xamarin forms), below the message: 

Attempting to gather dependency information for package 'Acr.UserDialogs.7.0.1' with respect to project 'MotoExpressApp', targeting '.NETPortable,Version=v4.5,Profile=Profile111'
  GET https://api.nuget.org/v3/registration3-gz-semver2/acr.userdialogs/index.json
  OK https://api.nuget.org/v3/registration3-gz-semver2/acr.userdialogs/index.json 998ms
Total number of results gathered : 4
Gathering dependency information took 1,04 sec
Summary of time taken to gather dependencies per source :
https://api.nuget.org/v3/index.json	-	1,03 sec
Attempting to resolve dependencies for package 'Acr.UserDialogs.7.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Acr.UserDialogs.7.0.1'
Resolved actions to install package 'Acr.UserDialogs.7.0.1'
Retrieving package 'Acr.UserDialogs 7.0.1' from 'nuget.org'.
For adding package 'Acr.UserDialogs.7.0.1' to project 'MotoExpressApp' that targets 'portable45-net45+win8+wpa81'.
Install failed. Rolling back...
Package 'Acr.UserDialogs.7.0.1' does not exist in project 'MotoExpressApp'
Package 'Acr.UserDialogs.7.0.1' does not exist in folder '/Users/claudioramosdesouza/GDrive/Projects/MotoExpressApp/packages'
Executing nuget actions took 33,74 ms
Could not install package 'Acr.UserDialogs 7.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)**
 - [X] iOS
 - [X] Android
 - [] UWP
 - [] NET Standard 2.0

**## Version of ACR UserDialogs Library**
7.01

**Comment by aritchie** [comment]
This has been answered many times already.  I do not support PCL.  This library is .netstandard based
