### ISSUE TITLE
UWP Kiosk mode (assigned apps) not working

### ISSUE THREAD

**Issue by csciallano** [aritchie/userdialogs#494]
Hi,
i just tried to integrate Acr.UserDialogs in a Xamarin (UWP netstandard 2.0) application who has to be configured through the kiosk mode (assigned apps)
[create-a-kiosk-app-for-assigned-access](https://docs.microsoft.com/fr-fr/windows-hardware/drivers/partnerapps/create-a-kiosk-app-for-assigned-access)

Windows version 1709 (16299.192)

This mode is used to let only a single app running on a machine.

I couldn't get it to work with Acr.UserDialogs because I'am getting exceptions. For example with ProgressDialog.Show.
> DialogService.ShowLoading
System.Runtime.InteropServices.COMException (0x8000001F): A COM call to an ASTA was blocked because the call chain originated in or passed through another ASTA. This call pattern is deadlock-prone and disallowed by apartment call control.

> A COM call (IID: {638BB2DB-451D-4661-B099-414F34FFB9F1}, method index: 6) to an ASTA (thread 8272) was blocked because the call chain originated in or passed through another ASTA (thread 3396). This call pattern is deadlock-prone and disallowed by apartment call control.
   at Windows.ApplicationModel.Core.CoreApplicationView.get_CoreWindow()
   at Acr.UserDialogs.ProgressDialog.Dispatch(Action action)
   at Acr.UserDialogs.ProgressDialog.Show()
   at Acr.UserDialogs.AbstractUserDialogs.Progress(ProgressDialogConfig config)
   at Acr.UserDialogs.AbstractUserDialogs.Loading(String title, Action onCancel, String cancelText, Boolean show, Nullable`1 maskType)
   at Acr.UserDialogs.AbstractUserDialogs.ShowLoading(String title, Nullable`1 maskType)
   at LockerApp.Helpers.DialogService.ShowLoading(String thestrMessage)

I looked the code of ProgressDialog and in the Dispatch method, the CoreApplication.MainView.CoreWindow.Dispatcher is used.

BUT, if i refer to the above link from microsoft, i can read that :

> The usage of CoreApplication.MainView.Dispatcher would cause the app crash in this example because in assigned access mode, the main window is not MainView but rendered in a secondary view. It is recommended you use CoreApplication.GetCurrentView.Dispatcher.

The only way by code to know if we are running under assigned access is : UWP App.xaml.cs
```
protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
            Frame rootFrame = Window.Current.Content as Frame;

            try
            {
                IsAssignedAccess = LockApplicationHost.GetForCurrentView() != null;
            }
            catch
            {
                IsAssignedAccess = false;
            }
```

Do you think we could adapt the different classes using the dispatcher to choose the right one according to the running mode? (i could write a pull request if you want)

Thank you very much for your work
Clément

**Comment by aritchie** [comment]
This will be built into the default dispatching mechanism as well with support for custom controlling the dispatching function as part of 7.0.2
