### ISSUE TITLE
NullPointerException in Release 

### ISSUE THREAD

**Issue by bastianbecker21** [aritchie/userdialogs#495]
- [] Android
Xamarin.Forms 2.5.0.280555
Xamarin.Android 8.2.0.15 
Xamarin.Android.Support.* 26.1.0.1
ACR UserDialogs 6.5.1

## Expected Behaviour
Show normal dialog by calling this line
`UserDialogs.Instance.Alert(message, title, "OK");
`
## Actual Behavior
When the app is running in debug mode, it works good
When the app is running in release mode, the app crashes

```
FATAL EXCEPTION: main
[AndroidRuntime] Process: com.ibase.mtwpublicapp, PID: 13820
[AndroidRuntime] java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.setVisibility(int)' on a null object reference
[AndroidRuntime] 	at android.support.v7.app.AlertController.setupCustomContent(AlertController.java:657)
[AndroidRuntime] 	at android.support.v7.app.AlertController.setupView(AlertController.java:464)
[AndroidRuntime] 	at android.support.v7.app.AlertController.installContent(AlertController.java:227)
[AndroidRuntime] 	at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:260)
[AndroidRuntime] 	at android.app.Dialog.dispatchOnCreate(Dialog.java:425)
[AndroidRuntime] 	at android.app.Dialog.show(Dialog.java:309)
[AndroidRuntime] 	at android.support.v4.app.DialogFragment.onStart(DialogFragment.java:416)
[AndroidRuntime] 	at android.support.v4.app.Fragment.performStart(Fragment.java:2380)
[AndroidRuntime] 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1458)
[AndroidRuntime] 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
[AndroidRuntime] 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
[AndroidRuntime] 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
[AndroidRuntime] 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
[AndroidRuntime] 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
[AndroidRuntime] 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
[AndroidRuntime] 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
[AndroidRuntime] 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:743)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:150)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:5546)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```

**Comment by aritchie** [comment]
I'm not really sure what's going on here and you haven't given me any code to help diagnose this.  How did you initial this?  Where are you calling this from - a user action?

**Comment by aritchie** [comment]
no feedback

**Comment by GalaxiaGuy** [comment]
I just started getting this same problem, although for me running it in DEBUG did not help.

Xamarin.Forms 2.5.1.340284
Xamarin.Android.Support.* 26.0.2
ACR UserDialogs 6.5.1

For me, calls to `ConfirmAsync` and `ActionSheetAsync` trigger it. `Progress` does not. I don't really have anything more useful to add right now, but it has only just started happening so I'm hoping to narrow down what changed.

**Comment by GalaxiaGuy** [comment]
Actually, it seems I only get it in DEBUG, and not in RELEASE at all.

**Comment by aritchie** [comment]
You need to add additional details if you want me to help!!  

How are you calling Init?
Where are yo calling for the dialog in your code?
Reproducible sample?

You have likely updated the support libraries and the build config hasn’t updated properly

**Comment by GalaxiaGuy** [comment]
Apologies. I didn't intend that to be enough information to actually solve the problem.

I suspect there is no issue with the library, but instead a problem with caching some build elements as I switch between branches. The builds of my produced by my CI server do not have the issue (nor do the ones after deleting the repository and pulling clean).

**Comment by vaindil** [comment]
I had this problem just now, @GalaxiaGuy's comment hinted at the solution. I did a full clean/rebuild of my solution and everything worked afterward.
