### ISSUE TITLE
iOS loading overlays Alerts and actionsheets

### ISSUE THREAD

**Issue by IeuanWalker** [aritchie/userdialogs#497]
OS: iOS 11.2.6
Nuget: v7.0.1

On iOS the loading overlay stays on top of Alerts and action sheets. This doesn't happen on Android so just wondering if this is a bug or if I'm doing something wrong.

Here is a basic version of my code - 

```csharp
try
{
    UserDialogs.Instance.ShowLoading();

    // Check if the user has search anything
    if (string.IsNullOrEmpty(userSearch))
    {
        await UserDialogs.Instance.Alert(
            AppResources.DisplayMessageEmptySearchBody,
            AppResources.DisplayMessageEmptySearch,
            AppResources.BtnOk);
        return null;
    }
   // return users selected address
}
catch (NullReferenceException ex)
{
    await UserDialogs.Instance.AlertAsync(
        AppResources.DisplayMessageNoConnectionBody,
        AppResources.DisplayMessageNoConnection,
        AppResources.BtnOk);
    Debug.WriteLine(ex);
}
catch (WebException ex)
{
    // No Internet Connect
    await UserDialogs.Instance.AlertAsync(
        AppResources.DisplayMessageNoConnectionBody,
        AppResources.DisplayMessageNoConnection,
        AppResources.BtnOk);

    Debug.WriteLine(ex);
}
catch (FormatException ex)
{
    // 400 bad request
    Debug.WriteLine(ex);
}
catch (HttpRequestException ex)
{
    // 403 Forbidden / 401 Unauthorized
    Debug.WriteLine(ex);
}
catch (Exception ex)
{
    // Any other error
    Debug.WriteLine(ex);
}
finally
{
    UserDialogs.Instance.HideLoading();
}
```

Basically, any of the alerts that pop up are behind the loading overlay, meaning I cant click ok on the alert and the loading overlay doesn't disappear (Works fine on Android).

## Expected Behaviour
Alerts on top, loading overlay disappear

## Actual Behavior
alerts are behind the loading overlay, and loading overlay doesn't disappear

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
You don't close the progress dialog before displaying the alert.  The finally block will fire after you display the alert.  Also, it isn't a great idea to do quick overlapping on iOS.  It will often create other issues where you will have to leave a Task.Delay between overlays.

**Comment by IeuanWalker** [comment]
@aritchie so if I put `UserDialogs.Instance.HideLoading();` before using any other type of alert it will be ok?

**Comment by aritchie** [comment]
why don't you try it :)

**Comment by IeuanWalker** [comment]
Thanks @aritchie, the only issue have with it now is there is quite a bit of delay waiting for the Action sheet to appear. 

Basically, its an address search part and if the user enters something really specific if can return 1 result but with the search is really broad you can get 1000+ results, which adds quite a delay for the Actionsheet to appear.

So do you have any suggestion on how to hide the loading once the action sheet is ready? or any other suggestions.

```csharp
UserDialogs.Instance.HideLoading();

selectedAddress = await UserDialogs.Instance.ActionSheetAsync(
    AppResources.DisplayActionSheetSelectAddress,
    AppResources.BtnCancel,
    null,
    null,
    addressList);
```

**Comment by aritchie** [comment]
No idea - I wouldn't do it like this.  Actionsheet is mainly for quick picks.

**Comment by IeuanWalker** [comment]
@aritchie  Ah ok thanks, how would you normally display something like this?

**Comment by aritchie** [comment]
on a page - with a listview

**Comment by IeuanWalker** [comment]
Ye i did that before but my manages and other people around the organisation, really didn't like that approach.
