### ISSUE TITLE
[Android] Top positioned toast placement

### ISSUE THREAD

**Issue by Nixon-Joseph** [aritchie/userdialogs#499]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Android 7.1 and 8.1 - Support.v4

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
Maybe slide down from the top, and rest just under the notification bar?

## Actual Behavior
Slides up from about 3/4 up the screen to about 7/8 up the screen. Looks really weird.

Happy to provide more information if you need more.

Screenshot
![image](https://user-images.githubusercontent.com/10250222/37493778-2450dfde-2874-11e8-953b-7b6ced74cbf1.png)

**Comment by wojtczakmat** [comment]
It looks like top toast sets its margin to 80, because according to Material status bar has height of 24dp + toolbar has height of 56dp = 80dp. It looks like on this device these values are different than this.

**Comment by joanbarros** [comment]
I assume this was never fixed. But if so why was it closed?

**Comment by aritchie** [comment]
I close stale issues where I don’t plan on resolving myself

**Comment by joanbarros** [comment]
Ohh, I see. I may try to solve this then. I'm currently having the issue and need to find a resolution for it.

Thnx. 👍
