### ISSUE TITLE
adding ACR.UserDialogs v 3.0.3 breaks Windows phone project 

### ISSUE THREAD

**Issue by supreettare** [aritchie/userdialogs#5]
Hello, 
If I add the above nuget package to my Xamarin Forms project (1.3.5 pre-release) it breaks the build on Windows Phone project with an error "An exception of type 'MS.Internal.WrappedException' occurred in System.Windows.ni.dll but was not handled in user code". 
As a workaround, if I uninstall the Xamarin Forms & then reinstall it, the above error is gone & WP project builds & works fine. 
Now if i use a simple code to open a prompt like below in PCL 

var result = await UserDialogs.Instance.PromptAsync("enter a label name and click apply", "apply label", "Apply", "Cancel", "enter label name", InputType.Default);

I get an error when I run the app in Windows phone emulator. Below is the error that I get. 
"An exception of type 'System.MissingMethodException' occurred in Acr.UserDialogs.DLL but was not handled in user code
Additional information: Method not found: 'Void Microsoft.Phone.Controls.PhoneTextBox.set_PlaceholderText(System.String)'."

Is this an issue with Acr library or the Toolkit.Kinnara library on which ACR has a dependency on? I will really appreciate if you can look into this when you have some free time. 

Thanks again for your time. 
Regards
Supreet

**Comment by aritchie** [comment]
Try the latest release

**Comment by supreettare** [comment]
I will. Thanks for the update.

**Comment by supreettare** [comment]
It worked. Thank you very much for your help. Appreciate it :)
