### ISSUE TITLE
Toast message text not vertically align to center against the icon.

### ISSUE THREAD

**Issue by edimaulana** [aritchie/userdialogs#503]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Xamarin.Android.Support.v4
Xamarin.Android.Support.v7.AppCompat

## Version of ACR UserDialogs Library
v7.0.1

## Expected Behaviour
Message text should vertically align to center against the icon.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
Message text is vertically align to bottom against the icon.

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Nope - that is exactly how they should behave.
