### ISSUE TITLE
How to override platform specific implementation

### ISSUE THREAD

**Issue by KorbinianMossandl** [aritchie/userdialogs#505]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
all

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
possibility to override implementation like stated in FAQ

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
when trying to actually use my custom implementation with
UserDialogs.Instance = new MyCustomUserDialogs();
I get the following error
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'getTopActivity' of 'MyCustomUserDialogs.MyCustomUserDialogs(Func<Activity>)'
 
could you please give a more detailed explanation in your FAQ? Thanks!

on a side note: I am trying to add more than one line of text input to a prompt.
Maybe that would be a welcome addition to the nuget?

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Works fine for me.  Not sure where your error is coming from?  Compiler?  I'm not sure what else I can add to the FAQ since setting it with a custom version of the interface is C# 101~!?

As for the addition request, not interested in complicating that dialog any further.  Thanks.

**Comment by KorbinianMossandl** [comment]
Thanks for the very quick reply!

I don't want to annoy you, but did you actually try it after reading my post?
I did try once more in an empty project with a fresh visual studio installation and am still getting the same error.
Maybe it used to work once but not anymore after a recent update?

There is also a typo in the FAQ:
"on the platform public class MyCustomUserDialogs : Acr.UserDialogs.UserDialogImpl { public override .. }"
there is an "s" missing in "UserDialogImpl". That is no big issue on its own but it makes one feel the FAQ is incomplete/faulty here.
Quite possible that this is C# 101 and I am just being stupid, but I still think the FAQ should show a working example that helps users like me.

So any help would be greatly appreciated. thanks in advance!

**Comment by aritchie** [comment]
I override the interface and implementations all the time without issue.  Seriously, if you're going to come here to whine about docs, just don't come.  People can contribute, otherwise everything here is free, so don't complain.  Contribute if you want to improve it.

The error you are having is the fact that you are trying to inherit the android version of my implementation which doesn't have an empty constructor.  You need to either implement the entire IUserDialogs interface or satisfy the requirements of the base constructor on UserDialogsImpl

**Comment by KorbinianMossandl** [comment]
Sorry if I came across whiny. I did just want to give a simple example why I am having problems with the short code snippet in the FAQ.
I can also assure you that I will be more than happy to update the FAQ once I figure out what my issue is exactly. 

So back to the problem:
Ok, so I see that the iOS version has an empty constructor. So on iOS the code from the FAQ works. But my issue is on Android, as you already know. So since there is no empty constructor I guess I need the right argument to initialize it? so a proper code snippet for Android how to initialize the new Instance would be a great help.

**Comment by aritchie** [comment]
Please understand that this is not a support area.  The code is open for you to figure all of this out on your own.  I'll fix defects and take feature requests around the library.  

```csharp
public class MyUserDialogsImpl : Acr.UserDialogs.UserDialogsImpl
{
        public MyUserDialogsImpl(Func<Activity> getTopActivity) : base(getTopActivity)
        {
        }
}
```
