### ISSUE TITLE
[Android] IDisposable pattern doesn't work with Activity being recreated after rotation

### ISSUE THREAD

**Issue by sylvain-toptal** [aritchie/userdialogs#508]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] NET Standard 2.0

The DisposableAction created by Android's UserDialogsImpl.Show and UserDialogsImpl.ShowDialog does not work well with the fact that Android recreates Activities on rotation.  The reason is that the DisposableAction keeps a reference to the Dialog that gets recreated after rotating the device.  Therefore, if you try to Dispose the DisposableAction, you will end up calling Dismiss on the Fragment that was on the old Activity (the one prior to the rotation).

In our case, we are waiting for an MFA approval for Okta and we automatically dismiss the AlertDialog when the server tells us it has been accepted through an polled endpoint.  However if the user rotates his device, we will crash because of the aforementionned reasons.

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
All

## Version of ACR UserDialogs Library
Current

## Expected Behaviour
We have worked our way around this issue by subclassing the various Config classes and adding a reference to the Dialog that needs to be dismissed.  We then subclassed the AlertAppCompatDialogFragment class and set the Dialog instance in the new Config throw overriding the  OnCreateDialog method.  Then we also overrode the ShowDialog method to use that Dialog reference instead of the Fragment originally created.

Following is a quick pseudo-code of the workaround we had to put forward.  Of course, because of the closed nature of the plugin this is a long way around that requires a lot of work for every type of dialog.  It can probably be better integrated in the plugin.

```
public class WBAlertConfig : Acr.AlertConfig
{
        public Dialog DismissableDialog { get; set; }
        
        public WBAlertConfig(AlertConfig source)
        {
                // Ccpy stuff from passed in copy
        }
}

public class WBAlertFragment : AlertAppCompatDialogFragment
{
        public override Dialog OnCreateDialog(Bundle bundle)
        {
                Dialog result = base.OnCreateDialog(bundle);
                
                (this.Config as WBAlertConfig).DismissableDialog = result;

                return result;
        }
}

public class AndroidUserDialogs : UserDialogsImpl, IUserDialogs
{
    IDisposable IUserDialogs.Alert(AlertConfig config)
    {
        var activity = this.TopActivityFunc();
    
        if (activity is AppCompatActivity act)
            return this.ShowDialog<WBAlertFragment, AlertConfig>(act, new WBAlertConfig(config));

        return this.Show(activity, () => new AlertBuilder().Build(activity, new WBAlertConfig(config)));
    }

    protected virtual IDisposable ShowDialog<TFragment, TConfig>(AppCompatActivity activity, TConfig config) where TFragment : AbstractAppCompatDialogFragment<TConfig> where TConfig : class, new()
    {
        var frag = (TFragment)Activator.CreateInstance(typeof(TFragment));
        
        activity.SafeRunOnUi(() =>
        {
            frag.Config = config;
            frag.Show(activity.SupportFragmentManager, FragmentTag);
        });
        
        return new DisposableAction(() =>
            activity.SafeRunOnUi(GetDismissableDialog(config).Dismiss)
        );
        }
        
        private Dialog GetDismissableDialog(object config)
        {
            if(config is WBAlertConfig)
            {
                return (config as WBAlertConfig).DismissableDialog;
            }
            
            ...
            
        }
}
```

## Actual Behavior
See above

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This is an interesting approach.  I'll take a look at this and see what I can do here.  

The way I usually deal with it is watching for OnPause (OnDisappearing in XamForms) and disposing of the dialog there.

**Comment by sylvain-toptal** [comment]
We are actually driving the dialogs from the PCL so that's not an option.

**Comment by sylvain-toptal** [comment]
So I was thinking it could be a better approach to use a generic Config wrapper instead of subclassing.  Using an implicit cast operator, it would reduce the amount of work required considerably.  I'm not sure it it would be 100% compatible with your implementation though.  I'm thinking something like this :

```
public class AndroidConfig<T>
{
    private T CommonConfig { get; set; }

    public AndroidConfig(T config)
    {
        CommonConfig = config;
    }

    public static implicit operator T(AndroidConfig<T> self)
    {
        return self.CommonConfig;
    }
}
```
