### ISSUE TITLE
ConfirmYesNoAsync/ShowActionSheetAsync truncates text at end of second line

### ISSUE THREAD

**Issue by borbmizzet** [aritchie/userdialogs#509]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [*] Android
 - [] UWP
 - [*] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Android 6.0
Samsung Galaxy S5
Xamarin.Android.Support=26.1.0.1

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
in ConfirmYesNoAsync/ShowActionSheetAsync:
Long text should wrap as many lines as needed.

## Actual Behavior
Long text gets truncated at end of second line with "..."

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
With confirm - this is the default behavior for Android which I don't alter.
Actionsheets only support message on iOS.  

You'll have to work with the OS here.
