### ISSUE TITLE
Nuget Update error

### ISSUE THREAD

**Issue by shinriyo** [aritchie/userdialogs#510]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [o] iOS
 - [o] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)

Visual Studio for Mac Version 7.4.1 (build 48)
macOS 10.13.4

## Version of ACR UserDialogs Library

7.0.1

## Expected Behaviour

I have 6.3.11
I just try to update.

<img width="376" alt="screen shot 2018-04-02 at 22 59 15" src="https://user-images.githubusercontent.com/396927/38198990-daf4a8a2-36c9-11e8-99c6-6dd381042cb2.png">

It happened
```
Could not install package 'Acr.UserDialogs 7.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

just update.

## Code of Conduct

no code. just update via NuGet of VS for Mac.

`xxx.csproj`

```
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <TargetFrameworkProfile>Profile78</TargetFrameworkProfile>
```

Must I modify there?

**Comment by aritchie** [comment]
Please read the supported platforms - https://github.com/aritchie/userdialogs (PCL supported has been gone for almost a year)

**Comment by shinriyo** [comment]
@aritchie 
Thank you for replying.
It's been a long time. I update my project.
Now, PCL is out of fashion?
Xamarin(VS for Mac) world, they use .NET Standard 2.0? it is trend?

**Comment by aritchie** [comment]
PCL is no longer supproted by Microsoft.  .NET Standard 2.0 is the target market for almost all plugins at this point.
