### ISSUE TITLE
ProgressDialog.Refresh () causes Java.Lang.RuntimeException

### ISSUE THREAD

**Issue by Sebastian1989101** [aritchie/userdialogs#511]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [x] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Android 5.1 - 8.1 all causes this exception

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
Does not crash

## Actual Behavior
Following excepttion is thrown sometimes (I'm not able to reproduce it for sure. It works in 90% of all cases and I do not know the exact crash cause; the activity which was used with `UserDialogs.Init(this)` is active all the time). 

```
Java.Lang.RuntimeException: Unable to add window -- token android.os.BinderProxy@aac1f80 is not valid; is your activity running?
ExceptionDispatchInfo.Throw ()
JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
Dialog.Show ()
AndHUD+<>c__DisplayClass26.<SetupDialog>b__24 (System.Object state)
SyncContext.Send (System.Threading.SendOrPostCallback d, System.Object state)
AndHUD.SetupDialog (Android.Content.Context context, AndroidHUD.MaskType maskType, System.Action cancelCallback, System.Func`4[T1,T2,T3,TResult] customSetup)
AndHUD.showStatus (Android.Content.Context context, System.Boolean spinner, System.String status, AndroidHUD.MaskType maskType, System.Nullable`1[T] timeout, System.Action clickCallback, System.Boolean centered, System.Action cancelCallback)
AndHUD.Show (Android.Content.Context context, System.String status, System.Int32 progress, AndroidHUD.MaskType maskType, System.Nullable`1[T] timeout, System.Action clickCallback, System.Boolean centered, System.Action cancelCallback)
ProgressDialog.Refresh ()
ProgressDialog.Show ()
GroupingSearchableRepositoryDataViewModel`2+<OnSearchCommandExecute>d__16[TGroup,TData].MoveNext ()
ExceptionDispatchInfo.Throw ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.2ec5f0dc-ca52-4ef5-894f-266f7efe34de(intptr,intptr)
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@27fb5e7 is not valid; is your activity running?
android.view.ViewRootImpl.setView(ViewRootImpl.java:571)
android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
android.view.WindowManagerImpl.addView(WindowManagerImpl.java:86)
android.app.Dialog.show(Dialog.java:319)
md5b60ffeb829f638581ab2bb9b1a7f4f3f.SearchBarRenderer.n_onQueryTextSubmit(Native Method)
md5b60ffeb829f638581ab2bb9b1a7f4f3f.SearchBarRenderer.onQueryTextSubmit(SearchBarRenderer.java:55)
android.widget.SearchView.onSubmitQuery(SearchView.java:1218)
android.widget.SearchView.-wrap8(SearchView.java)
android.widget.SearchView$6.onEditorAction(SearchView.java:1195)
android.widget.TextView.onEditorAction(TextView.java:4770)
com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:139)
com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:304)
com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
android.os.Handler.dispatchMessage(Handler.java:102)
android.os.Looper.loop(Looper.java:148)
android.app.ActivityThread.main(ActivityThread.java:5461)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Reproducible sample or exact steps to follow please.  You have to meet me half way if you want any sort of help!

The crash looks like it is just the wrong activity on top.  You can always use UserDialogs.Init(() => this); if it is always the same activity.

**Comment by Sebastian1989101** [comment]
@aritchie so I can basicly overwrite the activity used by the ProgressDialog if I call `UserDialogs.Init(this)` again? In this case I would just add it on every activity switch to see if this changes it. 

I'm not able to reproduce the issue because I don't know what causes it. I just see it my VS AppCenter as a crash report.

**Comment by aritchie** [comment]
UserDialogs.Init(this) installs additional support hooks to move with the app.  UserDialogs.Init(() => whatever) allows you to provide a factory method to send the top activity however you want.

This isn't how OSS works.  You can't just hand over a crash expect me to go research the issue for you.  I'm happy to help, but you'll need to supply some more detail before I invest my time into this.  Sorry.

**Comment by Sebastian1989101** [comment]
@aritchie I know that this is not the ideal way. But a reported issue is better than a missing one and maybe someone knows this problem already / knows the solution for it. I added additional crash logging for the next update of my app, if it happens again I might be able to reproduce it but as for now I just have no clue what the problem could be.

**Comment by aritchie** [comment]
I’ll leave this for the standard 4 days with the necessary steps missing.  After that I consider them stale and close them.  I don’t leave issues open because usually I get “me to” and nothing else helpful which is a complete waste of my time.

It isn’t that this “isn’t ideal”, this shouldn’t be treated as a general support form.  I’ll take full fledged reproducible issues and feature requests only.  This is OSS so you can easily help yourself to troubleshooting.  If I feel a user is abusing this in any way, I’ll simply remove them from being able to post here in the future.

**Comment by Sebastian1989101** [comment]
Well it's the issue section, isn't it? So it is the correct place to post issues. If I would know what happens there I would do a PR instead but for this case I have no clue what the problem could be but someone might. 

But I see, you have a very different opinion on OSS. I did not request any support or anything like this. I just reported an issue that is there and thats exactly the reason for a issue section on Github.

**Comment by aritchie** [comment]
You know, I was going to leave this issue open for you.  I was even going to take a look further into it, but not now.  My shop, my rules - I explained how things work in here.  You want to argue, simple answer for me, go elsewhere.  
The thing I've come to realize is that I don't have to help you.  I don't care if an issue even exists because it works for me and when it doesn't, I fix it.  Looks like its time for you to roll up the big boy sleeves and figure it out yourself.
