### ISSUE TITLE
[ANDROID] Acr.UserDialogs.UserDialogs.get_Instance' not found. 

### ISSUE THREAD

**Issue by plugowskismh** [aritchie/userdialogs#512]
- [] iOS
 - [+] Android
 - [] UWP
 - [] NET Standard 2.0

Xamarin.Android.Support.25.4.0

## Version of ACR UserDialogs Library
6.5.0

## Actual Behavior
Hi I have a weird problem with android version of this library. I can't run my Application because I receive error:  System.MissingMethodExceptions Method 'Acr.UserDialogs.UserDialogs.get_Instance' not found. 

This error show in MainActivity in line LoadApplication(new App()); In 
App.xaml.cs I have FreshIOC.Container.Register<IUserDialogs>(UserDialogs.Instance) to register singleton with FreshMVVM, the same error show when I use simple UserDialogs.Instance.Loading("Loading") in class. Of caurse in MainActivity I have this line:
UserDialogs.Init(() => this);

On iOS everything works fine

unfortunately I don't get any stacktrace in visual studio
I tested other versions of this library and I recieve also this error. Application works on Xamarin Forms 

I will be grateful for your help

**Comment by aritchie** [comment]
No idea - it looks like the library isn't being included in your project for some unknown reason.  

Please note that I only support the latest version.  If you have this issue with v7.0.1, please submit a full test project with the issue, so I can take a look

**Comment by plugowskismh** [comment]
I have another problem with version 7.0.1, I can't add it to my main project: 
Could not install package 'Acr.UserDialogs 7.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Have you turned off support for Xamarin Forms?
