### ISSUE TITLE
Can not add margins around toast notification (Enhancement?/Question?)

### ISSUE THREAD

**Issue by vikram-ma** [aritchie/userdialogs#514]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS 11
 - [] Android 7

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Xamarin.Android.Support.* 26.0.2

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
I want to add some margin below, left and to right of toast notification, so that it looks like something in the attached image(it's form AndHUD) ? Looks like AndHUD can do it, but I couldn't achieve the same thing using acr.userdialogs. I wanted to achieve same behavior for both Android and iOS.
![toastwithbottommargin](https://user-images.githubusercontent.com/2606667/38454836-b2663994-3aa9-11e8-903d-9495dc5837dd.png)

## Actual Behavior
Can not add margin below toast notification.

**Comment by aritchie** [comment]
Sorry this isn't something I want to change
