### ISSUE TITLE
Two requests.

### ISSUE THREAD

**Issue by rdcs** [aritchie/userdialogs#515]
I am having no issues with your wonderful product. I am using the toast message on an IOS app.
Just two requests and/or clarifications.
1.  Is there a way to clear the toast message prior to its timeout?, i.e., if I set the message to disappear in 5 seconds, can I make it disappear sooner?
2. Is there a way to place the message anywhere on the screen, other that top or bottom?

You did a great job and it was integrated into my app in 5 minutes, with no issues.  Just wanted to know if those two requests can be added or perhaps they have been and I don't know how to accomplish the task.

Thanks again,

Bob

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS Xamarin Version: 11.9.1.24 (Visual Studio Community)
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
1. Most dialogs return an IDisposable (non-async calls).  

```csharp
var dispose = UserDialogs.Instance.Toast(...);
// at some point before the timeout
dispose.Dispose(); // this will pop the toast right away
```

2. I do have options to place toasts at the top of the screen, but it was from a 3rd party (and is a hack) so it doesn't work very well.  Toasts really should be kept at the bottom of the screen with this library.

**Comment by rdcs** [comment]
Thanks very much for the extremely timely response!  I appreciate the answers and I will follow your guidance.

Bob
