### ISSUE TITLE
[iOS] Loading closes before finishing asynchronous method

### ISSUE THREAD

**Issue by cacaxiq** [aritchie/userdialogs#518]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)

iOS 11.2

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
using (_dialogs.Loading("message"))
            {
               //asynchronous method
                ...
            }

Loading should wait for the asynchronous method to finish to disappear from the screen.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

Loading disappears quickly from the screen after starting. Do not wait for the end of the asynchronous method.

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by cacaxiq** [comment]
This is the complete method. And none of the options mentioned in your answer

```

public async Task AprovarSimulacao()
        {
            if (_isAprovando) return;

            _isAprovando = true;

            var tarefas = default(DataResults<BPMTarefaResponseDto>);

            using (_dialogs.Loading(Message.Simulacao_Aprovando))
            {
                tarefas = await _bpmTarefaDataAgents.TratarTarefaBPM("APPROVE", Simulacao.IdTarefaBPM.ToString(), "Sem Justificativa", Guid.Empty, Settings.UsuarioLogin);
            }

            if (!tarefas.IsSuccess)
            {
                _dialogs.ShowError(Messages.Message.Simulacao_Aprovacao_TarefaBPM, 3000);
                _isAprovando = false;
            }
            else if (tarefas.Entity.Erros != null && tarefas.Entity.Erros.Codigo != 0)
            {
                _dialogs.ShowError(Messages.Message.Simulacao_Aprovacao_TarefaBPM, 3000);
                _isAprovando = false;
            }
            else
            {
                _dialogs.ShowSuccess(Message.Simulacao_Aprovada);
                await _navigationService.GoBackToRootAsync();
            }
        }
```

**Comment by aritchie** [comment]
By end-to-end sample, you need to submit a full reproducible app causing the issue that I can compile and run.  This method is used by a ton of people, if there was an issue here - there would be a lot of complainers.  Wrap the loading with the async in a try/catch.  Also, run a timer around it.

**Comment by aritchie** [comment]
No response from user.
