### ISSUE TITLE
Android: UserDialogs.Instance.ActionSheet() throws Exception (4.0.4)

### ISSUE THREAD

**Issue by davidtavarez** [aritchie/userdialogs#52]
//MainActivity.cs
UserDialogs.Init (this, true);

//var sheetconfig
UserDialogs.Instance.ActionSheet (sheetconfig); 
Throws an Exception.

Device: Alcatel Star
Android Version: 4.1.1

[MonoDroid]   --- End of managed exception stack trace ---
[MonoDroid] java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
[MonoDroid] 	at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:124)
[MonoDroid] 	at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
[MonoDroid] 	at android.support.v7.app.AppCompatDialog.<init>(AppCompatDialog.java:48)
[MonoDroid] 	at android.support.v7.app.AlertDialog.<init>(AlertDialog.java:92)
[MonoDroid] 	at android.support.v7.app.AlertDialog$Builder.create(AlertDialog.java:882)
[MonoDroid] 	at md5530bd51e982e6e7b340b73e88efe666e.GenericMenuClickListener.n_onMenuItemClick(Native Method)
[MonoDroid] 	at md5530bd51e982e6e7b340b73e88efe666e.GenericMenuClickListener.onMenuItemClick(GenericMenuClickListener.java:29)
[MonoDroid] 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:144)
[MonoDroid] 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
[MonoDroid] 	at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:523)
[MonoDroid] 	at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:100)
[MonoDroid] 	at android.view.View.performClick(View.java:4091)
[MonoDroid] 	at android.view.View$PerformClick.run(View.java:17072)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:615)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:92)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:153)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:5037)
[MonoDroid] 	at java.lang.reflect.Method.invokeNative(Native Method)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Method.java:511)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
[MonoDroid] 	at dalvik.system.NativeStart.main(Native Method)

**Comment by aritchie** [comment]
This is definitely not a bug. The intellisense on init method even says why. Your exception even explains what is wrong. Don't use appcompat (true in init - defaults to false) unless you know what to do with it

**Comment by davidtavarez** [comment]
Now I feel stupid! Sorry! I was confused because the App doesn't compile without AppCompat even I'm don't using it. You can close this.
