### ISSUE TITLE
WPF for Xamarin Forms Support

### ISSUE THREAD

**Issue by PawanJindal** [aritchie/userdialogs#520]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [x] NET Standard 2.0

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
I am using the latest Xamarin Forms build that allows WPF as a platform. I was able to add the library to the WPF head project. However, I am getting the following error in my shared .net standard project. I would really appreciate any help to resolve this. 

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
System.ArgumentException
  HResult=0x80070057
  Message=[Acr.UserDialogs] This is the bait library, not the platform library.  You must install the nuget package in your main executable/application project
 

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I don’t support WPF.  It isn’t even in the OS support list for the issue template you just filled out!!
