### ISSUE TITLE
BottomSheetDialogFragment doesn't use Config.AndroidStyleId

### ISSUE THREAD

**Issue by sylvain-toptal** [aritchie/userdialogs#521]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] NET Standard 2.0

The BottomSheetDialogFragment doesn't use the AndroidStyleId property of the config and therefore uses the default style instead of the passed in theme.

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
All

## Version of ACR UserDialogs Library
Latest

## Expected Behaviour
Use AndroidStyleIs in BottomSheetDialogFragment

## Actual Behavior
Always uses default style

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
already been fixed, not released
