### ISSUE TITLE
PropmtConfig NullReferenceException with OnAction unhooked

### ISSUE THREAD

**Issue by hessam2013** [aritchie/userdialogs#523]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 2.0
Not tested on other platforms

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Android Nougat 7.1
Xamarin.Android.Support.* => v25.4.0.2

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
 The app should continue running when PromptConfig OnAction is not hooked.

## Actual Behavior
In the snippet below if I dont hook OnAction for PromptConfig object, when action buttons(OK or Cancel) are selected the app crashes with a NullReferenceException. 
Stack trace is not available.
```
var prompt = new PromptConfig();
prompt.OnTextChanged += TextChanged;
prompt.OnAction += (action) => { UserDialogs.Instance.Toast(new ToastConfig(action.Value)); };
UserDialogs.Instance.Prompt(prompt);
```

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
OnAction is called by those action buttons.  You need to set it. 

TextChanged is for monitoring the actual text field to validate/change it in real time
