### ISSUE TITLE
Having issue with with Loading Dialog using Acr.UserDialogs in iOS App

### ISSUE THREAD

**Issue by VishalBoxer** [aritchie/userdialogs#525]
## Please check all of the platforms you are having the issue on (if the platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of ACR UserDialogs Library
PCL Project - v6.5.1
iOS Project - v7.0.0

## Expected Behaviour
it should work with iOS platform too.

## Actual Behavior
I am having an issue with iOS platform my app is just crash when click button for Start progress bar. same thing we checked with android platform its working fine for me.

App getting crash with below stacktrace:
**Attempting to JIT compile method 'MyApp.Views.LoginProcess.LoginPage/<LoginButton_Clicked>d__5:MoveNext ()' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.**

## Code of Conduct
 using (UserDialogs.Instance.Loading("Loading", null, null, true, MaskType.Black))
{
          await Task.Run(() =>
          {
                        // My code logic Goes Here
          });
}
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This library hasn’t support pcl for almost a year.  You have 2 different versions installed which isn’t good.  And the compiler error you are getting has absolutely nothing that says userdialogs in it.  Not a thing I can do here
