### ISSUE TITLE
Question: How do I add more than two options to a confirmation box?

### ISSUE THREAD

**Issue by RLittlesII** [aritchie/userdialogs#526]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 2.0

## Question
In this [Xamarin Forms Forum Post](https://forums.xamarin.com/discussion/80061/acr-userdialgos-more-than-two-options) its stated that its easy to extend the library to handle a Confirmation Box with more than two options.  I was wondering if there was any documentation or examples of how to make this happen.

**Comment by aritchie** [comment]
No - if you want to overwrite things, the basis is built on the IUserDialogs interface.  All methods on each platform are also marked as virtual.  You can change any aspect you want from there
