### ISSUE TITLE
Acr.UserDialogs 7.0.1 and OpenTK-1.0 

### ISSUE THREAD

**Issue by cvasquez-github** [aritchie/userdialogs#527]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [X] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Windows 10 - Microsoft Visual Studio 2017

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
Updating Acr.UserDialogs 6.5.1 to 7.0.1 using NuGet Packages Manager.

## Actual Behavior
Can't install, we receive the following message: 
Severity	Code	Description	Project	File	Line	Suppression State
Error Failed to add reference. The package 'Acr.UserDialogs' tried to add a framework reference to 'OpenTK-1.0' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance. Error HRESULT E_FAIL has been returned from a call to a COM component.	

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by cvasquez-github** [comment]
I get this error in Microsoft Visual Studio (Windows 10) when trying to update Acr 6.5.1 to 7.0.1 using NuGet Packages Manager. This is the actual Package Manager Ouput:

Attempting to gather dependency information for package 'Acr.UserDialogs.7.0.1' with respect to project 'VRAVOQR.iOS', targeting 'Xamarin.iOS,Version=v1.0'
Gathering dependency information took 749.13 ms
Attempting to resolve dependencies for package 'Acr.UserDialogs.7.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Acr.UserDialogs.7.0.1'
Resolved actions to install package 'Acr.UserDialogs.7.0.1'
Attempting to gather dependency information for package 'Acr.UserDialogs.7.0.1' with respect to project 'VRAVOQR.Android', targeting 'MonoAndroid,Version=v7.1'
Gathering dependency information took 3.08 sec
Attempting to resolve dependencies for package 'Acr.UserDialogs.7.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Acr.UserDialogs.7.0.1'
Resolved actions to install package 'Acr.UserDialogs.7.0.1'
Retrieving package 'Acr.UserDialogs 7.0.1' from 'nuget.org'.
Retrieving package 'BTProgressHUD 1.2.0.6' from 'nuget.org'.
Removed package 'Acr.UserDialogs.6.5.1' from 'packages.config'
Successfully uninstalled 'Acr.UserDialogs.6.5.1' from VRAVOQR.iOS
Removed package 'BTProgressHUD.1.2.0.5' from 'packages.config'
Successfully uninstalled 'BTProgressHUD.1.2.0.5' from VRAVOQR.iOS
Adding package 'BTProgressHUD.1.2.0.6' to folder 'D:\SVN\VravoQR\packages'
Added package 'BTProgressHUD.1.2.0.6' to folder 'D:\SVN\VravoQR\packages'
Added package 'BTProgressHUD.1.2.0.6' to 'packages.config'
Successfully installed 'BTProgressHUD 1.2.0.6' to VRAVOQR.iOS
Adding package 'Acr.UserDialogs.7.0.1' to folder 'D:\SVN\VravoQR\packages'
Added package 'Acr.UserDialogs.7.0.1' to folder 'D:\SVN\VravoQR\packages'
Install failed. Rolling back...
Package 'Acr.UserDialogs.7.0.1 : BTProgressHUD [1.2.0.6, )' does not exist in project 'VRAVOQR.iOS'
Removed package 'BTProgressHUD.1.2.0.6' from 'packages.config'
Package 'BTProgressHUD.1.2.0.5' already exists in folder 'D:\SVN\VravoQR\packages'
Added package 'BTProgressHUD.1.2.0.5' to 'packages.config'
Package 'Acr.UserDialogs.6.5.1' already exists in folder 'D:\SVN\VravoQR\packages'
Added package 'Acr.UserDialogs.6.5.1' to 'packages.config'
Removing package 'Acr.UserDialogs.7.0.1 : BTProgressHUD [1.2.0.6, )' from folder 'D:\SVN\VravoQR\packages'
Removed package 'Acr.UserDialogs.7.0.1 : BTProgressHUD [1.2.0.6, )' from folder 'D:\SVN\VravoQR\packages'
Removing package 'BTProgressHUD.1.2.0.6' from folder 'D:\SVN\VravoQR\packages'
Removed package 'BTProgressHUD.1.2.0.6' from folder 'D:\SVN\VravoQR\packages'
Executing nuget actions took 1.3 sec
Failed to add reference. The package 'Acr.UserDialogs' tried to add a framework reference to 'OpenTK-1.0' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
  Error HRESULT E_FAIL has been returned from a call to a COM component.
Time Elapsed: 00:00:05.1524493
========== Finished ==========

Thanks!

**Comment by aritchie** [comment]
Make sure your iOS project isn't using packages.config.  It needs to be using the <PackageReference> nuget system.  If you're using 6.5.1, that was around before package refs so you'll need to update your project

**Comment by cvasquez-github** [comment]
OK @aritchie thanks for your quick response!

BTW I unchecked the iOS version of our project, and left only the Android version checked.
The Android version of our mobile project was updated to 7.0.1 successfully.
The problem occurs when trying to update the iOS version of the project from 6.5.1 to 7.0.1.

Thanks

**Comment by aritchie** [comment]
It's the VS tooling change over.  Nothing I can do about it.  The newer nuget system knows what to do with this.
