### ISSUE TITLE
problem with last xamarin forms 3.0 stable

### ISSUE THREAD

**Issue by maherzaidoune** [aritchie/userdialogs#529]
i just updated xamarin forms to last 3.0 stable version , using Acr.userDialogs v7.0.1 UserDialogs.Instance.Toast(toastConfig)  no message appear on the screen , and no exception was thrown 
tested on android 6.0

**Comment by aritchie** [comment]
This library is not associated with Xamarin forms in any way.  You can use other init methods for detecting the top view.  My suggestion is to init from an application level in droid.

Use the issue template in the future if you want help!!

**Comment by oridotaoyebode** [comment]
@maherzaidoune Please clean and rebuild your solution. It should work after you do that. Regards

**Comment by maherzaidoune** [comment]
@oridotaoyebode  thank you, problem fixed after deleting bin and obj folders , cleaning and building
