### ISSUE TITLE
Android.Views.InflateException: Exception of type 'Android.Views.InflateException' was thrown. (4.0.4)

### ISSUE THREAD

**Issue by davidtavarez** [aritchie/userdialogs#53]
//MainActivity.cs
UserDialogs.Init (this, true);

UserDialogs.Instance.Toast() throws this exception.
Device: Alcatel Star
Android Version: 4.1.1

[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Android.Views.InflateException: Exception of type 'Android.Views.InflateException' was thrown.
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000b] in /Users/builder/data/lanes/1978/f98871a9/source/mono/mcs/class/corlib/System.Runtime.ExceptionServices/ExceptionDispatchInfo.cs:61
[MonoDroid] at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (object) [0x00000] in /Users/builder/data/lanes/1978/f98871a9/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1006
[MonoDroid] at Android.App.SyncContext/<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/src/Android.App/SyncContext.cs:18
[MonoDroid] at Java.Lang.Thread/RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/src/Java.Lang/Thread.cs:36
[MonoDroid] at Java.Lang.IRunnableInvoker.n_Run (intptr,intptr) [0x00009] in /Users/builder/data/lanes/1978/f98871a9/source/monodroid/src/Mono.Android/platforms/android-22/src/generated/Java.Lang.IRunnable.cs:71
[MonoDroid] at (wrapper dynamic-method) object.9b98f38d-baf0-4413-8fc5-deb3c7c230c0 (intptr,intptr) <IL 0x00011, 0x0003b>
[MonoDroid]   --- End of managed exception stack trace ---
[MonoDroid] android.view.InflateException: Binary XML file line #18: Error inflating class android.support.design.widget.Snackbar$SnackbarLayout
[MonoDroid] 	at android.view.LayoutInflater.createView(LayoutInflater.java:613)
[MonoDroid] 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
[MonoDroid] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
[MonoDroid] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
[MonoDroid] 	at android.support.design.widget.Snackbar.<init>(Snackbar.java:127)
[MonoDroid] 	at android.support.design.widget.Snackbar.make(Snackbar.java:148)
[MonoDroid] 	at md5530bd51e982e6e7b340b73e88efe666e.GenericMenuClickListener.n_onMenuItemClick(Native Method)
[MonoDroid] 	at md5530bd51e982e6e7b340b73e88efe666e.GenericMenuClickListener.onMenuItemClick(GenericMenuClickListener.java:29)
[MonoDroid] 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:144)
[MonoDroid] 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
[MonoDroid] 	at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:523)
[MonoDroid] 	at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:100)
[MonoDroid] 	at android.view.View.performClick(View.java:4091)
[MonoDroid] 	at android.view.View$PerformClick.run(View.java:17072)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:615)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:92)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:153)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:5037)
[MonoDroid] 	at java.lang.reflect.Method.invokeNative(Native Method)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Method.java:511)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
[MonoDroid] 	at dalvik.system.NativeStart.main(Native Method)
[MonoDroid] Caused by: java.lang.reflect.InvocationTargetException
[MonoDroid] 	at java.lang.reflect.Constructor.constructNative(Native Method)
[MonoDroid] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
[MonoDroid] 	at android.view.LayoutInflater.createView(LayoutInflater.java:587)
[MonoDroid] 	... 22 more
[MonoDroid] Caused by: android.view.InflateException: Binary XML file line #34: Error inflating class <unknown>
[MonoDroid] 	at android.view.LayoutInflater.createView(LayoutInflater.java:613)
[MonoDroid] 	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
[MonoDroid] 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
[MonoDroid] 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
[MonoDroid] 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
[MonoDroid] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:459)
[MonoDroid] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
[MonoDroid] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
[MonoDroid] 	at android.support.design.widget.Snackbar$SnackbarLayout.<init>(Snackbar.java:534)
[MonoDroid] 	... 25 more
[MonoDroid] Caused by: java.lang.reflect.InvocationTargetException
[MonoDroid] 	at java.lang.reflect.Constructor.constructNative(Native Method)
[MonoDroid] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
[MonoDroid] 	at android.view.LayoutInflater.createView(LayoutInflater.java:587)
[MonoDroid] 	... 33 more
[MonoDroid] Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x2/d=0x7f0100bc a=-1}
[MonoDroid] 	at android.content.res.Resources.loadDrawable(Resources.java:1951)
[MonoDroid] 	at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
[MonoDroid] 	at android.view.View.<init>(View.java:3343)
[MonoDroid] 	at android.widget.TextView.<init>(TextView.java:462)
[MonoDroid] 	at android.widget.TextView.<init>(TextView.java:457)
[MonoDroid] 	... 36 more

**Comment by aritchie** [comment]
This is definitely not a bug.  The intellisense on init method even says why.  Your exception even explains what is wrong.  Don't use appcompat (true in init - defaults to false) unless you know what to do with it

**Comment by aritchie** [comment]
This is definitely not a bug. The intellisense on init method even says why. Your exception even explains what is wrong. Don't use appcompat (true in init - defaults to false) unless you know what to do with it

**Comment by davidtavarez** [comment]
Now I feel stupid! Sorry! I was confused because the App doesn't compile without AppCompat even I'm don't using it. You can close this.

**Comment by aritchie** [comment]
I'm probably going to move appcompat to a secondary library.  You aren't the only one that has had this issue.

**Comment by adriancho5692** [comment]
Hi, I need to use AppCompat for project purpose and I'm getting this error. How can I fix it?

**Comment by aritchie** [comment]
@adriancho5692 please file a separate defect with the defect template questions if you would like help
