### ISSUE TITLE
Use of external plugins/packages.

### ISSUE THREAD

**Issue by MarcBruins** [aritchie/userdialogs#533]
Hi Allan,

We talked about this a while back but it just occurred to me we did no take action at that time. It would be nice if my components where used as a dependency for the userdialogs, this would increase my downloads on nuget which would be nice.

Both the datepicker and the snackbar can be added as a nuget dependency. Can make a PR soon if you'd like.

**Comment by aritchie** [comment]
Hey Marc.  There were a couple of bugs that ended up causing me to revert.  From what I remember, it was around the tap event.  I definitely want to switch to using your packages directly though.  Happy to take a PR for this

**Comment by SamuelDebruyn** [comment]
AFAIK including more assemblies on Android increases the startup time. Keeping the code in this package is indeed bad for the download stats of your package, but it does - very slightly however - increase the performance on Android.

**Comment by aritchie** [comment]
That rumour is mostly a crap sell on Xamarin's part.  We're talking about fractions of time.  Not one that I am willing to entertain.  When Marc has the time to update his package to what this library needs, I will use it.
