### ISSUE TITLE
Updating from 6.3.10 to 7.0.1 in PCL gives error

### ISSUE THREAD

**Issue by AaronBratcher** [aritchie/userdialogs#538]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Running Visual Studio Community - Mac v7.5.2

## Version of ACR UserDialogs Library
Updating from 6.3.10 to 7.0.1 in PCL

## Expected Behavior
Update

## Actual Behavior
Error: 
Could not install package 'Acr.UserDialogs 7.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by aritchie** [comment]
I haven’t supported pcl for quite some time

**Comment by ctrexler** [comment]
@aritchie I was having a lot of these exact issues because on the github description it says you support "shared/portable". If this refers to portable as in PCLs I think it would solve some headaches if you updated this. Thanks!
