### ISSUE TITLE
Loading not hiding

### ISSUE THREAD

**Issue by Ph0b0x** [aritchie/userdialogs#539]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] UWP
 - [x] NET Standard 2.0

## Actual Behavior
HideLoading() it's being hit properly (i debugged it) but the loading sequence it's still blocking the UI

## Code of Conduct

Here's the code i am using:
```
Device.BeginInvokeOnMainThread(() => UserDialogs.Instance.Loading(AppConstants.LOADING_CONTACTING_YOBIT_API, null, null, true, MaskType.Black));
                Task.Run(async () =>
                {
                    try
                    {
                        MyAPIDataService apiDataService = new MyAPIDataService();

                        item1 = await apiDataService.GetApiData(param1);
                        item2 = await apiDataService.GetApiData(param2);
                        item3 = await apiDataService.GetApiData(param3);
                        item4 = await apiDataService.GetApiData(param4);
                        item5 = await apiDataService.GetApiData(param5);
                        item6 = await apiDataService.GetApiData(param6);
                    }
                    catch (Exception ex)
                    {
                        UserDialogs.Instance.HideLoading();
                        System.Diagnostics.Debug.WriteLine("Error on MainViewModel.GetApiDataForApp: " + ex.Message);
                    }
                }).ContinueWith(result => Device.BeginInvokeOnMainThread(() =>
                {
                    UserDialogs.Instance.HideLoading();
                }));
```

**Comment by Ph0b0x** [comment]
I am testing the project on iOS and Android using emulator/simulator with the same results. I also tried something along the lines of:

`using(UserDialogs.Instance.Loading("loading"))
{
    //await calls here
}`

Same results here. I remember on another Xamarin project that i was (i think this is my 4th project using AcrUser dialogs, thanks a lot BTW) that i needed to use the main thread invocation for it to work. I took that approach from a discussion on StackOverflow. Can I see what would be your approach?

**Comment by aritchie** [comment]
I don't use Show/HideLoading.  I use the using statement as you've shown.  

In that the "//await calls here" that you have.  Add await Task.Delay(3000);  and let me know what appears.

**Comment by aritchie** [comment]
It could mean anything.  This is the standard things I do for await calls that incur loading
try
{
    using (Acr.UserDialogs.Instances.Loading("Do something"))
    {
         await DoThings();
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}

**Comment by Ph0b0x** [comment]
Tried that approach. No exception. The loading appeared briefly after the await calls finished. So weird. BTW i am testing on the iOS simulator now which is usually better than the Android Emulator (using a MAC book pro). Could it be that i am doing something wrong on my API calls?

**Comment by aritchie** [comment]
I have no idea.  I don't have any details.  The call works for me in the samples in another project I have right now. 

At this point, I need a SMALL reproducible sample if I'm to provide any sort of support.

**Comment by Ph0b0x** [comment]
Got you. Make sense to me. I will double check all the API calls and if i cannot find something i will provide you a sample. I've been looking at this since Yesterday but i might have skipped something. I will let you know. Thanks for the support and for UserDialogs.

**Comment by Ph0b0x** [comment]
I found the issue and it was on my end. I had something like this: 
`using(UserDaialogs.Instance.Loading("Waiting for api call")) 
{
   myDataProperty = await GetDataFromApi();
}`

Then on GetDataFromApi():
`public async Task<object> GetDataFromApi()
{
   object retVal = httpService.GetData().Result;
}`

That was my mistake, it should have been:
`public async Task<object> GetDataFromApi()
{
   object retVal = await httpService.GetData();
}`

These type of mistakes are the most difficult to find. I hope this helps other and thanks @aritchie for your patience.
