### ISSUE TITLE
Loading popup location varies

### ISSUE THREAD

**Issue by WilliamWatterson86** [aritchie/userdialogs#541]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [X] Android
 - [] UWP
 - [X] NET Standard 2.0

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
Loading popups are displayed in same position in Xamarin Forms iOS app

## Actual Behavior
I am using the loading popup throughout my app.  It works great.  However on the iOS version of my app, the loading popup appears not in the center on some screens and in the center in others.  Is there something this depends on?  Do I need to do something special on the app/page to make them always appear in the center?
Android it always displays in the center and looks great.

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
There is an infinite number of reasons why this can occur.  I have a hacky way of finding the top window & viewcontroller to be able to present the alert controller.  Other modals can often create issues like this.

You would need to provide small examples if I'm to shed any light on what's going on

**Comment by WilliamWatterson86** [comment]
Hi @aritchie - thank you for your reply.

I have a few forms where it is happening.  I have screenshots below:

This one (the AddEditSite.xaml - also attached) the popup appears towards the top of the screen.
![image](https://user-images.githubusercontent.com/32571925/41307879-50aae96e-6e72-11e8-90cc-72288701f709.png)

This one (the SelectZoneTemperaturePage.xaml attached) the popup appears in the center of the screen.
![image](https://user-images.githubusercontent.com/32571925/41307996-996f8f06-6e72-11e8-9585-e1e0757e9e11.png)

The strange thing is - if I open one of the pages that has the loading popup that is not centered, it affects the rest of them.  So say i open the app and go to the AddEditSite screen first, and then the SetTemperature page, the loading popup appears in both uncentered.  But if I open the temp screen first it appears centered but the AddEditSite still appears uncentered.

Both pages are added to the modal stack when being displayed.  

Hope this detail helps.  Would love to get the dialogs appearing in the center as they look great when they appear.

Thanks for your help

[CodeFiles.zip](https://github.com/aritchie/userdialogs/files/2095297/CodeFiles.zip)

**Comment by aritchie** [comment]
> Both pages are added to the modal stack when being displayed.

Ok, this library doesn't work well with modals as I mentioned.  You can override UserDialogs.Init(() => return topViewController); yourself.  Not sure how to manage that through forms, but I can't do much beyond that.  

If I'm reading your reply wrong, please provide an actual working sample that I can run to see the issue.  These are just xaml/cs files.  I need something I can run.

**Comment by WilliamWatterson86** [comment]
Hi @aritchie - thanks. 

I have narrowed it down a bit.  So it seems to only happen on a screen where the keyboard is displayed - so any form that has a textbox.  Everything is fine unless i tap the textbox.  As soon as i tap the textbox and display the keyboard, even if the keyboard is dismissed - the loading popup appears in the wrong position when it displays.

**Comment by aritchie** [comment]
Cases like this are things I can’t really do much about.  You can dismiss the keyboard before calling for loading.

**Comment by Ruddy2007** [comment]
Just to add onto this (though doesn't look like much can be done), I am having a similar issue. Sometimes its centered and others its not, for me its more random. No modal and it can happen on the same page sometimes.
