### ISSUE TITLE
[iOS] Crash in connection with Rg.Plugins.Popup Plugin

### ISSUE THREAD

**Issue by ParticularEric** [aritchie/userdialogs#542]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
iOS 11.*

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
No crash

## Actual Behavior
So, I have a Xamarin.Forms app that uses Rg.Plugins.Popup Plugin and this userdialogs plugin. I get a crash (not everytime, but often - cant really reproduce it) when calling a Loadingscreen (UserDialogs.Instance.ShowLoading) after a Popup of the other plugin was shown earlier sometime during the app runtime. The crash message referes to the Popup Plugin, though there is no code from it called where the crash actively occures. This is the crashlog:

```Application.Main (System.String[] args)
System.Exception: Failed to marshal the Objective-C object 0x13dd73030 (type: Rg_Plugins_Popup_IOS_Platform_PopupWindow). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'Rg.Plugins.Popup.IOS.Platform.PopupWindow' does not have a constructor that takes one IntPtr argument).

Runtime.MissingCtor (System.IntPtr ptr, System.IntPtr klass, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution resolution)
Runtime.ConstructNSObject[T] (System.IntPtr ptr, System.Type type, ObjCRuntime.Runtime+MissingCtorResolution missingCtorResolution)
Runtime.GetINativeObject[T] (System.IntPtr ptr, System.Boolean owns)
NSArray.UnsafeGetItem[T] (System.IntPtr handle, System.nuint index)
NSArray.ArrayFromHandle[T] (System.IntPtr handle)
UIApplication.get_Windows ()
ProgressHUD.ShowProgressWorker (System.Single progress, System.String status, BigTed.ProgressHUD+MaskType maskType, System.Boolean textOnly, BigTed.ProgressHUD+ToastPosition toastPosition, System.String cancelCaption, System.Action cancelCallback, System.Double timeoutMs, System.Boolean showContinuousProgress, UIKit.UIImage displayContinuousImage)
ProgressHUD+<>c__DisplayClass18_0.<Show>b__0 ()
NSActionDispatcher.Apply ()
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr,intptr,intptr,bool)
NSObject.InvokeOnMainThread (System.Action action)
ProgressHUD.Show (System.String status, System.Single progress, BigTed.ProgressHUD+MaskType maskType, System.Double timeoutMs)
BTProgressHUD.Show (System.String status, System.Single progress, BigTed.ProgressHUD+MaskType maskType)
ProgressDialog+<>c__DisplayClass17_0.<Refresh>b__0 ()
NSActionDispatcher.Apply ()
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr,intptr,intptr,bool)
NSObject.InvokeOnMainThread (System.Action action)
ProgressDialog.Refresh ()
ProgressDialog.Show ()
AbstractUserDialogs.Progress (Acr.UserDialogs.ProgressDialogConfig config)
AbstractUserDialogs.Loading (System.String title, System.Action onCancel, System.String cancelText, System.Boolean show, System.Nullable`1[T] maskType)
AbstractUserDialogs.ShowLoading (System.String title, System.Nullable`1[T] maskType)
MobileFeedback.SendButton_Clicked (System.Object sender, System.EventArgs e)
Button.SendClicked ()
ButtonRenderer.OnButtonTouchUpInside (System.Object sender, System.EventArgs eventArgs)
UIControlEventProxy.Activated ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I’m only going to toss out a guess - it sounds like you may be calling for loading right after closing the window.  I use a technique by finding the top window at the time you call for a dialog.  If the previous pop up has not finished animating closed, that window can be picked up which is bad since it is about to disappear.  I would set a delay before calling for loading. 

That’s about the extent I’ll go with this issue since this isn’t a defect directly to do with this library

**Comment by markdou812** [comment]
I'm experiencing the exact same problem.
