### ISSUE TITLE
Delay to display loading indicator

### ISSUE THREAD

**Issue by ErBhautik** [aritchie/userdialogs#543]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of ACR UserDialogs Library
7.0.1
## Expected Behaviour
Loader should be display

## Actual Behavior
UserDialogs.Instance.Loading("Loading"); display only after UserDialogs.Instance.(toast,progress etc).
 
**My Actual Code**
UserDialogs.Instance.Loading("Loading");
 
Call business logic or some method **which is not async**

UserDialogs.Instance.HideLoading(); //Once this line excute than after loader is disaply.

So is there any change are required to do that or am I missiong something?

**Comment by aritchie** [comment]
Your code is blocking the ui thread which this library needs to render on.  Even if it didn’t manage to render the dialog, the animation wouldn’t run very well

**Comment by aritchie** [comment]
No Response closing as not an issue
