### ISSUE TITLE
The package 'Acr.UserDialogs' tried to add a framework reference to 'System.Collections' which was not found in the GAC.

### ISSUE THREAD

**Issue by aymanrh** [aritchie/userdialogs#545]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by cvasquez-github** [comment]
Fix:
- Update Visual Studio to 15.8.0
- Right click in References -> Migrate packages.config to PackageReference...
- Then update Acr.UserDialogs to 7.0.1
