### ISSUE TITLE
iOS ARM 64 Build Architecture (App Store Required) causes text to truncate

### ISSUE THREAD

**Issue by highplains** [aritchie/userdialogs#55]
Debug Build....
![img_1968](https://cloud.githubusercontent.com/assets/1825076/9239531/da21586a-4119-11e5-88ac-d01a001314b5.PNG)

Release / App Store Build...
![img_1967-1](https://cloud.githubusercontent.com/assets/1825076/9239686/8fbdfede-411b-11e5-98f0-cacbdf93bec4.PNG)

Weird.... Any thoughts on this?

**Comment by highplains** [comment]
After further testing it seems that having the supported archs set to arm7 + arm64 is what is causing this issue. If i set the supported archs to just "arm7" the truncation seems to disappear. Hmmm....
<img width="560" alt="screen shot 2015-08-12 at 6 07 36 pm" src="https://cloud.githubusercontent.com/assets/1825076/9239872/2dc99010-411d-11e5-9e7b-f7c713968f54.png">

**Comment by highplains** [comment]
Should also note that this was tested on a iphone 6 plus

**Comment by aritchie** [comment]
No idea.  I don't even know where to start with this one

**Comment by highplains** [comment]
Lol no clue either. Same bug exists in the other Xamarin plugin that does just toasts too. Could be a xam bug or just a forms bug (or maybes project template) I will download your source and try some setting changes to see if I can find a fix tomorrow. The fact that this happens in multiple plugins is interesting though. I'll make a couple test projects with current templates tomorrow to see if I can narrow it more. By the way appreciate the quick feedback and releases, flipped my production projects to his because of that.

Cheers

**Comment by highplains** [comment]
Ok looks like I got this one figured out...
The problem does only exist when selecting a build architecture that includes x64. 

When targeting x64 the methods that use NSString.DrawString need to be converted to the non-deprecated extension methods and then the truncation disappears.

To Fix.

In Acr.UserDialogs.iOS.MessageBar.Messageview.Draw

Change.
Title.DrawString (titleRectangle, TitleFont, UILineBreakMode.TailTruncation, UITextAlignment.Left);
to
Title.DrawString(titleRectangle, new UIStringAttributes { Font = TitleFont, ForegroundColor = TitleColor });

and also
Description.DrawString (descriptionRectangle, DescriptionFont, UILineBreakMode.TailTruncation, UITextAlignment.Left);
to
Description.DrawString(descriptionRectangle, new UIStringAttributes { Font = DescriptionFont, ForegroundColor = DescriptionColor });



Perhaps this has to do with Unified API.  See
http://developer.xamarin.com/guides/cross-platform/macios/updating-tips/
Objective-C category methods are now generated as extension methods in the Unified API. For example, code that previously used UIView.DrawString would now reference NSString.DrawString in the Unified API.


Also my test project .......
https://github.com/highplains/ToastTest

**Comment by aritchie** [comment]
Thanks for the PR.  I'm going to have to decline the null icon because it prevents the default icons.  I'll look into this for a future release though
