### ISSUE TITLE
The package 'Acr.UserDialogs' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.   Reference unavailable.

### ISSUE THREAD

**Issue by schovan** [aritchie/userdialogs#550]
package manager log:
`
Attempting to gather dependency information for package 'Acr.UserDialogs.7.0.1' with respect to project 'App1.Droid', targeting 'MonoAndroid,Version=v7.1'
Gathering dependency information took 4,47 sec
Attempting to resolve dependencies for package 'Acr.UserDialogs.7.0.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Acr.UserDialogs.7.0.1'
Resolved actions to install package 'Acr.UserDialogs.7.0.1'
Retrieving package 'Acr.UserDialogs 7.0.1' from 'nuget.org'.
Retrieving package 'AndHUD 1.2.0' from 'nuget.org'.
Adding package 'AndHUD.1.2.0' to folder 'c:\Users\schov\Documents\Bitbucket\DsmXamarin\packages'
Added package 'AndHUD.1.2.0' to folder 'c:\Users\schov\Documents\Bitbucket\DsmXamarin\packages'
Added package 'AndHUD.1.2.0' to 'packages.config'
Successfully installed 'AndHUD 1.2.0' to App1.Droid
Adding package 'Acr.UserDialogs.7.0.1' to folder 'c:\Users\schov\Documents\Bitbucket\DsmXamarin\packages'
Added package 'Acr.UserDialogs.7.0.1' to folder 'c:\Users\schov\Documents\Bitbucket\DsmXamarin\packages'
Install failed. Rolling back...
Package 'Acr.UserDialogs.7.0.1 : AndHUD [1.2.0, ), Xamarin.Android.Support.Design [25.4.0.2, )' does not exist in project 'App1.Droid'
Removed package 'AndHUD.1.2.0' from 'packages.config'
Removing package 'Acr.UserDialogs.7.0.1 : AndHUD [1.2.0, ), Xamarin.Android.Support.Design [25.4.0.2, )' from folder 'c:\Users\schov\Documents\Bitbucket\DsmXamarin\packages'
Removed package 'Acr.UserDialogs.7.0.1 : AndHUD [1.2.0, ), Xamarin.Android.Support.Design [25.4.0.2, )' from folder 'c:\Users\schov\Documents\Bitbucket\DsmXamarin\packages'
Removing package 'AndHUD.1.2.0' from folder 'c:\Users\schov\Documents\Bitbucket\DsmXamarin\packages'
Removed package 'AndHUD.1.2.0' from folder 'c:\Users\schov\Documents\Bitbucket\DsmXamarin\packages'
Executing nuget actions took 3,94 sec
Failed to add reference. The package 'Acr.UserDialogs' tried to add a framework reference to 'System.Collections' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
  Reference unavailable.
Time Elapsed: 00:00:08.5087820
========== Finished ==========
`

**Comment by aritchie** [comment]
1) Follow the item template if you want help in the future.  
2) Read your error message fully!    Install failed. Rolling back... Package 'Acr.UserDialogs.7.0.1 : AndHUD [1.2.0, ), Xamarin.Android.Support.Design [25.4.0.2, )' does not exist in project 'App1.Droid' Removed package 'AndHUD.1.2.0' from 'packages.config' 
3) packages.config is the old nuget mechanism that isn't supported any longer.  You need to update to csproj package references

**Comment by cvasquez-github** [comment]
Fix:
- Update Visual Studio to 15.8.0
- Right click in References -> Migrate packages.config to PackageReference...
- Then update Acr.UserDialogs to 7.0.1
