### ISSUE TITLE
[iOS] Months are not translated on the DatePicker

### ISSUE THREAD

**Issue by galadril** [aritchie/userdialogs#551]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue 
11.4

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
If we have Russian translations, the Datepicker on iOS should also show russian month names. It is correctly working on Android but not on iOS

## Actual Behavior
Our app has Russian translations, on Android the months are correctly translated, but on IOS the months stay on English. Any suggestions?

**Comment by aritchie** [comment]
Saw this dupe, same - nothing to do with the library itself

**Comment by galadril** [comment]
Sorry that i didn't anwsered this issue when i found the solution.

i had to put the next array in the info.plist to enable the languages:

```

<key>CFBundleLocalizations</key>
      <array>
         <string>en</string>
         <string>de</string>
         <string>es</string>
         <string>fr</string>
         <string>it</string>
         <string>ja</string>
         <string>ko</string>
         <string>nl</string>
         <string>pt</string>
         <string>ru</string>
         <string>zh</string>
      </array>

```

So yeah.. fixed
