### ISSUE TITLE
icon not appearing in Android Toast

### ISSUE THREAD

**Issue by cvasquez-github** [aritchie/userdialogs#556]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 **- [X] Android**
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
**Xamarin.Android.Support 27.0.2.1**
Target Android 8.1 (Oreo)
Tested in Android 9.0 P devices

## Version of ACR UserDialogs Library
**Acr.UserDialogs 7.0.1**

## Expected Behaviour
Display text, message, and icon when calling Toast, testing with the following code.

`ToastConfig tcf = new ToastConfig(toastMessage);
tcf.SetAction(new ToastAction() { Text = toastText, TextColor = toastTextColor });
tcf.SetBackgroundColor(toastBgColor);
tcf.SetDuration(new TimeSpan(0, 0, 2));
tcf.SetPosition(ToastPosition.Bottom);
tcf.SetMessageTextColor(toastTxtColor);
tcf.SetIcon(toastIconFilename);
UserDialogs.Instance.Toast(tcf);`

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
The toast appears but no icon is displayed. Tried with just the name of the image resource file "icon_toast", including the extension as well "icon_toast.png", but same result. The image is in the Resources/Drawable folder of the Android Xamarin project. The image file Build Action is set to AndroidResource

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
It isn’t supported on android

**Comment by cvasquez-github** [comment]
Oh, good to know!

Maybe would be a good idea to add that as a comment in the function
description and/or documentation?

Thanks!
