### ISSUE TITLE
Soft Keyboard always obstructs Prompt in Landscape view

### ISSUE THREAD

**Issue by adolgov** [aritchie/userdialogs#558]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [X] NET Standard 2.0

Application is running on Xamarin.Android, but Prompt call is in a .NET Standard 2.0 library project that is a dependency to the application project.

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)

SW:
Android 7.1.1
Xamarin.Android.Support.* v27.0.2.1

HW:
Lenovo Tab4 8 (TB-8504F)

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
Prompt moves up to be centered in the "visible" portion of the screen (i.e. the portion not obstructed by the keyboard. I believe that this is how regular Android views with textboxes handle the soft keyboard.) Or maybe an ability to configure where the prompt will pop-up on the screen.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
Prompt pops up, and when the text field is clicked, the soft keyboard obstructs the entire prompt. The user is unable to see where/what they are typing.

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Stale issue
