### ISSUE TITLE
GTK support?

### ISSUE THREAD

**Issue by helzgate** [aritchie/userdialogs#559]
I know you don't currently support it but **can** this be supported in a GTK project now that it's available to us in Xamarin?  

By the way, I tried to use it anyway but got the infamous :  `ArgumentException: [Acr.UserDialogs] This is the bait library, not the platform library.  You must install the nuget package in your main executable/application project`

**Comment by aritchie** [comment]
I don't have any interest in GTK at the moment.  I'll take complete PR's on it if someone wants to do it.
