### ISSUE TITLE
Icons are not displayed in ActionSheet when UseBottomSheet is true

### ISSUE THREAD

**Issue by na2axl** [aritchie/userdialogs#561]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Xamarin.Android.Support.* v27.0.2.1
Android >= 5.0.1

## Version of ACR UserDialogs Library
v7.0.1

## Expected Behaviour
Icons are displayed in ActionSheet even if UseBottomSheet is set to true

## Actual Behavior
Icons are displayed only when UseBottomSheet is set to false

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Already fixed for a future release

**Comment by na2axl** [comment]
Thanks for the fast support 👍
