### ISSUE TITLE
Ability of changing Toast block padding for iOS.

### ISSUE THREAD

**Issue by agat366** [aritchie/userdialogs#569]
## Platform related

 - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s)
iOS 11.4

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
There is any way to setup the toast block padding(s), especially, left and right indents.

## Actual Behavior
The toast doesn't look quite appealing. The left padding is horrible (sorry, but it really is for prod version). However, I can't see any references in docs or code how I can improve that.

![image](https://user-images.githubusercontent.com/1586941/47492356-7d408400-d855-11e8-855d-d952e38fd010.png)

**Comment by aritchie** [comment]
The toasts aren’t meant to be overly customizable to keep the API fairly simple upfront.  However, I’ll take PRs from anyone who can pretty it up :)

**Comment by agat366** [comment]
Well, in my case I just add a few spaces in the beginning of the message to shift it, but this would work only for short one-line messages.
Otherwise, the Toast is not quite useful at all, frankly speaking (at least for iOS).

**Comment by aritchie** [comment]
Ok, your frankness has been heard.... twice now.  I've acknowledge it as an enhancement for anyone to pick up and issue a PR.  It doesn't really need an API enhancement.  It just needs some love in the control itself.  This is time I'm not able to give right now, so if this is a blocker for you, I'd be happy to take a PR or you can find another lib.  Best of luck
