### ISSUE TITLE
Editor/Multiline Textbox

### ISSUE THREAD

**Issue by dannythomas13** [aritchie/userdialogs#571]
I think the library is great and PromptConfig is very flexible but for something like a popup from which you can modify a comment field the Entry control isn't suitable, would it be possible to create a prompt which displays an Editor control so that we can allow users to entry a few hundred characters?

**Comment by aritchie** [comment]
It is possible, I just don't think it is something I want to add personally.  The prompt is already bloated.  Adding multiline opens a floodgate to another wad of things that can occur with editors (auto-grow, sizing on screen a vs b, etc).  I'd recommend something like Rg.Plugins.Popup for a more customized experience.  I'd also be happy to take a PR that covers all 3 platforms on this.
