### ISSUE TITLE
Question About PostAsync with Loading userdialogs

### ISSUE THREAD

**Issue by jagunosra** [aritchie/userdialogs#572]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of ACR UserDialogs Library
Updated

## Expected Behaviour
The asyncpost will not work if userdialogue is included. the entire method should do the postasync api and the userdialogue will load upto hide if done. may i know the reason why?. i am new to xamarin (2 days old) as i am only an asp.net dev. 

## Actual Behavior
`
            private async void UpdateEditDoctor(object sender, EventArgs e)
        {
            using (UserDialogs.Instance.Loading("Loading"))
            {
            //aiRefresh.IsRunning = true;
            //aiRefresh.IsVisible = true;
            string selectedGender = "";

            if (ddlGender.SelectedItem.ToString() == "Female")
            {
                selectedGender = "F";
             }
            else
            {
                selectedGender = "M";
               }

            DoctorModel FinalItems = new DoctorModel()
            {

                DoctorId = myId,
                FName = txtFName.Text,
                MName = txtMName.Text,
                LName = txtLName.Text,
                Street = txtStreetAddress.Text,
                City = txtCity.Text,
                Province = txtProvince.Text,
                BDate = txtBirthDate.Date.ToShortDateString(),
                Specialty = txtSpecialization.Text,
                MobileNumber = txtMobileNumber.Text,
                PhoneNumber = txtPhoneNumber.Text,
                PrcNumber = txtPRCNumber.Text,
                HMO = txtHMO.Text,
                S2 = txtS2.Text,
                PtrNumber = txtPTR.Text,
                Diplomate = txtDiplomate.Text,              
                ProfilePicture = byteData,
                Gender = selectedGender,

            };
                   
            var json = JsonConvert.SerializeObject(FinalItems);
            var content = new StringContent(json, Encoding.UTF8, "application/json");
            HttpClient client = new HttpClient();

        
            var result = await client.PostAsync(Api.BaseURL + "api/doctor/UpdateDoctor", content);

                if (!result.IsSuccessStatusCode)
                {
                    var message = result.RequestMessage;
                    var header = result.Headers;
                    var code = result.StatusCode;
                }

                else
                {
                    
                    //aiRefresh.IsRunning = false;
                    //aiRefresh.IsVisible = false;
                    await DisplayAlert("Successfully Saved", "Your information has been updated!", "OK");                
                    await App.NavigateMasterDetail(new DetailPatientDashboard());

                }
            }
        }`
## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Please fill out the issue template.  Like what platform... what version of UserDialogs? latest?  

What does "not work" mean?  Is it crashing, not displaying, what?

**Comment by jagunosra** [comment]
@aritchie  I am using the latest version of UserDialogs sir.. both iOS and android 

Actually, the userdialogs is working but when im trying to use it with postasync it doesn't return any result from the api... i have waited 5 mins max for it...

**Comment by aritchie** [comment]
This library will not block api calls.  

If I had to guess, your call is crashing (not try/catch on it) and because your method is async void, you can't see the error.

Other issue, as stated in the FAQ, you can't navigate if you have an open dialog.  You need to dispose that dialog ref before navigating or it will crash on android.

**Comment by aritchie** [comment]
I’m going to guess this is a closed case
