### ISSUE TITLE
UserDialogs.Instance.Loading("Loading") not showing animated loading icon

### ISSUE THREAD

**Issue by samrankin** [aritchie/userdialogs#573]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] Android
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)

27.0.2.1

## Version of ACR UserDialogs Library

7.01

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

Compiling using 9.0
Targeting 9.0
Min. Marshmallow

No exception.  Loading popup appears with text as configured however no animated loading symbol.  Works fine on > Oreo.

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Please provide a reproducible sample as it works for me.

**Comment by samrankin** [comment]
Thanks @aritchie.  Basic VS 2017 Xamarin Forms repo attached.  

Marshmallow -> "Progress" OK, "Loading" no symbol

[App1.zip](https://github.com/aritchie/userdialogs/files/2572582/App1.zip)

**Comment by royaza** [comment]
I have the same problem. It was showing the animated load before, but recently it doesn't show it anymore. (Acr.UserDialogs (7.0.1), Xamarin Forms(4.0.0.8055-pre1))

   public void StartWaiting(string WaitingText)
        {
            _lcProgressDialog = UserDialogs.Instance.Loading(WaitingText);
        }

Thank you.
