### ISSUE TITLE
Can't set the Toast background color

### ISSUE THREAD

**Issue by stesvis** [aritchie/userdialogs#575]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [] UWP
 - [x] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
v27.0.2.1

## Version of ACR UserDialogs Library
v7.0.1

## Expected Behaviour
The toast background color should be what I set.

## Actual Behavior
In Xamarin.Forms I am using this code in the PCL (.Net Standard 2.0):

```
var toastConfig = new ToastConfig("Saved");
toastConfig.SetDuration(3000);
toastConfig.SetBackgroundColor((Color)Application.Current.Resources["successColor"]);
toastConfig.SetMessageTextColor(Color.White);
UserDialogs.Instance.Toast("Saved");
```
Where I define the color in App.xaml:
`<Color x:Key="successColor">#41b341</Color>`

But the toast always shows with background color gray (the default one).

**Comment by aritchie** [comment]
You are trying to cast Xamarin.Forms.Color to Systrm.Drawing.Color by the looks of it.  If you put System.Drawing.Color.Blue in place of your cast, you’ll see the bgcolor working.

**Comment by stesvis** [comment]
Hi @aritchie I've tried with this too, but it's still gray:
`toastConfig.SetBackgroundColor(System.Drawing.Color.Green);`

**Comment by aritchie** [comment]
You aren’t passing that toastConfig to the actual toast method.

**Comment by stesvis** [comment]
What a waste of your time!
I'm sorry man, I didn't even realize that till you said so.

![image](https://user-images.githubusercontent.com/6062684/48748522-6f9fd380-ec34-11e8-8f74-f2b746b2f778.png)

**Comment by aritchie** [comment]
No worries.  Shit happens
