### ISSUE TITLE
Loading Indicator not shown at center of screen

### ISSUE THREAD

**Issue by bastianbecker21** [aritchie/userdialogs#576]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
iOS 12.1

## Version of ACR UserDialogs Library
6.5.1

## Expected Behaviour
Loading Indicator is shown at center of screen

## Actual Behavior
It works good in general but it's not shown at center of screen after keyboard is shown and hidden to input text in entry like login screen. It's shown at upper side.

## Code of Conduct
UserDialogs.Instance.ShowLoading("");

**Comment by bastianbecker21** [comment]
#491 doesn't give me solution, As I commented, it's just xamarin forms project and doesn't have any view controller, In this case, how can I fix this issue? Please give me solution.

**Comment by aritchie** [comment]
I don't have a solution for you then.  I've explained how it works with the top viewcontroller.
