### ISSUE TITLE
Loading is not hidden after the dispose

### ISSUE THREAD

**Issue by myisoria** [aritchie/userdialogs#578]
Hello,
in my case it does not work.

Simply  example test:

```
using (UserDialogs.Instance.Loading("loading"))
{
   //await Task.Delay (100);
}
```
The problem is that it is not hidden after the dispose.

with a Task.Delay (100) inside it goes

anyone have an idea?

-Tom

**Comment by aritchie** [comment]
Please be respectful and use the issue template so I don't have to ask routine questions

1) What OS and Version?
2) How are you calling Init?
3) Is there anything in the output?

**Comment by myisoria** [comment]
Hi aritchie,
sorry my mistake.

OS Android 7.1
Xamarin.Forms 3.4.0.1008975
Device Zebra TC25
ACR UserDialogs 7.0.1
Init in MainActivity OnCreate

` UserDialogs.Init(this);`

Output
```
12-28 11:58:36.191 D/Mono    (11964): Assembly Ref addref Isoria.XamarinApp[0x7f8f6ae580] -> Acr.UserDialogs[0x7f8f63aa00]: 3

12-28 11:58:36.207 D/Mono    (11964): Assembly Ref addref Acr.UserDialogs[0x7f8f63aa00] -> AndHUD[0x7f8f63ad00]: 3
```

it does not work
```
using (UserDialogs.Instance.Loading("Login user"))
{
        //await Task.Delay(100);
}//-- do not hide after dispose
```
it works
```
using (UserDialogs.Instance.Loading("Login user"))
{
        await Task.Delay(100);
}//-- hide after dispose
```

Many Thanks

-Tom

**Comment by myisoria** [comment]
That is really crazy.

When the Zebra scanner triggers the event, the "UserDialogs.Instance" is not the same.
I have this

`AppManager.Instance.ScanInput (data.Data);`

With

`Xamarin.Forms.Device.BeginInvokeOnMainThread (() => AppManager.Instance.ScanInput (data.Data));`

replaced.

Now it's working.

What confuses me is that it works with a delay.

I had the mistake of thinking ;)

Thank you for your time.

-Tom
