### ISSUE TITLE
Unable to install this plugin

### ISSUE THREAD

**Issue by HenrikHolmIT** [aritchie/userdialogs#579]
Im totally sorry if this is the wrong place to raise flag but I have tried to install and this plugin for days now and no matter which tutorial I find it never works.

This fork seems to be active and I hope some can point me in the right direction.

I've tried to download Plugin.UserDialogs from Nuget and installed it on all projects.

Then if I go to my Android project to do UserDialogs.Init(this);
But when I then try to use a dialog in my app I cannot find a UserDialogs.Instance.ShowSuccess function. I have a reference and I can find ShowLoading but not ShowSuccess...

What to do?

Again I totally sorry if this is the wrong place to post a question like this..

**Comment by aritchie** [comment]
Please use the issue template in the future as it helps with the usual questions.

There is no ShowSuccess.  I removed that method quite some time ago.
