### ISSUE TITLE
AndHud not found

### ISSUE THREAD

**Issue by torturegenitale** [aritchie/userdialogs#582]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
28.0.0.1

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
UserDialogs.Instance.Loading() to show up.

The Output Window provided these informations:

01-28 01:57:27.867 D/Mono    (24108): AOT: image '/storage/emulated/0/Android/data/com.myproject.mediatest/files/.__override__/AndHUD.dll.so' not found: dlopen failed: library "/data/app/com.myproject.mediatest-1/lib/arm/libaot-AndHUD.dll.so" not found
01-28 01:57:27.867 D/Mono    (24108): AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d15-9/xamarin-android/external/mono/sdks/out/android-armeabi-v7a-release/lib/mono/aot-cache/arm/AndHUD.dll.so' not found: dlopen failed: library "/data/app/com.myproject.mediatest-1/lib/arm/libaot-AndHUD.dll.so" not found

I did not pay much attention at first and finally solved it by rolling back AndHUD version to 1.2. Acr.Userdialogs does not seem to be compatible with the 1.4 AndHUD new version. I just wanted to share my solution for this problem. 
Maybe someone can indicate if Acr will be updated in the near future?

## Actual Behavior
Not Showing Up

**Comment by danielPollackGitHub** [comment]
Same issue here. Very frustrating. 1.4 AndHUD needs to be supported!!!
