### ISSUE TITLE
[UWP] Icons not shown on ActionSheet

### ISSUE THREAD

**Issue by Brosten** [aritchie/userdialogs#586]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [x] UWP
 - [] NET Standard 2.0

## Version of ACR UserDialogs Library
7.0.1

## Expected Behaviour
Icons next to text in action sheet

## Actual Behavior
No Icons displayed

UserDialogs.Instance.ActionSheet(myActionSheetConfigWithIcons);

Works fine on Android and iOS, but no Icon showing up on UWP

**Comment by aritchie** [comment]
Insufficient details provided

**Comment by Brosten** [comment]
Ok, here is a bit more details. I'm using the ActionSheet method in order to show some altternatives, with Icons to the left. Creating an ActionSheetConfig with ActionSheetOptions, setting the Icon to "myIcon.png". My Icon shows on ios and Android, but doesn't show up on UWP. I have also tried to include Assets in the path (like @"Assets\myIcon.png") but with no success. Does the UWP version not support Icons in the ActionSheet or am I doing something wrong with my Icon path?
