### ISSUE TITLE
handle back button in loading method 

### ISSUE THREAD

**Issue by mo-kml** [aritchie/userdialogs#587]
Hi
how to cancel loading dialog?
I wanna cancel loading on back button in android but i couldn't override it.
I tried using cancelText hope that it shows a cancel button but it didn't and tried onCancel method but i didn't work either.
if my task in Using block takes long i wanna give user the choice to cancel the task. but i can't cancel the loading block

>         public SampleViewModel(IUserDialogs userDialogs)
>         {
>             Select = new BitDelegateCommand(async () =>
>               {
>                   using (userDialogs.Loading())
>                   {
>                       //my task
>                   }
>               });

 - [] Android

**Comment by aritchie** [comment]
You have to set a cancel action in order for the cancel button to show up.

**Comment by mo-kml** [comment]
how can i set custom cancel button on loading block?
it's just not really user friendly because it's really really close to loading text and makes user confuse about it.

**Comment by aritchie** [comment]
Source code is all open and there are samples of exactly what you are looking for

**Comment by JigarM** [comment]
@aritchie Can you have any example how to do that?

**Comment by aritchie** [comment]
@JigarM same answer as above - samples in the repository
