### ISSUE TITLE
Add icon to Action Sheet items

### ISSUE THREAD

**Issue by martijn00** [aritchie/userdialogs#59]
Would it be possible to add functionality to this project to add an icon to row items?

Something like: https://www.google.com/design/spec/components/dialogs.html#dialogs-simple-dialogs

**Comment by aritchie** [comment]
I believe so.  Windows and android would be ok for this.  iOS would unfortunately be left behind

**Comment by martijn00** [comment]
How do you think that should work? It would be good if the user can set different image per platform, or maybe put the name of the image into the item and then resolve that in the platform.

**Comment by aritchie** [comment]
A rough idea is to use static defaults (it is my way of dealing with locales and theming via the config classes).  This also relieves me from dealing with platforms specifics.  What I usually do for platform specifics is create a startup type module and init everything there which could also be checking the platform.  I'll branch something out today

**Comment by aritchie** [comment]
https://github.com/aritchie/userdialogs/commit/e269f7e6b30e901f43ddcd4d7b4c51e4e040e021

This is the initial thought.  
You can set the icon global (ActionSheetConfig.DefaultItemIcon)
Per sheet instance (ActionSheetConfig.ItemIcon)
or per sheet item (ActionSheetOption.ItemIcon)

**Comment by martijn00** [comment]
Seems like i could work with that! Would it be possible to set the position of the icon, like: right and left?

**Comment by martijn00** [comment]
Is there any work to be done on this before release?

**Comment by aritchie** [comment]
Yes.  The actual implementations on windows and android.

**Comment by martijn00** [comment]
Looking at iOS it seems it would be possible there too: 
http://stackoverflow.com/a/28713433/4222823

item.SetValueForKey(SomeImage, new NSString("image"));

**Comment by aritchie** [comment]
Oh that is nice.  I'll look into it.  Thanks.

I'll be honest, this isn't a priority at the moment, but I do intend to implement this.  Maybe not the left/right scenario, but definitely the icon.

**Comment by martijn00** [comment]
I might be able to make a PR. Let me see what i can do.

**Comment by martijn00** [comment]
I've added an implementation for iOS and Android: https://github.com/martijn00/userdialogs/tree/Icons
Note that it is untested as i can't test it right now, but it compiles. Should i make a PR?
