### ISSUE TITLE
public static class UserDialogs is empty

### ISSUE THREAD

**Issue by whitewabbit** [aritchie/userdialogs#590]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS

## Version of ACR UserDialogs Library
Latest stable (7.0.2)

## Expected Behaviour
Show Loading

## Actual Behavior
UserDialogs.Instance.ShowLoading Not available in iOS

Extra Notes:
It occurs when I updated Xamarin.Forms to v4.0.0.169046-pre5

**Comment by aritchie** [comment]
This library has nothing to do with Xamarin Forms so it wouldn't cause any issues like this.  

The method is still in the interface and implemented on iOS, so by "not available" what do you mean?  It isn't working, it is crashing, etc?

**Comment by aritchie** [comment]
Nevermind - I see it.  Thanks
