### ISSUE TITLE
Error Payload file 'C:\Users\MyUser\.nuget\packages\acr.userdialogs\7.0.2\lib\uap10.0.16299\Acr.UserDialogs\Acr.UserDialogs.xr.xml' does not exist

### ISSUE THREAD

**Issue by Brosten** [aritchie/userdialogs#591]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [x] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Windows 10 Pro v 1809
Android.Support = 28.0.0.1

## Version of ACR UserDialogs Library
7.0.2

## Expected Behaviour
UWP Project compiling

## Actual Behavior
I get the following error
Error Payload file 'C:\Users\MyUser\.nuget\packages\acr.userdialogs\7.0.2\lib\uap10.0.16299\Acr.UserDialogs\Acr.UserDialogs.xr.xml' does not exist

When browsing there, I can see that the folder Acr.UserDialogs are missing under uap10.0.16299. I guess it's a missconfiguration of the nuget package? I have read about workarounds with creating the directory manually etc. Still thought it could be helpful to report it here. It worked great in 7.0.1.

**Comment by irongut** [comment]
I have the same issue when upgrading from v7.0.1 to v7.0.3!

Payload file 'C:\Users\username\.nuget\packages\acr.userdialogs\7.0.3\lib\uap10.0.16299\Acr.UserDialogs\Acr.UserDialogs.xr.xml' does not exist.

This is preventing compilation of the UWP project in my solution.

**Comment by pavloss** [comment]
I'm currently experiencing the same issue on 7.0.3 right after updating.
Could you please the workaround?

> Error Payload file 'C:\Users\PUser\.nuget\packages\acr.userdialogs\7.0.3\lib\uap10.0.16299\Acr.UserDialogs\Acr.UserDialogs.xr.xml' does not exist.	XCHXamarinKiosk.Uwp

**Comment by Brosten** [comment]
@pavloss 
I copied the folder structure from 7.0.1 
C:\Users\MyUser.nuget\packages\acr.userdialogs\7.0.1\lib\uap10.0.16299\Acr.UserDialogs\

**Comment by aritchie** [comment]
Here's the workaround for all those that for some reason need to update right away - if you are using UWP and it matters, DO NOT UPDATE.  Posting "I'm having this issue too" IS NOT HELPFUL.  The main portion of the update was to deal with the original people who had OCD and needed to update ANDHUD on android simply because an update was available on nuget!!!

**Comment by aritchie** [comment]
Should be fixed in 7.0.4
