### ISSUE TITLE
7.0.3 available, but no information in changelog + Nuget package version in ReadMe outdated

### ISSUE THREAD

**Issue by FinHorsley** [aritchie/userdialogs#592]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Please don't file things like this.  It isn't an actual issue with the library itself.

**Comment by FinHorsley** [comment]
I do not agree with this. Our app is in production, and it is important to be able to see changes to libraries we are using so that we can determine if it is safe to update them (check if there are breaking changes etc.)!

**Comment by aritchie** [comment]
No offense, I don't care if you agree or not.  You aren't a customer, you are a consumer

**Comment by FinHorsley** [comment]
You might as well remove the changelog then, clearly doesn't serve a purpose if it's not updated

**Comment by aritchie** [comment]
Look - it was a minor fix that was pushed as a mistake with UWP.  If you are going to argue or be rude, please go elsewhere.  I'm not paid for this.  I do it in my spare time.

**Comment by FinHorsley** [comment]
I'm not looking to be rude, i just felt like your response was too blunt. I get that it was a minor problem, please don't get the impression that i'm picking holes either
