### ISSUE TITLE
Wrong depency in nuspec for MonoAndroid.Version=8.1

### ISSUE THREAD

**Issue by patosz** [aritchie/userdialogs#594]
The library depends on Android Support Design version that does not exist for the target MonoAndroid.Version=8.1 

7.0.2 -> Xamarin.Android.Support.Design (>= 27.1.0.1)
7.0.3 -> Xamarin.Android.Support.Design (>= 27.1.0.1)

This causes an annoying false positive package downgrade warning at build.

**Comment by aritchie** [comment]
If something is annoying you in the future, please feel free to submit a patch.  7.0.4 should take care of this

**Comment by MagicAndre1981** [comment]
@aritchie simply update the Xamarin.Android.Support dependencies to 28, here the libs are included for all APIs, no longer a need to use latest SDK version:

![image](https://user-images.githubusercontent.com/8274816/54013091-4c177f00-4178-11e9-86a4-8c79c344f114.png)

https://blog.xamarin.com/multi-targeting-with-android-support-library-v28/
