### ISSUE TITLE
doesn't work in the android pie version

### ISSUE THREAD

**Issue by davidepetrilli** [aritchie/userdialogs#598]
sometimes It doesn't work in the android pie version, the application closes without error messages

**Comment by davidepetrilli** [comment]
sometimes It doesn't work in the android pie version, the application closes without error messages

**Comment by davidepetrilli** [comment]
Why was the dissolution closed without even an answer?

**Comment by aritchie** [comment]
You didn't file any sort of details - an error, a reproducible issue, or any of the questions in the issue template (the one you deleted before filing a one line statement).  As a professional developer, how would you answer someone that says "your app doesn't work"?  I have left the code of conduct below for you.



## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Can you share the exception?  Have you tried wrapping your code in try/catch?
