### ISSUE TITLE
UserDialog.Init() on iOS

### ISSUE THREAD

**Issue by Vinnie1991** [aritchie/userdialogs#6]
I'm just using Xamarin Forms, so it may be a problem of that ;).

But I'm using MVVM in Xamarin Forms. When I have a button I want to see a dialog with the input in the entry fields. Not very important.

Only when I'm calling UserDialogs.Init(); in *iOS*, I get a warning in Visual Studio that is Obsolate.
When I run this, the program will crash on this line of code.

How can I fix this?

**Comment by aritchie** [comment]
Read the obsolete problem and the crash.  They explain in detail what your problem is!
