### ISSUE TITLE
Where did the lib\wp8 directory go?

### ISSUE THREAD

**Issue by Brosten** [aritchie/userdialogs#60]
After updating to version 4.0.3 I have had alot of problems with the WinPhone Project (Silverlight 8.1).
I noticed that the WP8 directory existing in v 3.4.2 no longer exists... Instead I have WPA81 and uap10.0 directories.

I guess I should use the dll:s from WPA81? But they also gives me odd exceptions, like "The application called an interface that was marshalled for a different thread..."

Or am I missing something?

**Comment by aritchie** [comment]
My suggestion is to go back to 3.4.2 for now.  I didn't want to carry WP81 forward because of the new functionality that was added.  In the near future, only UAP will matter anyhow.

**Comment by Brosten** [comment]
Ok, then I know... Will revert to 3.4.2 for now.
Thank you
