### ISSUE TITLE
TimePromptConfig - change minute interval for Android

### ISSUE THREAD

**Issue by susyUberbiz** [aritchie/userdialogs#601]
Hi,

I have created a custom timepicker renderer for Android that changes the minute interval to 15 mins, however, doesn't know how to assign TimePromptConfig to use this custom timepicker.

Any suggestion?

Thank you.

Regards,

Susy

**Comment by aritchie** [comment]
This project has nothing to do with Xamarin forms so a custom renderer isn’t going to do anything to the timeconfig here
