### ISSUE TITLE
UserDialog Toast not showing in Android when enabled Proguard and change Linking to Sdk and User Assemblies (Xamarin Form))

### ISSUE THREAD

**Issue by RaashVision** [aritchie/userdialogs#604]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [o] Android
 - [] UWP
 - [o] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Android 7.1.1 to 9.0
Xamarin.Android.Support.v4 27.0.2.1
Xamarin.Android.Support.v7.AppCompat 27.0.2.1

## Version of ACR UserDialogs Library
7.0.4

## Expected Behaviour
When I call the userDialogs.Toast("Successfully Update", TimeSpan.FromSeconds(4)) , the toast should show.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_
The toast does not show at all. The Toast only shows when I change the Linking in Android Properties -> Android Options -> Linking to None. If I change the Linking to Sdk and User Assemblies, toast not showing. Below is the assemblies that I included in 'Skip linking assemblies' -

Mono.Android;Plugin.CurrentActivity;Acr.UserDialogs;Behaviours.Forms;ExpandableView;Plugin.Permissions;Plugin.Forms.ButtonCircle;Rg.Plugins.Popup;SuaveControls.FloatingActionButton;Syncfusion.Licensing;Syncfusion.Xamarin.SfAutoComplete;VMS.ResidentMobileApp;Xam.Plugin.Media;Xam.Plugins.Settings;Xamarin.Essentials;Xamarin.FFImageLoading.Forms;Xamarin.FFImageLoading.Svg.Forms;Xamarin.FFImageLoading.Transformations;Xamarin.Forms;Xamarin.Forms.InputKit;Xamarin.Android.Support.v4;Xamarin.Android.Support.v7.AppCompat;Xamarin.Android.Support.v7.CardView;Xamarin.Android.Support.v7.MediaRouter;System.IdentityModel.Tokens.Jwt

I even add the ACR.UserDialogs in the skip linking assemblies but still toast is not showing. I know it has something to do with missing library during linking. But i just cannot find it which one.

Summary
1. With Proguard and Linking (None) - Toast is working
2. With Proguard and Linking (Sdk and User Assemblies) -  Toast not working
3. All the other functionality of the app is working accept this toast 

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Please supply an exception so I can see what’s being delinked

**Comment by RaashVision** [comment]
Bro It does not throw any error bro. I put try catch around it still it does not throw anything.

**Comment by aritchie** [comment]
Please be respectful if you want help.  Calling me "bro" is not appropriate.

It likely isn't a linker issue if you aren't getting a MissingMethodException.  Do you see anything in the console output?  Do you have reproducible sample?

**Comment by RaashVision** [comment]
I'm sorry Mr Aritchie. I should not called you "bro".
I did'not see any error or weird output at the debug. I have created a sample that replicate the error. Try change the Android Properties 
1 .-> Android Options -> Linking to None  (Working)
2. -> Android Options -> Linking to Sdk and User Assemblies (Not Working)

The file at link below
https://drive.google.com/open?id=16Ctbf6oZfcRKfeaA_P_0asUNSGz1yYQd

**Comment by candidodmv** [comment]
Hi, I'm getting the same issue when update from 7.0.1 to 7.0.4

**Comment by pablogupi** [comment]
In my case, when option "Use the concurrent garbage collector" is active (release mode) and  Linking Sdk Assemblies only, dialogs not show.
If I disabled garbage collector, dialogs show correctly

**Comment by aritchie** [comment]
If you set your target to 9.0, then you need to upgrade your support libraries to 28.0.0.1.  If you look at the buffet support for 7.0.4 of this library

Monoandroid81 uses 27.x support libs
Monoandroid90 uses 28.0.0.1

**Comment by candidodmv** [comment]
@pablogupi I'm with same problem the dialogs not show, only appering the overlay. I've checkout your suggestions @aritchie and @pablogupi but the issue keeps. Thanks

**Comment by aritchie** [comment]
@candidodmv Please don't post in closed topics.  If you target the proper android target of 9.0 with v28.0.0.1 of the support libraries, it will work just fine
