### ISSUE TITLE
ShowLoading work only one time on MvvmCross

### ISSUE THREAD

**Issue by NatashaMykytyn** [aritchie/userdialogs#606]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] Android
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)

28
## Version of ACR UserDialogs Library

7.0.4
## Expected Behaviour
Method ShowLoading works always

## Actual Behavior
Method ShowLoading work only one time

## Code of Conduct

UserDialogs.Instance.ShowLoading();
var products = new await _productService.GetProducts();
UserDialogs.Instance.HideLoading();

**Comment by NatashaMykytyn** [comment]
If I call this code one more then loading dialog not shown

**Comment by aritchie** [comment]
Please provide a full sample of the issue.  Also, you are better off doing

using (UserDialogs.Instance.Loading(...))
{
   /// your async method call here
}

**Comment by NatashaMykytyn** [comment]
@aritchie 
In Android

```
public override void OnCreate()
{
    base.OnCreate();
    UserDialogs.Init(this);
}

```
In App.cs in method Initialize() 
`Mvx.IoCProvider.RegisterSingleton<IUserDialogs>(() => UserDialogs.Instance);
`
On main page I called 

```
public override async void ViewAppearing()
        {
            base.ViewAppearing();
            
            UserDialogs.Instance.ShowLoading();
            Products =
                new MvxObservableCollection<ProductsModel>(await _productService.GetProducts());
            UserDialogs.Instance.HideLoading();
        }
```

**Comment by NatashaMykytyn** [comment]
I'm tying use
```
using (UserDialogs.Instance.Loading())
            {
                Productst =
                    new MvxObservableCollection<ProductsModel>(await _productService.GetProducts());
            }
```
The same result.
When I go next from with page and go back then Loading doesn't work but data long loading without loading dialog.

**Comment by NatashaMykytyn** [comment]
It will worked when I use Loading in ViewAppeared().
@aritchie thanks
