### ISSUE TITLE
Feature request - Toast improvements

### ISSUE THREAD

**Issue by galadril** [aritchie/userdialogs#607]
## Feature request
1) I would love to have a different view for toast that have a long text (like 2 lines) and have an action button > If an action is long, it can be displayed on a third line.

![mio-design_assets_11e9M-CnUBfAefLLAMtckb_opQih-E3Gm_understanding-snackbars-text-2-lines-longer-action](https://user-images.githubusercontent.com/14561640/56196289-d932db00-6036-11e9-8e3f-92f43023477b.png)

2) Maybe we could add an icon like:
![mio-design_assets_1_u7D-s8fZquh7lCo8cHsenum8sMzFCq3_understanding-snackbars-text-dont-icon](https://user-images.githubusercontent.com/14561640/56196470-2dd65600-6037-11e9-8def-11d5ce4a324f.png)

I copied these from the material guidelines:
https://material.io/design/components/snackbars.html#anatomy

**Comment by galadril** [comment]
Or this is maybe a new components "Snackbar" ?

**Comment by galadril** [comment]
The feature would still be pretty neat.. please dont flag this as stale 🗡

**Comment by aritchie** [comment]
I’m not implementing this and I don’t see anyone else doing it either.
