### ISSUE TITLE
[Android] 'UserDialogs' does not contain a definition for 'Init'

### ISSUE THREAD

**Issue by pdecostervgls** [aritchie/userdialogs#608]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] Android

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)

- Xamarin.Android.Support.Compat: v28.0.0.1
- Xamarin.Android.Support.Core.Utils: v28.0.0.1

## Version of ACR UserDialogs Library
v7.0.4

## Expected Behaviour
As instructed in the readme, add a call to ```Acr.UserDialogs.UserDialogs.Init()``` in my MainActivity. Expect no errors and be able to trigger dialogs in my app.

## Actual Behavior
```Error 	CS0117	'UserDialogs' does not contain a definition for 'Init'```

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Are you using packages.config?  What IDE?  Can you provide a small reproducible sample? 

I don’t have anywhere near enough details to even guess what the actual issue is

**Comment by pdecostervgls** [comment]
@aritchie Understandably, but I didn't know beforehand what you needed :) I'll cooperate fully :)
To be exact, I added it to a solution using Uno Platform (http://platform.uno).

- I can't find a packages.config.
- I'm running Visual Studio 2019 16.0.2
- I'll get started on a repro project, are you familiar with Uno?

**Comment by pdecostervgls** [comment]
Repro at: https://github.com/pdecostervgls/repro-acruserdialogs

**Comment by aritchie** [comment]
Your android target is set to 8.0.  You need to set it to 8.1+

**Comment by pdecostervgls** [comment]
> Your android target is set to 8.0.  You need to set it to 8.1+

Yes! That's it! Didn't see that requirement in the docs though.

**Comment by aritchie** [comment]
It is in the nuget package targets.  If you want docs, feel free to send a PR.
