### ISSUE TITLE
More styling for toasts

### ISSUE THREAD

**Issue by martijn00** [aritchie/userdialogs#61]
This might only apply for iOS but i would like to set the Width, Height, Text align, Text size, and Font-style of the Toast config.

**Comment by aritchie** [comment]
These are more view concerns and have a lot of platform specifics that I don't want to get into for this library.  Sorry.

**Comment by martijn00** [comment]
Ok, but another thing. Now the toast on ios are show in the top. How can i show them in the bottom?

**Comment by aritchie** [comment]
I'm never going to have a one-size fits all library.  All methods are marked virtual, so you can override the main toast method yourself and swap to the bottom.
