### ISSUE TITLE
samung device keyboard separator decimal not display

### ISSUE THREAD

**Issue by reiterasrls** [aritchie/userdialogs#610]
- [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Android 7.1 Android 8.0

## Version of ACR UserDialogs Library
7.0.4

when use input dialog NumberDecimal in samsung device not display separator decimal with italian language.
I resolve change txt paramter from textview to edittext in your PromptBuilder and add txt.SetRawInputType.
Please can you confirm my solution and update your project?

**Comment by aritchie** [comment]
Raw input type is already set.  Please send a PR if you want me to look at something

**Comment by reiterasrls** [comment]
![Screenshot_20190507-114319 1](https://user-images.githubusercontent.com/24302188/57290399-a02dd980-70bd-11e9-9b72-68670ec21014.png)

as you can see not display any separator (comma or dot)

**Comment by aritchie** [comment]
I get there is a bug.  What I’m trying to understand is what is being requested which is why I’ve requested a PR

**Comment by reiterasrls** [comment]
io ti chiedo se è possibile risolvere il bug direttamente sulla libreria oppure se il problema è generato dal pacchetto nuget. aggiungendo il tuo codice sorgente al progetto sembra funzionare correttamente. scusami ma sono nuovo a non so cosa è un PR

**Comment by aritchie** [comment]
I'm sorry - I still don't know what you're asking me to fix.  If you don't know how to PR, simply copy/paste it into the chat

**Comment by reiterasrls** [comment]
Sorry, i hope to explain better.
i did two tests:
1) install your nuget package and i have problem with separator.
2) download you source code..recompile and add project reference to my code and seems to work.
My question...is possible nuget package problem?? 
Your work is beautiful and I would like to use your package not your source code

**Comment by aritchie** [comment]
I don’t know.  I don’t have the problem and I haven’t tested it myself.  You have to tell me

**Comment by jonaswde** [comment]
I came across the same issue on an Samsung Galaxy Tab A (2016) with Android 8.1.0. It seems to be related to Samsung devices using the _Samsung keyboard_ as soft keyboard. Same issue as described in #418.

To fix it you have to modify the _**SetInputType**_ method in _**src/Acr.UserDialogs/Platforms/Android/Builders/PromptBuilder.cs**_. Setting the _**KeyListener**_ before setting the _**InputType**_ seems to fix the issue. Source: [https://stackoverflow.com/questions/37721694/android-keyboard-with-number-and-decimal-for-lg-g4/40507863#40507863](https://stackoverflow.com/questions/37721694/android-keyboard-with-number-and-decimal-for-lg-g4/40507863#40507863)

[PromptBuilder.cs.patch.txt](https://github.com/aritchie/userdialogs/files/4576309/PromptBuilder.cs.patch.txt)

So put line 170
`txt.KeyListener = DigitsKeyListener.GetInstance($"1234567890{CultureInfo.CurrentCulture.NumberFormat.NumberDecimalSeparator}{CultureInfo.CurrentCulture.NumberFormat.NegativeSign}");`
before line 168
`txt.InputType = InputTypes.ClassNumber | InputTypes.NumberFlagDecimal | InputTypes.NumberFlagSigned;
`

**Comment by reiterasrls** [comment]
thanks for your suggest...i resolved long time ago with this fix but I didn't want to modify your source code.
great job your library

**Comment by matteopiccioni** [comment]
I have the same problem
With a Samsung S10, italian keyboard.

I show to the user a PromptAsync with InputType = InputType.DecimalNumber.
In Samsung keyboard I can see the '.' but I cant see the ','
If I tap the '.' the . is not added to the entry (correct) but I should see the ',' key (as in other phones)
Thanks
