### ISSUE TITLE
Question: Cancel click event alert.

### ISSUE THREAD

**Issue by AnthonyLatty** [aritchie/userdialogs#612]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [*] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of ACR UserDialogs Library
Latest

## Expected Behaviour
Is there a way to get the cancel button clicked? I want when the user clicks the cancel button it does something else.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
For what function specifically?  There are a bunch with Cancel buttons.  I usually use 
```csharp
.SetCancel("Cancel Button Text", () => {
// do what you want here
})
```

**Comment by AnthonyLatty** [comment]
The control is UserDialogs.Instance.Alert

**Comment by aritchie** [comment]
There is no cancel button on alert.  Only OK.  Cancel actions appears on actionsheets, progress, confirms, prompts, etc

**Comment by AnthonyLatty** [comment]
Can you provide a snippet of an any using the cancel actions?

**Comment by aritchie** [comment]
I did above.  There is also samples located within this repository

**Comment by AnthonyLatty** [comment]
Ok thanks.
