### ISSUE TITLE
Instance.HideLoading()  not HIDE  in IOS

### ISSUE THREAD

**Issue by ilakidain** [aritchie/userdialogs#613]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
(from .csproj)

<PackageReference Include="Xamarin.Android.Support.v4" Version="27.0.2.1" />
<PackageReference Include="Xamarin.Android.Support.Design" Version="27.0.2.1" />
<PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="27.0.2.1" />
<PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="27.0.2.1" />
<PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="27.0.2.1" />
<PackageReference Include="Xamarin.Android.Support.Vector.Drawable" Version="27.0.2.1" />
<PackageReference Include="Xamarin.Android.Support.Animated.Vector.Drawable" Version="27.0.2.1" />
<PackageReference Include="Xamarin.Android.Support.v7.RecyclerView" Version="27.0.2.1" />
<PackageReference Include="Xamarin.Android.Support.v8.RenderScript" Version="27.0.2.1" />

IOS Versión [12.1]
![screen](https://user-images.githubusercontent.com/31854644/58091957-39371700-7bcb-11e9-9c13-14ffd763ebe5.png)

## Version of ACR UserDialogs Library 
Versión 7.04

## Expected Behaviour
Firts, ALLAN , thank you the Library  👍 👍 
The Issue is IN IOS the call to " UserDialogs.Instance.HideLoading();" not HIDE the alert 
-----------------------------------------------

In Android Work Properly 👍 
In IOS the Alert NOT DISAPERING :-(

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct

** NOTE 1 In service are ine error (Json incorrect, for example)
** NOTE 2 IN IOS the ALERT NO DISAPEARING 

View: (MainView)
(press button)
       async private void EnergyPrices_Clicked(object sender, EventArgs e)
        {
            using (UserDialogs.Instance.Loading(ResourcesRespond.UI_HOMETAB_RECOVERING_FROM_SERVER))
            {
                await Task.Delay(100);
                await Navigation.PushAsync(new EnergyPrices()); // OK
            }
        }

View: (EnergyPrices.cs)
	public EnergyPrices () // ctor
	{
		InitializeComponent ();
	        BindingContext = ViewModelLocator.Instance.Resolve<EnergyPricesViewModel>();
        }

ViewModel:
public EnergyPricesViewModel(IEnergyPricesServices energyPricesServices, ILogActions logActions)  **// ctor**

        {
            _energyPricesServices = energyPricesServices;
            _energyPriceValues = new ObservableCollection<GridEnergyPrices>(); 
            _logActions = logActions;
            _itemError = null;
            this.GetEnergyPrice();
	}

        private  void GetEnergyPrice()
        {
            List<CDM> _energyPrice = new List<CDM>();
            titleerror = ResourcesRespond.UI_ERROR_ENERGYPRICES_TITLE;
            message = ResourcesRespond.UI_ERROR_ENERGYPRICES_ERROR;
            Task t = Task.Run(async  () => {
                try
                {
                    _energyPrice = await _energyPricesServices.GetEnergyPrice();  // **NOTE 1
                }
                catch (Exception ex) // ¿Problemas con la serializacion?
                {
                    messageDev = $"Error :";
                    _itemError = new LogItemError() { Message = ex.Message, Title = titleerror };
#if (!DEBUG)
                    message = messageDev;
#endif
                }
            });
            t.Wait();

            if (_itemError != null)
            {
                
                    UserDialogs.Instance.HideLoading();  // ** NOTE 2
                    UserDialogs.Instance.Alert(message, titleerror, ResourcesRespond.UI_DISPLAYALERT_OK);
                    _logActions.InsertErrorLog(new LogItemError { Message = _itemError.Message, Title = _itemError.Title });
            }

// Bla bla
// bla bla 
// Process _energyPrice for View
// 
}

**Comment by aritchie** [comment]
HideLoading has no effect on Loading.  It is the composite method to ShowLoading.  

```csharp
using (UserDialogs.Instance.Loading(...))
{
}
```
I see a navigation within your loading call which is not supported - see point #3 in https://github.com/aritchie/userdialogs/blob/master/docs/faq.md

**Comment by ilakidain** [comment]
Thanks Allan, I'll make the code changes.

My mistake was that Android works as I expected and not in IOS.

Thank you for the quick response.

**Comment by ilakidain** [comment]
Hi Allan:

As the issue is closed (I don't want to open another one), but I want to say how it solves the problem.

Simply moving then “Binding” from “Constructor”  to  “On Appering”

**NO
namespace Respond.Portable.Views.EnergyPrices
{
       [XamlCompilation(XamlCompilationOptions.Compile)]
       public partial class EnergyPrices : ContentPage
       {
             public EnergyPrices ()
             {
                    InitializeComponent ();
            this.slideView.Commands.Add(new CustomSlideViewCommand());
            BindingContext = ViewModelLocator.Instance.Resolve<EnergyPricesViewModel>();
        }
    }
}
** YES
namespace Respond.Portable.Views.EnergyPrices
{
       [XamlCompilation(XamlCompilationOptions.Compile)]
       public partial class EnergyPrices : ContentPage
       {
             public EnergyPrices ()
             {
                    InitializeComponent ();
            this.slideView.Commands.Add(new CustomSlideViewCommand());
        }
        protected override void OnAppearing()
        {
            base.OnAppearing();
            BindingContext = ViewModelLocator.Instance.Resolve<EnergyPricesViewModel>();
        }
    }
}


The call to View.
       async private void EnergyPrices_Clicked(object sender, EventArgs e)
        {
            using (UserDialogs.Instance.Loading (ResourcesRespond.UI_HOMETAB_RECOVERING_FROM_SERVER))
            {
                await Task.Delay(100);
                await Navigation.PushAsync(new EnergyPrices()); // OK
            }
       }

Thank.

Ignacio

De: Allan Ritchie <notifications@github.com>
Enviado el: miércoles, 22 de mayo de 2019 2:30
Para: aritchie/userdialogs <userdialogs@noreply.github.com>
CC: Ignacio Lakidain <ignacio.lakidain@tekniker.es>; Author <author@noreply.github.com>
Asunto: Re: [aritchie/userdialogs] Instance.HideLoading() not HIDE in IOS (#613)


Closed #613<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faritchie%2Fuserdialogs%2Fissues%2F613&data=02%7C01%7C%7Cc098cb1d106447917a5b08d6de4c8f60%7C62f653bf9c21465bbdbf1b18ba164624%7C0%7C0%7C636940818161200509&sdata=JOSCc%2BqOkhwk7klz0Hjr0W1FQ26tXUftC21eYHUykdo%3D&reserved=0>.
