### ISSUE TITLE
When using Moq, UserDialogs is throwing a null exception in ViewModel test

### ISSUE THREAD

**Issue by nick5454** [aritchie/userdialogs#614]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [X] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Android 28
iOS 8+ 12.2
Xamarin 3.6 and 4.0
However this is testing the ViewModel in xUnit Core 2.1
## Version of ACR UserDialogs Library
7.0.4

## Expected Behaviour
I expect to not get a null exception. 

## Actual Behavior
In view model testing (Mocking with Moq), it throws a null exception with no stack trace, other than the line it occurs on. I have a AlertAsync call in the try-catch and the Alert is mocked correctly. 

Running the app on a device or simulator works fine. I am trying to verify the text displayed by the call to UserDialogs.ConfirmAsync

Code snippet:
`return new Command(async () =>
				{
					try
					{
						var confirm = new ConfirmConfig()
						{
							CancelText = "No",
							OkText = "Yes",
							Title = "Allow Notifications",
							Message = "Would you like to allow notifications on this device?"
						};
						bool allowNotifications = await Dialogs.ConfirmAsync(
							"Would you like to allow notifications on this device?",
							"Allow Notifications",
							"Yes",
							 "No"
							);

						Debug.WriteLine("Allowed = " + (allowNotifications ? "true" : "false"));

					}
					catch (Exception ex)
					{
						await Dialogs.AlertAsync("This is the recover message", "Exception Caught");
					}
				}
				);`

Is there something I am doing wrong to Mock it?

Summary
I used the example in issue 201 that you mentioned. UserDialogs.Instance = _dialogMock.Object and I still receive an exception from the Intercept class.

I have also created a sample project to demonstrate this issue. It is attached.
[TestAcrDialogsMoq.zip](https://github.com/aritchie/userdialogs/files/3208224/TestAcrDialogsMoq.zip)

I have been testing this by running (or debugging) the only test in the xUnit test project. 

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I'm sorry - this has absolutely nothing to do with user dialogs.  You are creating the mock, so the bug could be any number of things in your test code.  The internal code doesn't use UserDialogs.Instance directly, so it won't have anything to do with that.

**Comment by gptucci** [comment]
Hi
Have you any news ? How is possible to mock IUserDialogs using moq ??
tnx
