### ISSUE TITLE
Xamarin.Forms - User Dialog Loading is not appearing center of the page on iOS.

### ISSUE THREAD

**Issue by vijaypalve** [aritchie/userdialogs#616]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

   - [x] iOS
 - [] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Xamarin.Forms- 4.0.0.482894
VS - 2017 (15.9.12)
Xamarin.iOS - 12.4.0.64

## Version of ACR UserDialogs Library
7.0.4

## Expected Behaviour
User Dialog is appearing center of the page on iOS.

## Actual Behavior
I am using "Acr.UserDialogs" 7.0.4 for showing loader and alert throughout my app. It's work fine on Android but not working properly on iOS.
Android it always displays in center but not on iOS.

## Code of Conduct
UserDialogs.Instance.ShowLoading("Loading..");
UserDialogs.Instance.HideLoading();

**Comment by aritchie** [comment]
Please provide a reproducible test case

**Comment by vijaypalve** [comment]
@aritchie Thank you for reply,
On every page, loader not displayed on centre. Not a specific case.
 I have used "UserDialogs.Instance.ShowLoading("Loading..");" this code for displaying loader/Alert in PCL.
Its works for Android and UWP but not on iOS.

**Comment by aritchie** [comment]
The sample I have works just fine with Xamarin Forms.  As requested, please send a reproducible sample otherwise there isn't much I can do to help.

**Comment by aritchie** [comment]
No valid information provided by author of issue.  Closing.
