### ISSUE TITLE
Spinner not working on API 23

### ISSUE THREAD

**Issue by HassanBedawy** [aritchie/userdialogs#617]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
API 23
Resolution 1280 x 720
DPI 420
## Version of ACR UserDialogs Library
7.0.4

## Expected Behaviour
Spinner Showing (It works fine on other screen sizes and API)
![Spinner_Working](https://user-images.githubusercontent.com/3680463/59273191-aee15080-8c68-11e9-87a9-4f333b8787d2.PNG)
## Actual Behavior
I can only see the background of the spinner, but the spinner itself not showing in some cases I can only see tiny part of it 
![spinner_not_working](https://user-images.githubusercontent.com/3680463/59273189-ae48ba00-8c68-11e9-8126-1faedde40ef7.PNG)

**Comment by aritchie** [comment]
Please provide a small reproducible sample.  I'd encourage you to try the sample app on your device as well to see if it also has this issue.

**Comment by HassanBedawy** [comment]
Hi @aritchie 

Thanks for your reply, I followed the sample code and it seems to be working perfectly now
