### ISSUE TITLE
The resource object with key 'DateHumanize_MultipleHoursAgo' was not found

### ISSUE THREAD

**Issue by jemunk** [aritchie/userdialogs#618]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [X] NET Standard 2.0

## Version of ACR UserDialogs Library
2.6.2

## Actual Behavior
For one user we are getting a `System.ArgumentException: The resource object with key 'DateHumanize_MultipleHoursAgo' was not found Parameter name: resourceKey`
The user is having his UI set to Polish

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
This library has never had a v2.6.2 and has no key or error like that
