### ISSUE TITLE
[Android] Toast title doesn't work - A: Use appcompat, but make sure to review readme

### ISSUE THREAD

**Issue by sheepware** [aritchie/userdialogs#62]
Toast in Android (not AppCompat) contains description but lacks title.

**Comment by aritchie** [comment]
You need to use the appcompat version to get the new toast mechanism.  The straight up android support just can't offer this functionality.  If you are using xamarin forms, please review the readme for the warnings around using appcompat

**Comment by sheepware** [comment]
Thanks for your quick response.
I don't want to use the new mechanism (yet).
In ToastConfig (same in ToastInfo, ToastError…) title and description can be set (title is mandatory). But in Android (with the old mechanism) only the description is shown.
Could the expression *(title  + '\n' + description)* be used instead of just passing *description*, to achieve a similar look to iOS?

**Comment by aritchie** [comment]
@sheepware I have updated the "classic" toast with title and description
