### ISSUE TITLE
Didn't find class "android.widget.View" on path: DexPathList

### ISSUE THREAD

**Issue by JTOne123** [aritchie/userdialogs#620]
## Please check all of the platforms you are having the issue on (if the platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include the version of Xamarin.Android.Support.* you are using)
Xamarin.Android.Support - v28.0.0.1
Target - Android 9
Xamarin.Forms - 4.0.0.497661
VS2019 16.1.3 (**it works fine in VS17**)
**Xamarin.Android 9.3.0.22**

## Version of ACR UserDialogs Library
7.0.4

## Expected Behaviour
no errors

## Actual Behavior
`Java.Lang.ClassNotFoundException: Didn't find class "android.widget.View" on path: DexPathList[[zip file "/data/app/my-app-1/base.apk"],nativeLibraryDirectories=[/data/app/my-app-1/lib/arm, /data/app/my-app-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]`

## Related issues **(Please read them)**
https://github.com/xamarin/xamarin-android/issues/2966
https://github.com/xamarin/xamarin-android/issues/3072

Looks like it's VS19 related issue but it occurs only with this library in my project.

If I understood correctly, as mentioned @brendanzagaeski it related to AOT compilation.

The issue reproduced every time when I try open Alert, Sheet and Confirm dialogs.

I understand it's the issue with the Android tooling, but I'm interested in your opinions.

**Comment by aritchie** [comment]
The issue isn’t really anything to do with this library and there isn’t anything I can do as a workaround in the library to help.  I’m afraid you’ll have to just push on xamarin to fix

**Comment by JTOne123** [comment]
I see your point, let's wait until @brendanzagaeski answered my comment with steps to reproduce https://github.com/xamarin/xamarin-android/issues/3072#issuecomment-503537987
