### ISSUE TITLE
Weird ui Bug on Dialogs.ShowLoading

### ISSUE THREAD

**Issue by Mr-Pearce** [aritchie/userdialogs#621]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [X] Android
 - [] UWP
 - [] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of you are using)
Xamarin.Android.Support.Design 
Xamarin.Android.Support.v4
Xamarin.Android.Support.v7.AppCompat
Xamarin.Android.Support.v7.CardView
Xamarin.Android.Support.v7.MediaRouter
all 28.0.0.1
Compiling usingAndroid 9.0
Android Version on Device 8.0.0

Xamarin.Forms 4.0.0.497661

## Version of ACR UserDialogs Library
7.0.4

## Expected Behaviour
![IMG_20190619_110130](https://user-images.githubusercontent.com/13457314/59753616-cfbb2e80-9284-11e9-975f-8cb62d7a0d22.jpg)

## Actual Behavior
It looks like the loading ui has some weired overlay.
Also sometimes it happens sometimes not.

![IMG_20190619_110100](https://user-images.githubusercontent.com/13457314/59753622-d3e74c00-9284-11e9-8f27-dc427df30873.jpg)
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Please submit some sort of test case so I know where to start

**Comment by Mr-Pearce** [comment]
the problem is i cant really get to reproduce it every time
sometimes i start my app, come to the login screen(first screenshot) and it is ok
sometimes it is like on the second screenshot.

**Comment by aritchie** [comment]
I’ll leave this open for a few days, but I’ll need some sort of reproducible sample before I can do anything

**Comment by Mr-Pearce** [comment]
I will check if i can reproduce it somehow

**Comment by aritchie** [comment]
No reproducible case provided
