### ISSUE TITLE
Xamarin Forms : Acr userdialog loading indicator not showing in Center

### ISSUE THREAD

**Issue by vijaypalve** [aritchie/userdialogs#622]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [x] NET Standard 2.0

## Version of OS(s) listed above with issue (if android - please include version of Xamarin.Android.Support.* you are using)
Microsoft Visual Studio Professional 2017 
Version 15.9.12
VisualStudio.15.Release/15.9.12+28307.665
Microsoft .NET Framework
Version 4.7.02556
Installed Version: Professional

Xamarin   4.12.3.83 (d15-9@23fa80172)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.30 (e0af99a34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.4.0.64 (9c8d8e0)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

## Version of ACR UserDialogs Library
Acr.UserDialogs - 7.0.4

## Expected Behaviour
UserDialogs always in the center of the device screen.

## Actual Behavior
Acr userdialog loading indicator not showing in Center.

## Code of Conduct
Please find the sample application and screen shot.
![IMG_1971](https://user-images.githubusercontent.com/14092016/59904309-cb2b7d00-9420-11e9-8b6f-ff200255b5e9.PNG)
[Loader.zip](https://github.com/aritchie/userdialogs/files/3313347/Loader.zip)

**Comment by vijaypalve** [comment]
Same issue in "Acr.UserDialogs" plugin sample. Please find attached screens.
![IMG_1976](https://user-images.githubusercontent.com/14092016/59905697-81449600-9424-11e9-9a60-6fd733749fc1.PNG)
![IMG_1975](https://user-images.githubusercontent.com/14092016/59905698-81449600-9424-11e9-9bcf-8143525604d2.PNG)
![IMG_1974](https://user-images.githubusercontent.com/14092016/59905700-81dd2c80-9424-11e9-8cc1-6438fec07ac6.PNG)
![IMG_1973](https://user-images.githubusercontent.com/14092016/59905701-81dd2c80-9424-11e9-942f-fcffe3892f5b.PNG)
![IMG_1972](https://user-images.githubusercontent.com/14092016/59905702-81dd2c80-9424-11e9-90e2-09c04e75a4a3.PNG)
![IMG_1979](https://user-images.githubusercontent.com/14092016/59905703-8275c300-9424-11e9-87c8-12026fe85096.PNG)
![IMG_1978](https://user-images.githubusercontent.com/14092016/59905704-8275c300-9424-11e9-9f5a-ff0bffb0747d.PNG)
![IMG_1977](https://user-images.githubusercontent.com/14092016/59905705-8275c300-9424-11e9-9cd6-165d4b7cf5dc.PNG)

**Comment by aritchie** [comment]
You can post an issue with this BTProgressHUD if you want, but it is external to this library

**Comment by Amaro96** [comment]
The same happens with me @aritchie

**Comment by aritchie** [comment]
And my answer is still the same
