### ISSUE TITLE
using(UserDialogs.Instance.Loading()) not working on Android

### ISSUE THREAD

**Issue by pmahend1** [aritchie/userdialogs#625]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [x] NET Standard 2.0

## Version of ACR UserDialogs Library
latest

## Expected Behaviour

On android when using ```using(UserDialogs.Instance.Loading())``` is not shown
however if I use ```IUserDialogs userdialog = UserDialogs.Instance;
userDialogs.Show();```  works
How do I fix this?

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

## Code of Conduct
* No Library Update Requests - THIS ESPECIALLY MEANS ANDROID SUPPORT LIBRARIES
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
Try the samples - they don't have the issue.  You'll need to provide a reproducible sample if you want help.

**Comment by pmahend1** [comment]
Thanks for directing me in right way.

The first call was UserDialogs.Instance.ShowLoading() and I was calling UserDialogs.Instance.HideLoading()

may be it was because it was not being disposed. 

Will check more and update if there is issue

**Comment by aritchie** [comment]
No followup received, closing issue
