### ISSUE TITLE
[Android] Wrong keyboard type is shown

### ISSUE THREAD

**Issue by adrianknight89** [aritchie/userdialogs#627]
When I call `UserDialogs.Instance.PromptAsync` on Android, the soft keyboard appears automatically when the dialog appears, but the wrong keyboard type is shown (this only happens if the last keyboard to be shown was different from the expected keyboard type) unless I click the textbox. When the dialog appears, the textbox is NOT focused. I believe that's the reason the keyboard type is wrong. I'm using XF 4.0.1 and Acr.UserDialogs 7.0.4.

More info: I have a login screen where the last keyboard is numeric. After the user logs in and I show a user dialog, Android will show a numeric keyboard even though the keyboard type of the dialog is default.

**Comment by aritchie** [comment]
Please submit a reproducible sample (and please use the issue template in the future!!).  I have not experienced this issue

**Comment by aritchie** [comment]
No response from user.
