### ISSUE TITLE
[Bug] Android Cropps text and color is too dull

### ISSUE THREAD

**Issue by JCKodel** [aritchie/userdialogs#628]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.4

## Version of OS(s) listed above with issue
Android 8.1

## Steps to Reproduce
1. Create an ActionSheet with long texts

## Expected Behavior
1) Texts should be completely visible
2) Options should have a distinct color from title

## Actual Behavior
![image](https://user-images.githubusercontent.com/379339/60390571-06c4e780-9ab0-11e9-9016-fa74cf7cdbbd.png)

1) Long texts are cropped
2) Options have the same dull color as title (users can't figure out they are clickable - specially with UseBottomSheet == false)

**Comment by aritchie** [comment]
You can change the styles through the android styles if you don't like the defaults. 

The long texts are by design with android as well.
