### ISSUE TITLE
Windows Phone throws ArgumentException on version 4.x

### ISSUE THREAD

**Issue by PaulAchess** [aritchie/userdialogs#63]
Hi,

I'm experiencing a little problem with the new user dialogs. I have a PCL project (xamarin forms) and a WP (silverlight, 8.1) project, both have the Acr.UserDialogs package on the same version.

When I try to use it I have the Argument Exception : `"This PCL library, not the platform library.  Did you include the nuget package in your project?"` when I try to use user dialogs (from PCL or from the WP project).

I checked, « PCL » is not a defined constant in my WP project (this could have caused the bug, but when I use `#if PCL` I'm not getting on the code). 

This also happens when I try to use `UserDialogs.Instance.Alert("anything")`. before creating my Xamarin Forms App. I have no idea why it would be creating the instance from a PCL project.

Both have version 4.0.5 of the package. I have no issue on iOS, which has exactly the same PCL project attached. (No problems on android too, but it still has a initializer).

**Comment by aritchie** [comment]
All windows support is beta in 4.x.  I don't plan to support silverlight going either.  Too many compatibility things trying to push forward.  Everything will be UWP soon anyhow.

**Comment by PaulAchess** [comment]
Oh, okay, I thought it was supported when I saw the main page, sorry for reporting this. I'll stick with the previous version for now.

I think this is a reasonable choice, as silverlight is doomed to die anyway.
I'll gladly use your framework as soon as I'm on UWP, it's just Xamarin Forms isn't there yet.

Thanks for your quick answer and your amazing work !
