### ISSUE TITLE
[iOS]  Dialogs will not appear after navigating to a tabbed page via the "More" option

### ISSUE THREAD

**Issue by RossGreig** [aritchie/userdialogs#630]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library 
7.0.4

## Version of OS(s) listed above with issue
iOS 12.3.1

## Steps to Reproduce
1. Create a tabbed page with more than 5 tabs
2. Navigate to "More", then select a tab from the list
3. Try and trigger a prompt (I tried DatePromptAsync, ActionSheetAsync and ConfirmAsync)

## Expected Behavior
Dialog would appear as expected.

## Actual Behavior
Dialog does not appear. Furthermore after navigating away from the tabbed page dialogs still don't want to appear.

**Comment by aritchie** [comment]
Please take a look at the sample app in this repo.  You'll note it uses tabs just fine.  I would need a reproducible sample since I don't have any details as to what the problem may be.

**Comment by RossGreig** [comment]
Happy to provide more information. Dialogs work perfectly fine on tabbed pages yes, but on iOS when adding more than 5 tabs the 5th tab becomes a more button which opens a menu displaying more pages. On selecting one of theses pages any attempt to open a dialog from that moment onward seems to fail...

Unfortunately I cant share what I am currently working on as it is sensitive and I am part way through exploring alternate options as I need to fix this asap, but I am happy to produce another sample as a demonstration of the issue if that will be helpful to you, although I wont be able to get around to that until the weekend earliest.
