### ISSUE TITLE
[Bug] Losing immersive mode when ShowLoading() is triggered

### ISSUE THREAD

**Issue by paulthedev** [aritchie/userdialogs#634]
#Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.4
## Version of OS(s) listed above with issue
Android 9 (Pie)

## Steps to Reproduce
1. Trigger UserDialogs.Instance.ShowLoading("Connecting", MaskType.Black)

## Expected Behavior
App should stay in immersive mode

## Actual Behavior
App loses immersive mode

**Comment by paulthedev** [comment]
At least Immersive mode should be triggered back on HideLoading()

**Comment by aritchie** [comment]
I’ve never actually used immersive mode so I’m unlikely to implement this.  Feel free to send a PR
