### ISSUE TITLE
[Enhancement] Add ability to set which item should get focus in Login.

### ISSUE THREAD

**Issue by Cattpot** [aritchie/userdialogs#636]
## Summary
My Login prompt has a value for _login_ so I dont need the focus at the _login_ field.

## API Changes
LoginConfig - DefaultTitle - DefaultOkText - DefaultCancelText - DefaultLoginPlaceholder - DefaultPasswordPlaceholder

and DefaultFocus => "Login" or "Password"

## Intended Use Case
I need the focus at the _password_ field.

Or I have to build a new prompt without the Login field.
Is it possible to build such a prompt?

```csharp
this.Dialogs.ActionSheet(new ActionSheetConfig()
  .SetTitle("Username Max")
  .Add("Password", () => this.PromptCommand(InputType.Password))
  .SetCancel())
```

Thanks for the cool stuff!

**Comment by aritchie** [comment]
You can use prompt for this.  I don’t plan to implement this on the login control though
