### ISSUE TITLE
On timing out ActionSheetAsync closes but does not return to caller

### ISSUE THREAD

**Issue by DavidPressman** [aritchie/userdialogs#639]
On timing out ActionSheetAsync closes but does not return to caller.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [X] UWP
 - [X ] .NET Standard

## Feature Library

 - [X ] Core
 - [ ] BluetoothLE
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Steps to Reproduce
1. In .Net Standard project await an ActionSheetAsync with several string choices and a Cancellation Token to timeout in about 20 seconds. Have a variable to accept the call's results.
2. Sheet appears. Left alone it disappears in the 20 seconds.
3. Result is never returned and the code remains awaiting the result.

## Expected Behavior
The ActionSheetAsync call should return an empty string (or "Cancel") if the sheet is allowed to timeout or user Cancels by pressing Escape key, rather than by using sheet's own Cancel button

## Actual Behavior
Call never returns even though the sheet is gone. May happen in all platforms, but only tested in UWP so far. I note several earlier reports of similar difficulties and promises this method would be removed; however it remains. Workaround for now: using static code: With Task.WhenAny() Include an action to call a separate Task that awaits the action sheet The other action is a simple Task.Delay with a slightly shorter timeout. If user taps Escape key at least the program will resume in a reasonable amount of time.

My workaround code follows:

Cancel, SheetResult, and TimesOut below are static strings. TimesOut is a warning added to the Sheet's title.

public static IUserDialogs Dialog => UserDialogs.Instance;

public static async Task<string> CallActionSheetAsync(string title, string[] actions, string cancel = null, string destructive = null)
        {
            SheetResult = string.Empty;
            int delay = 20000;
            await Task.WhenAny(GetSheetResult(title + TimesOut, actions, delay + 100, cancel, destructive), Task.Delay(delay));
            return SheetResult;
        }

        private static async Task GetSheetResult(string title, string[] actions, int delay, string cancel = null, string destructive = null)
        {
            // Unfortunately ActionSheet does not return if it just times out!! It simply stops being modal and disappears.
            SheetResult = await Dialog.ActionSheetAsync(title, cancel ?? Cancel, destructive, new CancellationTokenSource(delay).Token, actions);
        }

**Comment by aritchie** [comment]
It isn’t supposed to return anything.  Cancelling cancel tokens causes them to toss an exception

**Comment by aritchie** [comment]
In any case, you are better off with the sync version of this call if you want to dismiss it in a controlled fashion

**Comment by DavidPressman** [comment]
As to the exception, true, THAT is what is supposed to happen. However when I put the call within a try catch block I never saw the exception. May change to the sync version.

**Comment by aritchie** [comment]
Feel free to send a PR if it isn’t working as expected

**Comment by aritchie** [comment]
This method will be deprecated in 7.1.  I don't use it and I don't want the wad of edge cases that come with it
