### ISSUE TITLE
[Bug] Not able to update package, and not able to use older version.

### ISSUE THREAD

**Issue by vivekshah-zymr** [aritchie/userdialogs#641]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
6.5.1
## Version of OS(s) listed above with issue
Running Visual Studio Community - Mac v8.2.2(build 21)

## Steps to Reproduce
Issue 1: Not able to update from 6.5.1 to 7.0.1 in xamarin forms project.
Issue 2: While using the version 6.5.1, getting an error.

## Expected Behavior
1) Should update
2) Should Run

## Actual Behavior
**Error while update:** Could not install package 'Acr.UserDialogs 7.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Error while running version 6.5.1:**  The type or namespace name 'Acr' could not be found (are you missing a using directive or an assembly reference?)

**Comment by aritchie** [comment]
1) No it shouldn't update.  v7 is made for netstandard.  6.x and lower was meant for PCL.  Your project is PCL.  

2) First off, the version you are using is over 2 years old and I only really support the latest version.  Second, you haven't given really any details for me to potentially point you in a direction.  I have heard that the recent versions of VS don't do well with PCL.  In which case, you should message Xamarin about it
