### ISSUE TITLE
[Bug] UWP Toast position not working

### ISSUE THREAD

**Issue by Orgbrat** [aritchie/userdialogs#644]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [x] UWP
 - [x] .NET Standard

## Version of Library
7.0.4
## Version of OS(s) listed above with issue
Windows 10 (1903)

## Steps to Reproduce
1. Add Toast in code 
                var toastConfig = new ToastConfig(toastMsg);
                toastConfig.SetDuration(TimeSpan.FromSeconds(6));
                toastConfig.SetPosition(ToastPosition.Bottom);
                UserDialogs.Instance.Toast(toastConfig);`
`

## Expected Behavior
I have a Xamarin Forms 4.1 solution with Android, iOS and UWP projects that I am using Acr.UserDialogs. For the most part everything works as it should with the dialogs and toasts except for UWP. I need the toast to display at the bottom of the screen in UWP just as it does for Android and iOS. 

## Actual Behavior
 It works in UWP but the Toast messages display in the upper left hand corner which covers the menu button.

**Comment by sheperd13** [comment]
I am having this same issue. I can see it's closed but it was clearly not fixed. Did you ever figure out a workaround for this?
