### ISSUE TITLE
 Where is SetInputType for WP?

### ISSUE THREAD

**Issue by rubgithub** [aritchie/userdialogs#65]
I found for Android and IOs, by the way, Is WP supported? I didn't see any example.

**Comment by aritchie** [comment]
Windows support in general (due to UWP) is beta right now.

I am likely going to reintroduce a WP8 due to the number of requests, but it won't carry new functionality

**Comment by aritchie** [comment]
And UWP doesn't seem to have support for keyboard types that I've seen
