### ISSUE TITLE
[Bug] 7.0.20x builds - MTOUCH : error MT2101: Can't resolve the reference 'Acr.UserDialogs.IUserDialogs Acr.UserDialogs.UserDialogs::get_Instance()' during iOS AppStore build

### ISSUE THREAD

**Issue by lechuckcaptain** [aritchie/userdialogs#651]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.22

## Version of OS(s) listed above with issue
iOS

## Steps to Reproduce
1. Build solution with iOS->AppStore->iPhone configuration
2. Error during build:

MTOUCH : error MT2101: Can't resolve the reference 'Acr.UserDialogs.IUserDialogs Acr.UserDialogs.UserDialogs::get_Instance()', referenced from the method 'Acr.UserDialogs.IUserDialogs Test.ViewModelLocator/<>c::<.cctor>b__0_1()' in 'Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

## Expected Behavior
Solution should build correctly 

## Actual Behavior
Solution doesn't build. Using version 7.0.4 the solution build correctly.

**Comment by aritchie** [comment]
Not sure what your linker behaviour but usually bait/switch libraries don't get delinked at all.  

You'll need to submit a reproducible sample or try adding Acr.UserDialogs to your linker config

**Comment by aritchie** [comment]
Actually - looks like an issue with the azure devops build

**Comment by aritchie** [comment]
7.0.24 corrects the issue.  Azure DevOp builds have been suspended for now
