### ISSUE TITLE
[Bug] Changelog is not updated

### ISSUE THREAD

**Issue by lechuckcaptain** [aritchie/userdialogs#652]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [x] Android
 - [x] UWP
 - [x] .NET Standard

## Version of Library
7.0.25

## Version of OS(s) listed above with issue
All

## Steps to Reproduce
1. Open changelog file: https://github.com/aritchie/userdialogs/blob/master/docs/changelog.md
2. Last indexed version is 7.0.2 (6 months ago)

## Expected Behavior
Changelog should be updated to last version available to Nuget

## Actual Behavior
Changelog file is 6 months ago

**Comment by aritchie** [comment]
please don't file requests about docs.  I'm one person.  There have only been minor touches since 7.0.2

**Comment by lechuckcaptain** [comment]
It's not a direct request, I'm tracking an issue. I could be willing to help if you want.
