### ISSUE TITLE
[Bug] System.Drawing.Common Linker Issues

### ISSUE THREAD

**Issue by stesvis** [aritchie/userdialogs#654]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.25
## Version of OS(s) listed above with issue
Android 9.1.0.317

## Steps to Reproduce
1. Set up the toast
```
var toastConfig = new ToastConfig("My message");
toastConfig.SetDuration(2000);
toastConfig.SetBackgroundColor(System.Drawing.Color.ForestGreen);
toastConfig.SetMessageTextColor(System.Drawing.Color.White);

UserDialogs.Instance.Toast(toastConfig);
```
2. Show the toast

## Expected Behavior
In the previous versions (in my case up to v7.0.4) the toast shows with no errors.

## Actual Behavior
After updating to v7.0.25 I get this exception:
![Screenshot_20190821_112828_com veloguide mobile prod](https://user-images.githubusercontent.com/6062684/63454237-a5622a80-c407-11e9-90e4-f0c909076720.jpg)

**Comment by FIELDPOINT** [comment]
same here

**Comment by aritchie** [comment]
What version of visual studio are you using?

**Comment by stesvis** [comment]
> What version of visual studio are you using?

VS 2017 15.9.14

**Comment by aritchie** [comment]
Please try in VS2019.  I see xamarin has tacked in a default library called System.Drawing.Common in their latest stuff.  I’m not sure yet where to push this issue

**Comment by stesvis** [comment]
I'll try for curiosity but i can't use vs 2019 because of other issues..

**Comment by kvpt** [comment]
I have the same error when building in release.
> error  MSB4018: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Drawing.Color ' (defined in assembly 'Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'System.Drawing.Common,
Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. When the scope is different from the defining assembly, it usual ly means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Drawing.Color

I use VS2019, I tried to delete bin/obj but it doesn't work, rollback to version 7.0.4 fix the issue.

**Comment by aritchie** [comment]
Linking to the source points of the pain
https://github.com/mono/mono/issues/13483
https://github.com/xamarin/xamarin-macios/pull/6011

**Comment by BladeXR** [comment]
I'm having the exact same issue. Is there a workaround or just wait for a fix?

**Comment by aritchie** [comment]
Rollback if you are having the issue

**Comment by BladeXR** [comment]
> Rollback if you are having the issue

Sure, just did. Thanks for the great work btw

**Comment by stesvis** [comment]
For now I'm just staying on 7.0.4
Will there be a fix tho?

**Comment by aritchie** [comment]
Xamarin has said to verify you are using Xamarin Android 9.4+.  If you continue to have this issue, please contact them going forward
