### ISSUE TITLE
[Bug] Changelog is not updated

### ISSUE THREAD

**Issue by masonyc** [aritchie/userdialogs#655]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.25
## Steps to Reproduce
1. Open changelog.md
2. No logs related to 7.0.25

## Expected Behavior
Show Changes in 7.0.25 in the changelog

## Actual Behavior
No 7.0.25 section in the changelog

**Comment by aritchie** [comment]
Don't complain about docs
