### ISSUE TITLE
Alert not being shown

### ISSUE THREAD

**Issue by Alxandr** [aritchie/userdialogs#66]
I'm currently trying to figure out a alert not being shown. The following is printed to the console:

     Warning: Attempt to present <UIAlertController: 0x1a11f350> on <Xamarin_Forms_Platform_iOS_ModalWrapper: 0x196c7fc0> whose view is not in the window hierarchy!

**Comment by aritchie** [comment]
What type of page are you running (tabs, master, etc)?  Where are you executing the code from?  Please provide as much detail as possible

**Comment by Alxandr** [comment]
I was running a dialog in a dialog in a masterdetail page (xamarin forms). However, I uninstalled the `Acr.XamForms.UserDialogs` and installed `Acr.UserDialogs` package, and the problem was resolved, so it seems you've fixed this at some point. You should update the xamforms package on nuget to the spec you just added in this repo.
