### ISSUE TITLE
[Bug] Init is ignored when using in Xamarin.Android with MvvmCross after resume

### ISSUE THREAD

**Issue by nologinatgit** [aritchie/userdialogs#662]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.4
## Version of OS(s) listed above with issue
Android 6
Android 9

## Steps to Reproduce
1. Add the following code to both `SplashScreenActivity` and `MainActivity` in `OnCreate`:
```csharp
Activity dialogsHelper()
{
    var activity = Mvx.IoCProvider.Resolve<IMvxAndroidCurrentTopActivity>().Activity;
    if (activity == null)
      activity = this;
    return activity;
}

UserDialogs.Init(dialogsHelper);
UserDialogs.Instance = new VitarexUserDialogs(dialogsHelper); 
```
2. Add the  instance to the IoC container:
`Mvx.IoCProvider.RegisterType(() => UserDialogs.Instance);`
3. Try to resolve the instance, _after backgrounding the app_ (it skips SplashScreen when resuming):
`dialogsHelper = Mvx.IoCProvider.Resolve<IUserDialogs>();`

## Expected Behavior
I expect the instance to be available for use.

## Actual Behavior
I get the following exception:

> Failed to construct and initialize ViewModel for type MyApp.CustomFragmentViewModel from locator MvxDefaultViewModelLocator - check InnerException for more information ---> MvvmCross.Exceptions.MvxException: Problem creating viewModel of type CustomFragmentViewModel ---> MvvmCross.Exceptions.MvxIoCResolveException: Failed to construct CustomFragmentViewModel ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: [Acr.UserDialogs] In android, you must call UserDialogs.Init(Activity) from your first activity OR UserDialogs.Init(App) from your custom application OR provide a factory function to get the current top activity via UserDialogs.Init(() => supply top activity)
>   at Acr.UserDialogs.UserDialogs.get_Instance () [0x00007] in <3f407294605b43fc9816afc2b353d92c>:0 
>   at Acr.UserDialogs.UserDialogs.get_Instance () [0x00007] in <3f407294605b43fc9816afc2b353d92c>:0 
>   at MyApp.IoCConfig+<>c.<Init>b__0_1 () [0x00000]

Unfortunately adding a custom Application involves unnecessary behaviour so I need to solve it by using Activites. Why does it claim that `Init` was not called?

**Comment by aritchie** [comment]
I'm sorry but this is external to this library, so I'm not really sure how to help you beyond a guess.

UserDialogs.Init(dialogsHelper);
UserDialogs.Instance = new VitarexUserDialogs(dialogsHelper);   <= you are overriding what Init is doing right here.

**Comment by nologinatgit** [comment]
It seems that calling `Init` from the `OnCreate` was a bit too late. When we moved it to the constructor of the main activity, it didn't throw that exception (we can't say for sure without several verifying runs).

**Comment by aritchie** [comment]
@nologinatgit This issue is closed.  I can't help with external frameworks or custom overrides (especially since I have no idea what's happening).
