### ISSUE TITLE
[Enhancement] Possible documentation improvement / question

### ISSUE THREAD

**Issue by ndastur** [aritchie/userdialogs#664]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
```
UserDialogs.Init(this);
OR Xamarin.Forms - UserDialogs.Init(() => this);
```
I am not sure I see difference between the two. Is there a reason the docs show a different Init pattern on XF?
 
## API Changes
None

## Intended Use Case
Simplification

**Comment by aritchie** [comment]
It is just different ways of getting at the top activity.  I don't take requests for doc enhancements.  Feel free to send a PR in areas you can improve
