### ISSUE TITLE
[Bug] Get ErrorInflatingClass using AlertAsync with linking Sdk assemblies on and r8.

### ISSUE THREAD

**Issue by StevenGranados** [aritchie/userdialogs#665]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.27
## Version of OS(s) listed above with issue
API 28
## Steps to Reproduce
1. Click Button in below repro.
2. Should get exception.
3. If change to use shared runtime and fast deployment get different exception.
4. If don't link or don't use code shrink works fine.
[AlertTest.zip](https://github.com/aritchie/userdialogs/files/3626146/AlertTest.zip)
## Expected Behavior
Alert message shown.

## Actual Behavior
If code shrinking and linking is on get exception:

09-18 12:36:43.916 D/AndroidRuntime( 8756): Shutting down VM
09-18 12:36:43.917 E/AndroidRuntime( 8756): FATAL EXCEPTION: main
09-18 12:36:43.917 E/AndroidRuntime( 8756): Process: com.companyname.alerttest, PID: 8756
09-18 12:36:43.917 E/AndroidRuntime( 8756): android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class android.support.v7.widget.AlertDialogLayout
09-18 12:36:43.917 E/AndroidRuntime( 8756): Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class android.support.v7.widget.AlertDialogLayout
09-18 12:36:43.917 E/AndroidRuntime( 8756): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.AlertDialogLayout" on path: DexPathList[[zip file "/data/app/com.companyname.alerttest-j1AS-ka1HfPUbqY917Qrgg==/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.alerttest-j1AS-ka1HfPUbqY917Qrgg==/lib/x86, /data/app/com.companyname.alerttest-j1AS-ka1HfPUbqY917Qrgg==/base.apk!/lib/x86, /system/lib]]
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.view.LayoutInflater.createView(LayoutInflater.java:606)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v7.app.AppCompatDelegateImpl.setContentView(:469)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v7.app.AppCompatDialog.setContentView(:94)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v7.app.AlertController.installContent(:232)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v7.app.AlertDialog.onCreate(:279)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.app.Dialog.show(Dialog.java:302)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v4.app.DialogFragment.onStart(:436)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v4.app.Fragment.performStart(:2477)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v4.app.FragmentManagerImpl.moveToState(:1494)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(:1784)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v4.app.FragmentManagerImpl.moveToState(:1852)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v4.app.BackStackRecord.executeOps(:802)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v4.app.FragmentManagerImpl.executeOps(:2625)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(:2411)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(:2366)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(:2273)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.support.v4.app.FragmentManagerImpl$1.run(:733)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.os.Handler.handleCallback(Handler.java:873)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.os.Looper.loop(Looper.java:193)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at java.lang.reflect.Method.invoke(Native Method)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-18 12:36:43.917 E/AndroidRuntime( 8756): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
**Java.Lang.RuntimeException:** 'Binary XML file line #18: Binary XML file line #18: Error inflating class android.support.v7.widget.AlertDialogLayout'

If either is off it's fine.

**Comment by aritchie** [comment]
Linker issues are just part of the deal when doing things with Xamarin.  It isn't a defect with the library and it isn't something I can really do anything about.  It can change how it is manifests itself from release to release as well.  As it is, the portion delinked here isn't even dialogs, it is part of the support lib.  Add it to your linker.xml file

**Comment by StevenGranados** [comment]
Ok thanks for the reply. Should I post this to the Xamarin forms issues page then?

**Comment by aritchie** [comment]
It isn't a bug though.  It is just part of the things you need to do.  You should lookup docs on linker.xml

**Comment by StevenGranados** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/9318
Might help with this issue.
