### ISSUE TITLE
[Enhancement] Toast direction animation

### ISSUE THREAD

**Issue by wonea** [aritchie/userdialogs#668]
## Summary
Control the animation of the toast, expand upon simply popping up and down.

## API Changes

```
public enum ToastAnimate
{
	FlyPast,
	Judder
}

var toastConfig = new ToastConfig(message);
toastConfig.SetDuration(duration * 1000);
toastConfig.SetBackgroundColor(color);
toastConfig.Position = ToastPosition.Left;
toastConfig.Animate = ToastAnimate.FlyPast;
UserDialogs.Instance.Toast(toastConfig);
```

This would cause the toast to fly past the left to the right.

## Intended Use Case
In my App I user toasts to tell the user a message has been sent. It would be ideal a great visual hint to the user, if the toast flew past.

**Comment by joanbarros** [comment]
@wonea do you have a GIF or short video representing something similar to what you are looking for? might help to better understand exactly what you are describing.
