### ISSUE TITLE
[Bug] Update from v7.0.4 to 7.0.30 - Failed to resolve System.Drawing.Color for iOS project

### ISSUE THREAD

**Issue by iBobb** [aritchie/userdialogs#670]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.30 or 7.0.27 (going back to 7.0.4 my project works again)
## Version of OS(s) listed above with issue
Xamarin iOS 12.4.0.64
the shared project is .net standard 2.0
latest Xamarin Forms 4.2

## Steps to Reproduce
1. Build my iOS project referencing UserDialogs 7.0.4
2. Everything's fine
3. Update only the UserDialogs package to 7.0.30 and when I try to build I get an error

## Expected Behavior
It should build I guess

## Actual Behavior
Build does not work and I get error:
Failed to resolve "System.Drawing.Color" reference from "System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"	MobileSign.iOS			

I tried including 
Reference Include="netstandard"
In the iOS project file as per some suggestions but no change.

**Comment by aritchie** [comment]
Read the pinned closed issue - https://github.com/aritchie/userdialogs/issues/654

**Comment by iBobb** [comment]
Thanks for the quick response and for your work :)

**Comment by AndrewSatMap** [comment]
I get the same issue when building against 7.0.30 for Xamarin.Android - have to roll back to v.7.0.4 in order to  build a release version.

Is there likely to be a new version soon which fixes this problem?
Thanks

**Comment by aritchie** [comment]
@AndrewSatMap  read the pinned issue listed above
