### ISSUE TITLE
Error restoring Nuget packages

### ISSUE THREAD

**Issue by FinHorsley** [aritchie/userdialogs#671]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
Latest clone from `master`

## Version of OS(s) listed above with issue
N/A

## Steps to Reproduce
1) `git clone https://github.com/aritchie/userdialogs.git`
2) Nuget Restore
3) Get the following error
```
Getting restore information for project /Users/finhorsley/Labs/userdialogs/src/Samples/Samples.Droid/Samples.Droid.csproj
/Users/finhorsley/Labs/userdialogs/src/Acr.UserDialogs/Acr.UserDialogs.csproj : error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project.
Unable to create package spec for project. '/Users/finhorsley/Labs/userdialogs/src/Samples/Samples.Droid/Samples.Droid.csproj'
```
## Expected Behavior
Nuget restore finished successfully

## Actual Behavior
Restore fails

##
I've tried Googling this, but unless i've missed something i can't find anything. Is this a targeting problem, given that I'm opening the sln in VS4Mac? If anyone is currently working on this project on Mac, it would be great to know what build you're running (I'm currently on the latest stable 8.2.6 build 26)

**Comment by aritchie** [comment]
You cannot build multitargeted libraries on VS4mac
