### ISSUE TITLE
[Bug] NullReferenceException with Loading

### ISSUE THREAD

**Issue by stesvis** [aritchie/userdialogs#672]
When I use the Loading method I get an exception in iOS. Am I using it in the wrong way?
It works great on Android.

 - [X] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.30
Xamarin.Forms v4.0.0.54***

## Version of OS(s) listed above with issue
13.0

## Steps to Reproduce
1. I made this method 
 ```
public static IProgressDialog Loading(string message = null)
{
    var dialog = UserDialogs.Instance.Loading(message);
    return dialog;
}
```

2. Then I call it like this:

```
using (Common.Loading())
{
    // do stuff
}
```

## Expected Behavior
Spinning wheel shows, no exceptions (like on android)

## Actual Behavior
Throws an exception:

> System.NullReferenceException: Object reference not set to an instance of an object
>   at BigTed.ProgressHUD.PositionHUD (Foundation.NSNotification notification) [0x000d9] in <529e74e349834b0f9cc9bd7376eedc13>:0
>   at BigTed.ProgressHUD.ShowProgressWorker (System.Single progress, System.String status, BigTed.ProgressHUD+MaskType maskType, System.Boolean textOnly, BigTed.ProgressHUD+ToastPosition toastPosition, System.String cancelCaption, System.Action cancelCallback, System.Double timeoutMs, System.Boolean showContinuousProgress, UIKit.UIImage displayContinuousImage) [0x00241] in <529e74e349834b0f9cc9bd7376eedc13>:0
>   at BigTed.ProgressHUD+<>c__DisplayClass18_0.<Show>b__0 () [0x00000] in <529e74e349834b0f9cc9bd7376eedc13>:0
>   at Foundation.NSActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSAction.cs:62
> 

**NOTE**: I am not calling the Loading method from a constructor of my ViewModel, but from the **OnNavigatedTo** event.

**Comment by aritchie** [comment]
It's working fine for me.  How did you call Init on iOS?  What is the rest of that exception?

**Comment by stesvis** [comment]
Thanks for your reply.
After some investigation, it seems to happen only with the iPad and iOS 13+.
I started experiencing this after updating VS and Xcode two days ago.

I am not sure how to get more info on the exception, I copied the whole details and pasted them in the previous comment.
Thanks.

**Comment by stesvis** [comment]
Actually i finally managed to get more:

"  at BigTed.ProgressHUD.PositionHUD (Foundation.NSNotification notification) [0x000d9] in <529e74e349834b0f9cc9bd7376eedc13>:0 \n  at BigTed.ProgressHUD.ShowProgressWorker (System.Single progress, System.String status, BigTed.ProgressHUD+MaskType maskType, System.Boolean textOnly, BigTed.ProgressHUD+ToastPosition toastPosition, System.String cancelCaption, System.Action cancelCallback, System.Double timeoutMs, System.Boolean showContinuousProgress, UIKit.UIImage displayContinuousImage) [0x00241] in <529e74e349834b0f9cc9bd7376eedc13>:0 \n  at BigTed.ProgressHUD+<>c__DisplayClass18_0.<Show>b__0 () [0x00000] in <529e74e349834b0f9cc9bd7376eedc13>:0 \n  at Foundation.NSActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSAction.cs:62 \n--- End of stack trace from previous location where exception was thrown ---\n\n  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr_IntPtr_bool(intptr,intptr,intptr,intptr,bool)\n  at Foundation.NSObject.InvokeOnMainThread (System.Action action) [0x00007] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSObject2.cs:605 \n  at BigTed.ProgressHUD.Show (System.String status, System.Single progress, BigTed.ProgressHUD+MaskType maskType, System.Double timeoutMs) [0x0002a] in <529e74e349834b0f9cc9bd7376eedc13>:0 \n  at BigTed.BTProgressHUD.Show (System.String status, System.Single progress, BigTed.ProgressHUD+MaskType maskType) [0x00005] in <529e74e349834b0f9cc9bd7376eedc13>:0 \n  at Acr.UserDialogs.ProgressDialog+<>c__DisplayClass17_0.<Refresh>b__0 () [0x00038] in <bf5db8c0bfb546358fe4a980cfa7b069>:0 \n  at Foundation.NSActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSAction.cs:62 \n--- End of stack trace from previous location where exception was thrown ---\n\n  at (wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr_IntPtr_bool(intptr,intptr,intptr,intptr,bool)\n  at Foundation.NSObject.InvokeOnMainThread (System.Action action) [0x00007] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/Foundation/NSObject2.cs:605 \n  at Acr.UserDialogs.ProgressDialog.Refresh () [0x00096] in <bf5db8c0bfb546358fe4a980cfa7b069>:0 \n  at Acr.UserDialogs.ProgressDialog.Show () [0x00007] in <bf5db8c0bfb546358fe4a980cfa7b069>:0 \n  at Acr.UserDialogs.AbstractUserDialogs.Progress (Acr.UserDialogs.ProgressDialogConfig config) [0x0001c] in <bf5db8c0bfb546358fe4a980cfa7b069>:0 \n  at Acr.UserDialogs.AbstractUserDialogs.Loading (System.String title, System.Action onCancel, System.String cancelText, System.Boolean show, System.Nullable`1[T] maskType) [0x0005c] in <bf5db8c0bfb546358fe4a980cfa7b069>:0 \n  at VeloGuideApp.Misc.Common.Loading (System.String message) [0x00002] in /Users/stesvis/Documents/projects/veloguide/vg-mobile/VeloGuideApp/VeloGuideApp/Misc/Common.cs:30 "

**Comment by aritchie** [comment]
I just tried on ios 13 on an ipad.  The samples run fine.  You'll have to provide a reproducible sample.

**Comment by aritchie** [comment]
I generally only see this error when people are calling for loading before the view is ready.  OnAppearing on Xamarin Forms is usually sufficient.

**Comment by stesvis** [comment]
Hmmm i call it from OnNavigatedTo (i use Prism).
I'll try to reproduce it in a sample.
Only happening on ipads for me..

**Comment by stesvis** [comment]
Hey @aritchie I made a very basic sample app and it reproduces the exception.
https://github.com/stesvis/AcrTest

Please give it a try, thank you. And thanks for the great work.

**Comment by stesvis** [comment]
Here's a quick video. Try it with an(y) iPad. I updated Xcode so I have iOS 13.0 installed.
With iPhones (or any Android) it seems to work great.

[AcrTest.mov.zip](https://github.com/aritchie/userdialogs/files/3667923/AcrTest.mov.zip)

**Comment by aritchie** [comment]
Did you try this under OnAppearing though?  I don't usually take samples with 3rd party frameworks.

**Comment by stesvis** [comment]
Under OnAppearing() it does not crash, but in MVVM most times we need to start the loading overlay from a ViewModel rather than the code behind.
And I wonder why does this happen only on iPads?

**Comment by aritchie** [comment]
Prism has IPageLifecycle that is bound to OnAppearing.  I don't know why this only happens on iPads.  You are welcome to investigate, but I don't consider this an issue at this point.

**Comment by stesvis** [comment]
Actually, it does happen also on iPhones. I opened an issue on the Prism page.
If it gets marked as a non-issue as well, what would my options be?
I don't think that before it happened with iOS < 13.0

**Comment by aritchie** [comment]
This isn’t a bug with this library or Prism.  The view clearly isn’t ready at this stage.  Use IPageLifecycle from Prism as I’ve already stated.  That is your only optio

**Comment by stesvis** [comment]
Could it be an iOS issue then?
I would use OnAppearing, but that method doesn't take any navigation parameters.
I have to use OnNavigatedTo because of the navigation parameters...
