### ISSUE TITLE
[Bug] TimePrompt does not display properly on iOS 13

### ISSUE THREAD

**Issue by Hackavist** [aritchie/userdialogs#673]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.30
## Version of OS(s) listed above with issue
ios 13.1.2
ios 13.1.1
ios 13.1

## Steps to Reproduce
1.create a lable with tab gesture recognizer command  
2.    add this in the command "        UserDialogs.Instance.TimePrompt(new TimePromptConfig
            { OnAction = result => SetTime(result, type), IsCancellable = true } );" 
3. use the settime function to change the label  

## Expected Behavior
to show time prompt on the screen with 2 places for selecting hours and mins
## Actual Behavior
white box is shown only no text is visible on the real device (iphone xs / ios 13.1.1) but it visible on the emulator (ios 13.0)
![IMG_2211](https://user-images.githubusercontent.com/30315058/65831330-b4ff4980-e2b8-11e9-8239-a57ec3685662.PNG)

**Comment by pinkysek** [comment]
I have same problem with:

```
var cfg = new DatePromptConfig
            {
                Title = "Title",
                SelectedDate = DateOfBirth
            };
var result = await UserDialogs.Instance.DatePromptAsync(cfg);
```
@aritchie is any solution how to fix this problem? or we need wait for new version which will fix this issue?

**Comment by pinkysek** [comment]
btw fyi @aritchie @Hackavist this bug is only in Dark mode thats why on Simulator it works. I tried now in my real device Light mode and DatePrompt works fine.

**Comment by Hackavist** [comment]
@pinkysek  thank you for this insight it is life saving i was working on my custom time picker it get it working

**Comment by pinkysek** [comment]
@Hackavist it is not needed. Add this code into ViewDidLoad() in view when you used it or in BaseViewController.

```
if (UIDevice.CurrentDevice.CheckSystemVersion(13, 0))
    OverrideUserInterfaceStyle = UIUserInterfaceStyle.Dark;
```

and add this into Info.plist

```
<key>UIUserInterfaceStyle</key>
<string>Light</string>
```

It works for now and just wait till @aritchie fix this issue in lib. Maybe you can use only value in UIUserInterfaceStyle. I didn't try it separately yet. More info https://stackoverflow.com/questions/56546267/ios-13-disable-dark-mode-changes.

**Comment by pinkysek** [comment]
So you need set UIUserInterfaceStyle value in Info.plist probably because Userdialogs creating his own view for this.

**Comment by aritchie** [comment]
First off @pinkysek - quit pinging me please.  I'm not here as tech support.  

Secondly, guy - this is terrible for OSS

> It works for now and just wait till @aritchie fix this issue in lib. Maybe you can use only value in UIUserInterfaceStyle. I didn't try it separately yet. More info

> @pinkysek thank you for this insight it is life saving i was working on my custom time picker it get it working

Instead of creating a custom time picker - why not give back and fix the issue here!?  Lastly, don't sit around waiting for me to fix an issue you're having.  I don't personally use Time or Date prompt in any of my active projects.  

I'll look into a fix at some point in the future if I can't count on outside assistance, but I'm not making any promises as to when that will be.

**Comment by pinkysek** [comment]
Ok sorry for pinging you. I know that's not great solution but I need really fast fix for my app in production for now. If I will have more time at the weekend, I can look at this issue in this library.
