### ISSUE TITLE
[Enhancement] Add default timeout parameter in Loading method

### ISSUE THREAD

**Issue by EricCogen** [aritchie/userdialogs#676]
## Summary
Include a default timeout parameter to automatically close the loading dialog after {N} seconds.

## API Changes
Examples:

```c#
//timeout - call HideLoading() after ex: 10 seconds
public virtual IProgressDialog Progress(... bool show, MaskType? maskType, int? timeOutSeconds)
```

```c#
//timeout - call HideLoading() at a specific date and time
public virtual IProgressDialog Progress(...  bool show, MaskType? maskType, DateTime? timeOutAfter)
```

## Intended Use Case
```c#
UserDialogs.Instance.ShowLoading("Loading", MaskType.Black, 10);
```

if an unhandled exception occurs during processing, it would be nice to have the loading popup automatically close after {N} seconds.

**Comment by aritchie** [comment]
This is something that can easily be done outside of the library with existing calls.  The loading screen also wasn't intended for this type of auto dismissal.  Thanks for the suggestion, but I'm afraid I'll pass.
