### ISSUE TITLE
[Bug] Toast throws TypeLoadException on android 9 with xf 3.6

### ISSUE THREAD

**Issue by kicsiede** [aritchie/userdialogs#677]
## Platform

 - [ ] iOS
 - [x] Android

## Version of Library

Acr.UserDialogs 7.0.30
Xamarin.Forms 3.6

## Version of OS(s) listed above with issue

Android 9

## Steps to Reproduce

1. Acr.UserDialogs.UserDialogs.Init(this) in mainactivity
2. Acr.UserDialogs.UserDialogs.Instance.Toast("test"); from main page

## Expected Behavior

toast a test window

## Actual Behavior

TypeLoadException:

Could not load type of field 'Acr.UserDialogs.ToastConfig:<DefaultMessageTextColor>k__BackingField' (1) due to: Could not resolve type with token 01000029 from typeref (expected class 'System.Drawing.Color' in assembly 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51') assembly:System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:System.Drawing.Color member:(null)

**Comment by aritchie** [comment]
https://github.com/aritchie/userdialogs/issues/654

**Comment by kicsiede** [comment]
@aritchie thx! it would be more straightforward to put this info in the readme though. my 2 cents

**Comment by aritchie** [comment]
It's a pinned issue which is straightforward enough for me

**Comment by kicsiede** [comment]
Nice, but I wouldn't say that a product advertised as "working on Android" actually means that once you search through the CLOSED issues you will figure out how to get it working for the most basic imaginable usecase. :)
