### ISSUE TITLE
Make Dialogs Cancellable via Code

### ISSUE THREAD

**Issue by martijn00** [aritchie/userdialogs#68]
Would it be possible to cancel the dialog when the user presses the device back button?

**Comment by aritchie** [comment]
Too many pain points in this.  I can't really latch on to any event (activity is external) to catch the back button.  Also, inconsistencies between platforms for this behaviour.

**Comment by martijn00** [comment]
Would it be possible to add a parameter to Android only to set the SetCancelable as variable? I guess that would fix it at least for Android.

**Comment by aritchie** [comment]
I'm not going to do it this way.  I have ideas for a future release on how to cancel dialogs via code in the future

**Comment by Reminouche** [comment]
You can just add a simple CancellationTokenSource. If you want, i can open a pull request for fix that.

**Comment by aritchie** [comment]
I didn't want to add another argument and setting it on the current config objects would be weird.  I have a v5 design branch that is exploring better options.

**Comment by aritchie** [comment]
Released today

**Comment by highplains** [comment]
So there is a way to do this now?

**Comment by aritchie** [comment]
Yes.  All sync calls come back with a disposable object or you can use a task cancellationtoken.  The samples briefly cover this.  I'll try to document at some point

**Comment by highplains** [comment]
I see. But still nothing for Toasts?

**Comment by highplains** [comment]
I had a method similar to "HideLoading" for toasts in pull request #176

**Comment by aritchie** [comment]
I don't want to have the toasts work like that.  It already has a timer dismissal in any case.  I'll think about it long term, but it isn't in the immediate plans for now.
