### ISSUE TITLE
[Bug] Could not resolve reference to 'System.Drawing.Color'

### ISSUE THREAD

**Issue by stesvis** [aritchie/userdialogs#681]
With the latest version(s), it throws a build error but only in **Release** mode in **Android**. In Debug it works fine.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.35
Xamarin.Forms 4.2 (latest)
VS 2019 and 2017

## Last working version
7.0.4

## Version of OS(s) listed above with issue
Android 9.1

## Steps to Reproduce
1. I just have the package installed, and in the code i have references to the Loading() and Toast()
2. Build in **RELEASE** mode

## Expected Behavior
Solution builds

## Actual Behavior

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		The "LinkAssemblies" task failed unexpectedly.
> Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Drawing.Color' (defined in assembly 'Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Drawing.Color
>    at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
>    at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
>    at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
>    at Mono.Linker.Steps.MarkStep.MarkGenericArguments(IGenericInstance instance)
>    at Mono.Linker.Steps.MarkStep.GetOriginalType(TypeReference type)
>    at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
>    at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
>    at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
>    at Mono.Linker.Steps.MarkStep.InitializeFields(TypeDefinition type)
>    at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
>    at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
>    at Mono.Linker.Steps.MarkStep.Initialize()
>    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
>    at Mono.Linker.Pipeline.Process(LinkContext context)
>    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
>    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
>    --- End of inner exception stack trace ---
>    at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
>    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
>    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	LiveDispatch.Mobile.Android

**Comment by aritchie** [comment]
https://github.com/aritchie/userdialogs/issues/654 This was your issue and it has been pinned with who to contact.  DO NOT FILE THIS AGAIN
