### ISSUE TITLE
[Bug] [iOS] Cannot update NuGet package 

### ISSUE THREAD

**Issue by coldacid** [aritchie/userdialogs#682]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library

7.0.35

## Version of OS(s) listed above with issue

N/A

## Steps to Reproduce
1. Open NuGet package management in VS 2019
2. Attempt install or update of Acr.UserDialogs package in a Xamarin iOS app project
3.

## Expected Behavior

Package is installed/updated.

## Actual Behavior

>Failed to add reference. The package 'Acr.UserDialogs' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
>  Reference unavailable.

**Comment by coldacid** [comment]
Deployment target for the project is 8.0.

**Comment by aritchie** [comment]
Read the pinned issues please

**Comment by coldacid** [comment]
I did. That issue was about runtime failure. This is about not even being able to add the package dependency to a project in the first place.

**Comment by aritchie** [comment]
Anything to do with System.Drawing.Common is to do with Xamarin.  This issue is theirs, so talk to them.
