### ISSUE TITLE
[Bug] ActionSheet with message not working on Droid

### ISSUE THREAD

**Issue by gianlucasaroni** [aritchie/userdialogs#683]
##Platform:
 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard
## Version of Library
7.0.35
## Version of OS(s) listed above with issue
Android 9
## Issue
Trying to create ActionSheet with message and options, but on Droid the message is not showing. On iOS it's all OK
## Expected Behavior
Show ActionSheet with message and options.
## Actual Behavior
message is not showing.
## Some Code
`
var options = new List<ActionSheetOption>();
options.Add(new ActionSheetOption("Do stuff", () => foo()));
options.Add(new ActionSheetOption("Do other stuff", () => otherFoo()));
var actionSheet = new ActionSheetConfig
{
	Title = "title",
	Message = "message",
	Cancel = new ActionSheetOption("cancel"),
	Options = options
};
this.userDialogs.ActionSheet(actionSheet);
`

**Comment by aritchie** [comment]
Lists and the message label don't work well together in the standard android popup without something custom which has been requested many times, but no one has contributed it successfully and I don't have a personal requirement, so this is likely not going to happen
