### ISSUE TITLE
[Bug] Setting default style id on time prompt config does not change most attributes of the time prompt

### ISSUE THREAD

**Issue by KthProg** [aritchie/userdialogs#685]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.1

## Version of OS(s) listed above with issue
Android 7

## Steps to Reproduce
1. Create a dialog style on android
2. Override colorAccent in this style
3. Set the style as default for TimePromptConfig in the main activity

## Expected Behavior
The style should change.

## Actual Behavior
The style is not visibly changed.

**Comment by KthProg** [comment]
It appears that the style id is being set on the alert dialog, but not on the child view/control rendered inside of it when building the dialog.

**Comment by ram4b7** [comment]
They have used alert dialog and setting time picker as view. Instead if they directly use time picker dialog this issue will get resolved.

**Comment by KthProg** [comment]
Nevermind, this is an issue in our app. I'm able to change the style in the demo apps.
