### ISSUE TITLE
[Enhancement] Show Multiple toasts

### ISSUE THREAD

**Issue by gmoney494** [aritchie/userdialogs#688]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
When showing multiple toasts with `UserDialogs.Instance.Toast(toastConfig);`. They override each other only showing one. Could we have it where they float down showing all of them until the time expires or user dismisses it. 

## API Changes
No real changes needed i feel. A nice to have would be to maybe have an override or hide the rest in case someone wants to keep current UX. Something like:
`UserDialogs.Instance.Toast(bool clearOther = false)`

Another nice to have would be to overide the order, in case i want the new toast to go to the top instead of just the bottom. 
`toast.SetOrder(int position)`

## Intended Use Case
I potentially show many various alerts in quick succession, i dont want only the last one to be shown as they keep overriding each other.

**Comment by aritchie** [comment]
This is not something I'm willing to take on as I'm not a big fan of displaying multiple toasts at one time
