### ISSUE TITLE
No ActionSheetConfig in ActionSheetAsync method

### ISSUE THREAD

**Issue by martijn00** [aritchie/userdialogs#69]

**Comment by aritchie** [comment]
ActionSheetConfig does not apply for this method since the options contain the callbacks.  What would I be awaiting as a result?  This is basically a method to appeal to the xamarin form users... nothing more.  IMO, the best way to do action sheets isn't async/await.

**Comment by martijn00** [comment]
Hmm, you might be right. But maybe it would be possible to await a generics parameter that the user has to set as result?

**Comment by aritchie** [comment]
There wouldn't be a lot of difference though.  You would still have to do some sort of switch statement after the outcome to determine what to do with the result.  Essentially, an action sheet is nothing more than a dropdown, so what you are describing is more dropdown->viewmodel binding.  I have never and will never use this async method myself.

**Comment by martijn00** [comment]
Thanks for explaining!
