### ISSUE TITLE
[Bug] UserDialogs.ShowLoading("Message...") crashes on Android

### ISSUE THREAD

**Issue by simusr2** [aritchie/userdialogs#690]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [x] .NET Standard

## Version of Library
Acr.UserDialogs 7.0.35
AndHUD 1.4.2
Xamarin.Forms 4.3.0.908675

## Steps to Reproduce
1. Use `UserDialogs.Instance.ShowLoading("Message...")` or `UserDialogs.Instance.Loading("Message...", show: true)`

## Expected Behavior
Show loading alert

## Actual Behavior
Crashes: Java.Lang.RuntimeException: 'Resource ID #0x7f030000'

[Exception.txt](https://github.com/aritchie/userdialogs/files/3880661/Exception.txt)

**Comment by aritchie** [comment]
This usually means the android support libraries don't match or you simply need to recompile.  In any case, it has been a long standing issue with xamarin builds.  Talk to them if the problem persists
