### ISSUE TITLE
When orientation is locked in Landscape, presenting a Dialog on iOS allows orientation to change [Bug] 

### ISSUE THREAD

**Issue by jbeacham** [aritchie/userdialogs#691]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.1

## Version of OS(s) listed above with issue
iOS 13.1.3

## Steps to Reproduce
1. Lock landscape orientation to Landscape in iOS ViewController
2. Present dialog "ActionSheet" 
3. Turn device to portrait and it auto rotates

## Expected Behavior
Device stays locked in Landscape mode

## Actual Behavior
Orientation rotates when it should be locked

**Comment by jbeacham** [comment]
Is there some way to use a custom UIAlertController or override the one being used?

**Comment by aritchie** [comment]
All the methods are virtual or you can implement the IUserDialogs interface yourself
