### ISSUE TITLE
Using UserDialogs.showLoading in MVVM viewModel Constructor

### ISSUE THREAD

**Issue by alkharashiam** [aritchie/userdialogs#692]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [X] .NET Standard

## Version of Library
7.0.35
## Version of OS(s) listed above with issue
Android 8

## Steps to Reproduce
1. Calling  a showLoading inside a viewModel constructor (im using prism) 
2.
3.

## Expected Behavior
ShowLoading appears then disappear after finished calling all methods

## Actual Behavior
calling` UserDialogs.Instance.Loading("Loading");` without C# Using ( UserDialogs...) will make the Loading always showing . If Used it inside Using like this:
```
 Using (UserDialogs.Instance.Loading("Loading")){
//My code 
}
```
the Loading will never show up . 

Also if used it like this will not work ,it will not show up .
```
UserDialogs.Instance.Loading("Loading");
// code ...
UserDialogs.Instance.HideLoading();
```

I did test it on Android simulator and physical smart phone , both gave same results . did not test it on Iphone .

**Comment by alkharashiam** [comment]
I am using Asynchronous Pattern discussed here : 
https://docs.microsoft.com/en-us/archive/msdn-magazine/2014/march/async-programming-patterns-for-asynchronous-mvvm-applications-data-binding..

So I already have a class Named NotifyTaskCompletion (code in link) and my constructor looks like this : 

```
        public NotifyTaskCompletion<ObservableCollection<IBusiness1>> Businesses { get; private set; }

        public BusinessesListViewModel(INavigationService navigationService,IUserDialogs userDialogs) : base (navigationService)
        {
            _navigationService = navigationService;
            _service = new Service();            
            Businesses = new NotifyTaskCompletion<ObservableCollection<IBusiness1>>(getAllBusinessesAsync());
        }
```
and my async function is this : 
```
        public async Task<ObservableCollection<IBusiness1>> getAllBusinessesAsync()
        {
            using (UserDialogs.Instance.Loading("Loading", null, null, true, MaskType.Black))
            {
                _getAllBusinessesStream = await _service.client.GetAllBussinessesAsync().ConfigureAwait(false);
                //Businesses = new ObservableCollection<IBusiness1>(_getAllBusinessesStream.Data.AllBusinesses);
                return new ObservableCollection<IBusiness1>(_getAllBusinessesStream.Data.AllBusinesses);
            }
        }
```
**This way it works fine** if i wrapped using inside the function , But what if I have more than one Async Function called in the constructor ? wrapping them up with Using in the constructor does not work for me . Example code : 

```
        public BusinessesListViewModel(INavigationService navigationService,IUserDialogs userDialogs) : base (navigationService)
        {
            _navigationService = navigationService;
            MerchantSelectedCommand = new DelegateCommand<object>(MerchantSelected);
            _service = new Service();    
             using (UserDialogs.Instance.Loading("Loading", null, null, true, MaskType.Black))
            {
            Businesses = new NotifyTaskCompletion<ObservableCollection<IBusiness1>>(getAllBusinessesAsync());
            //second Async Function Here
            }
        }

```

**Comment by alkharashiam** [comment]
Ill try to wrap all async functions inside an async Command and inside the command I use using(Dialogs.Loading...) and then call the command inside the constructor .
Once I try it ill write my feedback .

**Comment by aritchie** [comment]
You can't call for a dialog in the constructor.  It is listed in point #1 of the FAQ

**Comment by alkharashiam** [comment]
This is what I have done to make it work .

I used AsyncAwaitBestPractices.MVVM Nuget for async command .

I created an async Task and inside it i used Users.Dialog
```
        async Task ExampleAsyncMethod()
        {
            using (UserDialogs.Instance.Loading("Loading", null, null, true, MaskType.Black))
            {
                _getAllBusinessesStream = await _service.client.GetAllBussinessesAsync().ConfigureAwait(false);
           
                Businesses = new ObservableCollection<IBusiness1>(_getAllBusinessesStream.Data.AllBusinesses);
            }
        }
```
made a new IAsyncCommand which is Icommand but from the nuget package .

in the viewModel constructor i added these two lines : 
```

            ExampleAsyncCommand = new AsyncCommand(ExampleAsyncMethod);
            ExampleAsyncCommand.ExecuteAsync();
```

**Comment by aritchie** [comment]
This is a non-issue.  You shouldn't be executing view centric stuff before the view is ready.  In 90% of the cases, it is not ready by the viewmodel constructor.
