### ISSUE TITLE
[Bug] Title is displayed right before the loading indicator is hidden

### ISSUE THREAD

**Issue by raindeer** [aritchie/userdialogs#694]
## Platforms:

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.35

## Version of OS(s) listed above with issue
Have tested on:
iOS 12.4 (real device)
iOS 13.2 (simulator)

## Steps to Reproduce
1. Run UserDialogs.Instance.Loading(title:"").Show(); to show loading indicator without a title.
2. Run UserDialogs.Instance.Loading().Hide();

## Expected Behavior
The loading indicator should not have a title.

## Actual Behavior
The default title, "Loading", is flashed briefly before the loading indicator is hidden.

**Comment by aritchie** [comment]
You are creating 2 instances of the loader.  You should only do 

`
using (UserDialogs.Instance.Loading('title')) {
    // your async code here
}
`

**Comment by raindeer** [comment]
ah, thanks!
