### ISSUE TITLE
[Bug] iOS does not display progress dialog in center

### ISSUE THREAD

**Issue by khanh245** [aritchie/userdialogs#695]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
6.5.1

## Version of OS(s) listed above with issue
All iOS

## Steps to Reproduce
1. Usage of any Loading/ShowLoading/Progress will display a loading dialog but it is not centered.

## Expected Behavior
Dialogs should be centered.

## Fix: A release of BTProgressHUD to address was just released a couple of days ago should fix this, please pull in the latest package and release a new version of Acr.UserDialogs

**Comment by aritchie** [comment]
I don’t have a hard version on btprogresshud so just update from nuget
