### ISSUE TITLE
[Enhancement][iOS] Date & Time Pickers Dark Mode Support

### ISSUE THREAD

**Issue by cjrvdev** [aritchie/userdialogs#699]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.35
## Version of OS(s) listed above with issue
iOS 13.X

## Steps to Reproduce
1. Open any datepicker dialog while Dark Mode is enabled

## Expected Behavior
- Datepicker dialog shows a dark background with white/ligher color text

## Actual Behavior
- Datepicker shows dark background with dark text which is almost illegible

Image removed upon project request. Sorry for the inconvenience

**Comment by cjrvdev** [comment]
@aritchie Is it possibly fixed already in master branch? I deployed it in simulator and it appears how it should be but not in my app. Maybe the nuget is out of date? Can you please confirm it?

**Comment by aritchie** [comment]
I haven't done anything with dark mode.  It is marked as an enhancement for whoever wants to add it.

**Comment by Jerome2606** [comment]
Hello,

Any news for that point ?

On my side here is the result on iOS:
![image](https://user-images.githubusercontent.com/4534893/76428573-20902b80-63ae-11ea-8edd-ac949734019e.png)

My app is no more usable with dark mode, user cannot choose a date.

Is there a workaround or a roadmap for this support ?

**Comment by aritchie** [comment]
@Jerome2606 As I stated previous, I'm not doing anything with this.  If anyone wants to submit a PR, I'm happy to take it.

**Comment by KthProg** [comment]
I'll take a look and submit a PR that prevents it from completely disappearing in dark mode on iOS 13.x at least. This doesn't seem like something the community should have to contribute though, it is essentially broken.

**Comment by aritchie** [comment]
@KthProg You think I should just do it for free even though I don't use this functionality anymore?  I guess I could just drop the functionality then.  Be respectful or don't use the library in the future.

**Comment by KthProg** [comment]
Uh. Okay. I have a PR up so if you merge that in it will at least be usable in dark mode on iOS 13+, thanks.

**Comment by Jerome2606** [comment]
@aritchie So what ? We have an issue that is critical and a PR that fixed it. Can you please take a look on the code and merge it if it is ok ?

Thanks

**Comment by aritchie** [comment]
@Jerome2606 If it's a critical issue for you, you can easily fork and take the PR.  I haven't decided if I'm even going to keep this functionality in the library right now.  I'm also not doing any work on the library right now since it isn't active in any of my projects

**Comment by Jerome2606** [comment]
@aritchie yes that's what I have done. But your library has huge download. It would be nice if all can get this fix no?
