### ISSUE TITLE
[Bug] Can't align Progress Dialog to Center of the device vertically

### ISSUE THREAD

**Issue by kgbuddhima** [aritchie/userdialogs#701]
## Version of Library
Acr.UserDialogs 7.0.3.5
## Version of OS(s) listed above with issue
Xamarin.Forms 4.3

## Steps to Reproduce
1. call  UserDialogs.Instance.ShowLoading(loadingMessage, MaskType.None);

## Expected Behavior
The progress bar should show center of the screen vertically on iOS

## Actual Behavior
But it does not show in the center of the screen vertically. It locates between top and center.

![image](https://user-images.githubusercontent.com/14989528/74436438-772c4780-4e8c-11ea-95c3-0c30e8e36dad.png)

And also the Toast config does not have Center align option.

![image](https://user-images.githubusercontent.com/14989528/74436098-db9ad700-4e8b-11ea-81b4-bd92c6ce8d00.png)

**So how to align it center**

**Comment by aritchie** [comment]
Toasts have absolutely nothing to do with progress dialogs... XF is not an operating system and has nothing to do with this library, so is this the latest iOS?  You have posted the absolute bare minimum info to get past the bot... please note that this is not a support forum.  You need to give details.

**Comment by aritchie** [comment]
No response from user - closing
