### ISSUE TITLE
[Bug] DatePicker in ModalPresentation mode FormSheet isn't displayed properly

### ISSUE THREAD

**Issue by Genfood** [aritchie/userdialogs#702]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ x ] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.35
## Version of OS(s) listed above with issue
iOS 13.3

## Steps to Reproduce
1. Push a page Modal in FormSheet mode
```csharp
var navigationPage = new NavigationPage(new MainPage());
Xamarin.Forms.PlatformConfiguration.iOSSpecific.Page.SetModalPresentationStyle(navigationPage.On<Xamarin.Forms.PlatformConfiguration.iOS>(), Xamarin.Forms.PlatformConfiguration.iOSSpecific.UIModalPresentationStyle.FormSheet);
await Navigation.PushModalAsync(navigationPage);
```
2.  Call `await UserDialogs.Instance.DatePromptAsync(config);` 

## Expected Behavior
Seeing the buttons completely.

## Actual Behavior
The Buttons to close and accept the DatePicker are croped.  
![2020-02-13_02-22-43-](https://user-images.githubusercontent.com/11618226/74439953-6ae4c200-4e6d-11ea-9461-7d3a2ab5b5d1.png)

**Comment by aritchie** [comment]
The whole library has troubles with modals on modals.  You are welcome to submit a patch, but this isn't something that I will be fixing.
