### ISSUE TITLE
ActionSheet message not shown

### ISSUE THREAD

**Issue by csanszan1** [aritchie/userdialogs#703]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.35

## Version of OS(s) listed above with issue
Android 10

## Steps to Reproduce
1. Make an actionsheet and set a message

## Expected Behavior
The message should be shown

## Actual Behavior
The message is not shown

```
UserDialogs.Instance.ActionSheet(new ActionSheetConfig()
.SetTitle("Csere érkezett")
.SetMessage("Csere érkezett: a(z) " + cserebecsapat + "(" + cserebecsapatnev + ") akar tőled " + cserebegivemennyi + " " + cserebegive + "-t " + cserebegetmennyi + " " + cserebeget + "-ért cserébe. Elfogadod a cserét?")
.Add("Elfogadom", () => UserDialogs.Instance.Alert("Elfogadtad"))
.Add("Nem fogadom el", () => UserDialogs.Instance.Alert("Nem fogadtad el"))
.Add("Később döntöm el", () => UserDialogs.Instance.Alert("Később döntöd el"))                           
                       );
```
![Screenshot_2020-02-16-13-03-17-576_hu csanszan1 tozsde](https://user-images.githubusercontent.com/14258227/74604298-d2dd1780-50bc-11ea-8aef-f28932bd0144.jpg)

**Comment by aritchie** [comment]
Message is not supported on android

**Comment by kerbooo** [comment]
Hello is there any way to show long title with ActionSheet without trim from end? Thank you in advance.

**Comment by kerbooo** [comment]
Hello @aritchie firstly thank you for your very useful plugin. I would like to ask is there any way to create a dialog with 3 or more buttons and long title or message that seems center of screen for Android Platform? Thank you in advance.
