### ISSUE TITLE
[Enhancement] Support for AndroidX and Xamarin Forms 4.5

### ISSUE THREAD

**Issue by ysmoradi** [aritchie/userdialogs#704]
## Summary
I'd like to update project to use AndroidX which is now recommended by both Google and Microsoft. It will also enable us to use this fantastic library in Xamarin Forms 4.5 based projects.

https://devblogs.microsoft.com/xamarin/xamarin-forms-xamarin-essentials-go-androidx/

## API Changes
We need to drop support for android 8.1
We need to use Xamarin.Google.Android.Material package instead of Xamarin.Android.Support.Design

## Intended Use Case
N/A

**Comment by aritchie** [comment]
This has been released in 7.1
