### ISSUE TITLE
[Enhancement] Touch target size of input in PromptAsync too small 

### ISSUE THREAD

**Issue by SKeehnen** [aritchie/userdialogs#708]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.1.0.440 (also with earlier versions)
## Version of OS(s) listed above with issue
Tested with all Android versions starting at 5.0

## Steps to Reproduce
1. Create a Xamarin Android project
2. Add a PromptAsyc, for example:
`var result = await Acr.UserDialogs.UserDialogs.Instance.PromptAsync("message", "title", "OK", "Cancel", "Enter a value", Acr.UserDialogs.InputType.Default);`
3. Build the project and upload the APK as Beta to the Google Play store. After uploading a pre-launch report will be generated.

## Expected Behavior
A pre-launch report without warnings. A setting for the input height or a default height of 48dp would solve this. 

## Actual Behavior
The pre-launch report gives a warning for all Android versions, saying the touch target size is too small. Current height is 45dp, but the Material Design Accessibility Guidelines describes this should be at least 48dp. Also see [https://support.google.com/accessibility/android/answer/7101858?hl=en](https://support.google.com/accessibility/android/answer/7101858?hl=en) 

The following image (in Dutch) is one of the warnings which is generated in the report:
![image](https://user-images.githubusercontent.com/7467040/75968595-f7632d00-5ecd-11ea-9f34-98fb6159353d.png)

**Comment by aritchie** [comment]
This is something I definitely won't be fixing myself.  Feel free to send a PR
