### ISSUE TITLE
[Enhancement] Enable option SetUseBottomSheet(true) for ActionSheetAsync on Android

### ISSUE THREAD

**Issue by jsabacinski** [aritchie/userdialogs#709]
## Summary
I want to be able to call **ActionSheetAsync** with the **SetUseBottomSheet(true)** on **Android**, so the Dialog shows up at the bottom of the screen.

## API Changes
As I investigated the code, there are probably 2 steps necessary, whereby the second one is more important for my case
1. Extend the **ActionSheetAsync** signature (**bool setUseBottomSheet = false** parameter) and implementation:

```
public virtual async Task<string> ActionSheetAsync(string title, string cancel, string destructive, 
bool setUseBottomSheet = false, CancellationToken? cancelToken = null, params string[] buttons)
{
   [...]
   if (setUseBottomSheet)
		cfg.SetUseBottomSheet(true);
   [...]
}
```

2. Override the **Dismiss** method in the **BottomSheetDialogFragment** class, as it is done in **ActionSheetDialogFragment** class. Background - I implemented my own ActionSheetAsync method, where I set **SetUseBottomSheet** option to the config object and it was shown in the correct way (at the bottom of the screen). Nevertheless, when I click outside the dialog, it disappears, but the method would not finish, because the task is not completed.
       
 ```
        public override void Dismiss()
        {
            base.Dismiss();
            this.Config?.Cancel?.Action?.Invoke();
        }
```

## Intended Use Case
I want to call **ActionSheetAsync** in Android from an async command, which shows at the bottom, and when I click outside the dialog, I want the ActionSheetAsync task to be finished, so the code can move on.

**Comment by aritchie** [comment]
I will probably pulling ActionSheetAsync out in a future version.

**Comment by jsabacinski** [comment]
What do you mean by pulling it out? You are going to remove it from repository? May I ask why? How are we supposed to use ActionSheet with async code then?

**Comment by aritchie** [comment]
You don't need async for the action sheet.  There is an ActionSheet that accepts a bunch of callbacks.

**Comment by jsabacinski** [comment]
Ok, I see. Maybe you could help me out then, because I'm not sure, if I use it correctly: I have an IMvxAsyncCommand with an async handler, in which I call an ActionSheet. The ActionSheet has as a Callback an async method, too:

```
new MvxAsyncCommand(async () => {
                    UserDialogs.Instance.ActionSheet(new ActionSheetConfig()
                    {
                        Options = new List<ActionSheetOption>()
                        {
                            new ActionSheetOption("New",
                                async () => await NewAsync())
                        }
                    });
})
```

My question is: when I click on "New" button, the NewAsync async method will be called asynchronously. Is it "fire&forget", and the IMvxCommand code will finish? Or the IMvxCommand call isn't done, till the NewAsync method is done?

**Comment by aritchie** [comment]
No - the methods in the callback are not awaited.

**Comment by cjrvdev** [comment]
In my humble opinion: awaitable Task > callbacks.
In my experience I've always struggled with "split in half" methods by being forced to use callbacks for example when using any registration service that might need to be awaited and not virtually sync.

Again this is just my opinion, cases may vary :)
