### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by rubgithub** [aritchie/userdialogs#71]
Hi, how did you get this time? I mean Tab Page, looks like lollipop. How do you apply this theme in xamarin forms?

Thanks.

**Comment by aritchie** [comment]
You need NativeCode.Mobile.AppCompat and a change to your mainactivity.  Take a look at the MainActivity in Samples.Droid.  

Careful with this though, I don't believe it supports all page types

**Comment by rubgithub** [comment]
Thanks.
