### ISSUE TITLE
ShowLoading not showing on Xamain Forms iOS

### ISSUE THREAD

**Issue by Nerves82** [aritchie/userdialogs#711]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [ ] UWP
 - [x ] .NET Standard

## Version of Library
7.1.0.440

## Version of OS(s) listed above with issue
2.1

## Steps to Reproduce
1.Not sure yet

## Expected Behavior
Calling ShowLoading() should show loading screen as the screen loads data after init.

## Actual Behavior
ShowLoading() does not show the loading dialog. 

So I am still trying to debug the issue and am looking to get help/input for the lib author and community. I have a xamarin forms application. I use ACR extensively throughout. There is one instance in my app that "ShowLoading" does not work. The app starts with a sign in screen. Then after that it moves to a main menu screen. When I do this transition I am actually changing the "Application.Current.MainPage" and I think that might have something to do with the issue. 

        UserDialogs.Instance.HideLoading();
        Device.BeginInvokeOnMainThread(async () =>
         {
                Application.Current.MainPage = new NavigationPage(new MainMenuPage());
         });

After this happens, I have a lifecycle method in my ViewModel that gets called on the pages's "OnAppearing()" method. Within this method I call "ShowLoading()" but it does not show. Strangely, if I call "ShowAlert()" in the same spot, it will show. And then after the view has fully loaded, if I call "ShowLoading()" when saving data or some such, it shows just fine. Any advice I can get to help me debug this would be very helpful. Thanks.

**Comment by aritchie** [comment]
I usually tell people to use Loading in a using statement.  All navigation must done outside of the using statement.

**Comment by Nerves82** [comment]
Hi Archie, can you point me to an example of what you are talking about? I don't see how to use ShowLoading() inside a using statement since the method returns a void and does not implement IDisposable or have a dispose method. Thanks.

**Comment by acaliaro** [comment]
> Hi Archie, can you point me to an example of what you are talking about? I don't see how to use ShowLoading() inside a using statement since the method returns a void and does not implement IDisposable or have a dispose method. Thanks.

you have to use "Loading", not ShowLoading, in a using statement

**Comment by Nerves82** [comment]
Ah, got it. Thanks a lot for that, it did the trick. I changed my usage to the below and all is good. 

      using (var loading = UserDialogs.Instance.Loading("Logging in..."))
            {
                loading.Show();
                ...
                Device.BeginInvokeOnMainThread(async () =>
                    {
                        Application.Current.MainPage = new NavigationPage(new PlayersViewPage())
                        {
                            BarBackgroundColor = AppColors.PrimaryDark,
                            BarTextColor = Color.White
                        };
                    });
               }
