### ISSUE TITLE
[Bug] Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch

### ISSUE THREAD

**Issue by nrooban** [aritchie/userdialogs#712]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ √] iOS
 - [ √] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.1.0.440
## Version of OS(s) listed above with issue
Iphone Pro 13.3 (Simulator)

## Steps to Reproduce
1. Installed ACR.Dialog on Xamarin forms PCL, iOS and Android projects.
2. Passed it from LoginViewModel to Base
       public LoginPageViewModel( INavigationService navigationService, IUserDialogs dialogs): 
                      base(navigationService, dialogs)

3. implemented in the ViewModelBase
       protected IUserDialogs Dialogs { get; set; }
       public ViewModelBase(INavigationService navigationService, IUserDialogs dialogs)
        {
            NavigationService = navigationService;
            Dialogs = dialogs;
        }

4. Added to Android Project MainActivity
       protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);
            UserDialogs.Init(this);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            LoadApplication(new App(new AndroidInitializer()));
       }

5. I have not used the dialog yet, just did the setup and ran the project on iOS.

## Expected Behavior
Run the application 

## Actual Behavior
Throws the error on iOS project Main.cs ([Bug] Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch)
![image](https://user-images.githubusercontent.com/4565888/77228450-748be300-6bec-11ea-9cd3-9ee63d10ca0c.png)

**Comment by aritchie** [comment]
This has absolutely nothing to do with this plugin.

**Comment by nrooban** [comment]
HI, the problem coms as soon as I installed this plugin. When I removing this plugin and ran its working. Any Idea?

**Comment by aritchie** [comment]
It looks like you are using dependency injection (via prism by the looks of it), my guess is you haven't registered it with the container.  There will be messages in the output window that should tell you this.

**Comment by nrooban** [comment]
Hi, yes you absolutely right.  i forgot to register with container. This is how i did it and worked as expected. 

```
containerRegistry.RegisterInstance<IUserDialogs>(UserDialogs.Instance);
```
