### ISSUE TITLE
[Bug] UWP Toasts always show up in the top left corner

### ISSUE THREAD

**Issue by sheperd13** [aritchie/userdialogs#713]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [x] UWP
 - [ ] .NET Standard

## Version of Library
7.1.0.440
## Version of OS(s) listed above with issue
Windows 10

## Steps to Reproduce
1. Instantiate toast using ToastConfig. Whatever position is set is ignored.
```
        var toastConfig = new ToastConfig("message");
        ToastConfig.DefaultPosition = ToastPosition.Bottom;
        toastConfig.BackgroundColor = System.Drawing.Color.FromArgb(48, 66, 105);
        toastConfig.SetDuration(2000);
        UserDialogs.Instance.Toast(toastConfig);
```

## Expected Behavior
Toast appears at the bottom of the page as it does with Android and iOS

## Actual Behavior
Toast appears in top left corner ignoring both default positioning and explicit position settings

**Comment by aritchie** [comment]
This is the intended behaviour for UWP
