### ISSUE TITLE
[Bug] ProgressDialog not showing after update version plugin

### ISSUE THREAD

**Issue by Abesoddy** [aritchie/userdialogs#714]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.1.0.440

## Version of OS(s) listed above with issue
Android API 28

## Steps to Reproduce
1. I have a bug after updating the plugin when I want to use the progress dialog. It does not appear and in debug nothing happens after `using (IProgressDialog progressDialog = UserDialogs.Instance.Progress(Strings.messageUnzipAlertView, null, null, true, MaskType.Black))`

Here is my function which allows you to unzip a zip file and display a progress dialog :

`public async static Task<bool> UnzipFileInDirectory(int currentVersion)
        {
            Assembly assembly = Assembly.GetExecutingAssembly();
            Stream stream = assembly.GetManifestResourceStream(Strings.fileRessourcesName);

            // Create folder version
            IFolder rootFolder = await PCLHelper.CreateFolder((currentVersion + 1).ToString());

            ZipFile zipFile = null;

            try
            {
                zipFile = new ZipFile(stream);

                int filesOk = 0;

                using (IProgressDialog progressDialog = UserDialogs.Instance.Progress(Strings.messageUnzipAlertView, null, null, true, MaskType.Black))
                {
                    foreach (ZipEntry zipEntry in zipFile)
                    {
                        Stream zipEntryStream = zipFile.GetInputStream(zipEntry);
                        IFolder folder;

                        if (zipEntry.Name.EndsWith("/", StringComparison.Ordinal))
                        {
                            folder = await PCLHelper.CreateFolder(zipEntry.Name, rootFolder);
                            System.Diagnostics.Debug.WriteLine("Directory created : " + folder.Path);
                        }
                        else
                        {
                            folder = rootFolder;

                            // Create the file in file system and copy entry stream to it
                            IFile zipEntryFile = await rootFolder.CreateFileAsync(zipEntry.Name, CreationCollisionOption.FailIfExists);
                            using (Stream outPutFileStream = await zipEntryFile.OpenAsync(PCLStorage.FileAccess.ReadAndWrite))
                            {
                                await zipEntryStream.CopyToAsync(outPutFileStream);
                                System.Diagnostics.Debug.WriteLine("File created : " + zipEntryFile.Path);
                            }
                        }

                        filesOk++;

                        int percentage = unchecked((int)((filesOk * 100) / zipFile.Count) + 1);

                        // Update progress loader
                        progressDialog.PercentComplete = percentage;
                    }

                    await Task.Delay(1000);
                }

                return true;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("Error unzip file : " + ex);

                return false;
            }
            finally
            {
                if (zipFile != null)
                {
                    zipFile.IsStreamOwner = true;
                    zipFile.Close();
                }
            }
        }`

## Actual Behavior

Version 7.0.1 works perfectly so I don't really understand why the progress dialog no longer appears and blocks the rest of the code...

**Comment by aritchie** [comment]
It works fine for me.  Nothing has changed in this area in quite some time
