### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by xgianni** [aritchie/userdialogs#716]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.1.0.442
## Steps to Reproduce
1. Installed the nuget package to all my project (iOS,Android,UWP)
2. I tested it on UWP and it works
3. I tested in Android and it doesn' work

## Expected Behavior
Open UserDialog with my message

## Actual Behavior
I get the follow error:
[Acr.UserDialogs] This is the bait library, not the platform library.  You must install the nuget package in your main executable/application project

**Comment by aritchie** [comment]
You have to target the appropriate android major version as listed in the nuget package.  Currently android 9+
