### ISSUE TITLE
[Enhancement] AvaloniaUI Support

### ISSUE THREAD

**Issue by fncap** [aritchie/userdialogs#717]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
It would be useful if this library could be used with AvaloniaUI Framework.

## API Changes
n/a

## Intended Use Case
ref: https://avaloniaui.net

**Comment by aritchie** [comment]
Sorry - I'm going to pass on this.  It isn't something I want to support going forward.
