### ISSUE TITLE
[Bug] ConfirmAsync does not await

### ISSUE THREAD

**Issue by sachinkanadia** [aritchie/userdialogs#722]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.1.0.442
## Version of OS(s) listed above with issue
Android Version 9

## Steps to Reproduce
1. Call and await ConfirmAsync(..);

## Expected Behavior
The call is awaited and the debugger moves to the next statement.

## Actual Behavior
The call gets invoked but the debugger skips out of currently executing block. Once that executing block completes the debugger moves back to the next statement after the ConfirmAsync(..); call. This maybe happening by design but I need to get the result of the ConfirmAsync(..); call in order to continue processing correctly. How can I achieve this?

**Comment by aritchie** [comment]
The library is working fine for this case.  Please submit a reproducible test case if you want help in the future.

**Comment by sachinkanadia** [comment]
How would you create a test case for calling an async method? Can you provide an example? Should I supply a sample solution which replicates the issue?
