### ISSUE TITLE
Dialog hangs when showing in MacOS after App installation (works fine in development)

### ISSUE THREAD

**Issue by BlueFire-LLC** [aritchie/userdialogs#723]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard
-  [X] MacOS

## Version of Library
Latest
## Version of OS(s) listed above with issue
Catalina 10.15.4

## Steps to Reproduce
1. Create .pkg file
2. Install App
3. Show a dialog
4. Dialog is displayed but App hangs

## Expected Behavior
Dialog accepts button and App continues

## Actual Behavior
Dialog is displayed but App hangs

**Comment by BlueFire-LLC** [comment]
It's now working. Not sure what I did but it might have something to do with the Sandbox entitlements I added. I can remove some to figure out which one it was (if any) but if someone here actually knows then that would be great. I would however suggest that MacOS be added to the list of supported devices in the ReadMe file and also what is needed for a distributed package to be installed outside of the App Store.

Nice job by the way. I really appreciate all the hard work that you all put into this.

**Comment by BlueFire-LLC** [comment]
I might have spoke too soon. My beta tester tried to install the version with UserDialog enabled and the App crashed on startup. Still investigating ...

**Comment by aritchie** [comment]
I don't actually want to support macOS which is why it isn't in the list.  macOS isn't something I ever target other than messing around.  I'll take PR's for it, but not issues.  Best of luck.

**Comment by BlueFire-LLC** [comment]
Oh, Ok. I guess I was confused with the Federico Maccaroni credit for the macOS Implementation.
