### ISSUE TITLE
[Bug] Touch screen to close BottomActionSheet when close option not set

### ISSUE THREAD

**Issue by Saqo1995s** [aritchie/userdialogs#726]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if the platform is not listed, it is not supported)

 - [ ] Android

## Version of Library
7.1.0.446
## Version of OS(s) listed above with issue
Any version

## Steps to Reproduce
* Cant Close it without adding the close option (I don't want to show close button)
1. Create new ActionSheet(ActionSheetConfig config)(UseBottomSheet= true),
2. Set cancel option to null,
3. Touch to screen (not on the ActionSheet to close it

* Showing extra place when cancel option text is a new ActionSheetOption with Text = null or string.Empty
1. Create new ActionSheet(ActionSheetConfig config )(UseBottomSheet= true),
2. Set cancel option to new ActionSheetOption(null/string.Empty),
3. Showing extra place in the bottom of the ActionSheet 

bottom extra place!
![image](https://user-images.githubusercontent.com/35834865/86445153-f24ea700-bd22-11ea-8bdb-f50a5c281815.png)

**Comment by aritchie** [comment]
@Saqo1995s seems to be a bug in the bot. 

In any case, this is a feature request, not a bug.  I'm happy to take a PR for this, but I'm not doing much work with this library right now.
