### ISSUE TITLE
[Question] Xamarin.Forms.MacOS

### ISSUE THREAD

**Issue by juanp3053** [aritchie/userdialogs#728]
## Summary
Hello,
I have been working on the MacOS implementation of one of my apps and I was wondering if it is currently supported for Xamarin.Forms.Mac, if not, is there or will there be any plans of implementing this?

I've been using the ACR.Userdialogs for some time now in my Xamarin.Forms app, it has been great. So I want to thank everyone that contributed!

## API Changes
MacOS

## Intended Use Case
Using Acr.UserDialogs with MacOS platform

**Comment by aritchie** [comment]
This project has absolutely nothing to do with Xamarin Forms.  This project already has a base implementation of macOS but it won't ever be supported beyond PRs

**Comment by juanp3053** [comment]
@aritchie Thanks for the quick answer.
