### ISSUE TITLE
UserDialogs.Instance.Loading is not working with Xamarin.Forms above version 4.4.0.991864

### ISSUE THREAD

**Issue by nbs888** [aritchie/userdialogs#731]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ ] Android
 - [ x] UWP
 - [ ] .NET Standard

## Steps to Reproduce
1. Execute project (UWP)
2.
3.

## Expected Behavior
UserDialogs.Instance.Loading is supposed to show a loading box.

## Actual Behavior
The loading box does not appear. The rest of the project works fine.
This happens, if I use a version of Xamarin.Forms above version 4.4.0.991864.

**Comment by aritchie** [comment]
This project has nothing to do with Xamarin Forms
