### ISSUE TITLE
[Enhancement] Can this be used to display an Alert Box with an image and/or other components inside?

### ISSUE THREAD

**Issue by tdbe** [aritchie/userdialogs#734]
## Summary
Not sure if this is already possible and how, but I would love a cross platform way to show an Alert Box that can display an image, a gif, a scrollview etc. Just an image would be a great start.

## API Changes
not sure

## Intended Use Case
Display a user dialog alert box (a hovering box of content) that can display more than just plain text. To better but quickly indicate (graphically) to the user what might have gone wrong and how to fix it instead of pushing to a new page.

**Comment by aritchie** [comment]
This can't be done with native dialogs
