### ISSUE TITLE
[Enhancement] Better control of toast's position.

### ISSUE THREAD

**Issue by Tommigun1980** [aritchie/userdialogs#736]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
ToastConfig.DefaultPosition only accepts Top and Bottom, but both options cover essential navigation options. Please allow for more fine-grained control of the positions (such as percentage of screen area).

## API Changes
Add the enum option ToastPosition.Custom, and add double ToastConfig.CustomPosition.

## Intended Use Case
Make toast messages not cover the back button in the nav bar, or tab buttons at the bottom.

**Comment by aritchie** [comment]
Again, not supported well on the Android side

**Comment by Tommigun1980** [comment]
@aritchie In that case do you have any advice on how to get around it on iOS? On iOS the Top position covers any modal navigation buttons (like the back arrow and close), and the Bottom position covers the tabs. So either option completely blocks navigation from the user.

This combined with no ability to swipe them away, and with only one action button (which is already taken so can't add a "Close" action) -- completely locks up the user's ability to navigate. Why not add this option on iOS - on Android the Top position does not block modal navigation.
