### ISSUE TITLE
[Enhancement] Allow dismissing toast early by swiping it

### ISSUE THREAD

**Issue by Tommigun1980** [aritchie/userdialogs#737]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
Toast messages can sometimes linger and it's customary to swipe away unwanted ones. Currently the toast message doesn't react to swipes. Please add this.

## API Changes
Add bool ToastConfig.DismissableBySwipe.

## Intended Use Case

**Comment by aritchie** [comment]
Add a dismiss button and dispose of toast instance manually

**Comment by Tommigun1980** [comment]
> Add a dismiss button and dispose of toast instance manually

It's not the same thing at all. People are used to swiping away notifications with a swipe gesture. Also, the plugin only supports one action at a time and it's already taken.

**Comment by aritchie** [comment]
@Tommigun1980 You are welcome to send a PR then.  It isn't something that comes OOB with some of the platforms.  It isn't anything that I will be personally investing time into.

**Comment by Tommigun1980** [comment]
> @Tommigun1980 You are welcome to send a PR then. It isn't something that comes OOB with some of the platforms. It isn't anything that I will be personally investing time into.

You already closed the issue so it I thought  you didn't think the suggestion had any merit. I will look into adding support for it later.
Thanks.
