### ISSUE TITLE
[Enhancement] Add support for CancellationToken to toast

### ISSUE THREAD

**Issue by Tommigun1980** [aritchie/userdialogs#738]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
It would be nice of toast messages could be closed by sending in a cancellation token when displaying them.

## API Changes
Add ToastConfig.SetCancellationToken(CancellationToken token)

## Intended Use Case
For example when a user logs out, things are torn down but toasts are still active. This forces one to add code in the action itself to see if it's still valid.

**Comment by aritchie** [comment]
Unnecessary - toast returns an idisposable that is used to dismiss toast
