### ISSUE TITLE
[Enhancement] Add support for multiple action buttons in toast.

### ISSUE THREAD

**Issue by Tommigun1980** [aritchie/userdialogs#739]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE! 

## Summary
It seems like toast messages can only have one action. It would be nice if they could have multiple action buttons.

## API Changes
Just let the user chain multiple actions in the toast config, without the last one overwriting all the other ones.

## Intended Use Case
For example adding an action button and a hide notification button (to dismiss it early).

**Comment by aritchie** [comment]
This is not supported well on the Android side
