### ISSUE TITLE
[Enhancement] Add % to ProgressDialog

### ISSUE THREAD

**Issue by dannythomas13** [aritchie/userdialogs#744]
## Summary
I don't believe it is always clear that the number shown is the progress as a percentage, suggest adding the symbol for clarity.

## API Changes
None

## Intended Use Case
Showing % of items downloaded, when the number of items being downloaded is large it appears to me as though we are showing the number downloaded and not the percentage

**Comment by aritchie** [comment]
I show % in the text.  I'm not sure what you are referring to.  Can you please take a screenshot or something to better explain what you are asking for

**Comment by dannythomas13** [comment]
Hi, sure thing 👍 
I current set the PercentComplete value on IProgressDialog and use UserDialogs.Instance.Progress(title); to render.

I can see the value but no % symbol.

Here is a screenshot as requested:
https://paste.pics/A07FL

**Comment by aritchie** [comment]
Feel free to send a PR and I'll approve it.  I don't do much work at all on the UWP side of things

**Comment by dannythomas13** [comment]
Embarrassingly I'm not sure how to push my branch to submit a PR, I do have the fix, can you offer some guidance?
