### ISSUE TITLE
[Bug]  In Android X , calling confirmasync causes Android to crash

### ISSUE THREAD

**Issue by dorisoy** [aritchie/userdialogs#745]
######  Hi,aritchie !
 
 In Android X , calling confirmasync causes Android to crash, my package reference as follows:

##### Forms:
Xamarin.Forms Version="4.8.0.1269"

##### AndroidX:
 
*Xamarin.AndroidX.Browser  Version="1.2.0.1*
*Xamarin.AndroidX.Lifecycle.LiveData  Version="2.2.0.1*
*Xamarin.Google.Android.Material  Version="1.0.0.1*
*Xamarin.AndroidX.Legacy.Support.V4  Version="1.0.0.1*
*Xamarin.AndroidX.AppCompat  Version="1.1.0.1*
*Xamarin.AndroidX.Migration Version="1.0.6.1"*

Crash occurred while executing  ---->> "var disp = this.Confirm(config);" ???

    public virtual async Task<bool> ConfirmAsync(ConfirmConfig config, CancellationToken? cancelToken = null)
    {
        if (config.OnAction != null)
            throw new ArgumentException(NO_ONACTION);
    
        var tcs = new TaskCompletionSource<bool>();
    
        config.OnAction = x => tcs.TrySetResult(x);
    
        //--->>
        var disp = this.Confirm(config); 
        //<<---
    
        using (cancelToken?.Register(() => Cancel(disp, tcs)))
        {
            return await tcs.Task;
        }
    }
    

After I demoted Android x, the code worked correctly.

*Xamarin.AndroidX.Browser Version="1.2.0.2"*
*Xamarin.AndroidX.Lifecycle.LiveData Version="2.2.0.2"*
*Xamarin.Google.Android.Material Version="1.0.0.2"*
*Xamarin.AndroidX.Legacy.Support.V4 Version="1.0.0.2"*
*Xamarin.AndroidX.AppCompat Version="1.1.0.2"*
*Xamarin.AndroidX.Migration" Version="1.0.6.2"*

I hope I can get your help. Thank you very much.!!

**Comment by CleverSoftwarePoland** [comment]
Did you find proper solution for this problem?
