### ISSUE TITLE
[Bug] Time and Date dialogs broken in iOS14

### ISSUE THREAD

**Issue by salgiza** [aritchie/userdialogs#750]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.1.0.454

## Version of OS(s) listed above with issue
iOS 14.0

## Steps to Reproduce
1. Call DatePromptAsync or DatePromptAsync TimePromptAsync in your code.

## Expected Behavior
A date or time picker should appear.

## Actual Behavior
A black box appears covering most of the screen with a small input box.

**Comment by Hualumi** [comment]
Any updates on this?

**Comment by syle20091** [comment]
@salgiza  I was be able to fix it by change adding `datePicker.PreferredDatePickerStyle = UIDatePickerStyle.Wheels; ` for datePicker in the AIDatePickerController. Seems AIDatePickerController are not fully support iOS 14.

**Comment by rr-autoit** [comment]
this is proberly connected to https://github.com/xamarin/Xamarin.Forms/issues/12258

**Comment by rr-autoit** [comment]
> 
> 
> @salgiza I was be able to fix it by change adding `datePicker.PreferredDatePickerStyle = UIDatePickerStyle.Wheels; ` for datePicker in the AIDatePickerController. Seems AIDatePickerController are not fully support iOS 14.

may i ask how you changed that? 
did you fork this repo and make your own?

**Comment by rr-autoit** [comment]
@syle20091 how did you manage that?

**Comment by syle20091** [comment]
@rr-autoit Hi, I did it in a very ugly way, because PreferredDatePickerStyle is new in iOS 14, so there is no way AIDatePickerController would expose any API for us to modify this property back to "wheel". So I created my own "AIDatePickerController" and add PreferredDatePickerStyle into the constructor during the initialisation of DatePicker, And pass my modified "AIDatePickerController" to DatePrompt to make it like before.

**Comment by rr-autoit** [comment]
haha thanks mate, thought it was something like that.

**Comment by syle20091** [comment]
no worries

**Comment by aritchie** [comment]
Fixed by PR
