### ISSUE TITLE
[Bug] [iOS] [LayoutConstraints] warning

### ISSUE THREAD

**Issue by jocontacter** [aritchie/userdialogs#752]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.1.0.442
## Version of OS(s) listed above with issue
13.6

## Steps to Reproduce
`
            ActionSheetConfig options = new ActionSheetConfig();
            options.Add("menu_add_page".Translate(), async () => await CreatePage(null), null);
            options.Add("menu_add_category".Translate(), async () => await CreateCategory(), null);
            options.Add("menu_course_settings".Translate(), NavigateToSettings, null);

            options.UseBottomSheet = true;
            options.SetCancel("ask_cancel".Translate());
            var d = UserDialogs.Instance.ActionSheet(options);
            SubscriptionDisposables.Add(d);
`
## Expected Behavior
working without warnings

## Actual Behavior
All working, but warning appears:

[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x60000390a8f0 UIView:0x7fadf1f268e0.width == - 16   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000390a8f0 UIView:0x7fadf1f268e0.width == - 16   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by aritchie** [comment]
I’m not really worried about warnings.  You’re welcome to submit a PR but this isn’t something I will personally be dealing with
