### ISSUE TITLE
[Bug] DebugType=Full will be depreciated for Xamarin.Android

### ISSUE THREAD

**Issue by MagicAndre1981** [aritchie/userdialogs#756]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library

7.1.0.462

## Version of OS(s) listed above with issue

unrelated to issue

## Steps to Reproduce
1. install nightly of Xamarin.Android to VS2019 (should come with some of the first VS2019 16.9 previews) 
2. compile an app that references Acr.UserDialogs

## Expected Behavior

no warning

## Actual Behavior

You get  [warning XA0125 about old pdb format](https://github.com/xamarin/xamarin-android/pull/5162):

```
6>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(377,5): warning XA0125: 'Acr.UserDialogs.pdb' is using a deprecated debug information level.
6>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(377,5): warning XA0125: Set the debugging information to Portable in the Visual Studio project property pages or edit the project file in a text editor and set the 'DebugType' MSBuild property to 'portable' to use the newer, cross-platform debug information level.
6>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(377,5): warning XA0125: If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the library author.
```

I opened the issue because of this note:

`If this file comes from a NuGet package, update to a newer version of the NuGet package or notify the library author.`

**Comment by MagicAndre1981** [comment]
what should I do here? 🤔 This is a notification so that it gets fixed before VS 2019 16.9 release

**Comment by aritchie** [comment]
@MagicAndre1981 it won't make any difference.  send a PR if you want this, otherwise it will be closed.

**Comment by MagicAndre1981** [comment]
> send a PR if you want this

done in #767
