### ISSUE TITLE
[Enhancement] Android - In PromptBuilder set "No suggestion"-Flag if InputType.Password

### ISSUE THREAD

**Issue by OliverMDr** [aritchie/userdialogs#757]
## Summary
When using PromptAsync with InputType.Password, Android is presenting suggestions based on earlier entries. For security reasons, no suggestions should be presented when using InputType.Password.

## API Changes
In class PromptBuilder in Method SetInputType, in the following cases the InputType of the TextView should be set to InputTypes.TextFlagNoSuggestions:

```
public static void SetInputType(TextView txt, InputType inputType)
{
...
case InputType.NumericPassword:
                    txt.TransformationMethod = PasswordTransformationMethod.Instance;
                    txt.InputType = InputTypes.ClassNumber | InputTypes.TextFlagNoSuggestions;

                    break;
case InputType.Password:
                    txt.TransformationMethod = PasswordTransformationMethod.Instance;
                    txt.InputType = InputTypes.TextFlagNoSuggestions;
                    //txt.InputType = InputTypes.ClassText | InputTypes.TextVariationPassword;
                    break;
...
```

## Intended Use Case
An attacker who gains access to a device could get the password simply by opening the input dialog because of the suggestions presented by Android. With the proposed changes that wouldn't be possible anymore.

**Comment by aritchie** [comment]
You are welcome to submit a PR for this.  I have never personally used the prompt dialog for passwords, nor will I ever (and hopefully no one else is either).

**Comment by OliverMDr** [comment]
Great thanks. I will make a PR as soon as possible.

Do you mean it's not secure to use prompt dialog for passwords? What would be a better way?
