### ISSUE TITLE
[Enhancement] WPF with .net Core 3.1

### ISSUE THREAD

**Issue by jeremiejimblet** [aritchie/userdialogs#764]
## Summary
Add support for WPF with .Net Core 3.1

## API Changes
Add a new platform for WPF to mostly display alert and loading

## Intended Use Case
I would like to have the same functioning in WPF as my application on Android (Tablet). Other than UWP which was discontinued by Microsoft.

**Comment by aritchie** [comment]
UWP is not discontinued.  This isn't something I intend to ever add myself as I have no need for Windows native UI at this time.  Feel free to send a PR.

**Comment by tkouba** [comment]
I have preview version of WPF implementation for my project (Alert, Confirm and Progress). This is tested on .Net 4.7 WPF application. It is not for PR (yet), but you could se it at https://gist.github.com/tkouba/2dd84a513ccec5bf4329a595c2bdc759

**Comment by tkouba** [comment]
PR #772 does not support Toast. I would like to discuss about it. It it better use Windows Toast API (https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-ux-guidance) or something application specific like https://github.com/Federerer/Notifications.Wpf?

**Comment by aritchie** [comment]
I don't really use WPF so I will defer here.  However, the nature of the project is to avoid external dependencies when possible

**Comment by tkouba** [comment]
It is not possible to change colors in Windows Toast API and Toast is not part of application main window, but it is part of OS. UWP implementation uses external Coding4Fun Toast, whis is part of application main window.

**Comment by tkouba** [comment]
I have created extension for WPF (using Xamarin Forms platform WPF library), see https://github.com/tkouba/UserDialogs.WPF
