### ISSUE TITLE
[Bug] TimePicker Not Working in iOS 14

### ISSUE THREAD

**Issue by Brosten** [aritchie/userdialogs#768]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)
 - [ x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
ACR 7.1.0.468
Xamarin Forms 4.8.0.1687

## Version of OS(s) listed above with issue
iOS 14.1

## Steps to Reproduce
1. call TimePromptAsync

## Expected Behavior
A good looking timepicker should appear

## Actual Behavior
A timepicker with strange look appear.
![image](https://user-images.githubusercontent.com/10629345/100415603-d99daf80-307c-11eb-806a-4f23a293e36b.png)

The resolution from [this one](https://github.com/aritchie/userdialogs/issues/750)
only seem to fix the date picker. Timepicker still doesn't have an option to use Wheels.
I created a custom renderer for the timepicker as described [here](https://github.com/xamarin/Xamarin.Forms/issues/11963) but it doesn't seem to be used when using UserDialogs.

Is there any other workaround that I can't find?

**Comment by aritchie** [comment]
Why do you mean "still"?  This is open source - you "still" need a fix, send one!!

Not sure why you think a custom renderer would fix anything as this project doesn't have anything from xamarin forms

**Comment by Brosten** [comment]
With still, i'm refering to [this](https://github.com/aritchie/userdialogs/issues/750) issue being closed with comment "fixed by pr". (It's title is "**Time** and Date dialogs broken...")
But from what I can see the fix only deals with the DatePicker, not the TimePicker.

With the renderer, I just didn't know UserDialogs didn't use any parts of forms.

I know this is open source and that I can contribute if I want to. But I also see a value in reporting a problem, even if I don't have the time, knowledge or intention to fix the problem myself.

**Comment by jamsoft** [comment]
I just fixed this and created a pull request for review:

https://github.com/aritchie/userdialogs/pull/771
