### ISSUE TITLE
[Bug] Login Dialog - Cannot type numerics in the password field

### ISSUE THREAD

**Issue by phillw1994** [aritchie/userdialogs#770]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [X] .NET Standard

## Version of Library
7.1.0.466

## Version of OS(s) listed above with issue
Android 4.4

## Steps to Reproduce
1. Create a Xamarin Forms Solution
2. Add Nuget Packages
3.Debug to an Emulator running Android 4.4 API 19

## Expected Behavior
Numeric Keys work

## Actual Behavior
Numeric Keys do not work

**Comment by aritchie** [comment]
Sorry -  I don't promise support for old versions of android like that anymore.  It's pretty much 8+ now
