### ISSUE TITLE
Prompt(sync) not working with AndroidX

### ISSUE THREAD

**Issue by gocmenali** [aritchie/userdialogs#774]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [*] iOS
 - [*] Android
 - [*] .NET Standard

## Version of Library
Acr.Userdialogs
7.1.0.466

## Version of OS(s) listed above with issue
Android 21+

## Steps to Reproduce
1. creating new PromptConfig
2. UserDialogs.Instance.Prompt(cfg);

## Expected Behavior
expect a dialog with inputtype.name

## Actual Behavior
crashes with this exception
Java.Lang.NoSuchMethodError: 'no non-static method "Landroidx/appcompat/app/AlertDialog$Builder;.setCancelable(Z)Landroidx/appcompat/app/AlertDialog$Builder;"'

**Comment by aritchie** [comment]
Please submit a full reproducible sample if you want this looked at.  Many AndroidX answers have already been given.

**Comment by gocmenali** [comment]
Sample project
https://github.com/gocmenali/AcrDemo

I think because of a NuGet package conflict this error occures. When i try Prompt feature on a clean project it works successfully, but on my project it doesn't.

**Comment by aritchie** [comment]
This has been answered in other issues.  You need to use the androidx migration if you want to mix things up like this.  This package does work fine with AndroidX otherwise.
