### ISSUE TITLE
On Android, a Toast can only show a maximum of 2 lines

### ISSUE THREAD

**Issue by meschi89** [aritchie/userdialogs#775]
## Summary
On Android we can show a Toast with a message. However, the message is cut off after two lines. On iOS all lines are shown.
I don't see a reason why this needs to be cut off.
![Screenshot_20201228-170410](https://user-images.githubusercontent.com/45665020/103277145-a37b8480-49c8-11eb-882d-cd70b56ffe7c.jpg)

## API Changes
The API does not need to change. The Implementation only

## Intended Use Case
For example when I display a message with some additional error information.

**Comment by aritchie** [comment]
This is actually by design since the snackbar doesn’t really resize well on all size factors for droid

**Comment by meschi89** [comment]
Ok, thanks for your fast answer and your work. I appreciate it.
