### ISSUE TITLE
xamarin.forms IOS can't be used?[Bug] 

### ISSUE THREAD

**Issue by bbhxwl** [aritchie/userdialogs#778]
xamarin.forms IOS can't be used?

 - [ ] iOS
 - [ ] .NET Standard

## Steps to Reproduce
1.System.NullReferenceException: 'Object reference not set to an instance of an object'

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/104059088-afb8da80-522f-11eb-9d8f-535eef80c148.png)

**Comment by aritchie** [comment]
Your question doesn't make any sense and you haven't given any details.  Don't waste my time.

**Comment by bbhxwl** [comment]
> Your question doesn't make any sense and you haven't given any details. Don't waste my time.

I know why, but Android toast will be displayed at the bottom of the interface, not in the middle? Uwp is shown in the upper left corner.
