### ISSUE TITLE
[Bug] Version 14.3 iOS break the date picker

### ISSUE THREAD

**Issue by Jerome2606** [aritchie/userdialogs#779]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ 14.6.0.15 ] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard
Xamarin: 16.8.000.260
Xamarin.Forms: 4.4.0

## Version of Library
7.1.0.470

## Version of OS(s) listed above with issue
14.2 - 14.3

## Steps to Reproduce
1. Open date picker with iOS (both simulator or real device)

## Expected Behavior
Like before

## Actual Behavior
![2021-01-14_14h43_52](https://user-images.githubusercontent.com/4534893/104599070-a38dac80-5677-11eb-8f25-0a09215c52ee.png)

![2021-01-14_14h44_09](https://user-images.githubusercontent.com/4534893/104599084-a7213380-5677-11eb-87c0-332d00137139.png)

**Comment by Jerome2606** [comment]
As a workaround, I'm forcing the wheel for iOS:

```
DatePromptResult resultat = await UserDialogs.Instance.DatePromptAsync(new DatePromptConfig { Title = AppResources.LabelDateNaissance, iOSDatePickerStyle = iOSDatePickerStyle.Wheels }, null);
```

But that's not a behavior I  want to keep 

BTW, I updated to Xamarin.Forms 4,8,0,1821 but I was keeping to have the issue

**Comment by aritchie** [comment]
This is what the behavior is now.  

XF has nothing to do with this project.
