### ISSUE TITLE
iOS Toasts don't look great

### ISSUE THREAD

**Issue by rid00z** [aritchie/userdialogs#78]
Just an FYI.

The new toast notifications on iOS are very hard to style and lack configuration options. 

It would be good for configuration options for a simple screen centered toast. 

Suggested options: SlideDown | TopSimple | CentreSimple | BottomSimple

When I say simple I mean just a little rounded view like it used to be. :)

We had to remove UserDialogs and go back to ProgressHUDs to get the older style.

**Comment by rid00z** [comment]
Unless we've done something wrong.

**Comment by aritchie** [comment]
You can still use ShowSuccess and ShowError for the center style messages.  I find stuff in the center not very toasty like.  

What options do you feel are missing (position aside)?

**Comment by rid00z** [comment]
We went back to the toasts from ProgressHUDs and centred at the top. 

The large slidedown was too overwhelming for the UI. 

So it's both 
1) Ability to have a simple toast 
2) Ability to position the simple toast

**Comment by davidtavarez** [comment]
3) Change color.

**Comment by aritchie** [comment]
#3 already exists

**Comment by aritchie** [comment]
Sorry.  I'm going to have to push this one off.  I don't want to add a method for one function on one platform.  I've left an example on how to override the functionality on the FAQ.

**Comment by aritchie** [comment]
There is a new toast window coming in v6.0.  Beta1 is on Nuget now
