### ISSUE TITLE
[Enhancement] Add flexible FontSize and more positions and close functionality for toasts

### ISSUE THREAD

**Issue by dxt-rr** [aritchie/userdialogs#781]
## Summary
This package is a great! But having the following enhancements would be great, too... :)

## API Changes
- The toast text is a little small. It would be nice to be able to set an individual font size in ToastConfig.
- Bottom and top is not always suitable for toasts. More positions like "Center" (in the middle of the screen) and "OneQuarter" (toast starts at 25% of the screen's height) and "ThreeQuarter" (toast ends at 75% of the screen's height) in ToastPosition would be really nice.
- Especially for long displayed toasts (more than 3 seconds because the text is a bit longer) it would be nice to have a "Closable" property in ToastConfig. In case this property is set to true the toast should hide if one taps on it.

## Intended Use Case
Well, I would use it in our apps to provide a better user experience...

**Comment by aritchie** [comment]
This also fails the nature of the template.  You are welcome to send PRs for any of this, but I won’t be adding any of this stuff
