### ISSUE TITLE
Exception in AIDatePickerController (german region) [Bug] 

### ISSUE THREAD

**Issue by steveattwood** [aritchie/userdialogs#784]
- [ x] iOS
 - [ ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.1.0.475

## Version of OS(s) listed above with issue
14.4

## Steps to Reproduce
Set device region to german/deutschland (regional format has to be 4.567,89)
5 + safeAreaInsets.Bottom has to be fractional.

## Expected Behavior
No exception is thrown. NSLayoutConstraint is successfully created.

## Actual Behavior
{5 + safeAreaInsets.Bottom} creates a string with "," instead of "." and throws an exception.

**Comment by aritchie** [comment]
Please include the exception!!

**Comment by steveattwood** [comment]
> Please include the exception!!


[exception.pdf](https://github.com/aritchie/userdialogs/files/5924903/exception.pdf)

**Comment by aritchie** [comment]
You are welcome to send a PR for this.  This isn't something I will fix since it doesn't personally effect my dev efforts.  Easiest workaround is not to use a fraction on the insets in this case anyhow
