### ISSUE TITLE
Toast hide tabbar is there anway to make in above tababr

### ISSUE THREAD

**Issue by Tafanan** [aritchie/userdialogs#785]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!
 platforms
 - iOS
 -  Android
 

Version of Library latest

## Version of OS(s) listed above with issue

 Steps to Reproduce
1.using tost defalut postion to bottom
2.
3.
 Expected Behavior
To no overide the tabar or hide it

 Actual Behavior
![received_411347666791385](https://user-images.githubusercontent.com/75538574/107154899-0d9b2800-697e-11eb-9220-325045df22cd.jpeg)

**Comment by aritchie** [comment]
No - there isn't
