### ISSUE TITLE
How-to

### ISSUE THREAD

**Issue by Tafanan** [aritchie/userdialogs#786]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ x] iOS
 - [x ] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.1.0.475
## Version of OS(s) listed above with issue
Ios 14.4
Android 10

## Steps to Reproduce
1. Using toast with bottom postion

## Expected Behavior
I want to have it over tabbar

## Actual Behavior
It overlay on the tabbar
![received_411347666791385](https://user-images.githubusercontent.com/75538574/107160314-2ca9b200-699e-11eb-89cb-2dd7dc4a8f16.jpeg)

**Comment by aritchie** [comment]
Your question has already been answered.  Do not spam here again or you will be removed.  Remember, this is OSS, you can look at the code for yourself!
