### ISSUE TITLE
ToastConfig.SuccessTextColor doesn't update color

### ISSUE THREAD

**Issue by rid00z** [aritchie/userdialogs#79]
When attempting to set the SuccessTextColor we found it wasn't changing the color of the text.

**Comment by aritchie** [comment]
On what platform?

**Comment by rid00z** [comment]
Sorry it's iOS.


*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by aritchie** [comment]
Can you share the code you are using for the call?  I can't reproduce any issue on iOS.

**Comment by rid00z** [comment]
Just Add this into the Sample project

Samples\Samples\MainPage.cs Line 60


                    ToastConfig.ErrorBackgroundColor = System.Drawing.Color.DeepPink;
		    ToastConfig.SuccessTextColor = System.Drawing.Color.Black;

We want to change the TextColor of Success Toast
