### ISSUE TITLE
[Bug] ActionSheetConfig - Item Text appearance can't be changed

### ISSUE THREAD

**Issue by JMan7777** [aritchie/userdialogs#791]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.1.0.475

## Version of OS(s) listed above with issue
Xamarin Android

## Steps to Reproduce
Hi,

I know I can customize the style of the the UserDialogs but I can't find a way to change the
text style / size / font of the "Item Text".

```
ActionSheetConfig actionSheetConfig = new ActionSheetConfig()
                    .SetTitle("My Title")
                    .SetMessage("My Message")
                    .SetUseBottomSheet(false);

actionSheetConfig.AndroidStyleId = Resource.Style.MyStyle;

actionSheetConfig.Add(
                "Item Text",
                () =>
                {
                     //Do something
                },
                "icon.png"
                );

UserDialogs.Instance.ActionSheet(actionSheetConfig);
```

What style.xml items are used to modify the "Item Text" appearance ?

```
<style name="MyStyle">
    <item name="????????">???????</item>
  </style>
```

I don't want to change any title, message or button style properties.

Thx.

## Expected Behavior
Some way to change the "Item Text" appearance.

## Actual Behavior
Can't change the "Item Text" appearance.

**Comment by aritchie** [comment]
I don't recall.  This is something you will have to search up in the android docs
