### ISSUE TITLE
[Enhancement] Dark Dialogs on Dark Mode

### ISSUE THREAD

**Issue by bluekuen** [aritchie/userdialogs#793]
## Summary
I want to get a black/dark background when the Current Apptheme color is dark:
OSAppTheme currentTheme = Xamarin.Forms.Application.Current.RequestedTheme;
if (currentTheme == OSAppTheme.Dark) { //apply dark background color}

## API Changes
maybe define a dark or light parameter in constructor of the Confirm or Async Method.

## Intended Use Case
Apply Dark dialogs when device theme is set to dark.

Kind Regards
bluekuen

**Comment by aritchie** [comment]
You are welcome to send a PR for this (without a xamarin forms dependency), but I don't touch this project myself anymore
