### ISSUE TITLE
[Bug] InputType set as InputType.Password isn't hide the user input.

### ISSUE THREAD

**Issue by polotto** [aritchie/userdialogs#794]
I tried create a prompt dialog of type password and the user prompt ins't hide the user input. I'm using a Xamarin Forms project.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
Xamarin forms: 7.1.0.475
Xamarin Andrioid: 7.1.0.475

## Version of OS(s) listed above with issue
Android Q 10.0 API 29

## Steps to Reproduce
1. Create a PromptAsync with Password input type: ` var prompt = await UserDialogs.Instance.PromptAsync("Test", inputType: InputType.Password);`
2. Open the screen where you put the dialog
3. Try type some input in the prompt dialog

## Expected Behavior
Hide user input.

## Actual Behavior
The dialog isn't hide the user input.

**Comment by aritchie** [comment]
It has been fixed, but this is an awful user experience.  I wouldn't do it, but its your app

**Comment by polotto** [comment]
What's the version that was fixed?

**Comment by aritchie** [comment]
I’m sorry I misread this issue.  In any case, this isn’t something I’m willing to fix.  In fact, as of today, this two will no longer be taking issues.  You are welcome to send a Pr but I won’t be doing anything with this
