### ISSUE TITLE
iOS: ShowError ShowSuccess background color inconsistency?

### ISSUE THREAD

**Issue by durandt** [aritchie/userdialogs#81]
Hi A.Ritchie!

You are doing a great job otherwise I wouldn't be writing an issue :)
(I mean, sometimes it's hard to get the motivation to write an issue when you see that the last comment or commit was two years ago or more). 

So here is my question: 
__Why do `ShowError` and `ShowSuccess` have a white background?__
I'm using `ShowProgress` to lock the UI while doing some processing that I consider blocking. Then, I would like to notify the user with `ShowSuccess`. 
The thing is that `ShowProgress` has a black-transparent background with white text, which is what I'm used to from the time I was using `SVProgressHUD` on native iOS apps. It makes your dialog stick out on your white UI background. 
But the `ShowError` and `ShowSuccess` dialogs use a white background instead, making it hard to actually notice that their is a dialog on a UI with rather clear colors (like most iOS apps should). 

So my question is double: 
 - Am I missing an easy way to change the style of `ShowError` and `ShowSuccess` ?
 - If no, why are `ShowProgress` and `ShowSuccess` using different styles?

I have looked a bit and it looks like the problem comes from `BTProgressHUD` but I'm not sure what is the right way to solve it. 

Regards,

**Comment by aritchie** [comment]
This is something with BTProgressHUD.  There is no way to control the mask for these two methods (or any of the upstream methods they call).

**Comment by durandt** [comment]
Ok thank you, I think I read the same answer somewhere else but couldn't put my hand on it when I wrote the issue. 
I may try to look at the issue this week or next week.

**Comment by johncbc** [comment]
Bit of a hack:

UserDialogs.Instance.ShowLoading();
UserDialogs.Instance.ShowError(Message);
await Task.Delay(2800);
UserDialogs.Instance.HideLoading();

**Comment by aritchie** [comment]
This is fixed as 5.1
