### ISSUE TITLE
Object reference not set to an instance of an object iOS

### ISSUE THREAD

**Issue by muhammetsahin** [aritchie/userdialogs#82]
public static IContainer Container { get; set; }
		public App ()
		{
			
			var builder = new ContainerBuilder();

			builder.RegisterInstance(new ApiService()).As<IApiService>().SingleInstance();
			builder.RegisterInstance(new AccountService(new ApiService())).As<IAccountService>().SingleInstance();
			builder.RegisterInstance(UserDialogs.Instance).As<IUserDialogs>().SingleInstance();
			App.Container = builder.Build ();

			AutoMapperConfiguration.Configure ();
		
			// The root page of your application
			MainPage = new HomePage( Container.Resolve<IAccountService>());
			
		}

private static IUserDialogs _userDialogs;

		public LoginController (HybridWebView hybridWebView, IAccountService accountService)
		{
			_hybridWebView = hybridWebView;
			_accountService = accountService;

			_userDialogs= App.Container.Resolve<IUserDialogs> ();

		}

		public async  void ShowLogin()
		{
			_userDialogs.ShowLoading ("Please waiting...",MaskType.Gradient);
                }

![image](https://cloud.githubusercontent.com/assets/2045788/9913078/823317d2-5cb3-11e5-9c58-274239944269.png)

**Comment by aritchie** [comment]
You can't call for progress dialogs until the view is ready (onappearing)

**Comment by muhammetsahin** [comment]
Thanks for help
