### ISSUE TITLE
iOS 9 : If I go to mail sender from my app, there is no spinner on come back

### ISSUE THREAD

**Issue by anthonybattel** [aritchie/userdialogs#83]
Hi !
Thanks for your work, It's a great help for us.
Like I said in the title, since iOS 9, the spinners are not visible if I come back to my app from the mail composer (delete draft button) but the popups works. When I show a popup, the spinners are visible again.

I am at your disposal for further information.

Thanks

**Comment by aritchie** [comment]
You'll need to provide some source code for how you are managing the dialog.
To be honest though, this isn't really an issue I'm sure I can solve for you and even if I can, I'm no sure it is something that I should internalize as a fix.

**Comment by anthonybattel** [comment]
Ok thanks for your help.
I'm using the 4.1.4 Acr.UserDialogs version.

This is the function that I call in order to compose a mail : 

    public void ComposeMail(string emailAddressTo, string subject, string body, bool isHTMLBody) {
		var emailAddressToString = (emailAddressTo == null) ? String.Empty : emailAddressTo;
		var subjectString = (subject == null) ? String.Empty : subject;
		var bodyString = (body == null) ? String.Empty : body;

		if (MFMailComposeViewController.CanSendMail) {
			MFMailComposeViewController mailController;
			mailController = new MFMailComposeViewController();
			if (!string.IsNullOrWhiteSpace(emailAddressToString)) {
				mailController.SetToRecipients(new string[]{emailAddressToString});
			}
			mailController.SetSubject(subjectString);
			mailController.SetMessageBody(bodyString, isHTMLBody);
			mailController.Finished += (object s, MFComposeResultEventArgs args) => {
				args.Controller.DismissViewController(true, null);
			};
        }      

         UIApplication.SharedApplication.KeyWindow.RootViewController.PresentViewController(mailController, true, null);
     }

I'm using UserDialogs in this simple way :

    UserDialogs.Instance.ShowLoading(title, MaskType.Black);

**Comment by anthonybattel** [comment]
Hi !
If I build my app with the last iOS 9 SDK, the problem is solved.

Thanks for your help
