### ISSUE TITLE
iOS: All user dialogs become invisible in iOS 9 after opening and closing a QLPreview! Help?

### ISSUE THREAD

**Issue by mikey-mike** [aritchie/userdialogs#84]
Hey there @aritchie! I've come across a new issue in our app that coincides with iOS 9. All of the user dialogs in the app work perfectly up until a QuickLook preview window (displaying a PDF) is opened. As soon as you close the preview and continue using the app, the dialogs are no longer visible! They aren't rendered in any way but are still active and fully functional, I can actually tap on the invisible ActionSheets and they'll act as intended. I realized I was using the deprecated version of the user dialogs, and moved to using this NuGet package but the issue has not been resolved. Can you offer any insight as to what is going on?

Thanks in advance!

**Comment by aritchie** [comment]
@mikey-mike please provide a full test-case/gist with your issue and I'll take a look

**Comment by mikey-mike** [comment]
Never mind! Ended up having a lot of compilation issues with the build host along with trouble trying to update all of the NuGet packages. Those were resolved by reverting to a previous version of the app, manually going into the csproj and cleaning up duplicate asset catalogs, and then removing the old NuGet packages prior to using the new ones. You can mark this issue as resolved!
