### ISSUE TITLE
Referencing Cirrious.CrossCore 1.0.0.0?

### ISSUE THREAD

**Issue by follesoe** [aritchie/userdialogs#85]
We've run into an issue after upgrading to MvvmCross 4.0 beta-3. In Xamarin Studio the build fails with the following message:

```
Error CS0012: 

The type `Cirrious.CrossCore.Plugins.IMvxPluginLoader' is defined in an assembly that is not referenced. 

Consider adding a reference to assembly `Cirrious.CrossCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e16445fd9b451819' (CS0012)
```

It builds and runs fine on Visual Studio 2015, so this might be a Xamarin Studio problem, but figured I'd report it and see if anyone else has tested the plugin with beta-3.

**Comment by martijn00** [comment]
This is a problem with your code / project file. You have to update all your references to MvvmCross 4.0 beta-3 to get this working, just like this: https://github.com/MvvmCross/MvvmCross-AndroidSupport/blob/master/Samples/Example.Droid/Example.Droid.csproj#L41

**Comment by follesoe** [comment]
We have updated all references. Checked both in packages file, csproj files references. But looking at https://github.com/aritchie/userdialogs/blob/master/src/Acr.MvvmCross.Plugins.UserDialogs/Acr.MvvmCross.Plugins.UserDialogs.csproj#L43 you can see it's referencing 1.0.0.0:

```
    <Reference Include="Cirrious.CrossCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e16445fd9b451819, processorArchitecture=MSIL">
      <HintPath>..\packages\MvvmCross.HotTuna.CrossCore.3.5.1\lib\portable-win+net45+wp8+win8+wpa81\Cirrious.CrossCore.dll</HintPath>
      <Private>True</Private>
    </Reference>
```

**Comment by martijn00** [comment]
That might be right, but i believe the MvvmCross plugin is not maintained currently, and i myself am using the normal dialogs in combination with MvvmCross without problems.

**Comment by aritchie** [comment]
I haven't updated the plugin official to MvvmCross 4 since it is still in beta.  I will update the nuget packages accordingly when it goes live.

**Comment by JelleDamen** [comment]
I've forked the repo and migrated to mvx 4 beta 3. You can clone it from here: https://github.com/JelleDamen/userdialogs

**Comment by martijn00** [comment]
@JelleDamen Would it an idea to make a PR of it?

**Comment by JelleDamen** [comment]
I Could do that, but i've only changed the references for the Droid and Touch project. Fairly easy change

**Comment by aritchie** [comment]
I'll release a beta package if people are really wanting it

**Comment by JelleDamen** [comment]
@aritchie That would be really great!

**Comment by darochapires** [comment]
@aritchie I'm waiting for it too. Thanks.

**Comment by aritchie** [comment]
The mvx support plugin is seriously not needed anymore.  In android, you have to add one line of code, in your PCL, you have to add one line of code.  The library is just extraneous to keep.

In your App.cs, add Mvx.RegisterSingleton<IUserDialogs>(() => UserDialogs.Instance);
In your main android project, Acr.UserDialogs.UserDialogs.Init();

In the next release, I'm going to make it so Init is optional for android as well, thereby making this even less of an issue.

**Comment by martijn00** [comment]
I use the Userdialogs plugin without MvvmCross specific stuff in my MvvmCross apps. I agree with @aritchie that it is not needed anymore. It might be even better to clean all code that references MvvmCross right now, just to prevent any confusion.

**Comment by aritchie** [comment]
@martijn00 I'm thinking I may create a pure pcl mvx plugin.  that will save the many repeat questions that will come in regarding how to register the lib with mvx.

**Comment by martijn00** [comment]
Hmm, but it is just 1 line of code!

**Comment by aritchie** [comment]
1 line of code to save future headache.  

With Mvx4 treading into XForms territory, you will likely begin to appreciate what I'm saying lol.  I can of course document that one line of code, but the question will still be asked.... a lot.

In any case, I'll have to redirect the nuget packages.

**Comment by aritchie** [comment]
I am going to drop the MvvmCross plugin.  I do tend to agree with @martijn00 that it is just one line of code in you App.cs and one line of init code in your android project.
