### ISSUE TITLE
UserDialogs.Instance.ActionSheet on Droid, not working

### ISSUE THREAD

**Issue by JournyxMatt** [aritchie/userdialogs#86]
I have the following piece of code:

        private void ListViewAttachmentSelectSize(MediaFile IMediaFile)
        {
            ActionSheetConfig ASImageSize = new ActionSheetConfig();
            ASImageSize.Title = "Attachment Size";
            ASImageSize.Add("Small", OnSaveSmallSize(IMediaFile));
            ASImageSize.Add("Medium", OnSaveMediumSize(IMediaFile));
            ASImageSize.Add("Large", OnSaveLargeSize(IMediaFile));
            UserDialogs.Instance.ActionSheet(ASImageSize);
        }

Its been working just fine and then about a week ago stopped.  I reverted back to the previous version of Xamarin.Forms 1.4.4.6449 and Acr.UserDialogs -Version 4.1.0 with no luck.

**Comment by aritchie** [comment]
What isn't working?  They don't show?  There is an exception?  Underlying warning?  Please provide some sort of detail with the issue.
