### ISSUE TITLE
Can't compile with latest android design support (v26)

### ISSUE THREAD

**Issue by davidtavarez** [aritchie/userdialogs#89]
I did update all the package. Now it won't compile with 4 errors.
![screen shot 2015-10-05 at 6 36 05 pm](https://cloud.githubusercontent.com/assets/337107/10295679/32a5e7da-6b90-11e5-9d29-a307e26bdfc7.png)
![screen shot 2015-10-05 at 6 38 36 pm](https://cloud.githubusercontent.com/assets/337107/10295694/55edb038-6b90-11e5-8328-40778bb903af.png)
![screen shot 2015-10-05 at 6 38 19 pm](https://cloud.githubusercontent.com/assets/337107/10295695/561609ca-6b90-11e5-846c-258dc2eafdbd.png)

**Comment by aritchie** [comment]
Update your android SDK with the latest API.  You have to do this with almost every major support library update.
