### ISSUE TITLE
Blocking Toast on android

### ISSUE THREAD

**Issue by PaulAchess** [aritchie/userdialogs#9]
I'm sure sure wether this is a bug or not, but I prefer report it just in case.

When calling a `dialogs.Toast("xxx");` on Android, the toast is blocking the screen. To be more precise, I am no longer able to use the back button or the navigation icon to get back until the toast disappear.

This is not really huge but it's actually a bit frustrating for the user experience.

Maybe I'm just doing something wrong / this is a normal behavior, in that case don't hesitate to close the issue.

**Comment by aritchie** [comment]
I can't actually reproduce the case.  I'll need a test case.

**Comment by PaulAchess** [comment]
I'll create a small project tomorrow for you

**Comment by PaulAchess** [comment]
Hi, sorry for the delay.
I have created a small project with a button, a label and a toast. Explanations are in comments ;)

http://www.filedropper.com/blockingtoastticket9acr
