### ISSUE TITLE
Using a Loading/Progress Dialog with Navigation

### ISSUE THREAD

**Issue by yeenfei** [aritchie/userdialogs#90]
I'm using Acr.UserDialogs with Xamarin Forms for my Azure Mobile Service project that requires authentication. The app will first load into welcome page, with a button to initiate fb login (followed the standard way from msdn). 

Call to MobileServiceClient.LoginAsync() is awaited from viewmodel, then welcome page is notified via MessagingCenter to initiate data fetching from server. The entire data loading routine is encapsulated within a "using" statement similar to below:

	//	using (var dlg = UserDialogs.Instance.Loading("Loading", maskType: MaskType.Black)) {
		try {
			if (loginResult.Type == eLoginType.ONLINE) {
				Settings.DeviceId = loginResult.DeviceId;
				vm.AccountId = loginResult.AccountId;
				vm.AccountToken = loginResult.Token;
				vm.AccountTokenExpiry = loginResult.TokenExpiry.ToString();
				await vm.MasterData.Sync();
			}

			await Navigation.PopModalAsync();
		}
		catch { }
	//	}

I noticed that when the UserDialogs is not commented out, I will get the following errors in my output log (my application is fully written in XF, the webview is used by mobileServiceClient::loginAsync):

[WindowManager] 
[WindowManager] android.view.WindowLeaked: Activity md588920fb9403ed228b036d6919cddd329.WebAuthenticatorActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{26b31aa8 V.E..... R......D 0,0-165,198} that was originally added here
[WindowManager] 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
[WindowManager] 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
[WindowManager] 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
[WindowManager] 	at android.app.Dialog.show(Dialog.java:286)
[WindowManager] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[WindowManager] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
[WindowManager] 	at android.app.Activity.runOnUiThread(Activity.java:4713)
[WindowManager] 	at md588920fb9403ed228b036d6919cddd329.WebAuthenticatorActivity_Client.n_onPageStarted(Native Method)
[WindowManager] 	at md588920fb9403ed228b036d6919cddd329.WebAuthenticatorActivity_Client.onPageStarted(WebAuthenticatorActivity_Client.java:46)
[WindowManager] 	at com.android.webview.chromium.WebViewContentsClientAdapter.onPageStarted(WebViewContentsClientAdapter.java:439)
[WindowManager] 	at com.android.org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:104)
[WindowManager] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[WindowManager] 	at android.os.Looper.loop(Looper.java:149)
[WindowManager] 	at android.app.ActivityThread.main(ActivityThread.java:5045)
[WindowManager] 	at java.lang.reflect.Method.invokeNative(Native Method)
[WindowManager] 	at java.lang.reflect.Method.invoke(Method.java:515)
[WindowManager] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
[WindowManager] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
[WindowManager] 	at dalvik.system.NativeStart.main(Native Method)

**Comment by aritchie** [comment]
Hide the progress/loading dialog before navigation/popping the modal.

**Comment by aritchie** [comment]
Updated FAQ to answer this question
