### ISSUE TITLE
PCL Library issue for new projects

### ISSUE THREAD

**Issue by TylerBrinks** [aritchie/userdialogs#91]
I've got a new Xamarin.Forms project where I'm trying to add Acr.UserDialogs version 4.1.4.

When I try to access UserDialogs.Instance, I get the following error.  I see where the error is being thrown in code inside UserDialogs.cs with a #if PCL flag.  I'm using the Xamarin NuGet package manager - is there something I need to do manually to get this to work?

Exception thrown is "This PCL library, not the platform library.  Did you include the nuget package in your project?"

**Comment by aritchie** [comment]
Install the nuget package in the platform (main executables) as well

**Comment by TylerBrinks** [comment]
I installed the package in all projects via NuGet and subsequently tried adding the dlls manually.  Neither seemed to work.  My solution consists of an iOS app, an Android app, and a shared PCL library.  All 3 have the package installed, but when running either device-specific app I get the exception.

Any ideas or pointers on the correct way to add the references?  I must be missing something simple.

**Comment by aritchie** [comment]
The correct way to add the instances is through nuget.  Try visual studio... beyond that, I have no idea what the issue is that you are having

**Comment by TylerBrinks** [comment]
I wish that was an option.  I'm using Xamarin on a Mac, not Visual Studio.

**Comment by aritchie** [comment]
Try 4.1.6.  I've changed the nuspec definition to be more exact.  This may fix xam studio referencing.  I would suggest a full remove and reinstall of the packages just to be safe

**Comment by snehaljadhavgit** [comment]
Facing the same issue in NUnit test project
