### ISSUE TITLE
Custom loading image.

### ISSUE THREAD

**Issue by yumshinetech** [aritchie/userdialogs#92]
Hi, is there any way to change the image of Loading dialog?

**Comment by aritchie** [comment]
No.  The library uses a few other libraries to accomplish the progress dialog.

**Comment by IeuanWalker** [comment]
This would be a good feature, especially if we could use lottie animations

**Comment by aritchie** [comment]
@IeuanWalker please don't comment on closed issues.  If this is a feature you want, you are welcome to contribute a PR.  I closed this because I don't have any plans to implement it myself.
