### ISSUE TITLE
UIKit.UIKitThreadAccessException when calling Alert from iOS

### ISSUE THREAD

**Issue by Qonstrukt** [aritchie/userdialogs#94]
Since commit e79694550ff3f46c2b942800cff35b0d18cd957a I've been getting UIKit.UIKitThreadAccessExceptions when calling Alert when running my app on iOS.

I've noticed you moved all the calls to UIApplication.SharedApplication.InvokeOnMainThread() to the Present() method in Acr.UserDialogs.iOS/UserDialogsImpl.cs, but unfortunately, creating an UIAlertController also needs to happen on the UI thread I've noticed.

Could you revert the way it's working for now?

**Comment by aritchie** [comment]
Please post the entire stack trace please

**Comment by aritchie** [comment]
I'm going to close this since I have insufficient information and no reply

**Comment by Qonstrukt** [comment]
Yeah, I'm sorry, have been kinda swamped and downgraded to an older version (4.1.4) to solve it for now. I'll reopen it when I'm able to make a stack trace.
