### ISSUE TITLE
Acr.XamForms.UserDialogs Showloading issue on WinPhone

### ISSUE THREAD

**Issue by Rohitwagh** [aritchie/userdialogs#96]
When using Showloading from acr.userdialogs it gives the issue on WinPhone 8.1

`e.ExceptionObject).StackTrace	"   at Microsoft.Phone.Controls.CustomMessageBox.ClosePopup(Boolean restoreOriginalValues)\r\n   at Microsoft.Phone.Controls.CustomMessageBox.<>c__DisplayClass4.<Dismiss>b__1(Object s, EventArgs e)\r\n   at Microsoft.Phone.Controls.Transition.OnCompleted(Object sender, EventArgs e)\r\n   at MS.Internal.CoreInvokeHandler.InvokeEventHandler(Int32 typeIndex, Delegate handlerDelegate, Object sender, Object args)\r\n   at MS.Internal.JoltHelper.FireEvent(IntPtr unmanagedObj, IntPtr unmanagedObjArgs, Int32 argsTypeIndex, Int32 actualArgsTypeIndex, String eventName)"	string`

this looks similar to the issue at https://github.com/aritchie/acr-xamarin-forms/issues/26

**Comment by aritchie** [comment]
Please copy the whole exception.  This is missing some key points of the stack trace that is needed.

**Comment by Rohitwagh** [comment]
This is what is get in the complete stack trace. tried to find more.

This happens when using 

`using(var dialog = Acr.UserDialogs.Instance.Loading("Please wait"))`

**Comment by aritchie** [comment]
You've actually cut off part of the stack trace above.  I need the full stack trace please.

**Comment by Rohitwagh** [comment]
That the only info i get from stacktrace from `Application_UnhandledException` handler in App.xaml.cs

![image](https://cloud.githubusercontent.com/assets/1315166/10902621/b12fdb0e-8226-11e5-8c38-e52eb1b933cb.png)

**Comment by aritchie** [comment]
Log the exception yourself then.  Without that whole stack trace, there isn't anything for me to look into.

**Comment by aritchie** [comment]
Without more details on this error, I can't be of much help.  If you get the rest of the exception details, please reply to this thread and I will reopen this.

**Comment by pavan7parekh** [comment]
Hi @aritchie 
I have facing same issue
Please have a look below StackTrace:

   at Microsoft.Phone.Controls.CustomMessageBox.ClosePopup(Boolean restoreOriginalValues)
   at Microsoft.Phone.Controls.CustomMessageBox.<>c__DisplayClass4.<Dismiss>b__1(Object s, EventArgs e)
   at Microsoft.Phone.Controls.Transition.OnCompleted(Object sender, EventArgs e)
   at MS.Internal.CoreInvokeHandler.InvokeEventHandler(Int32 typeIndex, Delegate handlerDelegate, Object sender, Object args)
   at MS.Internal.JoltHelper.FireEvent(IntPtr unmanagedObj, IntPtr unmanagedObjArgs, Int32 argsTypeIndex, Int32 actualArgsTypeIndex, String eventName)

**Comment by aritchie** [comment]
@pavan7parekh As with the original poster, you have missed a chunk of the exception that I need to even begin to assess the problem.  As it is, I am preparing to drop any sort of support for WP8
