### ISSUE TITLE
Resource not Found for UserDialogs.Instance.ActionSheetAsync

### ISSUE THREAD

**Issue by DavePilks** [aritchie/userdialogs#97]
I have a Xamarin.Forms app but when I try to use the Android app, I get a ResourceNotFound exception when I try and show the ActionSheet. I have updated the packages and nothing is working.

Others seems to be having issues as well.

https://forums.xamarin.com/discussion/52483/acr-userdialogs-actionsheet-actionsheetconfig-not-working-consistently

**Comment by aritchie** [comment]
Update to the latest version
