### ISSUE TITLE
Toast snackbar shows up behind soft keys on Android

### ISSUE THREAD

**Issue by dylanschoenmakers** [aritchie/userdialogs#99]
I'm having a problem with the Toast appcompat snackbar on Android showing up behind the keys at the bottom. 

![screenshot 2015-11-06 12 36 42](https://cloud.githubusercontent.com/assets/4159787/10996200/35ea6e96-8483-11e5-8a1e-2ebb6a36982c.png)

I don't know if it's a bug or a possibly problem in my layouts. Anyone else encountered this?

**Comment by aritchie** [comment]
This is very likely a defect.  The snackbar requires an existing top view to latch on to.  This is how I grab that top view (https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs.Android/UserDialogsImpl.cs#L197) and I've never been a fan.  Any suggestions?

**Comment by dylanschoenmakers** [comment]
Hi @aritchie thanks for getting back so quickly. 

Could we use something like this: 
```top.Window.DecorView.FindViewById (Android.Resource.Id.Content)```

It is what I've used before and seemed to be working well.

**Comment by aritchie** [comment]
I remember trying something like this and it didn't work out very well.  I just don't remember why.  I'll revisit it in the next couple of days.

**Comment by dylanschoenmakers** [comment]
I also had issues with it in the past but that was because I wasn't running that on the UI thread

**Comment by xleon** [comment]
@dylanschoenmakers Invoking toasts in the main thread didn´t work for me. They still get behind the soft keyboard

**Comment by aritchie** [comment]
@dylanschoenmakers your suggested fix seems to have done the trick.  I'll be shipping this in the next day or so.

**Comment by dylanschoenmakers** [comment]
Thanks @aritchie ! Can I buy you a beer?
